import frog from './icons/animals-nature/animal-amphibian/frog.svg';
import frogColor from './icons/animals-nature/animal-amphibian/frog_color.svg';
import babyChick from './icons/animals-nature/animal-bird/baby-chick.svg';
import babyChickColor from './icons/animals-nature/animal-bird/baby-chick_color.svg';
import bird from './icons/animals-nature/animal-bird/bird.svg';
import birdColor from './icons/animals-nature/animal-bird/bird_color.svg';
import chicken from './icons/animals-nature/animal-bird/chicken.svg';
import chickenColor from './icons/animals-nature/animal-bird/chicken_color.svg';
import dodo from './icons/animals-nature/animal-bird/dodo.svg';
import dodoColor from './icons/animals-nature/animal-bird/dodo_color.svg';
import dove from './icons/animals-nature/animal-bird/dove.svg';
import doveColor from './icons/animals-nature/animal-bird/dove_color.svg';
import duck from './icons/animals-nature/animal-bird/duck.svg';
import duckColor from './icons/animals-nature/animal-bird/duck_color.svg';
import eagle from './icons/animals-nature/animal-bird/eagle.svg';
import eagleColor from './icons/animals-nature/animal-bird/eagle_color.svg';
import feather from './icons/animals-nature/animal-bird/feather.svg';
import featherColor from './icons/animals-nature/animal-bird/feather_color.svg';
import flamingo from './icons/animals-nature/animal-bird/flamingo.svg';
import flamingoColor from './icons/animals-nature/animal-bird/flamingo_color.svg';
import frontFacingBabyChick from './icons/animals-nature/animal-bird/front-facing-baby-chick.svg';
import frontFacingBabyChickColor from './icons/animals-nature/animal-bird/front-facing-baby-chick_color.svg';
import hatchingChick from './icons/animals-nature/animal-bird/hatching-chick.svg';
import hatchingChickColor from './icons/animals-nature/animal-bird/hatching-chick_color.svg';
import owl from './icons/animals-nature/animal-bird/owl.svg';
import owlColor from './icons/animals-nature/animal-bird/owl_color.svg';
import parrot from './icons/animals-nature/animal-bird/parrot.svg';
import parrotColor from './icons/animals-nature/animal-bird/parrot_color.svg';
import peacock from './icons/animals-nature/animal-bird/peacock.svg';
import peacockColor from './icons/animals-nature/animal-bird/peacock_color.svg';
import penguin from './icons/animals-nature/animal-bird/penguin.svg';
import penguinColor from './icons/animals-nature/animal-bird/penguin_color.svg';
import rooster from './icons/animals-nature/animal-bird/rooster.svg';
import roosterColor from './icons/animals-nature/animal-bird/rooster_color.svg';
import swan from './icons/animals-nature/animal-bird/swan.svg';
import swanColor from './icons/animals-nature/animal-bird/swan_color.svg';
import turkey from './icons/animals-nature/animal-bird/turkey.svg';
import turkeyColor from './icons/animals-nature/animal-bird/turkey_color.svg';
import ant from './icons/animals-nature/animal-bug/ant.svg';
import antColor from './icons/animals-nature/animal-bug/ant_color.svg';
import beetle from './icons/animals-nature/animal-bug/beetle.svg';
import beetleColor from './icons/animals-nature/animal-bug/beetle_color.svg';
import bug from './icons/animals-nature/animal-bug/bug.svg';
import bugColor from './icons/animals-nature/animal-bug/bug_color.svg';
import butterfly from './icons/animals-nature/animal-bug/butterfly.svg';
import butterflyColor from './icons/animals-nature/animal-bug/butterfly_color.svg';
import cockroach from './icons/animals-nature/animal-bug/cockroach.svg';
import cockroachColor from './icons/animals-nature/animal-bug/cockroach_color.svg';
import cricket from './icons/animals-nature/animal-bug/cricket.svg';
import cricketColor from './icons/animals-nature/animal-bug/cricket_color.svg';
import fly from './icons/animals-nature/animal-bug/fly.svg';
import flyColor from './icons/animals-nature/animal-bug/fly_color.svg';
import honeybee from './icons/animals-nature/animal-bug/honeybee.svg';
import honeybeeColor from './icons/animals-nature/animal-bug/honeybee_color.svg';
import ladyBeetle from './icons/animals-nature/animal-bug/lady-beetle.svg';
import ladyBeetleColor from './icons/animals-nature/animal-bug/lady-beetle_color.svg';
import microbe from './icons/animals-nature/animal-bug/microbe.svg';
import microbeColor from './icons/animals-nature/animal-bug/microbe_color.svg';
import mosquito from './icons/animals-nature/animal-bug/mosquito.svg';
import mosquitoColor from './icons/animals-nature/animal-bug/mosquito_color.svg';
import scorpion from './icons/animals-nature/animal-bug/scorpion.svg';
import scorpionColor from './icons/animals-nature/animal-bug/scorpion_color.svg';
import snail from './icons/animals-nature/animal-bug/snail.svg';
import snailColor from './icons/animals-nature/animal-bug/snail_color.svg';
import spider from './icons/animals-nature/animal-bug/spider.svg';
import spiderColor from './icons/animals-nature/animal-bug/spider_color.svg';
import spiderWeb from './icons/animals-nature/animal-bug/spider-web.svg';
import spiderWebColor from './icons/animals-nature/animal-bug/spider-web_color.svg';
import worm from './icons/animals-nature/animal-bug/worm.svg';
import wormColor from './icons/animals-nature/animal-bug/worm_color.svg';
import badger from './icons/animals-nature/animal-mammal/badger.svg';
import badgerColor from './icons/animals-nature/animal-mammal/badger_color.svg';
import bat from './icons/animals-nature/animal-mammal/bat.svg';
import batColor from './icons/animals-nature/animal-mammal/bat_color.svg';
import bear from './icons/animals-nature/animal-mammal/bear.svg';
import bearColor from './icons/animals-nature/animal-mammal/bear_color.svg';
import beaver from './icons/animals-nature/animal-mammal/beaver.svg';
import beaverColor from './icons/animals-nature/animal-mammal/beaver_color.svg';
import bison from './icons/animals-nature/animal-mammal/bison.svg';
import bisonColor from './icons/animals-nature/animal-mammal/bison_color.svg';
import blackCat from './icons/animals-nature/animal-mammal/black-cat.svg';
import blackCatColor from './icons/animals-nature/animal-mammal/black-cat_color.svg';
import boar from './icons/animals-nature/animal-mammal/boar.svg';
import boarColor from './icons/animals-nature/animal-mammal/boar_color.svg';
import camel from './icons/animals-nature/animal-mammal/camel.svg';
import camelColor from './icons/animals-nature/animal-mammal/camel_color.svg';
import cat from './icons/animals-nature/animal-mammal/cat.svg';
import catColor from './icons/animals-nature/animal-mammal/cat_color.svg';
import catFace from './icons/animals-nature/animal-mammal/cat-face.svg';
import catFaceColor from './icons/animals-nature/animal-mammal/cat-face_color.svg';
import chipmunk from './icons/animals-nature/animal-mammal/chipmunk.svg';
import chipmunkColor from './icons/animals-nature/animal-mammal/chipmunk_color.svg';
import cow from './icons/animals-nature/animal-mammal/cow.svg';
import cowColor from './icons/animals-nature/animal-mammal/cow_color.svg';
import cowFace from './icons/animals-nature/animal-mammal/cow-face.svg';
import cowFaceColor from './icons/animals-nature/animal-mammal/cow-face_color.svg';
import deer from './icons/animals-nature/animal-mammal/deer.svg';
import deerColor from './icons/animals-nature/animal-mammal/deer_color.svg';
import dog from './icons/animals-nature/animal-mammal/dog.svg';
import dogColor from './icons/animals-nature/animal-mammal/dog_color.svg';
import dogFace from './icons/animals-nature/animal-mammal/dog-face.svg';
import dogFaceColor from './icons/animals-nature/animal-mammal/dog-face_color.svg';
import elephant from './icons/animals-nature/animal-mammal/elephant.svg';
import elephantColor from './icons/animals-nature/animal-mammal/elephant_color.svg';
import ewe from './icons/animals-nature/animal-mammal/ewe.svg';
import eweColor from './icons/animals-nature/animal-mammal/ewe_color.svg';
import fox from './icons/animals-nature/animal-mammal/fox.svg';
import foxColor from './icons/animals-nature/animal-mammal/fox_color.svg';
import giraffe from './icons/animals-nature/animal-mammal/giraffe.svg';
import giraffeColor from './icons/animals-nature/animal-mammal/giraffe_color.svg';
import goat from './icons/animals-nature/animal-mammal/goat.svg';
import goatColor from './icons/animals-nature/animal-mammal/goat_color.svg';
import gorilla from './icons/animals-nature/animal-mammal/gorilla.svg';
import gorillaColor from './icons/animals-nature/animal-mammal/gorilla_color.svg';
import guideDog from './icons/animals-nature/animal-mammal/guide-dog.svg';
import guideDogColor from './icons/animals-nature/animal-mammal/guide-dog_color.svg';
import hamster from './icons/animals-nature/animal-mammal/hamster.svg';
import hamsterColor from './icons/animals-nature/animal-mammal/hamster_color.svg';
import hedgehog from './icons/animals-nature/animal-mammal/hedgehog.svg';
import hedgehogColor from './icons/animals-nature/animal-mammal/hedgehog_color.svg';
import hippopotamus from './icons/animals-nature/animal-mammal/hippopotamus.svg';
import hippopotamusColor from './icons/animals-nature/animal-mammal/hippopotamus_color.svg';
import horse from './icons/animals-nature/animal-mammal/horse.svg';
import horseColor from './icons/animals-nature/animal-mammal/horse_color.svg';
import horseFace from './icons/animals-nature/animal-mammal/horse-face.svg';
import horseFaceColor from './icons/animals-nature/animal-mammal/horse-face_color.svg';
import kangaroo from './icons/animals-nature/animal-mammal/kangaroo.svg';
import kangarooColor from './icons/animals-nature/animal-mammal/kangaroo_color.svg';
import koala from './icons/animals-nature/animal-mammal/koala.svg';
import koalaColor from './icons/animals-nature/animal-mammal/koala_color.svg';
import leopard from './icons/animals-nature/animal-mammal/leopard.svg';
import leopardColor from './icons/animals-nature/animal-mammal/leopard_color.svg';
import lion from './icons/animals-nature/animal-mammal/lion.svg';
import lionColor from './icons/animals-nature/animal-mammal/lion_color.svg';
import llama from './icons/animals-nature/animal-mammal/llama.svg';
import llamaColor from './icons/animals-nature/animal-mammal/llama_color.svg';
import mammoth from './icons/animals-nature/animal-mammal/mammoth.svg';
import mammothColor from './icons/animals-nature/animal-mammal/mammoth_color.svg';
import monkey from './icons/animals-nature/animal-mammal/monkey.svg';
import monkeyColor from './icons/animals-nature/animal-mammal/monkey_color.svg';
import monkeyFace from './icons/animals-nature/animal-mammal/monkey-face.svg';
import monkeyFaceColor from './icons/animals-nature/animal-mammal/monkey-face_color.svg';
import mouse from './icons/animals-nature/animal-mammal/mouse.svg';
import mouseColor from './icons/animals-nature/animal-mammal/mouse_color.svg';
import mouseFace from './icons/animals-nature/animal-mammal/mouse-face.svg';
import mouseFaceColor from './icons/animals-nature/animal-mammal/mouse-face_color.svg';
import orangutan from './icons/animals-nature/animal-mammal/orangutan.svg';
import orangutanColor from './icons/animals-nature/animal-mammal/orangutan_color.svg';
import otter from './icons/animals-nature/animal-mammal/otter.svg';
import otterColor from './icons/animals-nature/animal-mammal/otter_color.svg';
import ox from './icons/animals-nature/animal-mammal/ox.svg';
import oxColor from './icons/animals-nature/animal-mammal/ox_color.svg';
import panda from './icons/animals-nature/animal-mammal/panda.svg';
import pandaColor from './icons/animals-nature/animal-mammal/panda_color.svg';
import pawPrints from './icons/animals-nature/animal-mammal/paw-prints.svg';
import pawPrintsColor from './icons/animals-nature/animal-mammal/paw-prints_color.svg';
import pig from './icons/animals-nature/animal-mammal/pig.svg';
import pigColor from './icons/animals-nature/animal-mammal/pig_color.svg';
import pigFace from './icons/animals-nature/animal-mammal/pig-face.svg';
import pigFaceColor from './icons/animals-nature/animal-mammal/pig-face_color.svg';
import pigNose from './icons/animals-nature/animal-mammal/pig-nose.svg';
import pigNoseColor from './icons/animals-nature/animal-mammal/pig-nose_color.svg';
import polarBear from './icons/animals-nature/animal-mammal/polar-bear.svg';
import polarBearColor from './icons/animals-nature/animal-mammal/polar-bear_color.svg';
import poodle from './icons/animals-nature/animal-mammal/poodle.svg';
import poodleColor from './icons/animals-nature/animal-mammal/poodle_color.svg';
import rabbit from './icons/animals-nature/animal-mammal/rabbit.svg';
import rabbitColor from './icons/animals-nature/animal-mammal/rabbit_color.svg';
import rabbitFace from './icons/animals-nature/animal-mammal/rabbit-face.svg';
import rabbitFaceColor from './icons/animals-nature/animal-mammal/rabbit-face_color.svg';
import raccoon from './icons/animals-nature/animal-mammal/raccoon.svg';
import raccoonColor from './icons/animals-nature/animal-mammal/raccoon_color.svg';
import ram from './icons/animals-nature/animal-mammal/ram.svg';
import ramColor from './icons/animals-nature/animal-mammal/ram_color.svg';
import rat from './icons/animals-nature/animal-mammal/rat.svg';
import ratColor from './icons/animals-nature/animal-mammal/rat_color.svg';
import rhinoceros from './icons/animals-nature/animal-mammal/rhinoceros.svg';
import rhinocerosColor from './icons/animals-nature/animal-mammal/rhinoceros_color.svg';
import serviceDog from './icons/animals-nature/animal-mammal/service-dog.svg';
import serviceDogColor from './icons/animals-nature/animal-mammal/service-dog_color.svg';
import skunk from './icons/animals-nature/animal-mammal/skunk.svg';
import skunkColor from './icons/animals-nature/animal-mammal/skunk_color.svg';
import sloth from './icons/animals-nature/animal-mammal/sloth.svg';
import slothColor from './icons/animals-nature/animal-mammal/sloth_color.svg';
import tiger from './icons/animals-nature/animal-mammal/tiger.svg';
import tigerColor from './icons/animals-nature/animal-mammal/tiger_color.svg';
import tigerFace from './icons/animals-nature/animal-mammal/tiger-face.svg';
import tigerFaceColor from './icons/animals-nature/animal-mammal/tiger-face_color.svg';
import twoHumpCamel from './icons/animals-nature/animal-mammal/two-hump-camel.svg';
import twoHumpCamelColor from './icons/animals-nature/animal-mammal/two-hump-camel_color.svg';
import unicorn from './icons/animals-nature/animal-mammal/unicorn.svg';
import unicornColor from './icons/animals-nature/animal-mammal/unicorn_color.svg';
import waterBuffalo from './icons/animals-nature/animal-mammal/water-buffalo.svg';
import waterBuffaloColor from './icons/animals-nature/animal-mammal/water-buffalo_color.svg';
import wolf from './icons/animals-nature/animal-mammal/wolf.svg';
import wolfColor from './icons/animals-nature/animal-mammal/wolf_color.svg';
import zebra from './icons/animals-nature/animal-mammal/zebra.svg';
import zebraColor from './icons/animals-nature/animal-mammal/zebra_color.svg';
import blowfish from './icons/animals-nature/animal-marine/blowfish.svg';
import blowfishColor from './icons/animals-nature/animal-marine/blowfish_color.svg';
import coral from './icons/animals-nature/animal-marine/coral.svg';
import coralColor from './icons/animals-nature/animal-marine/coral_color.svg';
import dolphin from './icons/animals-nature/animal-marine/dolphin.svg';
import dolphinColor from './icons/animals-nature/animal-marine/dolphin_color.svg';
import fish from './icons/animals-nature/animal-marine/fish.svg';
import fishColor from './icons/animals-nature/animal-marine/fish.svg';
import octopus from './icons/animals-nature/animal-marine/octopus.svg';
import octopusColor from './icons/animals-nature/animal-marine/octopus_color.svg';
import seal from './icons/animals-nature/animal-marine/seal.svg';
import sealColor from './icons/animals-nature/animal-marine/seal_color.svg';
import shark from './icons/animals-nature/animal-marine/shark.svg';
import sharkColor from './icons/animals-nature/animal-marine/shark_color.svg';
import spiralShell from './icons/animals-nature/animal-marine/spiral-shell.svg';
import spiralShellColor from './icons/animals-nature/animal-marine/spiral-shell_color.svg';
import spoutingWhale from './icons/animals-nature/animal-marine/spouting-whale.svg';
import spoutingWhaleColor from './icons/animals-nature/animal-marine/spouting-whale_color.svg';
import tropicalFish from './icons/animals-nature/animal-marine/tropical-fish.svg';
import tropicalFishColor from './icons/animals-nature/animal-marine/tropical-fish_color.svg';
import whale from './icons/animals-nature/animal-marine/whale.svg';
import whaleColor from './icons/animals-nature/animal-marine/whale_color.svg';
import crocodile from './icons/animals-nature/animal-reptile/crocodile.svg';
import crocodileColor from './icons/animals-nature/animal-reptile/crocodile_color.svg';
import dragon from './icons/animals-nature/animal-reptile/dragon.svg';
import dragonColor from './icons/animals-nature/animal-reptile/dragon_color.svg';
import dragonFace from './icons/animals-nature/animal-reptile/dragon-face.svg';
import dragonFaceColor from './icons/animals-nature/animal-reptile/dragon-face_color.svg';
import lizard from './icons/animals-nature/animal-reptile/lizard.svg';
import lizardColor from './icons/animals-nature/animal-reptile/lizard_color.svg';
import sauropod from './icons/animals-nature/animal-reptile/sauropod.svg';
import sauropodColor from './icons/animals-nature/animal-reptile/sauropod_color.svg';
import snake from './icons/animals-nature/animal-reptile/snake.svg';
import snakeColor from './icons/animals-nature/animal-reptile/snake_color.svg';
import TRex from './icons/animals-nature/animal-reptile/T-Rex.svg';
import TRexColor from './icons/animals-nature/animal-reptile/T-Rex_color.svg';
import turtle from './icons/animals-nature/animal-reptile/turtle.svg';
import turtleColor from './icons/animals-nature/animal-reptile/turtle_color.svg';
import blossom from './icons/animals-nature/plant-flower/blossom.svg';
import blossomColor from './icons/animals-nature/plant-flower/blossom_color.svg';
import bouquet from './icons/animals-nature/plant-flower/bouquet.svg';
import bouquetColor from './icons/animals-nature/plant-flower/bouquet_color.svg';
import cherryBlossom from './icons/animals-nature/plant-flower/cherry-blossom.svg';
import cherryBlossomColor from './icons/animals-nature/plant-flower/cherry-blossom_color.svg';
import hibiscus from './icons/animals-nature/plant-flower/hibiscus.svg';
import hibiscusColor from './icons/animals-nature/plant-flower/hibiscus_color.svg';
import lotus from './icons/animals-nature/plant-flower/lotus.svg';
import lotusColor from './icons/animals-nature/plant-flower/lotus_color.svg';
import rose from './icons/animals-nature/plant-flower/rose.svg';
import roseColor from './icons/animals-nature/plant-flower/rose_color.svg';
import rosette from './icons/animals-nature/plant-flower/rosette.svg';
import rosetteColor from './icons/animals-nature/plant-flower/rosette_color.svg';
import sunflower from './icons/animals-nature/plant-flower/sunflower.svg';
import sunflowerColor from './icons/animals-nature/plant-flower/sunflower_color.svg';
import tulip from './icons/animals-nature/plant-flower/tulip.svg';
import tulipColor from './icons/animals-nature/plant-flower/tulip_color.svg';
import whiteFlower from './icons/animals-nature/plant-flower/white-flower.svg';
import whiteFlowerColor from './icons/animals-nature/plant-flower/white-flower_color.svg';
import wiltedFlower from './icons/animals-nature/plant-flower/wilted-flower.svg';
import wiltedFlowerColor from './icons/animals-nature/plant-flower/wilted-flower_color.svg';
import cactus from './icons/animals-nature/plant-other/cactus.svg';
import cactusColor from './icons/animals-nature/plant-other/cactus_color.svg';
import deciduousTree from './icons/animals-nature/plant-other/deciduous-tree.svg';
import deciduousTreeColor from './icons/animals-nature/plant-other/deciduous-tree_color.svg';
import emptyNest from './icons/animals-nature/plant-other/empty-nest.svg';
import emptyNestColor from './icons/animals-nature/plant-other/empty-nest_color.svg';
import evergreenTree from './icons/animals-nature/plant-other/evergreen-tree.svg';
import evergreenTreeColor from './icons/animals-nature/plant-other/evergreen-tree_color.svg';
import fallenLeaf from './icons/animals-nature/plant-other/fallen-leaf.svg';
import fallenLeafColor from './icons/animals-nature/plant-other/fallen-leaf_color.svg';
import fourLeafClover from './icons/animals-nature/plant-other/four-leaf-clover.svg';
import fourLeafCloverColor from './icons/animals-nature/plant-other/four-leaf-clover_color.svg';
import herb from './icons/animals-nature/plant-other/herb.svg';
import herbColor from './icons/animals-nature/plant-other/herb_color.svg';
import leafFlutteringInWind from './icons/animals-nature/plant-other/leaf-fluttering-in-wind.svg';
import leafFlutteringInWindColor from './icons/animals-nature/plant-other/leaf-fluttering-in-wind_color.svg';
import mapleLeaf from './icons/animals-nature/plant-other/maple-leaf.svg';
import mapleLeafColor from './icons/animals-nature/plant-other/maple-leaf_color.svg';
import nestWithEggs from './icons/animals-nature/plant-other/nest-with-eggs.svg';
import nestWithEggsColor from './icons/animals-nature/plant-other/nest-with-eggs_color.svg';
import palmTree from './icons/animals-nature/plant-other/palm-tree.svg';
import palmTreeColor from './icons/animals-nature/plant-other/palm-tree_color.svg';
import pottedPlant from './icons/animals-nature/plant-other/potted-plant.svg';
import pottedPlantColor from './icons/animals-nature/plant-other/potted-plant_color.svg';
import seedling from './icons/animals-nature/plant-other/seedling.svg';
import seedlingColor from './icons/animals-nature/plant-other/seedling_color.svg';
import shamrock from './icons/animals-nature/plant-other/shamrock.svg';
import shamrockColor from './icons/animals-nature/plant-other/shamrock_color.svg';
import sheafOfRice from './icons/animals-nature/plant-other/sheaf-of-rice.svg';
import sheafOfRiceColor from './icons/animals-nature/plant-other/sheaf-of-rice_color.svg';

import {IconProps} from './use-search';

export const openAnimalNatureTable = new Map<string, Omit<IconProps, 'id'>>();

openAnimalNatureTable.set('frog', {name: 'Frog', icon: frog});
openAnimalNatureTable.set('frogColor', {name: 'Frog Color', icon: frogColor});
openAnimalNatureTable.set('babyChick', {name: 'Baby Chick', icon: babyChick});
openAnimalNatureTable.set('babyChickColor', {name: 'Baby Chick Color', icon: babyChickColor});
openAnimalNatureTable.set('bird', {name: 'Bird', icon: bird});
openAnimalNatureTable.set('birdColor', {name: 'Bird Color', icon: birdColor});
openAnimalNatureTable.set('chicken', {name: 'Chicken', icon: chicken});
openAnimalNatureTable.set('chickenColor', {name: 'Chicken Color', icon: chickenColor});
openAnimalNatureTable.set('dodo', {name: 'Dodo', icon: dodo});
openAnimalNatureTable.set('dodoColor', {name: 'Dodo Color', icon: dodoColor});
openAnimalNatureTable.set('dove', {name: 'Dove', icon: dove});
openAnimalNatureTable.set('doveColor', {name: 'Dove Color', icon: doveColor});
openAnimalNatureTable.set('duck', {name: 'Duck', icon: duck});
openAnimalNatureTable.set('duckColor', {name: 'Duck Color', icon: duckColor});
openAnimalNatureTable.set('eagle', {name: 'Eagle', icon: eagle});
openAnimalNatureTable.set('eagleColor', {name: 'Eagle Color', icon: eagleColor});
openAnimalNatureTable.set('feather', {name: 'Feather', icon: feather});
openAnimalNatureTable.set('featherColor', {name: 'Feather Color', icon: featherColor});
openAnimalNatureTable.set('flamingo', {name: 'Flamingo', icon: flamingo});
openAnimalNatureTable.set('flamingoColor', {name: 'Flamingo Color', icon: flamingoColor});
openAnimalNatureTable.set('frontFacingBabyChick', {name: 'Front Facing Baby Chick', icon: frontFacingBabyChick});
openAnimalNatureTable.set('frontFacingBabyChickColor', {
    name: 'Front Facing Baby Chick Color',
    icon: frontFacingBabyChickColor,
});
openAnimalNatureTable.set('hatchingChick', {name: 'Hatching Chick', icon: hatchingChick});
openAnimalNatureTable.set('hatchingChickColor', {name: 'Hatching Chick Color', icon: hatchingChickColor});
openAnimalNatureTable.set('owl', {name: 'Owl', icon: owl});
openAnimalNatureTable.set('owlColor', {name: 'Owl Color', icon: owlColor});
openAnimalNatureTable.set('parrot', {name: 'Parrot', icon: parrot});
openAnimalNatureTable.set('parrotColor', {name: 'Parrot Color', icon: parrotColor});
openAnimalNatureTable.set('peacock', {name: 'Peacock', icon: peacock});
openAnimalNatureTable.set('peacockColor', {name: 'Peacock Color', icon: peacockColor});
openAnimalNatureTable.set('penguin', {name: 'Penguin', icon: penguin});
openAnimalNatureTable.set('penguinColor', {name: 'Penguin Color', icon: penguinColor});
openAnimalNatureTable.set('rooster', {name: 'Rooster', icon: rooster});
openAnimalNatureTable.set('roosterColor', {name: 'Rooster Color', icon: roosterColor});
openAnimalNatureTable.set('swan', {name: 'Swan', icon: swan});
openAnimalNatureTable.set('swanColor', {name: 'Swan Color', icon: swanColor});
openAnimalNatureTable.set('turkey', {name: 'Turkey', icon: turkey});
openAnimalNatureTable.set('turkeyColor', {name: 'Turkey Color', icon: turkeyColor});
openAnimalNatureTable.set('ant', {name: 'Ant', icon: ant});
openAnimalNatureTable.set('antColor', {name: 'Ant Color', icon: antColor});
openAnimalNatureTable.set('beetle', {name: 'Beetle', icon: beetle});
openAnimalNatureTable.set('beetleColor', {name: 'Beetle Color', icon: beetleColor});
openAnimalNatureTable.set('bug', {name: 'Bug', icon: bug});
openAnimalNatureTable.set('bugColor', {name: 'Bug Color', icon: bugColor});
openAnimalNatureTable.set('butterfly', {name: 'Butterfly', icon: butterfly});
openAnimalNatureTable.set('butterflyColor', {name: 'Butterfly Color', icon: butterflyColor});
openAnimalNatureTable.set('cockroach', {name: 'Cockroach', icon: cockroach});
openAnimalNatureTable.set('cockroachColor', {name: 'Cockroach Color', icon: cockroachColor});
openAnimalNatureTable.set('cricket', {name: 'Cricket', icon: cricket});
openAnimalNatureTable.set('cricketColor', {name: 'Cricket Color', icon: cricketColor});
openAnimalNatureTable.set('fly', {name: 'Fly', icon: fly});
openAnimalNatureTable.set('flyColor', {name: 'Fly Color', icon: flyColor});
openAnimalNatureTable.set('honeybee', {name: 'Honeybee', icon: honeybee});
openAnimalNatureTable.set('honeybeeColor', {name: 'Honeybee Color', icon: honeybeeColor});
openAnimalNatureTable.set('ladyBeetle', {name: 'Lady Beetle', icon: ladyBeetle});
openAnimalNatureTable.set('ladyBeetleColor', {name: 'Lady Beetle Color', icon: ladyBeetleColor});
openAnimalNatureTable.set('microbe', {name: 'Microbe', icon: microbe});
openAnimalNatureTable.set('microbeColor', {name: 'Microbe Color', icon: microbeColor});
openAnimalNatureTable.set('mosquito', {name: 'Mosquito', icon: mosquito});
openAnimalNatureTable.set('mosquitoColor', {name: 'Mosquito COlor', icon: mosquitoColor});
openAnimalNatureTable.set('scorpion', {name: 'Scorpion', icon: scorpion});
openAnimalNatureTable.set('scorpionColor', {name: 'Scorpion Color', icon: scorpionColor});
openAnimalNatureTable.set('snail', {name: 'Snail', icon: snail});
openAnimalNatureTable.set('snailColor', {name: 'Snail Color', icon: snailColor});
openAnimalNatureTable.set('spider', {name: 'Spider', icon: spider});
openAnimalNatureTable.set('spiderColor', {name: 'Spider Color', icon: spiderColor});
openAnimalNatureTable.set('spiderWeb', {name: 'Spider Web', icon: spiderWeb});
openAnimalNatureTable.set('spiderWebColor', {name: 'Spider Web Color', icon: spiderWebColor});
openAnimalNatureTable.set('worm', {name: 'Worm', icon: worm});
openAnimalNatureTable.set('wormColor', {name: 'Worm Color', icon: wormColor});
openAnimalNatureTable.set('badger', {name: 'Badger', icon: badger});
openAnimalNatureTable.set('badgerColor', {name: 'Badger Color', icon: badgerColor});
openAnimalNatureTable.set('bat', {name: 'Bat', icon: bat});
openAnimalNatureTable.set('batColor', {name: 'Bat Color', icon: batColor});
openAnimalNatureTable.set('bear', {name: 'Bear', icon: bear});
openAnimalNatureTable.set('bearColor', {name: 'Bear Color', icon: bearColor});
openAnimalNatureTable.set('beaver', {name: 'Beaver', icon: beaver});
openAnimalNatureTable.set('beaverColor', {name: 'Beaver Color', icon: beaverColor});
openAnimalNatureTable.set('bison', {name: 'Bison', icon: bison});
openAnimalNatureTable.set('bisonCOlor', {name: 'Bison COlor', icon: bisonColor});
openAnimalNatureTable.set('blackCat', {name: 'Black Cat', icon: blackCat});
openAnimalNatureTable.set('blackCatColor', {name: 'Black Cat Color', icon: blackCatColor});
openAnimalNatureTable.set('boar', {name: 'Boar', icon: boar});
openAnimalNatureTable.set('boarColor', {name: 'BoarCOlor', icon: boarColor});
openAnimalNatureTable.set('camel', {name: 'Camel', icon: camel});
openAnimalNatureTable.set('camelColor', {name: 'Camel Color', icon: camelColor});
openAnimalNatureTable.set('cat', {name: 'Cat', icon: cat});
openAnimalNatureTable.set('catColor', {name: 'Cat Color', icon: catColor});
openAnimalNatureTable.set('catFace', {name: 'Cat Face', icon: catFace});
openAnimalNatureTable.set('catFaceColor', {name: 'Cat Face Color', icon: catFaceColor});
openAnimalNatureTable.set('chipmunk', {name: 'Chipmunk', icon: chipmunk});
openAnimalNatureTable.set('chipmunkColor', {name: 'Chipmunk Color', icon: chipmunkColor});
openAnimalNatureTable.set('cow', {name: 'Cow', icon: cow});
openAnimalNatureTable.set('cowColor', {name: 'Cow Color', icon: cowColor});
openAnimalNatureTable.set('cowFace', {name: 'Cow Face', icon: cowFace});
openAnimalNatureTable.set('cowFaceColor', {name: 'Cow Face Color', icon: cowFaceColor});
openAnimalNatureTable.set('deer', {name: 'Deer', icon: deer});
openAnimalNatureTable.set('deerColor', {name: 'Deer Color', icon: deerColor});
openAnimalNatureTable.set('dog', {name: 'Dog', icon: dog});
openAnimalNatureTable.set('dogColor', {name: 'Dog Color', icon: dogColor});
openAnimalNatureTable.set('dogFace', {name: 'Dog Face', icon: dogFace});
openAnimalNatureTable.set('dogFaceColor', {name: 'Dog Face Color', icon: dogFaceColor});
openAnimalNatureTable.set('elephant', {name: 'Elephant', icon: elephant});
openAnimalNatureTable.set('elephantColor', {name: 'Elephant Color', icon: elephantColor});
openAnimalNatureTable.set('ewe', {name: 'Ewe', icon: ewe});
openAnimalNatureTable.set('eweColor', {name: 'Ewe Color', icon: eweColor});
openAnimalNatureTable.set('fox', {name: 'Fox', icon: fox});
openAnimalNatureTable.set('foxColor', {name: 'Fox Color', icon: foxColor});
openAnimalNatureTable.set('giraffe', {name: 'Giraffe', icon: giraffe});
openAnimalNatureTable.set('giraffeColor', {name: 'Giraffe Color', icon: giraffeColor});
openAnimalNatureTable.set('goat', {name: 'Goat', icon: goat});
openAnimalNatureTable.set('goatColor', {name: 'Goat Color', icon: goatColor});
openAnimalNatureTable.set('gorilla', {name: 'Gorilla', icon: gorilla});
openAnimalNatureTable.set('gorillaColor', {name: 'Gorilla Color', icon: gorillaColor});
openAnimalNatureTable.set('guideDog', {name: 'Guide Dog', icon: guideDog});
openAnimalNatureTable.set('guideDogColor', {name: 'Guide Dog Color', icon: guideDogColor});
openAnimalNatureTable.set('hamster', {name: 'Hamster', icon: hamster});
openAnimalNatureTable.set('hamsterColor', {name: 'Hamster Color', icon: hamsterColor});
openAnimalNatureTable.set('hedgehog', {name: 'Hedgehog', icon: hedgehog});
openAnimalNatureTable.set('hedgehogColor', {name: 'Hedgehog', icon: hedgehogColor});
openAnimalNatureTable.set('hippopotamus', {name: 'Hippopotamus', icon: hippopotamus});
openAnimalNatureTable.set('hippopotamusColor', {name: 'Hippopotamus Color', icon: hippopotamusColor});
openAnimalNatureTable.set('horse', {name: 'Horse', icon: horse});
openAnimalNatureTable.set('horseColor', {name: 'Horse Color', icon: horseColor});
openAnimalNatureTable.set('horseFace', {name: 'Horse Face', icon: horseFace});
openAnimalNatureTable.set('horseFaceColor', {name: 'Horse Face Color', icon: horseFaceColor});
openAnimalNatureTable.set('kangaroo', {name: 'Kangaroo', icon: kangaroo});
openAnimalNatureTable.set('kangarooColor', {name: 'Kangaroo Color', icon: kangarooColor});
openAnimalNatureTable.set('koala', {name: 'Koala', icon: koala});
openAnimalNatureTable.set('koalaColor', {name: 'Koala Color', icon: koalaColor});
openAnimalNatureTable.set('leopard', {name: 'Leopard', icon: leopard});
openAnimalNatureTable.set('leopardColor', {name: 'Leopard Color', icon: leopardColor});
openAnimalNatureTable.set('lion', {name: 'Lion', icon: lion});
openAnimalNatureTable.set('lionColor', {name: 'Lion Color', icon: lionColor});
openAnimalNatureTable.set('llama', {name: 'Llama', icon: llama});
openAnimalNatureTable.set('llamaColor', {name: 'Llama Color', icon: llamaColor});
openAnimalNatureTable.set('mammoth', {name: 'Mammoth', icon: mammoth});
openAnimalNatureTable.set('mammothColor', {name: 'Mammoth Color', icon: mammothColor});
openAnimalNatureTable.set('monkey', {name: 'Monkey', icon: monkey});
openAnimalNatureTable.set('monkeyColor', {name: 'Monkey Color', icon: monkeyColor});
openAnimalNatureTable.set('monkeyFace', {name: 'Monkey Face', icon: monkeyFace});
openAnimalNatureTable.set('monkeyFaceColor', {name: 'Monkey Face Color', icon: monkeyFaceColor});
openAnimalNatureTable.set('mouse', {name: 'Mouse', icon: mouse});
openAnimalNatureTable.set('mouseColor', {name: 'Mouse Color', icon: mouseColor});
openAnimalNatureTable.set('mouseFace', {name: 'Mouse Face', icon: mouseFace});
openAnimalNatureTable.set('mouseFaceColor', {name: 'Mouse Face Color', icon: mouseFaceColor});
openAnimalNatureTable.set('orangutan', {name: 'Orangutan', icon: orangutan});
openAnimalNatureTable.set('orangutanColor', {name: 'Orangutan Color', icon: orangutanColor});
openAnimalNatureTable.set('otter', {name: 'Otter', icon: otter});
openAnimalNatureTable.set('otterCOlor', {name: 'Otter Color', icon: otterColor});
openAnimalNatureTable.set('ox', {name: 'Ox', icon: ox});
openAnimalNatureTable.set('oxColor', {name: 'Ox Color', icon: oxColor});
openAnimalNatureTable.set('panda', {name: 'Panda', icon: panda});
openAnimalNatureTable.set('pandaColor', {name: 'Panda Color', icon: pandaColor});
openAnimalNatureTable.set('pawPrints', {name: 'Paw Prints', icon: pawPrints});
openAnimalNatureTable.set('pawPrintsColor', {name: 'Paw Prints Color', icon: pawPrintsColor});
openAnimalNatureTable.set('pig', {name: 'Pig', icon: pig});
openAnimalNatureTable.set('pigColor', {name: 'Pig Color', icon: pigColor});
openAnimalNatureTable.set('pigFace', {name: 'Pig Face', icon: pigFace});
openAnimalNatureTable.set('pigFaceColor', {name: 'Pig Face Color', icon: pigFaceColor});
openAnimalNatureTable.set('pigNose', {name: 'Pig Nose', icon: pigNose});
openAnimalNatureTable.set('pigNoseColor', {name: 'Pig Nose Color', icon: pigNoseColor});
openAnimalNatureTable.set('polarBear', {name: 'Polar Bear', icon: polarBear});
openAnimalNatureTable.set('polarBearColor', {name: 'Polar Bear Color', icon: polarBearColor});
openAnimalNatureTable.set('poodle', {name: 'Poodle', icon: poodle});
openAnimalNatureTable.set('poodleColor', {name: 'Poodle Color', icon: poodleColor});
openAnimalNatureTable.set('rabbit', {name: 'Rabbit', icon: rabbit});
openAnimalNatureTable.set('rabbitColor', {name: 'Rabbit Color', icon: rabbitColor});
openAnimalNatureTable.set('rabbitFace', {name: 'Rabbit Face', icon: rabbitFace});
openAnimalNatureTable.set('rabbitFaceColor', {name: 'Rabbit Face Color', icon: rabbitFaceColor});
openAnimalNatureTable.set('raccoon', {name: 'Raccoon', icon: raccoon});
openAnimalNatureTable.set('raccoonColor', {name: 'Raccoon Color', icon: raccoonColor});
openAnimalNatureTable.set('ram', {name: 'Ram', icon: ram});
openAnimalNatureTable.set('ramColor', {name: 'Ram Color', icon: ramColor});
openAnimalNatureTable.set('rat', {name: 'Rat', icon: rat});
openAnimalNatureTable.set('ratColor', {name: 'Rat Color', icon: ratColor});
openAnimalNatureTable.set('rhinoceros', {name: 'Rhinoceros', icon: rhinoceros});
openAnimalNatureTable.set('rhinocerosColor', {name: 'Rhinoceros Color', icon: rhinocerosColor});
openAnimalNatureTable.set('serviceDog', {name: 'Service Dog', icon: serviceDog});
openAnimalNatureTable.set('serviceDogColor', {name: 'Service Dog Color', icon: serviceDogColor});
openAnimalNatureTable.set('skunk', {name: 'Skunk', icon: skunk});
openAnimalNatureTable.set('skunkColor', {name: 'Skunk Color', icon: skunkColor});
openAnimalNatureTable.set('sloth', {name: 'Sloth', icon: sloth});
openAnimalNatureTable.set('slothColor', {name: 'Sloth Color', icon: slothColor});
openAnimalNatureTable.set('tiger', {name: 'Tiger', icon: tiger});
openAnimalNatureTable.set('tigerColor', {name: 'Tiger Color', icon: tigerColor});
openAnimalNatureTable.set('tigerFace', {name: 'Tiger Face', icon: tigerFace});
openAnimalNatureTable.set('tigerFaceColor', {name: 'Tiger Face Color', icon: tigerFaceColor});
openAnimalNatureTable.set('twoHumpCamel', {name: 'Two Hump Camel', icon: twoHumpCamel});
openAnimalNatureTable.set('twoHumpCamelColor', {name: 'Two Hump Camel Color', icon: twoHumpCamelColor});
openAnimalNatureTable.set('unicorn', {name: 'Unicorn', icon: unicorn});
openAnimalNatureTable.set('unicornColor', {name: 'Unicorn Color', icon: unicornColor});
openAnimalNatureTable.set('waterBuffalo', {name: 'Water Buffalo', icon: waterBuffalo});
openAnimalNatureTable.set('waterBuffaloColor', {name: 'Water Buffalo Color', icon: waterBuffaloColor});
openAnimalNatureTable.set('wolf', {name: 'Wolf', icon: wolf});
openAnimalNatureTable.set('wolfColor', {name: 'Wolf Color', icon: wolfColor});
openAnimalNatureTable.set('zebra', {name: 'Zebra', icon: zebra});
openAnimalNatureTable.set('zebraColor', {name: 'Zebra Color', icon: zebraColor});
openAnimalNatureTable.set('blowfish', {name: 'Blow Fish', icon: blowfish});
openAnimalNatureTable.set('blowfishColor', {name: 'Blow Fish Color', icon: blowfishColor});
openAnimalNatureTable.set('coral', {name: 'Coral', icon: coral});
openAnimalNatureTable.set('coralColor', {name: 'Coral Color', icon: coralColor});
openAnimalNatureTable.set('dolphin', {name: 'Dolphin', icon: dolphin});
openAnimalNatureTable.set('dolphinColor', {name: 'Dolphin Color', icon: dolphinColor});
openAnimalNatureTable.set('fish', {name: 'Fish', icon: fish});
openAnimalNatureTable.set('fishColor', {name: 'Fish Color', icon: fishColor});
openAnimalNatureTable.set('octopus', {name: 'Octopus', icon: octopus});
openAnimalNatureTable.set('octopusColor', {name: 'Octopus Color', icon: octopusColor});
openAnimalNatureTable.set('seal', {name: 'Seal', icon: seal});
openAnimalNatureTable.set('sealColor', {name: 'Seal Color', icon: sealColor});
openAnimalNatureTable.set('shark', {name: 'Shark', icon: shark});
openAnimalNatureTable.set('sharkColor', {name: 'Shark Color', icon: sharkColor});
openAnimalNatureTable.set('spiralShell', {name: 'Spiral Shell', icon: spiralShell});
openAnimalNatureTable.set('spiralShellColor', {name: 'Spiral Shell Color', icon: spiralShellColor});
openAnimalNatureTable.set('spoutingWhale', {name: 'Spouting Whale', icon: spoutingWhale});
openAnimalNatureTable.set('spoutingWhaleColor', {name: 'Spouting Whale Color', icon: spoutingWhaleColor});
openAnimalNatureTable.set('tropicalFish', {name: 'Tropical Fish', icon: tropicalFish});
openAnimalNatureTable.set('tropicalFishColor', {name: 'Tropical Fish Color', icon: tropicalFishColor});
openAnimalNatureTable.set('whale', {name: 'Whale', icon: whale});
openAnimalNatureTable.set('whaleColor', {name: 'Whale Color', icon: whaleColor});
openAnimalNatureTable.set('crocodile', {name: 'Crocodile', icon: crocodile});
openAnimalNatureTable.set('crocodileColor', {name: 'Crocodile Color', icon: crocodileColor});
openAnimalNatureTable.set('dragon', {name: 'Dragon', icon: dragon});
openAnimalNatureTable.set('dragonColor', {name: 'Dragon Color', icon: dragonColor});
openAnimalNatureTable.set('dragonFace', {name: 'Dragon Face', icon: dragonFace});
openAnimalNatureTable.set('dragonFaceColor', {name: 'Dragon Face Color', icon: dragonFaceColor});
openAnimalNatureTable.set('lizard', {name: 'Lizard', icon: lizard});
openAnimalNatureTable.set('lizardColor', {name: 'Lizard Color', icon: lizardColor});
openAnimalNatureTable.set('sauropod', {name: 'Sauropod', icon: sauropod});
openAnimalNatureTable.set('sauropodColor', {name: 'Sauropod Color', icon: sauropodColor});
openAnimalNatureTable.set('snake', {name: 'Snake', icon: snake});
openAnimalNatureTable.set('snakeColor', {name: 'Snake Color', icon: snakeColor});
openAnimalNatureTable.set('TRex', {name: 'T Rex', icon: TRex});
openAnimalNatureTable.set('TRexColor', {name: 'T Rex Color', icon: TRexColor});
openAnimalNatureTable.set('turtle', {name: 'Turtle', icon: turtle});
openAnimalNatureTable.set('turtleColor', {name: 'Turtle Color', icon: turtleColor});
openAnimalNatureTable.set('blossom', {name: 'Blossom', icon: blossom});
openAnimalNatureTable.set('blossomColor', {name: 'Blossom Color', icon: blossomColor});
openAnimalNatureTable.set('bouquet', {name: 'Bouquet', icon: bouquet});
openAnimalNatureTable.set('bouquetColor', {name: 'Bouquet Color', icon: bouquetColor});
openAnimalNatureTable.set('cherryBlossom', {name: 'Cherry Blossom', icon: cherryBlossom});
openAnimalNatureTable.set('cherryBlossomColor', {name: 'Cherry Blossom Color', icon: cherryBlossomColor});
openAnimalNatureTable.set('hibiscus', {name: 'Hibiscus', icon: hibiscus});
openAnimalNatureTable.set('hibiscusColor', {name: 'Hibiscus Color', icon: hibiscusColor});
openAnimalNatureTable.set('lotus', {name: 'Lotus', icon: lotus});
openAnimalNatureTable.set('lotusColor', {name: 'Lotus Color', icon: lotusColor});
openAnimalNatureTable.set('rose', {name: 'Rose', icon: rose});
openAnimalNatureTable.set('roseColor', {name: 'Rose Color', icon: roseColor});
openAnimalNatureTable.set('rosette', {name: 'Rosette', icon: rosette});
openAnimalNatureTable.set('rosetteColor', {name: 'Rosette Color', icon: rosetteColor});
openAnimalNatureTable.set('sunflower', {name: 'Sunflower', icon: sunflower});
openAnimalNatureTable.set('sunflowerColor', {name: 'Sunflower Color', icon: sunflowerColor});
openAnimalNatureTable.set('tulip', {name: 'Tulip', icon: tulip});
openAnimalNatureTable.set('tulipColor', {name: 'Tulip Color', icon: tulipColor});
openAnimalNatureTable.set('whiteFlower', {name: 'White Flower', icon: whiteFlower});
openAnimalNatureTable.set('whiteFlowerColor', {name: 'White Flower Color', icon: whiteFlowerColor});
openAnimalNatureTable.set('wiltedFlower', {name: 'Wilted Flower', icon: wiltedFlower});
openAnimalNatureTable.set('wiltedFlowerColor', {name: 'Wilted Flower Color', icon: wiltedFlowerColor});
openAnimalNatureTable.set('cactus', {name: 'Cactus', icon: cactus});
openAnimalNatureTable.set('cactusColor', {name: 'Cactus Color', icon: cactusColor});
openAnimalNatureTable.set('deciduousTree', {name: 'Deciduous Tree', icon: deciduousTree});
openAnimalNatureTable.set('deciduousTreeColor', {name: 'Deciduous Tree Color', icon: deciduousTreeColor});
openAnimalNatureTable.set('emptyNest', {name: 'Empty Nest', icon: emptyNest});
openAnimalNatureTable.set('emptyNestColor', {name: 'Empty Nest Color', icon: emptyNestColor});
openAnimalNatureTable.set('evergreenTree', {name: 'Evergreen Tree', icon: evergreenTree});
openAnimalNatureTable.set('evergreenTreeColor', {name: 'Evergreen Tree Color', icon: evergreenTreeColor});
openAnimalNatureTable.set('fallenLeaf', {name: 'Fallen Leaf', icon: fallenLeaf});
openAnimalNatureTable.set('fallenLeafColor', {name: 'Fallen Leaf Color', icon: fallenLeafColor});
openAnimalNatureTable.set('fourLeafClover', {name: 'Four Leaf Clover', icon: fourLeafClover});
openAnimalNatureTable.set('fourLeafCloverColor', {name: 'Four Leaf Clover Color', icon: fourLeafCloverColor});
openAnimalNatureTable.set('herb', {name: 'Herb', icon: herb});
openAnimalNatureTable.set('herbColor', {name: 'Herb Color', icon: herbColor});
openAnimalNatureTable.set('leafFlutteringInWind', {name: 'Leaf Fluttering In Wind', icon: leafFlutteringInWind});
openAnimalNatureTable.set('leafFlutteringInWindColor', {
    name: 'Leaf Fluttering In Wind Color',
    icon: leafFlutteringInWindColor,
});
openAnimalNatureTable.set('mapleLeaf', {name: 'Maple Leaf', icon: mapleLeaf});
openAnimalNatureTable.set('mapleLeafColor', {name: 'Maple Leaf Color', icon: mapleLeafColor});
openAnimalNatureTable.set('nestWithEggs', {name: 'Nest With Eggs', icon: nestWithEggs});
openAnimalNatureTable.set('nestWithEggsColor', {name: 'Nest With Eggs Color', icon: nestWithEggsColor});
openAnimalNatureTable.set('palmTree', {name: 'Palm Tree', icon: palmTree});
openAnimalNatureTable.set('palmTreeColor', {name: 'Palm Tree', icon: palmTreeColor});
openAnimalNatureTable.set('pottedPlant', {name: 'Potted Plant', icon: pottedPlant});
openAnimalNatureTable.set('pottedPlantColor', {name: 'Potted Plant Color', icon: pottedPlantColor});
openAnimalNatureTable.set('seedling', {name: 'Seedling', icon: seedling});
openAnimalNatureTable.set('seedlingColor', {name: 'Seedling Color', icon: seedlingColor});
openAnimalNatureTable.set('shamrock', {name: 'Shamrock', icon: shamrock});
openAnimalNatureTable.set('shamrockColor', {name: 'Shamrock Color', icon: shamrockColor});
openAnimalNatureTable.set('sheafOfRice', {name: 'Sheaf Of Rice', icon: sheafOfRice});
openAnimalNatureTable.set('sheafOfRiceColor', {name: 'Sheaf Of Rice Color', icon: sheafOfRiceColor});

export const OA_ICON_SIZE = openAnimalNatureTable.size;
