import artistPallete from './icons/activities/arts-crafts/artist-palette.svg'
import artistPalleteColor from './icons/activities/arts-crafts/artist-palette_color.svg'
import framedPicture from './icons/activities/arts-crafts/framed-picture.svg'
import framedPictureColor from './icons/activities/arts-crafts/framed-picture_color.svg'
import knot from './icons/activities/arts-crafts/knot.svg'
import knotColor from './icons/activities/arts-crafts/knot_color.svg'
import performingArts from './icons/activities/arts-crafts/performing-arts.svg'
import performingArtsColor from './icons/activities/arts-crafts/performing-arts_color.svg'
import sewingNeedle from './icons/activities/arts-crafts/sewing-needle.svg'
import sewingNeedleColor from './icons/activities/arts-crafts/sewing-needle_color.svg'
import thread from './icons/activities/arts-crafts/thread.svg'
import threadColor from './icons/activities/arts-crafts/thread_color.svg'
import yarn from './icons/activities/arts-crafts/yarn.svg'
import yarnColor from './icons/activities/arts-crafts/yarn_color.svg'
import firstPlaceMedal from './icons/activities/award-medal/1st-place-medal.svg'
import firstPlaceMedalColor from './icons/activities/award-medal/1st-place-medal_color.svg'
import secondPlaceMedal from './icons/activities/award-medal/2nd-place-medal.svg'
import secondPlaceMedalColor from './icons/activities/award-medal/2nd-place-medal_color.svg'
import thirdPlaceMedal from './icons/activities/award-medal/3rd-place-medal.svg'
import thirdPlaceMedalColor from './icons/activities/award-medal/3rd-place-medal_color.svg'
import militaryMedal from './icons/activities/award-medal/military-medal.svg'
import militaryMedalColor from './icons/activities/award-medal/military-medal_color.svg'
import sportsMedal from'./icons/activities/award-medal/sports-medal.svg'
import sportsMedalColor from './icons/activities/award-medal/sports-medal_color.svg'
import trophy from './icons/activities/award-medal/trophy.svg'
import trophyColor from './icons/activities/award-medal/trophy_color.svg'
import admissionTickets from './icons/activities/event/admission-tickets.svg'
import admissionTicketsColor from './icons/activities/event/admission-tickets_color.svg'
import balloon from './icons/activities/event/balloon.svg'
import balloonColor from './icons/activities/event/balloon_color.svg'
import carpStreamer from './icons/activities/event/carp-streamer.svg'
import carpStreamerColor from './icons/activities/event/carp-streamer_color.svg'
import christmasTree from './icons/activities/event/Christmas-tree.svg'
import christmasTreeColor from './icons/activities/event/Christmas-tree_color.svg'
import confettiBall from './icons/activities/event/confetti-ball.svg'
import confettiBallColor from './icons/activities/event/confetti-ball_color.svg'
import fireCracker from './icons/activities/event/firecracker.svg'
import fireCrackerColor from './icons/activities/event/firecracker_color.svg'
import fireWorks from './icons/activities/event/fireworks.svg'
import fireWorksColor from './icons/activities/event/fireworks_color.svg'
import jackOLantern from './icons/activities/event/jack-o-lantern.svg'
import jackOLanternColor from './icons/activities/event/jack-o-lantern_color.svg'
import japaneseDolls from './icons/activities/event/Japanese-dolls.svg'
import japaneseDollsColor from './icons/activities/event/Japanese-dolls_color.svg'
import moonViewingCeremony from './icons/activities/event/moon-viewing-ceremony.svg'
import moonViewingCeremonyColor from './icons/activities/event/moon-viewing-ceremony_color.svg'
import partyPopper from './icons/activities/event/party-popper.svg'
import partyPopperColor from './icons/activities/event/party-popper_color.svg'
import pineDecoration from './icons/activities/event/pine-decoration.svg'
import pineDecorationColor from './icons/activities/event/pine-decoration_color.svg'
import redEnvelope from './icons/activities/event/red-envelope.svg'
import redEnvelopeColor from './icons/activities/event/red-envelope_color.svg'
import ribbon from './icons/activities/event/ribbon.svg'
import ribbonColor from './icons/activities/event/ribbon_color.svg'
import sparkler from './icons/activities/event/sparkler.svg'
import sparklerColor from './icons/activities/event/sparkler_color.svg'
import sparkles from './icons/activities/event/sparkles.svg'
import sparklesColor from './icons/activities/event/sparkles_color.svg'
import tanabataTree from './icons/activities/event/tanabata-tree.svg'
import tanabataTreeColor from './icons/activities/event/tanabata-tree_color.svg'
import ticket from './icons/activities/event/ticket.svg'
import ticketColor from './icons/activities/event/ticket_color.svg'
import windChime from './icons/activities/event/wind-chime.svg'
import windChimeColor from './icons/activities/event/wind-chime_color.svg'
import wrappedGift from './icons/activities/event/wrapped-gift.svg'
import wrappedGiftColor from './icons/activities/event/wrapped-gift_color.svg'
import bullsEye from './icons/activities/game/bullseye.svg'
import bullsEyeColor from './icons/activities/game/bullseye_color.svg'
import chessPawn from './icons/activities/game/chess-pawn.svg'
import chessPawnColor from './icons/activities/game/chess-pawn_color.svg'
import clubSuit from './icons/activities/game/club-suit.svg'
import clubSuitColor from './icons/activities/game/club-suit_color.svg'
import crystalBall from './icons/activities/game/crystal-ball.svg'
import crystalBallColor from './icons/activities/game/crystal-ball_color.svg'
import diamondSuit from './icons/activities/game/diamond-suit.svg'
import diamondSuitColor from './icons/activities/game/diamond-suit_color.svg'
import flowerPlayingCards from './icons/activities/game/flower-playing-cards.svg'
import flowerPlayingCardsColor from './icons/activities/game/flower-playing-cards_color.svg'
import gameDie from './icons/activities/game/game-die.svg'
import gameDieColor from './icons/activities/game/game-die_color.svg'
import hamsa from './icons/activities/game/hamsa.svg'
import hamsaColor from './icons/activities/game/hamsa_color.svg'
import heartSuit from './icons/activities/game/heart-suit.svg'
import heartSuitColor from './icons/activities/game/heart-suit_color.svg'
import joker from './icons/activities/game/joker.svg'
import jokerColor from './icons/activities/game/joker_color.svg'
import joyStick from './icons/activities/game/joystick.svg'
import joyStickColor from './icons/activities/game/joystick_color.svg'
import kite from './icons/activities/game/kite.svg'
import kiteColor from './icons/activities/game/kite_color.svg'
import magicWand from './icons/activities/game/magic-wand.svg'
import magicWandColor from './icons/activities/game/magic-wand_color.svg'
import mahjongRedDragon from './icons/activities/game/mahjong-red-dragon.svg'
import mahjongRedDragonColor from './icons/activities/game/mahjong-red-dragon_color.svg'
import mirrorBall from './icons/activities/game/mirror-ball.svg'
import mirrorBallColor from './icons/activities/game/mirror-ball_color.svg'
import nazarAmulet from './icons/activities/game/nazar-amulet.svg'
import nazarAmuletColor from './icons/activities/game/nazar-amulet_color.svg'
import nestingDolls from './icons/activities/game/nesting-dolls.svg'
import nestingDollsColor from './icons/activities/game/nesting-dolls_color.svg'
import pinata from './icons/activities/game/piñata.svg'
import pinataColor from './icons/activities/game/piñata_color.svg'
import pool8Ball from './icons/activities/game/pool-8-ball.svg'
import pool8BallColor from './icons/activities/game/pool-8-ball_color.svg'
import puzzlePiece from './icons/activities/game/puzzle-piece.svg'
import puzzlePieceColor from './icons/activities/game/puzzle-piece_color.svg'
import slotMachine from './icons/activities/game/slot-machine.svg'
import slotMachineColor from './icons/activities/game/slot-machine_color.svg'
import spadeSuit from './icons/activities/game/spade-suit.svg'
import spadeSuitColor from './icons/activities/game/spade-suit_color.svg'
import teddyBear from './icons/activities/game/teddy-bear.svg'
import teddyBearColor from './icons/activities/game/teddy-bear_color.svg'
import videoGame from './icons/activities/game/video-game.svg'
import videoGameColor from './icons/activities/game/video-game_color.svg'
import yoyo from './icons/activities/game/yo-yo.svg'
import yoyoColor from './icons/activities/game/yo-yo_color.svg'
import americanFootball from './icons/activities/sport/american-football.svg'
import americanFootballColor from './icons/activities/sport/american-football_color.svg'
import badminton from './icons/activities/sport/badminton.svg'
import badmintonColor from './icons/activities/sport/badminton_color.svg'
import baseball from './icons/activities/sport/baseball.svg'
import baseballColor from './icons/activities/sport/baseball_color.svg'
import basketball from './icons/activities/sport/basketball.svg'
import basketballColor from './icons/activities/sport/basketball_color.svg'
import bowling from './icons/activities/sport/bowling.svg'
import bowlingColor from './icons/activities/sport/bowling_color.svg'
import boxingGlove from './icons/activities/sport/boxing-glove.svg'
import boxingGloveColor from './icons/activities/sport/boxing-glove_color.svg'
import cricketGame from './icons/activities/sport/cricket-game.svg'
import cricketGameColor from './icons/activities/sport/cricket-game_color.svg'
import curlingStone from './icons/activities/sport/curling-stone.svg'
import curlingStoneColor from './icons/activities/sport/curling-stone_color.svg'
import divingMask from './icons/activities/sport/diving-mask.svg'
import divingMaskColor from './icons/activities/sport/diving-mask_color.svg'
import fieldHockey from './icons/activities/sport/field-hockey.svg'
import fieldHockeyColor from './icons/activities/sport/field-hockey_color.svg'
import fishingPole from './icons/activities/sport/fishing-pole.svg'
import fishingPoleColor from './icons/activities/sport/fishing-pole_color.svg'
import flagInHole from './icons/activities/sport/flag-in-hole.svg'
import flagInHoleColor from './icons/activities/sport/flag-in-hole_color.svg'
import flyingDisc from './icons/activities/sport/flying-disc.svg'
import flyingDiscColor from './icons/activities/sport/flying-disc_color.svg'
import goalNet from './icons/activities/sport/goal-net.svg'
import goalNetColor from './icons/activities/sport/goal-net_color.svg'
import iceHockey from './icons/activities/sport/ice-hockey.svg'
import iceHockeyColor from './icons/activities/sport/ice-hockey_color.svg'
import iceSkate from './icons/activities/sport/ice-skate.svg'
import iceSkateColor from './icons/activities/sport/ice-skate_color.svg'
import lacrosse from './icons/activities/sport/lacrosse.svg'
import lacrosseColor from './icons/activities/sport/lacrosse_color.svg'
import martialArtsUniform from './icons/activities/sport/martial-arts-uniform.svg'
import martialArtsUniformColor from './icons/activities/sport/martial-arts-uniform_color.svg'
import pingPong from './icons/activities/sport/ping-pong.svg'
import pingPongColor from './icons/activities/sport/ping-pong_color.svg'
import rugbyFootball from './icons/activities/sport/rugby-football.svg'
import rugbyFootballColor from './icons/activities/sport/rugby-football_color.svg'
import runningShirt from './icons/activities/sport/running-shirt.svg'
import runningShirtColor from './icons/activities/sport/running-shirt_color.svg'
import skis from './icons/activities/sport/skis.svg'
import skisColor from './icons/activities/sport/skis_color.svg'
import sled from './icons/activities/sport/sled.svg'
import sledColor from './icons/activities/sport/sled_color.svg'
import soccerball from './icons/activities/sport/soccer-ball.svg'
import soccerballColor from './icons/activities/sport/soccer-ball_color.svg'
import softball from './icons/activities/sport/softball.svg'
import softballColor from './icons/activities/sport/softball_color.svg'
import tennis from './icons/activities/sport/tennis.svg'
import tennisColor from './icons/activities/sport/tennis_color.svg'
import volleyball from './icons/activities/sport/volleyball.svg'
import volleyballColor from './icons/activities/sport/volleyball_color.svg'

import { IconProps } from './use-search'

export const openActivitiesTable = new Map<string, Omit<IconProps, 'id'>>();

openActivitiesTable.set('artistPallete', { name: 'Artist Pallete', icon: artistPallete })
openActivitiesTable.set('artistPalleteColor', { name: 'Artist Pallete Color', icon: artistPalleteColor })
openActivitiesTable.set('framedPicture', { name: 'Framed Picture', icon: framedPicture })
openActivitiesTable.set('framedPictureColor', { name: 'Framed Picture Color', icon: framedPictureColor })
openActivitiesTable.set('knot', { name: 'Knot', icon: knot })
openActivitiesTable.set('knotColor', { name: 'Knot Color', icon: knotColor })
openActivitiesTable.set('performingArts', { name: 'Performing Arts', icon: performingArts })
openActivitiesTable.set('performingArtsColor', { name: 'Performing Arts Color', icon: performingArtsColor })
openActivitiesTable.set('sewingNeedle', { name: 'Sewing Neddle', icon: sewingNeedle })
openActivitiesTable.set('sewingNeedleColor', { name: 'Sewing Neddle', icon: sewingNeedleColor })
openActivitiesTable.set('thread', { name: 'Thread', icon: thread })
openActivitiesTable.set('threadColor', { name: 'Thread Color', icon: threadColor })
openActivitiesTable.set('yarn', { name: 'Yarn', icon: yarn })
openActivitiesTable.set('yarnColor', { name: 'Yarn Color', icon: yarnColor })



export const OA_ICON_SIZE = openActivitiesTable.size;