import artistPallete from './icons/activities/arts-crafts/artist-palette.svg';
import artistPalleteColor from './icons/activities/arts-crafts/artist-palette_color.svg';
import framedPicture from './icons/activities/arts-crafts/framed-picture.svg';
import framedPictureColor from './icons/activities/arts-crafts/framed-picture_color.svg';
import knot from './icons/activities/arts-crafts/knot.svg';
import knotColor from './icons/activities/arts-crafts/knot_color.svg';
import performingArts from './icons/activities/arts-crafts/performing-arts.svg';
import performingArtsColor from './icons/activities/arts-crafts/performing-arts_color.svg';
import sewingNeedle from './icons/activities/arts-crafts/sewing-needle.svg';
import sewingNeedleColor from './icons/activities/arts-crafts/sewing-needle_color.svg';
import thread from './icons/activities/arts-crafts/thread.svg';
import threadColor from './icons/activities/arts-crafts/thread_color.svg';
import yarn from './icons/activities/arts-crafts/yarn.svg';
import yarnColor from './icons/activities/arts-crafts/yarn_color.svg';
import firstPlaceMedal from './icons/activities/award-medal/1st-place-medal.svg';
import firstPlaceMedalColor from './icons/activities/award-medal/1st-place-medal_color.svg';
import secondPlaceMedal from './icons/activities/award-medal/2nd-place-medal.svg';
import secondPlaceMedalColor from './icons/activities/award-medal/2nd-place-medal_color.svg';
import thirdPlaceMedal from './icons/activities/award-medal/3rd-place-medal.svg';
import thirdPlaceMedalColor from './icons/activities/award-medal/3rd-place-medal_color.svg';
import militaryMedal from './icons/activities/award-medal/military-medal.svg';
import militaryMedalColor from './icons/activities/award-medal/military-medal_color.svg';
import sportsMedal from './icons/activities/award-medal/sports-medal.svg';
import sportsMedalColor from './icons/activities/award-medal/sports-medal_color.svg';
import trophy from './icons/activities/award-medal/trophy.svg';
import trophyColor from './icons/activities/award-medal/trophy_color.svg';
import admissionTickets from './icons/activities/event/admission-tickets.svg';
import admissionTicketsColor from './icons/activities/event/admission-tickets_color.svg';
import balloon from './icons/activities/event/balloon.svg';
import balloonColor from './icons/activities/event/balloon_color.svg';
import carpStreamer from './icons/activities/event/carp-streamer.svg';
import carpStreamerColor from './icons/activities/event/carp-streamer_color.svg';
import christmasTree from './icons/activities/event/Christmas-tree.svg';
import christmasTreeColor from './icons/activities/event/Christmas-tree_color.svg';
import confettiBall from './icons/activities/event/confetti-ball.svg';
import confettiBallColor from './icons/activities/event/confetti-ball_color.svg';
import fireCracker from './icons/activities/event/firecracker.svg';
import fireCrackerColor from './icons/activities/event/firecracker_color.svg';
import fireWorks from './icons/activities/event/fireworks.svg';
import fireWorksColor from './icons/activities/event/fireworks_color.svg';
import jackOLantern from './icons/activities/event/jack-o-lantern.svg';
import jackOLanternColor from './icons/activities/event/jack-o-lantern_color.svg';
import japaneseDolls from './icons/activities/event/Japanese-dolls.svg';
import japaneseDollsColor from './icons/activities/event/Japanese-dolls_color.svg';
import moonViewingCeremony from './icons/activities/event/moon-viewing-ceremony.svg';
import moonViewingCeremonyColor from './icons/activities/event/moon-viewing-ceremony_color.svg';
import partyPopper from './icons/activities/event/party-popper.svg';
import partyPopperColor from './icons/activities/event/party-popper_color.svg';
import pineDecoration from './icons/activities/event/pine-decoration.svg';
import pineDecorationColor from './icons/activities/event/pine-decoration_color.svg';
import redEnvelope from './icons/activities/event/red-envelope.svg';
import redEnvelopeColor from './icons/activities/event/red-envelope_color.svg';
import ribbon from './icons/activities/event/ribbon.svg';
import ribbonColor from './icons/activities/event/ribbon_color.svg';
import sparkler from './icons/activities/event/sparkler.svg';
import sparklerColor from './icons/activities/event/sparkler_color.svg';
import sparkles from './icons/activities/event/sparkles.svg';
import sparklesColor from './icons/activities/event/sparkles_color.svg';
import tanabataTree from './icons/activities/event/tanabata-tree.svg';
import tanabataTreeColor from './icons/activities/event/tanabata-tree_color.svg';
import ticket from './icons/activities/event/ticket.svg';
import ticketColor from './icons/activities/event/ticket_color.svg';
import windChime from './icons/activities/event/wind-chime.svg';
import windChimeColor from './icons/activities/event/wind-chime_color.svg';
import wrappedGift from './icons/activities/event/wrapped-gift.svg';
import wrappedGiftColor from './icons/activities/event/wrapped-gift_color.svg';
import bullsEye from './icons/activities/game/bullseye.svg';
import bullsEyeColor from './icons/activities/game/bullseye_color.svg';
import chessPawn from './icons/activities/game/chess-pawn.svg';
import chessPawnColor from './icons/activities/game/chess-pawn_color.svg';
import clubSuit from './icons/activities/game/club-suit.svg';
import clubSuitColor from './icons/activities/game/club-suit_color.svg';
import crystalBall from './icons/activities/game/crystal-ball.svg';
import crystalBallColor from './icons/activities/game/crystal-ball_color.svg';
import diamondSuit from './icons/activities/game/diamond-suit.svg';
import diamondSuitColor from './icons/activities/game/diamond-suit_color.svg';
import flowerPlayingCards from './icons/activities/game/flower-playing-cards.svg';
import flowerPlayingCardsColor from './icons/activities/game/flower-playing-cards_color.svg';
import gameDie from './icons/activities/game/game-die.svg';
import gameDieColor from './icons/activities/game/game-die_color.svg';
import hamsa from './icons/activities/game/hamsa.svg';
import hamsaColor from './icons/activities/game/hamsa_color.svg';
import heartSuit from './icons/activities/game/heart-suit.svg';
import heartSuitColor from './icons/activities/game/heart-suit_color.svg';
import joker from './icons/activities/game/joker.svg';
import jokerColor from './icons/activities/game/joker_color.svg';
import joyStick from './icons/activities/game/joystick.svg';
import joyStickColor from './icons/activities/game/joystick_color.svg';
import kite from './icons/activities/game/kite.svg';
import kiteColor from './icons/activities/game/kite_color.svg';
import magicWand from './icons/activities/game/magic-wand.svg';
import magicWandColor from './icons/activities/game/magic-wand_color.svg';
import mahjongRedDragon from './icons/activities/game/mahjong-red-dragon.svg';
import mahjongRedDragonColor from './icons/activities/game/mahjong-red-dragon_color.svg';
import mirrorBall from './icons/activities/game/mirror-ball.svg';
import mirrorBallColor from './icons/activities/game/mirror-ball_color.svg';
import nazarAmulet from './icons/activities/game/nazar-amulet.svg';
import nazarAmuletColor from './icons/activities/game/nazar-amulet_color.svg';
import nestingDolls from './icons/activities/game/nesting-dolls.svg';
import nestingDollsColor from './icons/activities/game/nesting-dolls_color.svg';
import pinata from './icons/activities/game/piñata.svg';
import pinataColor from './icons/activities/game/piñata_color.svg';
import pool8Ball from './icons/activities/game/pool-8-ball.svg';
import pool8BallColor from './icons/activities/game/pool-8-ball_color.svg';
import puzzlePiece from './icons/activities/game/puzzle-piece.svg';
import puzzlePieceColor from './icons/activities/game/puzzle-piece_color.svg';
import slotMachine from './icons/activities/game/slot-machine.svg';
import slotMachineColor from './icons/activities/game/slot-machine_color.svg';
import spadeSuit from './icons/activities/game/spade-suit.svg';
import spadeSuitColor from './icons/activities/game/spade-suit_color.svg';
import teddyBear from './icons/activities/game/teddy-bear.svg';
import teddyBearColor from './icons/activities/game/teddy-bear_color.svg';
import videoGame from './icons/activities/game/video-game.svg';
import videoGameColor from './icons/activities/game/video-game_color.svg';
import yoyo from './icons/activities/game/yo-yo.svg';
import yoyoColor from './icons/activities/game/yo-yo_color.svg';
import americanFootball from './icons/activities/sport/american-football.svg';
import americanFootballColor from './icons/activities/sport/american-football_color.svg';
import badminton from './icons/activities/sport/badminton.svg';
import badmintonColor from './icons/activities/sport/badminton_color.svg';
import baseball from './icons/activities/sport/baseball.svg';
import baseballColor from './icons/activities/sport/baseball_color.svg';
import basketball from './icons/activities/sport/basketball.svg';
import basketballColor from './icons/activities/sport/basketball_color.svg';
import bowling from './icons/activities/sport/bowling.svg';
import bowlingColor from './icons/activities/sport/bowling_color.svg';
import boxingGlove from './icons/activities/sport/boxing-glove.svg';
import boxingGloveColor from './icons/activities/sport/boxing-glove_color.svg';
import cricketGame from './icons/activities/sport/cricket-game.svg';
import cricketGameColor from './icons/activities/sport/cricket-game_color.svg';
import curlingStone from './icons/activities/sport/curling-stone.svg';
import curlingStoneColor from './icons/activities/sport/curling-stone_color.svg';
import divingMask from './icons/activities/sport/diving-mask.svg';
import divingMaskColor from './icons/activities/sport/diving-mask_color.svg';
import fieldHockey from './icons/activities/sport/field-hockey.svg';
import fieldHockeyColor from './icons/activities/sport/field-hockey_color.svg';
import fishingPole from './icons/activities/sport/fishing-pole.svg';
import fishingPoleColor from './icons/activities/sport/fishing-pole_color.svg';
import flagInHole from './icons/activities/sport/flag-in-hole.svg';
import flagInHoleColor from './icons/activities/sport/flag-in-hole_color.svg';
import flyingDisc from './icons/activities/sport/flying-disc.svg';
import flyingDiscColor from './icons/activities/sport/flying-disc_color.svg';
import goalNet from './icons/activities/sport/goal-net.svg';
import goalNetColor from './icons/activities/sport/goal-net_color.svg';
import iceHockey from './icons/activities/sport/ice-hockey.svg';
import iceHockeyColor from './icons/activities/sport/ice-hockey_color.svg';
import iceSkate from './icons/activities/sport/ice-skate.svg';
import iceSkateColor from './icons/activities/sport/ice-skate_color.svg';
import lacrosse from './icons/activities/sport/lacrosse.svg';
import lacrosseColor from './icons/activities/sport/lacrosse_color.svg';
import martialArtsUniform from './icons/activities/sport/martial-arts-uniform.svg';
import martialArtsUniformColor from './icons/activities/sport/martial-arts-uniform_color.svg';
import pingPong from './icons/activities/sport/ping-pong.svg';
import pingPongColor from './icons/activities/sport/ping-pong_color.svg';
import rugbyFootball from './icons/activities/sport/rugby-football.svg';
import rugbyFootballColor from './icons/activities/sport/rugby-football_color.svg';
import runningShirt from './icons/activities/sport/running-shirt.svg';
import runningShirtColor from './icons/activities/sport/running-shirt_color.svg';
import skis from './icons/activities/sport/skis.svg';
import skisColor from './icons/activities/sport/skis_color.svg';
import sled from './icons/activities/sport/sled.svg';
import sledColor from './icons/activities/sport/sled_color.svg';
import soccerball from './icons/activities/sport/soccer-ball.svg';
import soccerballColor from './icons/activities/sport/soccer-ball_color.svg';
import softball from './icons/activities/sport/softball.svg';
import softballColor from './icons/activities/sport/softball_color.svg';
import tennis from './icons/activities/sport/tennis.svg';
import tennisColor from './icons/activities/sport/tennis_color.svg';
import volleyball from './icons/activities/sport/volleyball.svg';
import volleyballColor from './icons/activities/sport/volleyball_color.svg';

import {IconProps} from './use-search';

export const openActivitiesTable = new Map<string, Omit<IconProps, 'id'>>();

openActivitiesTable.set('artistPallete', {name: 'Artist Pallete', icon: artistPallete});
openActivitiesTable.set('artistPalleteColor', {name: 'Artist Pallete Color', icon: artistPalleteColor});
openActivitiesTable.set('framedPicture', {name: 'Framed Picture', icon: framedPicture});
openActivitiesTable.set('framedPictureColor', {name: 'Framed Picture Color', icon: framedPictureColor});
openActivitiesTable.set('knot', {name: 'Knot', icon: knot});
openActivitiesTable.set('knotColor', {name: 'Knot Color', icon: knotColor});
openActivitiesTable.set('performingArts', {name: 'Performing Arts', icon: performingArts});
openActivitiesTable.set('performingArtsColor', {name: 'Performing Arts Color', icon: performingArtsColor});
openActivitiesTable.set('sewingNeedle', {name: 'Sewing Neddle', icon: sewingNeedle});
openActivitiesTable.set('sewingNeedleColor', {name: 'Sewing Neddle', icon: sewingNeedleColor});
openActivitiesTable.set('thread', {name: 'Thread', icon: thread});
openActivitiesTable.set('threadColor', {name: 'Thread Color', icon: threadColor});
openActivitiesTable.set('yarn', {name: 'Yarn', icon: yarn});
openActivitiesTable.set('yarnColor', {name: 'Yarn Color', icon: yarnColor});
openActivitiesTable.set('firstPlaceMedal', {name: 'First Place Medal', icon: firstPlaceMedal});
openActivitiesTable.set('firstPlaceMedalColor', {name: 'First Place Medal Color', icon: firstPlaceMedalColor});
openActivitiesTable.set('secondPlaceMedal', {name: 'Second Place Medal', icon: secondPlaceMedal});
openActivitiesTable.set('secondPlaceMedalColor', {name: 'Second Place Medal Color', icon: secondPlaceMedalColor});
openActivitiesTable.set('thirdPlaceMedal', {name: 'Third Place Medal', icon: thirdPlaceMedal});
openActivitiesTable.set('thirdPlaceMedalColor', {name: 'Third Place Medal Color', icon: thirdPlaceMedalColor});
openActivitiesTable.set('militaryMedal', {name: 'Military Medal', icon: militaryMedal});
openActivitiesTable.set('militaryMedalColor', {name: 'Military Medal Color', icon: militaryMedalColor});
openActivitiesTable.set('sportsMedal', {name: 'Sports Medal', icon: sportsMedal});
openActivitiesTable.set('sportsMedalColor', {name: 'Sports Medal Color', icon: sportsMedalColor});
openActivitiesTable.set('trophy', {name: 'Trophy', icon: trophy});
openActivitiesTable.set('trophyColor', {name: 'Trophy Color', icon: trophyColor});
openActivitiesTable.set('admissionTickets', {name: 'Admission Tickets', icon: admissionTickets});
openActivitiesTable.set('admissionTicketsColor', {name: 'Admission Tickets Color', icon: admissionTicketsColor});
openActivitiesTable.set('balloon', {name: 'Balloon', icon: balloon});
openActivitiesTable.set('balloonColor', {name: 'Balloon Color', icon: balloonColor});
openActivitiesTable.set('carpStreamer', {name: 'Carp Streamer', icon: carpStreamer});
openActivitiesTable.set('carpStreamerColor', {name: 'Carp Streamer Color', icon: carpStreamerColor});
openActivitiesTable.set('christmasTree', {name: 'Christmas Tree', icon: christmasTree});
openActivitiesTable.set('christmasTreeColor', {name: 'Christmas Tree Color', icon: christmasTreeColor});
openActivitiesTable.set('confettiBall', {name: 'Confetti Ball', icon: confettiBall});
openActivitiesTable.set('confettiBallColor', {name: 'Confetti Ball Color', icon: confettiBallColor});
openActivitiesTable.set('fireCracker', {name: 'Fire Cracker', icon: fireCracker});
openActivitiesTable.set('fireCrackerColor', {name: 'Fire Cracker Color', icon: fireCrackerColor});
openActivitiesTable.set('fireWorks', {name: 'Fire Works', icon: fireWorks});
openActivitiesTable.set('fireWorksColor', {name: 'Fire Works Color', icon: fireWorksColor});
openActivitiesTable.set('jackOLantern', {name: 'Jack O Lantern', icon: jackOLantern});
openActivitiesTable.set('jackOLanternColor', {name: 'Jack O Lantern Color', icon: jackOLanternColor});
openActivitiesTable.set('japaneseDolls', {name: 'Japanese Dolls', icon: japaneseDolls});
openActivitiesTable.set('japaneseDollsColor', {name: 'Japanses Dolls Color', icon: japaneseDollsColor});
openActivitiesTable.set('moonViewingCeremony', {name: 'Moon Viewing Ceremony', icon: moonViewingCeremony});
openActivitiesTable.set('moonViewingCeremonyColor', {
    name: 'Moon Viewing Ceremony Color',
    icon: moonViewingCeremonyColor,
});
openActivitiesTable.set('partyPopper', {name: 'Party Popper', icon: partyPopper});
openActivitiesTable.set('partyPopperColor', {name: 'Party Popper Color', icon: partyPopperColor});
openActivitiesTable.set('pineDecoration', {name: 'Pine Decoration', icon: pineDecoration});
openActivitiesTable.set('pineDecorationColor', {name: 'Pine Decoration Color', icon: pineDecorationColor});
openActivitiesTable.set('redEnvelope', {name: 'Red Envelope', icon: redEnvelope});
openActivitiesTable.set('redEnvelopeColor', {name: 'Red Envelope Color', icon: redEnvelopeColor});
openActivitiesTable.set('ribbon', {name: 'Ribbon', icon: ribbon});
openActivitiesTable.set('ribbonColor', {name: 'Ribbon Color', icon: ribbonColor});
openActivitiesTable.set('sparkler', {name: 'Sparkler', icon: sparkler});
openActivitiesTable.set('sparklerColor', {name: 'Sparkler Color', icon: sparklerColor});
openActivitiesTable.set('sparkles', {name: 'Sparkles', icon: sparkles});
openActivitiesTable.set('sparklesColor', {name: 'Sparkles Color', icon: sparklesColor});
openActivitiesTable.set('tanabataTree', {name: 'Tanabata Tree', icon: tanabataTree});
openActivitiesTable.set('tanabataTreeColor', {name: 'Tanabata Tree Color', icon: tanabataTreeColor});
openActivitiesTable.set('ticket', {name: 'Ticket', icon: ticket});
openActivitiesTable.set('ticketColor', {name: 'Tickets Color', icon: ticketColor});
openActivitiesTable.set('windChime', {name: 'Wind Chime', icon: windChime});
openActivitiesTable.set('windChimeColor', {name: 'Wind Chime Color', icon: windChimeColor});
openActivitiesTable.set('wrappedGift', {name: 'Wrapped Gift', icon: wrappedGift});
openActivitiesTable.set('wrappedGiftColor', {name: 'Wrapped Gift Color', icon: wrappedGiftColor});
openActivitiesTable.set('bullsEye', {name: 'Bulls Eye', icon: bullsEye});
openActivitiesTable.set('bullsEyeColor', {name: 'Bulls Eye Color', icon: bullsEyeColor});
openActivitiesTable.set('chessPawn', {name: 'Chess Pawn', icon: chessPawn});
openActivitiesTable.set('chessPawnColor', {name: 'Chess Pawn Color', icon: chessPawnColor});
openActivitiesTable.set('clubSuit', {name: 'Club Suit', icon: clubSuit});
openActivitiesTable.set('clubSuitColor', {name: 'Club Suit Color', icon: clubSuitColor});
openActivitiesTable.set('crystalBall', {name: 'Crystal Ball', icon: crystalBall});
openActivitiesTable.set('crystalBallColor', {name: 'Crystal Ball Color', icon: crystalBallColor});
openActivitiesTable.set('diamondSuit', {name: 'Diamond Suit', icon: diamondSuit});
openActivitiesTable.set('diamondSuitColor', {name: 'Diamond Suit Color', icon: diamondSuitColor});
openActivitiesTable.set('flowerPlayingCards', {name: 'Flower Playing Cards', icon: flowerPlayingCards});
openActivitiesTable.set('flowerPlayingCardsColor', {name: 'Flower Playing Cards Color', icon: flowerPlayingCardsColor});
openActivitiesTable.set('gameDie', {name: 'Game Die', icon: gameDie});
openActivitiesTable.set('gameDieColor', {name: 'Game Die Color', icon: gameDieColor});
openActivitiesTable.set('hamsa', {name: 'Hamsa', icon: hamsa});
openActivitiesTable.set('hamsaColor', {name: 'Hamsa Color', icon: hamsaColor});
openActivitiesTable.set('heartSuit', {name: 'Heart Suit', icon: heartSuit});
openActivitiesTable.set('heartSuitColor', {name: 'Heart Suit Color', icon: heartSuitColor});
openActivitiesTable.set('joker', {name: 'Joker', icon: joker});
openActivitiesTable.set('jokerColor', {name: 'Joker Color', icon: jokerColor});
openActivitiesTable.set('joyStick', {name: 'Joy Stick', icon: joyStick});
openActivitiesTable.set('joyStickColor', {name: 'Joy Stick Color', icon: joyStickColor});
openActivitiesTable.set('kite', {name: 'Kite', icon: kite});
openActivitiesTable.set('kiteColor', {name: 'Kite COlor', icon: kiteColor});
openActivitiesTable.set('magicWand', {name: 'Magic Wand', icon: magicWand});
openActivitiesTable.set('magicWandColor', {name: 'Magic Wand Color', icon: magicWandColor});
openActivitiesTable.set('mahjongRedDragon', {name: 'Mahjong Red Dragon', icon: mahjongRedDragon});
openActivitiesTable.set('mahjongRedDragonColor', {name: 'Mahjong Red Dragon Color', icon: mahjongRedDragonColor});
openActivitiesTable.set('mirrorBall', {name: 'Mirror Ball', icon: mirrorBall});
openActivitiesTable.set('mirrorBallColor', {name: 'Mirror Ball Color', icon: mirrorBallColor});
openActivitiesTable.set('nazarAmulet', {name: 'Nazar Amulet', icon: nazarAmulet});
openActivitiesTable.set('nazarAmuletColor', {name: 'Nazar Amulet Color', icon: nazarAmuletColor});
openActivitiesTable.set('nestingDolls', {name: 'Nesting Dolls', icon: nestingDolls});
openActivitiesTable.set('nestingDollsColor', {name: 'Nesting Dolls Color', icon: nestingDollsColor});
openActivitiesTable.set('pinata', {name: 'Pinata', icon: pinata});
openActivitiesTable.set('pinataColor', {name: 'Pinata Color', icon: pinataColor});
openActivitiesTable.set('pool8Ball', {name: 'Pool 8 Ball', icon: pool8Ball});
openActivitiesTable.set('pool8BallColor', {name: 'Pool 8 Ball Color', icon: pool8BallColor});
openActivitiesTable.set('puzzlePiece', {name: 'Puzzle Piece', icon: puzzlePiece});
openActivitiesTable.set('puzzlePieceColor', {name: 'Puzzle Piece Color', icon: puzzlePieceColor});
openActivitiesTable.set('slotMachine', {name: 'Slot Machine', icon: slotMachine});
openActivitiesTable.set('slotMachineColor', {name: 'Slot Machine Color', icon: slotMachineColor});
openActivitiesTable.set('spadeSuit', {name: 'Spade Suit', icon: spadeSuit});
openActivitiesTable.set('spadeSuitColor', {name: 'Spade Suit COlor', icon: spadeSuitColor});
openActivitiesTable.set('teddyBear', {name: 'Teddy Bear', icon: teddyBear});
openActivitiesTable.set('teddyBearColor', {name: 'Teddy Bear Color', icon: teddyBearColor});
openActivitiesTable.set('videoGame', {name: 'Video Game', icon: videoGame});
openActivitiesTable.set('videoGameColor', {name: 'Video Game Color', icon: videoGameColor});
openActivitiesTable.set('yoyo', {name: 'Yoyo', icon: yoyo});
openActivitiesTable.set('yoyoColor', {name: 'Yoyo Color', icon: yoyoColor});
openActivitiesTable.set('americanFootball', {name: 'American Football', icon: americanFootball});
openActivitiesTable.set('americanFootballColor', {name: 'American Football Color', icon: americanFootballColor});
openActivitiesTable.set('badminton', {name: 'Badminton', icon: badminton});
openActivitiesTable.set('badmintonColor', {name: 'Badminton Color', icon: badmintonColor});
openActivitiesTable.set('baseball', {name: 'Baseball', icon: baseball});
openActivitiesTable.set('baseballColor', {name: 'Baseball Color', icon: baseballColor});
openActivitiesTable.set('basketball', {name: 'Basketball', icon: basketball});
openActivitiesTable.set('basketballColor', {name: 'Basketball Color', icon: basketballColor});
openActivitiesTable.set('bowling', {name: 'Bowling', icon: bowling});
openActivitiesTable.set('bowlingColor', {name: 'Bowling Color', icon: bowlingColor});
openActivitiesTable.set('boxingGlove', {name: 'Boxing Glove', icon: boxingGlove});
openActivitiesTable.set('boxingGloveColor', {name: 'Boxing Glove Color', icon: boxingGloveColor});
openActivitiesTable.set('cricketGame', {name: 'Cricket Game', icon: cricketGame});
openActivitiesTable.set('cricketGameColor', {name: 'Cricket Game Color', icon: cricketGameColor});
openActivitiesTable.set('curlingStone', {name: 'Curling Stone', icon: curlingStone});
openActivitiesTable.set('curlingStoneColor', {name: 'Curling Stone Color', icon: curlingStoneColor});
openActivitiesTable.set('divingMask', {name: 'Diving Mask', icon: divingMask});
openActivitiesTable.set('divingMaskColor', {name: 'Diving Mask Color', icon: divingMaskColor});
openActivitiesTable.set('fieldHockey', {name: 'Field Hockey', icon: fieldHockey});
openActivitiesTable.set('fieldHockeyColor', {name: 'Field Hockey Color', icon: fieldHockeyColor});
openActivitiesTable.set('fishingPole', {name: 'Fishing Pole', icon: fishingPole});
openActivitiesTable.set('fishingPoleColor', {name: 'Fishing Pole COlor', icon: fishingPoleColor});
openActivitiesTable.set('flagInHole', {name: 'Flag In Hole', icon: flagInHole});
openActivitiesTable.set('flagInHoleColor', {name: 'Flag In Hole Color', icon: flagInHoleColor});
openActivitiesTable.set('flyingDisc', {name: 'Flying Disc', icon: flyingDisc});
openActivitiesTable.set('flyingDiscColor', {name: 'Flying Disc Color', icon: flyingDiscColor});
openActivitiesTable.set('goalNet', {name: 'Goal Net', icon: goalNet});
openActivitiesTable.set('goalNetColor', {name: 'Goal Net Color', icon: goalNetColor});
openActivitiesTable.set('iceHockey', {name: 'Ice Hockey', icon: iceHockey});
openActivitiesTable.set('iceHockeyColor', {name: 'Ice Hockey Color', icon: iceHockeyColor});
openActivitiesTable.set('iceSkate', {name: 'Ice Skate', icon: iceSkate});
openActivitiesTable.set('iceSkateColor', {name: 'Ice Skate Color', icon: iceSkateColor});
openActivitiesTable.set('lacrosse', {name: 'Lacrosse', icon: lacrosse});
openActivitiesTable.set('lacrosseColor', {name: 'Lacrosse Color', icon: lacrosseColor});
openActivitiesTable.set('martialArtsUniform', {name: 'Martial Arts Uniform', icon: martialArtsUniform});
openActivitiesTable.set('martialArtsUniformColor', {name: 'Martial Arts Uniform Color', icon: martialArtsUniformColor});
openActivitiesTable.set('pingPong', {name: 'Ping Pong', icon: pingPong});
openActivitiesTable.set('pingPongColor', {name: 'Ping Pong Color', icon: pingPongColor});
openActivitiesTable.set('rugbyFootball', {name: 'Rugby Football', icon: rugbyFootball});
openActivitiesTable.set('rugbyFootballColor', {name: 'Rugby Football Color', icon: rugbyFootballColor});
openActivitiesTable.set('runningShirt', {name: 'Running Shirt', icon: runningShirt});
openActivitiesTable.set('runningShirtColor', {name: 'Running Shirt Color', icon: runningShirtColor});
openActivitiesTable.set('skis', {name: 'Skis', icon: skis});
openActivitiesTable.set('skisColor', {name: 'Skis Color', icon: skisColor});
openActivitiesTable.set('sled', {name: 'Sled', icon: sled});
openActivitiesTable.set('sledColor', {name: 'Sled Color', icon: sledColor});
openActivitiesTable.set('soccerball', {name: 'Soccerball', icon: soccerball});
openActivitiesTable.set('soccerballColor', {name: 'Soccerball COlor', icon: soccerballColor});
openActivitiesTable.set('softball', {name: 'Softball', icon: softball});
openActivitiesTable.set('softballColor', {name: 'Softball Color', icon: softballColor});
openActivitiesTable.set('tennis', {name: 'Tennis', icon: tennis});
openActivitiesTable.set('tennisColor', {name: 'Tennis Color', icon: tennisColor});
openActivitiesTable.set('volleyball', {name: 'Volleyball', icon: volleyball});
openActivitiesTable.set('volleyballColor', {name: 'Volleyball Color', icon: volleyballColor});

export const OPEN_ACTIVITY_ICON_SIZE = openActivitiesTable.size;
