import flagAfghanistan from './icons/flags/country-flag/flag_-Afghanistan.svg';
import flagAfghanistanColor from './icons/flags/country-flag/flag_-Afghanistan_color.svg';
import flagAlbania from './icons/flags/country-flag/flag_-Albania.svg';
import flagAlbaniaColor from './icons/flags/country-flag/flag_-Albania_color.svg';
import flagAlgeria from './icons/flags/country-flag/flag_-Algeria.svg';
import flagAlgeriaColor from './icons/flags/country-flag/flag_-Algeria_color.svg';
import flagAmericanSamoa from './icons/flags/country-flag/flag_-American-Samoa.svg';
import flagAmericanSamoaColor from './icons/flags/country-flag/flag_-American-Samoa_color.svg';
import flagAndorra from './icons/flags/country-flag/flag_-Andorra.svg';
import flagAndorraColor from './icons/flags/country-flag/flag_-Andorra_color.svg';
import flagAngola from './icons/flags/country-flag/flag_-Angola.svg';
import flagAngolaColor from './icons/flags/country-flag/flag_-Angola_color.svg';
import flagAnguilla from './icons/flags/country-flag/flag_-Anguilla.svg';
import flagAnguillaColor from './icons/flags/country-flag/flag_-Anguilla_color.svg';
import flagAntarctica from './icons/flags/country-flag/flag_-Antarctica.svg';
import flagAntarcticaColor from './icons/flags/country-flag/flag_-Antarctica_color.svg';
import flagAntiguaAndBarbuda from './icons/flags/country-flag/flag_-Antigua-&-Barbuda.svg';
import flagAntiguaAndBarbudaColor from './icons/flags/country-flag/flag_-Antigua-&-Barbuda_color.svg';
import flagArgentina from './icons/flags/country-flag/flag_-Argentina.svg';
import flagArgentinaColor from './icons/flags/country-flag/flag_-Argentina_color.svg';
import flagArmenia from './icons/flags/country-flag/flag_-Armenia.svg';
import flagArmeniaColor from './icons/flags/country-flag/flag_-Armenia_color.svg';
import flagAruba from './icons/flags/country-flag/flag_-Aruba.svg';
import flagArubaColor from './icons/flags/country-flag/flag_-Aruba_color.svg';
import flagAscensionIsland from './icons/flags/country-flag/flag_-Ascension-Island.svg';
import flagAscensionIslandColor from './icons/flags/country-flag/flag_-Ascension-Island_color.svg';
import flagAustralia from './icons/flags/country-flag/flag_-Australia.svg';
import flagAustraliaColor from './icons/flags/country-flag/flag_-Australia_color.svg';
import flagAustria from './icons/flags/country-flag/flag_-Austria.svg';
import flagAustriaColor from './icons/flags/country-flag/flag_-Austria_color.svg';
import flagAzerbaijan from './icons/flags/country-flag/flag_-Azerbaijan.svg';
import flagAzerbaijanColor from './icons/flags/country-flag/flag_-Azerbaijan_color.svg';
import flagBahamas from './icons/flags/country-flag/flag_-Bahamas.svg';
import flagBahamasColor from './icons/flags/country-flag/flag_-Bahamas_color.svg';
import flagBahrain from './icons/flags/country-flag/flag_-Bahrain.svg';
import flagBahrainColor from './icons/flags/country-flag/flag_-Bahrain_color.svg';
import flagBangladesh from './icons/flags/country-flag/flag_-Bangladesh.svg';
import flagBangladeshColor from './icons/flags/country-flag/flag_-Bangladesh_color.svg';
import flagBarbados from './icons/flags/country-flag/flag_-Barbados_color.svg';
import flagBarbadosColor from './icons/flags/country-flag/flag_-Barbados_color.svg';
import flagBelarus from './icons/flags/country-flag/flag_-Belarus.svg';
import flagBelarusColor from './icons/flags/country-flag/flag_-Belarus_color.svg';
import flagBelgium from './icons/flags/country-flag/flag_-Belgium.svg';
import flagBelgiumColor from './icons/flags/country-flag/flag_-Belgium_color.svg';
import flagBelize from './icons/flags/country-flag/flag_-Belize.svg';
import flagBelizeColor from './icons/flags/country-flag/flag_-Belize_color.svg';
import flagBenin from './icons/flags/country-flag/flag_-Benin.svg';
import flagBeninColor from './icons/flags/country-flag/flag_-Benin_color.svg';
import flagBermuda from './icons/flags/country-flag/flag_-Bermuda.svg';
import flagBermudaColor from './icons/flags/country-flag/flag_-Bermuda_color.svg';
import flagBhutan from './icons/flags/country-flag/flag_-Bhutan.svg';
import flagBhutanColor from './icons/flags/country-flag/flag_-Bhutan_color.svg';
import flagBolivia from './icons/flags/country-flag/flag_-Bolivia.svg';
import flagBoliviaColor from './icons/flags/country-flag/flag_-Bolivia_color.svg';
import flagBosniaAndHerzegovina from './icons/flags/country-flag/flag_-Bosnia-&-Herzegovina.svg';
import flagBosniaAndHerzegovinaColor from './icons/flags/country-flag/flag_-Bosnia-&-Herzegovina_color.svg';
import flagBotswana from './icons/flags/country-flag/flag_-Botswana.svg';
import flagBotswanaColor from './icons/flags/country-flag/flag_-Botswana_color.svg';
import flagBouvetIsland from './icons/flags/country-flag/flag_-Bouvet-Island.svg';
import flagBouvetIslandColor from './icons/flags/country-flag/flag_-Bouvet-Island_color.svg';
import flagBrazil from './icons/flags/country-flag/flag_-Brazil.svg';
import flagBrazilColor from './icons/flags/country-flag/flag_-Brazil_color.svg';
import flagBritishIndianOceanTerritory from './icons/flags/country-flag/flag_-British-Indian-Ocean-Territory.svg';
import flagBritishIndianOceanTerritoryColor from './icons/flags/country-flag/flag_-British-Indian-Ocean-Territory_color.svg';
import flagBritishVirginIslands from './icons/flags/country-flag/flag_-British-Virgin-Islands.svg';
import flagBritishVirginIslandsColor from './icons/flags/country-flag/flag_-British-Virgin-Islands_color.svg';
import flagBrunei from './icons/flags/country-flag/flag_-Brunei.svg';
import flagBruneiColor from './icons/flags/country-flag/flag_-Brunei_color.svg';
import flagBulgaria from './icons/flags/country-flag/flag_-Bulgaria.svg';
import flagBulgariaColor from './icons/flags/country-flag/flag_-Bulgaria_color.svg';
import flagBurkinaFaso from './icons/flags/country-flag/flag_-Burkina-Faso.svg';
import flagBurkinaFasoColor from './icons/flags/country-flag/flag_-Burkina-Faso_color.svg';
import flagBurundi from './icons/flags/country-flag/flag_-Burundi.svg';
import flagBurundiColor from './icons/flags/country-flag/flag_-Burundi_color.svg';
import flagCambodia from './icons/flags/country-flag/flag_-Cambodia.svg';
import flagCambodiaColor from './icons/flags/country-flag/flag_-Cambodia_color.svg';
import flagCameroon from './icons/flags/country-flag/flag_-Cameroon.svg';
import flagCameroonColor from './icons/flags/country-flag/flag_-Cameroon_color.svg';
import flagCanada from './icons/flags/country-flag/flag_-Canada.svg';
import flagCanadaColor from './icons/flags/country-flag/flag_-Canada_color.svg';
import flagCanaryIslands from './icons/flags/country-flag/flag_-Canary-Islands.svg';
import flagCanaryIslandsColor from './icons/flags/country-flag/flag_-Canary-Islands_color.svg';
import flagCapeVerde from './icons/flags/country-flag/flag_-Cape-Verde.svg';
import flagCapeVerdeColor from './icons/flags/country-flag/flag_-Cape-Verde_color.svg';
import flagCaribbeanNetherlands from './icons/flags/country-flag/flag_-Caribbean-Netherlands.svg';
import flagCaribbeanNetherlandsColor from './icons/flags/country-flag/flag_-Caribbean-Netherlands_color.svg';
import flagCaymanIslands from './icons/flags/country-flag/flag_-Cayman-Islands.svg';
import flagCaymanIslandsColor from './icons/flags/country-flag/flag_-Cayman-Islands_color.svg';
import flagCentralAfricanRepublic from './icons/flags/country-flag/flag_-Central-African-Republic.svg';
import flagCentralAfricanRepublicColor from './icons/flags/country-flag/flag_-Central-African-Republic_color.svg';
import flagCeutaAndMelilla from './icons/flags/country-flag/flag_-Ceuta-&-Melilla.svg';
import flagCeutaAndMelillaColor from './icons/flags/country-flag/flag_-Ceuta-&-Melilla_color.svg';
import flagChad from './icons/flags/country-flag/flag_-Chad.svg';
import flagChadColor from './icons/flags/country-flag/flag_-Chad_color.svg';
import flagChile from './icons/flags/country-flag/flag_-Chile.svg';
import flagChileColor from './icons/flags/country-flag/flag_-Chile_color.svg';
import flagChina from './icons/flags/country-flag/flag_-China.svg';
import flagChinaColor from './icons/flags/country-flag/flag_-China_color.svg';
import flagChristmasIsland from './icons/flags/country-flag/flag_-Christmas-Island.svg';
import flagChristmasIslandColor from './icons/flags/country-flag/flag_-Christmas-Island_color.svg';
import flagClippertonIsland from './icons/flags/country-flag/flag_-Clipperton-Island.svg';
import flagClippertonIslandColor from './icons/flags/country-flag/flag_-Clipperton-Island_color.svg';
import flagCocosKeelingIslands from './icons/flags/country-flag/flag_-Cocos-(Keeling)-Islands.svg';
import flagCocosKeelingIslandsColor from './icons/flags/country-flag/flag_-Cocos-(Keeling)-Islands_color.svg';
import flagColombia from './icons/flags/country-flag/flag_-Colombia.svg';
import flagColombiaColor from './icons/flags/country-flag/flag_-Colombia_color.svg';
import flagComoros from './icons/flags/country-flag/flag_-Comoros.svg';
import flagComorosColor from './icons/flags/country-flag/flag_-Comoros_color.svg';
import flagCongoBrazzaville from './icons/flags/country-flag/flag_-Congo---Brazzaville.svg';
import flagCongoBrazzavilleColor from './icons/flags/country-flag/flag_-Congo---Brazzaville_color.svg';
import flagCongoKinshasa from './icons/flags/country-flag/flag_-Congo---Kinshasa.svg';
import flagCongoKinshasaColor from './icons/flags/country-flag/flag_-Congo---Kinshasa_color.svg';
import flagCookIslands from './icons/flags/country-flag/flag_-Cook-Islands.svg';
import flagCookIslandsColor from './icons/flags/country-flag/flag_-Cook-Islands_color.svg';
import flagCostaRica from './icons/flags/country-flag/flag_-Costa-Rica.svg';
import flagCostaRicaColor from './icons/flags/country-flag/flag_-Costa-Rica_color.svg';
import flagCroatia from './icons/flags/country-flag/flag_-Croatia.svg';
import flagCroatiaColor from './icons/flags/country-flag/flag_-Croatia_color.svg';
import flagCuba from './icons/flags/country-flag/flag_-Cuba.svg';
import flagCubaColor from './icons/flags/country-flag/flag_-Cuba_color.svg';
import flagCyprus from './icons/flags/country-flag/flag_-Cyprus.svg';
import flagCyprusColor from './icons/flags/country-flag/flag_-Cyprus_color.svg';
import flagCzechia from './icons/flags/country-flag/flag_-Czechia.svg';
import flagCzechiaColor from './icons/flags/country-flag/flag_-Czechia_color.svg';
import flagDenmark from './icons/flags/country-flag/flag_-Denmark.svg';
import flagDenmarkColor from './icons/flags/country-flag/flag_-Denmark_color.svg';
import flagDiegoGarcia from './icons/flags/country-flag/flag_-Diego-Garcia.svg';
import flagDiegoGarciaColor from './icons/flags/country-flag/flag_-Diego-Garcia_color.svg';
import flagDjibouti from './icons/flags/country-flag/flag_-Djibouti.svg';
import flagDjiboutiColor from './icons/flags/country-flag/flag_-Djibouti_color.svg';
import flagDominica from './icons/flags/country-flag/flag_-Dominica.svg';
import flagDominicaColor from './icons/flags/country-flag/flag_-Dominica_color.svg';
import flagDominicanRepublic from './icons/flags/country-flag/flag_-Dominican-Republic.svg';
import flagDominicanRepublicColor from './icons/flags/country-flag/flag_-Dominican-Republic_color.svg';
import flagEcuador from './icons/flags/country-flag/flag_-Ecuador.svg';
import flagEcuadorColor from './icons/flags/country-flag/flag_-Ecuador_color.svg';
import flagEgypt from './icons/flags/country-flag/flag_-Egypt.svg';
import flagEgyptColor from './icons/flags/country-flag/flag_-Egypt_color.svg';
import flagElSalvador from './icons/flags/country-flag/flag_-El-Salvador.svg';
import flagElSalvadorColor from './icons/flags/country-flag/flag_-El-Salvador_color.svg';
import flagEquatorialGuinea from './icons/flags/country-flag/flag_-Equatorial-Guinea.svg';
import flagEquatorialGuineaColor from './icons/flags/country-flag/flag_-Equatorial-Guinea_color.svg';
import flagEritrea from './icons/flags/country-flag/flag_-Eritrea.svg';
import flagEritreaColor from './icons/flags/country-flag/flag_-Eritrea_color.svg';
import flagEstonia from './icons/flags/country-flag/flag_-Estonia.svg';
import flagEstoniaColor from './icons/flags/country-flag/flag_-Estonia_color.svg';
import flagEswatini from './icons/flags/country-flag/flag_-Eswatini.svg';
import flagEswatiniColor from './icons/flags/country-flag/flag_-Eswatini_color.svg';
import flagEthiopia from './icons/flags/country-flag/flag_-Ethiopia.svg';
import flagEthiopiaColor from './icons/flags/country-flag/flag_-Ethiopia_color.svg';
import flagEuropeanUnion from './icons/flags/country-flag/flag_-European-Union.svg';
import flagEuropeanUnionColor from './icons/flags/country-flag/flag_-European-Union_color.svg';
import flagFalklandIslands from './icons/flags/country-flag/flag_-Falkland-Islands.svg';
import flagFalklandIslandsColor from './icons/flags/country-flag/flag_-Falkland-Islands_color.svg';
import flagFaroeIslands from './icons/flags/country-flag/flag_-Faroe-Islands.svg';
import flagFaroeIslandsColor from './icons/flags/country-flag/flag_-Faroe-Islands_color.svg';
import flagFiji from './icons/flags/country-flag/flag_-Fiji.svg';
import flagFijiColor from './icons/flags/country-flag/flag_-Fiji_color.svg';
import flagFinland from './icons/flags/country-flag/flag_-Finland.svg';
import flagFinlandColor from './icons/flags/country-flag/flag_-Finland_color.svg';
import flagFrance from './icons/flags/country-flag/flag_-France.svg';
import flagFranceColor from './icons/flags/country-flag/flag_-France_color.svg';
import flagFrenchGuiana from './icons/flags/country-flag/flag_-French-Guiana.svg';
import flagFrenchGuianaColor from './icons/flags/country-flag/flag_-French-Guiana_color.svg';
import flagFrenchPolynesia from './icons/flags/country-flag/flag_-French-Polynesia.svg';
import flagFrenchPolynesiaColor from './icons/flags/country-flag/flag_-French-Polynesia_color.svg';
import flagFrenchSouthernTerritories from './icons/flags/country-flag/flag_-French-Southern-Territories.svg';
import flagFrenchSouthernTerritoriesColor from './icons/flags/country-flag/flag_-French-Southern-Territories_color.svg';
import flagGabon from './icons/flags/country-flag/flag_-Gabon.svg';
import flagGabonColor from './icons/flags/country-flag/flag_-Gabon_color.svg';
import flagGambia from './icons/flags/country-flag/flag_-Gambia.svg';
import flagGambiaColor from './icons/flags/country-flag/flag_-Gambia_color.svg';
import flagGeorgia from './icons/flags/country-flag/flag_-Georgia.svg';
import flagGeorgiaColor from './icons/flags/country-flag/flag_-Georgia_color.svg';
import flagGermany from './icons/flags/country-flag/flag_-Germany.svg';
import flagGermanyColor from './icons/flags/country-flag/flag_-Germany_color.svg';
import flagGhana from './icons/flags/country-flag/flag_-Ghana.svg';
import flagGhanaColor from './icons/flags/country-flag/flag_-Ghana_color.svg';
import flagGibraltar from './icons/flags/country-flag/flag_-Gibraltar.svg';
import flagGibraltarColor from './icons/flags/country-flag/flag_-Gibraltar_color.svg';
import flagGreece from './icons/flags/country-flag/flag_-Greece.svg';
import flagGreeceColor from './icons/flags/country-flag/flag_-Greece_color.svg';
import flagGreenland from './icons/flags/country-flag/flag_-Greenland.svg';
import flagGreenlandColor from './icons/flags/country-flag/flag_-Greenland_color.svg';
import flagGrenada from './icons/flags/country-flag/flag_-Grenada.svg';
import flagGrenadaColor from './icons/flags/country-flag/flag_-Grenada_color.svg';
import flagGuadeloupe from './icons/flags/country-flag/flag_-Guadeloupe.svg';
import flagGuadeloupeColor from './icons/flags/country-flag/flag_-Guadeloupe_color.svg';
import flagGuam from './icons/flags/country-flag/flag_-Guam.svg';
import flagGuamColor from './icons/flags/country-flag/flag_-Guam_color.svg';
import flagGuatemala from './icons/flags/country-flag/flag_-Guatemala.svg';
import flagGuatemalaColor from './icons/flags/country-flag/flag_-Guatemala_color.svg';
import flagGuernsey from './icons/flags/country-flag/flag_-Guernsey.svg';
import flagGuernseyColor from './icons/flags/country-flag/flag_-Guernsey_color.svg';
import flagGuinea from './icons/flags/country-flag/flag_-Guinea.svg';
import flagGuineaColor from './icons/flags/country-flag/flag_-Guinea_color.svg';
import flagGuineaBissau from './icons/flags/country-flag/flag_-Guinea-Bissau.svg';
import flagGuineaBissauColor from './icons/flags/country-flag/flag_-Guinea-Bissau_color.svg';
import flagGuyana from './icons/flags/country-flag/flag_-Guyana.svg';
import flagGuyanaColor from './icons/flags/country-flag/flag_-Guyana_color.svg';
import flagHaiti from './icons/flags/country-flag/flag_-Haiti.svg';
import flagHaitiColor from './icons/flags/country-flag/flag_-Haiti_color.svg';
import flagHeardAndMcDonaldIslands from './icons/flags/country-flag/flag_-Heard-&-McDonald-Islands.svg';
import flagHeardAndMcDonaldIslandsColor from './icons/flags/country-flag/flag_-Heard-&-McDonald-Islands_color.svg';
import flagHonduras from './icons/flags/country-flag/flag_-Honduras.svg';
import flagHondurasColor from './icons/flags/country-flag/flag_-Honduras_color.svg';
import flagHongKongSARChina from './icons/flags/country-flag/flag_-Hong-Kong-SAR-China.svg';
import flagHongKongSARChinaColor from './icons/flags/country-flag/flag_-Hong-Kong-SAR-China_color.svg';
import flagHungary from './icons/flags/country-flag/flag_-Hungary.svg';
import flagHungaryColor from './icons/flags/country-flag/flag_-Hungary_color.svg';
import flagIceland from './icons/flags/country-flag/flag_-Iceland.svg';
import flagIcelandColor from './icons/flags/country-flag/flag_-Iceland_color.svg';
import flagIndia from './icons/flags/country-flag/flag_-India.svg';
import flagIndiaColor from './icons/flags/country-flag/flag_-India_color.svg';
import flagIndonesia from './icons/flags/country-flag/flag_-Indonesia.svg';
import flagIndonesiaColor from './icons/flags/country-flag/flag_-Indonesia_color.svg';
import flagIran from './icons/flags/country-flag/flag_-Iran.svg';
import flagIranColor from './icons/flags/country-flag/flag_-Iran_color.svg';
import flagIraq from './icons/flags/country-flag/flag_-Iraq.svg';
import flagIraqColor from './icons/flags/country-flag/flag_-Iraq_color.svg';
import flagIreland from './icons/flags/country-flag/flag_-Ireland.svg';
import flagIrelandColor from './icons/flags/country-flag/flag_-Ireland_color.svg';
import flagIsleOfMan from './icons/flags/country-flag/flag_-Isle-of-Man.svg';
import flagIsleOfManColor from './icons/flags/country-flag/flag_-Isle-of-Man_color.svg';
import flagIsrael from './icons/flags/country-flag/flag_-Israel.svg';
import flagIsraelColor from './icons/flags/country-flag/flag_-Israel_color.svg';
import flagItaly from './icons/flags/country-flag/flag_-Italy.svg';
import flagItalyColor from './icons/flags/country-flag/flag_-Italy_color.svg';
import flagJamaica from './icons/flags/country-flag/flag_-Jamaica.svg';
import flagJamaicaColor from './icons/flags/country-flag/flag_-Jamaica_color.svg';
import flagJapan from './icons/flags/country-flag/flag_-Japan.svg';
import flagJapanColor from './icons/flags/country-flag/flag_-Japan_color.svg';
import flagJersey from './icons/flags/country-flag/flag_-Jersey.svg';
import flagJerseyColor from './icons/flags/country-flag/flag_-Jersey_color.svg';
import flagJordan from './icons/flags/country-flag/flag_-Jordan.svg';
import flagJordanColor from './icons/flags/country-flag/flag_-Jordan_color.svg';
import flagKazakhstan from './icons/flags/country-flag/flag_-Kazakhstan.svg';
import flagKazakhstanColor from './icons/flags/country-flag/flag_-Kazakhstan_color.svg';
import flagKenya from './icons/flags/country-flag/flag_-Kenya.svg';
import flagKenyaColor from './icons/flags/country-flag/flag_-Kenya_color.svg';
import flagKiribati from './icons/flags/country-flag/flag_-Kiribati.svg';
import flagKiribatiColor from './icons/flags/country-flag/flag_-Kiribati_color.svg';
import flagKosovo from './icons/flags/country-flag/flag_-Kosovo.svg';
import flagKosovoColor from './icons/flags/country-flag/flag_-Kosovo_color.svg';
import flagKuwait from './icons/flags/country-flag/flag_-Kuwait.svg';
import flagKuwaitColor from './icons/flags/country-flag/flag_-Kuwait_color.svg';
import flagKyrgyzstan from './icons/flags/country-flag/flag_-Kyrgyzstan.svg';
import flagKyrgyzstanColor from './icons/flags/country-flag/flag_-Kyrgyzstan_color.svg';
import flagLaos from './icons/flags/country-flag/flag_-Laos.svg';
import flagLaosColor from './icons/flags/country-flag/flag_-Laos_color.svg';
import flagLatvia from './icons/flags/country-flag/flag_-Latvia.svg';
import flagLatviaColor from './icons/flags/country-flag/flag_-Latvia_color.svg';
import flagLebanon from './icons/flags/country-flag/flag_-Lebanon.svg';
import flagLebanonColor from './icons/flags/country-flag/flag_-Lebanon_color.svg';
import flagLesotho from './icons/flags/country-flag/flag_-Lesotho.svg';
import flagLesothoColor from './icons/flags/country-flag/flag_-Lesotho_color.svg';
import flagLiberia from './icons/flags/country-flag/flag_-Liberia.svg';
import flagLiberiaColor from './icons/flags/country-flag/flag_-Liberia_color.svg';
import flagLibya from './icons/flags/country-flag/flag_-Libya.svg';
import flagLibyaColor from './icons/flags/country-flag/flag_-Libya_color.svg';
import flagLiechtenstein from './icons/flags/country-flag/flag_-Liechtenstein.svg';
import flagLiechtensteinColor from './icons/flags/country-flag/flag_-Liechtenstein_color.svg';
import flagLithuania from './icons/flags/country-flag/flag_-Lithuania.svg';
import flagLithuaniaColor from './icons/flags/country-flag/flag_-Lithuania_color.svg';
import flagLuxembourg from './icons/flags/country-flag/flag_-Luxembourg.svg';
import flagLuxembourgColor from './icons/flags/country-flag/flag_-Luxembourg_color.svg';
import flagMacaoSARChina from './icons/flags/country-flag/flag_-Macao-SAR-China.svg';
import flagMacaoSARChinaColor from './icons/flags/country-flag/flag_-Macao-SAR-China_color.svg';
import flagMadagascar from './icons/flags/country-flag/flag_-Madagascar.svg';
import flagMadagascarColor from './icons/flags/country-flag/flag_-Madagascar_color.svg';
import flagMalawi from './icons/flags/country-flag/flag_-Malawi.svg';
import flagMalawiColor from './icons/flags/country-flag/flag_-Malawi_color.svg';
import flagMalaysia from './icons/flags/country-flag/flag_-Malaysia.svg';
import flagMalaysiaColor from './icons/flags/country-flag/flag_-Malaysia_color.svg';
import flagMaldives from './icons/flags/country-flag/flag_-Maldives.svg';
import flagMaldivesColor from './icons/flags/country-flag/flag_-Maldives_color.svg';
import flagMali from './icons/flags/country-flag/flag_-Mali.svg';
import flagMaliColor from './icons/flags/country-flag/flag_-Mali_color.svg';
import flagMalta from './icons/flags/country-flag/flag_-Malta.svg';
import flagMaltaColor from './icons/flags/country-flag/flag_-Malta_color.svg';
import flagMarshallIslands from './icons/flags/country-flag/flag_-Marshall-Islands.svg';
import flagMarshallIslandsColor from './icons/flags/country-flag/flag_-Marshall-Islands_color.svg';
import flagMartinique from './icons/flags/country-flag/flag_-Martinique.svg';
import flagMartiniqueColor from './icons/flags/country-flag/flag_-Martinique_color.svg';
import flagMauritania from './icons/flags/country-flag/flag_-Mauritania.svg';
import flagMauritaniaColor from './icons/flags/country-flag/flag_-Mauritania_color.svg';
import flagMauritius from './icons/flags/country-flag/flag_-Mauritius.svg';
import flagMauritiusColor from './icons/flags/country-flag/flag_-Mauritius_color.svg';
import flagMayotte from './icons/flags/country-flag/flag_-Mayotte.svg';
import flagMayotteColor from './icons/flags/country-flag/flag_-Mayotte_color.svg';
import flagMexico from './icons/flags/country-flag/flag_-Mexico.svg';
import flagMexicoColor from './icons/flags/country-flag/flag_-Mexico_color.svg';
import flagMicronesia from './icons/flags/country-flag/flag_-Micronesia.svg';
import flagMicronesiaColor from './icons/flags/country-flag/flag_-Micronesia_color.svg';
import flagMoldova from './icons/flags/country-flag/flag_-Moldova.svg';
import flagMoldovaColor from './icons/flags/country-flag/flag_-Moldova_color.svg';
import flagMonaco from './icons/flags/country-flag/flag_-Monaco.svg';
import flagMonacoColor from './icons/flags/country-flag/flag_-Monaco_color.svg';
import flagMongolia from './icons/flags/country-flag/flag_-Mongolia.svg';
import flagMongoliaColor from './icons/flags/country-flag/flag_-Mongolia_color.svg';
import flagMontenegro from './icons/flags/country-flag/flag_-Montenegro.svg';
import flagMontenegroColor from './icons/flags/country-flag/flag_-Montenegro_color.svg';
import flagMontserrat from './icons/flags/country-flag/flag_-Montserrat.svg';
import flagMontserratColor from './icons/flags/country-flag/flag_-Montserrat_color.svg';
import flagMorocco from './icons/flags/country-flag/flag_-Morocco.svg';
import flagMoroccoColor from './icons/flags/country-flag/flag_-Morocco_color.svg';
import flagMozambique from './icons/flags/country-flag/flag_-Mozambique.svg';
import flagMozambiqueColor from './icons/flags/country-flag/flag_-Mozambique_color.svg';
import flagMyanmarBurma from './icons/flags/country-flag/flag_-Myanmar-(Burma).svg';
import flagMyanmarBurmaColor from './icons/flags/country-flag/flag_-Myanmar-(Burma)_color.svg';
import flagNamibia from './icons/flags/country-flag/flag_-Namibia.svg';
import flagNamibiaColor from './icons/flags/country-flag/flag_-Namibia_color.svg';
import flagNauru from './icons/flags/country-flag/flag_-Nauru.svg';
import flagNauruColor from './icons/flags/country-flag/flag_-Nauru_color.svg';
import flagNepal from './icons/flags/country-flag/flag_-Nepal.svg';
import flagNepalColor from './icons/flags/country-flag/flag_-Nepal_color.svg';
import flagNetherlands from './icons/flags/country-flag/flag_-Netherlands.svg';
import flagNetherlandsColor from './icons/flags/country-flag/flag_-Netherlands_color.svg';
import flagNewCaledonia from './icons/flags/country-flag/flag_-New-Caledonia.svg';
import flagNewCaledoniaColor from './icons/flags/country-flag/flag_-New-Caledonia_color.svg';
import flagNewZealand from './icons/flags/country-flag/flag_-New-Zealand.svg';
import flagNewZealandColor from './icons/flags/country-flag/flag_-New-Zealand_color.svg';
import flagNicaragua from './icons/flags/country-flag/flag_-Nicaragua.svg';
import flagNicaraguaColor from './icons/flags/country-flag/flag_-Nicaragua_color.svg';
import flagNiger from './icons/flags/country-flag/flag_-Niger.svg';
import flagNigerColor from './icons/flags/country-flag/flag_-Niger_color.svg';
import flagNigeria from './icons/flags/country-flag/flag_-Nigeria.svg';
import flagNigeriaColor from './icons/flags/country-flag/flag_-Nigeria_color.svg';
import flagNiue from './icons/flags/country-flag/flag_-Niue.svg';
import flagNiueColor from './icons/flags/country-flag/flag_-Niue_color.svg';
import flagNorfolkIsland from './icons/flags/country-flag/flag_-Norfolk-Island.svg';
import flagNorfolkIslandColor from './icons/flags/country-flag/flag_-Norfolk-Island_color.svg';
import flagNorthernMarianaIslands from './icons/flags/country-flag/flag_-Northern-Mariana-Islands.svg';
import flagNorthernMarianaIslandsColor from './icons/flags/country-flag/flag_-Northern-Mariana-Islands_color.svg';
import flagNorthKorea from './icons/flags/country-flag/flag_-North-Korea.svg';
import flagNorthKoreaColor from './icons/flags/country-flag/flag_-North-Korea_color.svg';
import flagNorthMacedonia from './icons/flags/country-flag/flag_-North-Macedonia.svg';
import flagNorthMacedoniaColor from './icons/flags/country-flag/flag_-North-Macedonia_color.svg';
import flagNorway from './icons/flags/country-flag/flag_-Norway.svg';
import flagNorwayColor from './icons/flags/country-flag/flag_-Norway_color.svg';
import flagOman from './icons/flags/country-flag/flag_-Oman.svg';
import flagOmanColor from './icons/flags/country-flag/flag_-Oman_color.svg';
import flagPakistan from './icons/flags/country-flag/flag_-Pakistan.svg';
import flagPakistanColor from './icons/flags/country-flag/flag_-Pakistan_color.svg';
import flagPalau from './icons/flags/country-flag/flag_-Palau.svg';
import flagPalauColor from './icons/flags/country-flag/flag_-Palau_color.svg';
import flagPalestinianTerritories from './icons/flags/country-flag/flag_-Palestinian-Territories.svg';
import flagPalestinianTerritoriesColor from './icons/flags/country-flag/flag_-Palestinian-Territories_color.svg';
import flagPanama from './icons/flags/country-flag/flag_-Panama.svg';
import flagPanamaColor from './icons/flags/country-flag/flag_-Panama_color.svg';
import flagPapuaNewGuinea from './icons/flags/country-flag/flag_-Papua-New-Guinea.svg';
import flagPapuaNewGuineaColor from './icons/flags/country-flag/flag_-Papua-New-Guinea_color.svg';
import flagParaguay from './icons/flags/country-flag/flag_-Paraguay.svg';
import flagParaguayColor from './icons/flags/country-flag/flag_-Paraguay_color.svg';
import flagPeru from './icons/flags/country-flag/flag_-Peru.svg';
import flagPeruColor from './icons/flags/country-flag/flag_-Peru_color.svg';
import flagPhilippines from './icons/flags/country-flag/flag_-Philippines.svg';
import flagPhilippinesColor from './icons/flags/country-flag/flag_-Philippines_color.svg';
import flagPitcairnIslands from './icons/flags/country-flag/flag_-Pitcairn-Islands.svg';
import flagPitcairnIslandsColor from './icons/flags/country-flag/flag_-Pitcairn-Islands_color.svg';
import flagPoland from './icons/flags/country-flag/flag_-Poland.svg';
import flagPolandColor from './icons/flags/country-flag/flag_-Poland_color.svg';
import flagPortugal from './icons/flags/country-flag/flag_-Portugal.svg';
import flagPortugalColor from './icons/flags/country-flag/flag_-Portugal_color.svg';
import flagPuertoRico from './icons/flags/country-flag/flag_-Puerto-Rico.svg';
import flagPuertoRicoColor from './icons/flags/country-flag/flag_-Puerto-Rico_color.svg';
import flagQatar from './icons/flags/country-flag/flag_-Qatar.svg';
import flagQatarColor from './icons/flags/country-flag/flag_-Qatar_color.svg';
import flagRomania from './icons/flags/country-flag/flag_-Romania.svg';
import flagRomaniaColor from './icons/flags/country-flag/flag_-Romania_color.svg';
import flagRussia from './icons/flags/country-flag/flag_-Russia.svg';
import flagRussiaColor from './icons/flags/country-flag/flag_-Russia_color.svg';
import flagRwanda from './icons/flags/country-flag/flag_-Rwanda.svg';
import flagRwandaColor from './icons/flags/country-flag/flag_-Rwanda_color.svg';
import flagSamoa from './icons/flags/country-flag/flag_-Samoa.svg';
import flagSamoaColor from './icons/flags/country-flag/flag_-Samoa_color.svg';
import flagSanMarino from './icons/flags/country-flag/flag_-San-Marino.svg';
import flagSanMarinoColor from './icons/flags/country-flag/flag_-San-Marino_color.svg';
import flagSaudiArabia from './icons/flags/country-flag/flag_-Saudi-Arabia.svg';
import flagSaudiArabiaColor from './icons/flags/country-flag/flag_-Saudi-Arabia_color.svg';
import flagSenegal from './icons/flags/country-flag/flag_-Senegal.svg';
import flagSenegalColor from './icons/flags/country-flag/flag_-Senegal_color.svg';
import flagSerbia from './icons/flags/country-flag/flag_-Serbia.svg';
import flagSerbiaColor from './icons/flags/country-flag/flag_-Serbia_color.svg';
import flagSeychelles from './icons/flags/country-flag/flag_-Seychelles.svg';
import flagSeychellesColor from './icons/flags/country-flag/flag_-Seychelles_color.svg';
import flagSierraLeone from './icons/flags/country-flag/flag_-Sierra-Leone.svg';
import flagSierraLeoneColor from './icons/flags/country-flag/flag_-Sierra-Leone_color.svg';
import flagSingapore from './icons/flags/country-flag/flag_-Singapore.svg';
import flagSingaporeColor from './icons/flags/country-flag/flag_-Singapore_color.svg';
import flagSintMaarten from './icons/flags/country-flag/flag_-Sint-Maarten.svg';
import flagSintMaartenColor from './icons/flags/country-flag/flag_-Sint-Maarten_color.svg';
import flagSlovakia from './icons/flags/country-flag/flag_-Slovakia.svg';
import flagSlovakiaColor from './icons/flags/country-flag/flag_-Slovakia_color.svg';
import flagSlovenia from './icons/flags/country-flag/flag_-Slovenia.svg';
import flagSloveniaColor from './icons/flags/country-flag/flag_-Slovenia_color.svg';
import flagSolomonIslands from './icons/flags/country-flag/flag_-Solomon-Islands.svg';
import flagSolomonIslandsColor from './icons/flags/country-flag/flag_-Solomon-Islands_color.svg';
import flagSomalia from './icons/flags/country-flag/flag_-Somalia.svg';
import flagSomaliaColor from './icons/flags/country-flag/flag_-Somalia_color.svg';
import flagSouthAfrica from './icons/flags/country-flag/flag_-South-Africa.svg';
import flagSouthAfricaColor from './icons/flags/country-flag/flag_-South-Africa_color.svg';
import flagSouthGeorgiaAndSouthSandwichIslands from './icons/flags/country-flag/flag_-South-Georgia-&-South-Sandwich-Islands.svg';
import flagSouthGeorgiaAndSouthSandwichIslandsColor from './icons/flags/country-flag/flag_-South-Georgia-&-South-Sandwich-Islands_color.svg';
import flagSouthKorea from './icons/flags/country-flag/flag_-South-Korea.svg';
import flagSouthKoreaColor from './icons/flags/country-flag/flag_-South-Korea_color.svg';
import flagSouthSudan from './icons/flags/country-flag/flag_-South-Sudan.svg';
import flagSouthSudanColor from './icons/flags/country-flag/flag_-South-Sudan_color.svg';
import flagSpain from './icons/flags/country-flag/flag_-Spain.svg';
import flagSpainColor from './icons/flags/country-flag/flag_-Spain_color.svg';
import flagSriLanka from './icons/flags/country-flag/flag_-Sri-Lanka.svg';
import flagSriLankaColor from './icons/flags/country-flag/flag_-Sri-Lanka_color.svg';
import flagStHelena from './icons/flags/country-flag/flag_-St.-Helena.svg';
import flagStHelenaColor from './icons/flags/country-flag/flag_-St.-Helena_color.svg';
import flagStKittsAndNevis from './icons/flags/country-flag/flag_-St.-Kitts-&-Nevis.svg';
import flagStKittsAndNevisColor from './icons/flags/country-flag/flag_-St.-Kitts-&-Nevis_color.svg';
import flagStLucia from './icons/flags/country-flag/flag_-St.-Lucia.svg';
import flagStLuciaColor from './icons/flags/country-flag/flag_-St.-Lucia_color.svg';
import flagStMartin from './icons/flags/country-flag/flag_-St.-Martin.svg';
import flagStMartinColor from './icons/flags/country-flag/flag_-St.-Martin_color.svg';
import flagStPierreAndMiquelon from './icons/flags/country-flag/flag_-St.-Pierre-&-Miquelon.svg';
import flagStPierreAndMiquelonColor from './icons/flags/country-flag/flag_-St.-Pierre-&-Miquelon_color.svg';
import flagStVincentAndGrenadines from './icons/flags/country-flag/flag_-St.-Vincent-&-Grenadines.svg';
import flagStVincentAndGrenadinesColor from './icons/flags/country-flag/flag_-St.-Vincent-&-Grenadines_color.svg';
import flagSudan from './icons/flags/country-flag/flag_-Sudan.svg';
import flagSudanColor from './icons/flags/country-flag/flag_-Sudan_color.svg';
import flagSuriname from './icons/flags/country-flag/flag_-Suriname.svg';
import flagSurinameColor from './icons/flags/country-flag/flag_-Suriname_color.svg';
import flagSvalbardAndJanMayen from './icons/flags/country-flag/flag_-Svalbard-&-Jan-Mayen.svg';
import flagSvalbardAndJanMayenColor from './icons/flags/country-flag/flag_-Svalbard-&-Jan-Mayen_color.svg';
import flagSweden from './icons/flags/country-flag/flag_-Sweden.svg';
import flagSwedenColor from './icons/flags/country-flag/flag_-Sweden_color.svg';
import flagSwitzerland from './icons/flags/country-flag/flag_-Switzerland.svg';
import flagSwitzerlandColor from './icons/flags/country-flag/flag_-Switzerland_color.svg';
import flagSyria from './icons/flags/country-flag/flag_-Syria.svg';
import flagSyriaColor from './icons/flags/country-flag/flag_-Syria_color.svg';
import flagTaiwan from './icons/flags/country-flag/flag_-Taiwan.svg';
import flagTaiwanColor from './icons/flags/country-flag/flag_-Taiwan_color.svg';
import flagTajikistan from './icons/flags/country-flag/flag_-Tajikistan.svg';
import flagTajikistanColor from './icons/flags/country-flag/flag_-Tajikistan_color.svg';
import flagTanzania from './icons/flags/country-flag/flag_-Tanzania.svg';
import flagTanzaniaColor from './icons/flags/country-flag/flag_-Tanzania_color.svg';
import flagThailand from './icons/flags/country-flag/flag_-Thailand.svg';
import flagThailandColor from './icons/flags/country-flag/flag_-Thailand_color.svg';
import flagTimorLeste from './icons/flags/country-flag/flag_-Timor-Leste.svg';
import flagTimorLesteColor from './icons/flags/country-flag/flag_-Timor-Leste_color.svg';
import flagTogo from './icons/flags/country-flag/flag_-Togo.svg';
import flagTogoColor from './icons/flags/country-flag/flag_-Togo_color.svg';
import flagTokelau from './icons/flags/country-flag/flag_-Tokelau.svg';
import flagTokelauColor from './icons/flags/country-flag/flag_-Tokelau_color.svg';
import flagTonga from './icons/flags/country-flag/flag_-Tonga.svg';
import flagTongaColor from './icons/flags/country-flag/flag_-Tonga_color.svg';
import flagTrinidadAndTobago from './icons/flags/country-flag/flag_-Trinidad-&-Tobago.svg';
import flagTrinidadAndTobagoColor from './icons/flags/country-flag/flag_-Trinidad-&-Tobago_color.svg';
import flagTristanDaCunha from './icons/flags/country-flag/flag_-Tristan-da-Cunha.svg';
import flagTristanDaCunhaColor from './icons/flags/country-flag/flag_-Tristan-da-Cunha_color.svg';
import flagTunisia from './icons/flags/country-flag/flag_-Tunisia.svg';
import flagTunisiaColor from './icons/flags/country-flag/flag_-Tunisia_color.svg';
import flagTurkey from './icons/flags/country-flag/flag_-Turkey.svg';
import flagTurkeyColor from './icons/flags/country-flag/flag_-Turkey_color.svg';
import flagTurkmenistan from './icons/flags/country-flag/flag_-Turkmenistan.svg';
import flagTurkmenistanColor from './icons/flags/country-flag/flag_-Turkmenistan_color.svg';
import flagTurksAndCaicosIslands from './icons/flags/country-flag/flag_-Turks-&-Caicos-Islands.svg';
import flagTurksAndCaicosIslandsColor from './icons/flags/country-flag/flag_-Turks-&-Caicos-Islands_color.svg';
import flagTuvalu from './icons/flags/country-flag/flag_-Tuvalu.svg';
import flagTuvaluColor from './icons/flags/country-flag/flag_-Tuvalu_color.svg';
import flagUSOutlyingIslands from './icons/flags/country-flag/flag_-U.S.-Outlying-Islands.svg';
import flagUSOutlyingIslandsColor from './icons/flags/country-flag/flag_-U.S.-Outlying-Islands_color.svg';
import flagUSVirginIslands from './icons/flags/country-flag/flag_-U.S.-Virgin-Islands.svg';
import flagUSVirginIslandsColor from './icons/flags/country-flag/flag_-U.S.-Virgin-Islands_color.svg';
import flagUganda from './icons/flags/country-flag/flag_-Uganda.svg';
import flagUgandaColor from './icons/flags/country-flag/flag_-Uganda_color.svg';
import flagUkraine from './icons/flags/country-flag/flag_-Ukraine.svg';
import flagUkraineColor from './icons/flags/country-flag/flag_-Ukraine_color.svg';
import flagUnitedArabEmirates from './icons/flags/country-flag/flag_-United-Arab-Emirates.svg';
import flagUnitedArabEmiratesColor from './icons/flags/country-flag/flag_-United-Arab-Emirates_color.svg';
import flagUnitedKingdom from './icons/flags/country-flag/flag_-United-Kingdom.svg';
import flagUnitedKingdomColor from './icons/flags/country-flag/flag_-United-Kingdom_color.svg';
import flagUnitedNations from './icons/flags/country-flag/flag_-United-Nations.svg';
import flagUnitedNationsColor from './icons/flags/country-flag/flag_-United-Nations_color.svg';
import flagUnitedStates from './icons/flags/country-flag/flag_-United-States.svg';
import flagUnitedStatesColor from './icons/flags/country-flag/flag_-United-States_color.svg';
import flagUruguay from './icons/flags/country-flag/flag_-Uruguay.svg';
import flagUruguayColor from './icons/flags/country-flag/flag_-Uruguay_color.svg';
import flagUzbekistan from './icons/flags/country-flag/flag_-Uzbekistan.svg';
import flagUzbekistanColor from './icons/flags/country-flag/flag_-Uzbekistan_color.svg';
import flagVanuatu from './icons/flags/country-flag/flag_-Vanuatu.svg';
import flagVanuatuColor from './icons/flags/country-flag/flag_-Vanuatu_color.svg';
import flagVaticanCity from './icons/flags/country-flag/flag_-Vatican-City.svg';
import flagVaticanCityColor from './icons/flags/country-flag/flag_-Vatican-City_color.svg';
import flagVenezuela from './icons/flags/country-flag/flag_-Venezuela.svg';
import flagVenezuelaColor from './icons/flags/country-flag/flag_-Venezuela_color.svg';
import flagVietnam from './icons/flags/country-flag/flag_-Vietnam.svg';
import flagVietnamColor from './icons/flags/country-flag/flag_-Vietnam_color.svg';
import flagWallisAndFutuna from './icons/flags/country-flag/flag_-Wallis-&-Futuna.svg';
import flagWallisAndFutunaColor from './icons/flags/country-flag/flag_-Wallis-&-Futuna_color.svg';
import flagWesternSahara from './icons/flags/country-flag/flag_-Western-Sahara.svg';
import flagWesternSaharaColor from './icons/flags/country-flag/flag_-Western-Sahara_color.svg';
import flagYemen from './icons/flags/country-flag/flag_-Yemen.svg';
import flagYemenColor from './icons/flags/country-flag/flag_-Yemen_color.svg';
import flagZambia from './icons/flags/country-flag/flag_-Zambia.svg';
import flagZambiaColor from './icons/flags/country-flag/flag_-Zambia_color.svg';
import flagZimbabwe from './icons/flags/country-flag/flag_-Zimbabwe.svg';
import flagZimbabweColor from './icons/flags/country-flag/flag_-Zimbabwe_color.svg';
import blackFlag from './icons/flags/flag/black-flag.svg';
import blackFlagColor from './icons/flags/flag/black-flag_color.svg';
import chequeredFlag from './icons/flags/flag/chequered-flag.svg';
import chequeredFlagColor from './icons/flags/flag/chequered-flag_color.svg';
import crossedFlags from './icons/flags/flag/crossed-flags.svg';
import crossedFlagsColor from './icons/flags/flag/crossed-flags_color.svg';
import pirateFlag from './icons/flags/flag/pirate-flag.svg';
import pirateFlagColor from './icons/flags/flag/pirate-flag_color.svg';
import rainbowFlag from './icons/flags/flag/rainbow-flag.svg';
import rainbowFlagColor from './icons/flags/flag/rainbow-flag_color.svg';
import transgenderFlag from './icons/flags/flag/transgender-flag.svg';
import transgenderFlagColor from './icons/flags/flag/transgender-flag_color.svg';
import triangularFlag from './icons/flags/flag/triangular-flag.svg';
import triangularFlagColor from './icons/flags/flag/triangular-flag_color.svg';
import whiteFlag from './icons/flags/flag/white-flag.svg';
import whiteFlagColor from './icons/flags/flag/white-flag_color.svg';
import flagEngland from './icons/flags/subdivision-flag/flag_-England.svg';
import flagEnglandColor from './icons/flags/subdivision-flag/flag_-England_color.svg';
import flagScotland from './icons/flags/subdivision-flag/flag_-Scotland.svg';
import flagScotlandColor from './icons/flags/subdivision-flag/flag_-Scotland_color.svg';
import flagWales from './icons/flags/subdivision-flag/flag_-Wales.svg';
import flagWalesColor from './icons/flags/subdivision-flag/flag_-Wales_color.svg';

import {IconProps} from './use-search';

export const openFlagsTable = new Map<string, Omit<IconProps, 'id'>>();

openFlagsTable.set('flagAfghanistan', {name: 'Flag Afghanistan', icon: flagAfghanistan});
openFlagsTable.set('flagAfghanistanColor', {name: 'Flag Afghanistan Color', icon: flagAfghanistanColor});
openFlagsTable.set('flagAlbania', {name: 'Flag Albania', icon: flagAlbania});
openFlagsTable.set('flagAlbaniaColor', {name: 'Flag Albania Color', icon: flagAlbaniaColor});
openFlagsTable.set('flagAlgeria', {name: 'Flag Algeria', icon: flagAlgeria});
openFlagsTable.set('flagAlgeriaColor', {name: 'Flag Algeria Color', icon: flagAlgeriaColor});
openFlagsTable.set('flagAmericanSamoa', {name: 'Flag American Samoa', icon: flagAmericanSamoa});
openFlagsTable.set('flagAmericanSamoaColor', {name: 'Flag American Samoa Color', icon: flagAmericanSamoaColor});
openFlagsTable.set('flagAndorra', {name: 'Flag Andorra', icon: flagAndorra});
openFlagsTable.set('flagAndorraColor', {name: 'Flag Andorra Color', icon: flagAndorraColor});
openFlagsTable.set('flagAngola', {name: 'Flag Angola', icon: flagAngola});
openFlagsTable.set('flagAngolaColor', {name: 'Flag Angola Color', icon: flagAngolaColor});
openFlagsTable.set('flagAnguilla', {name: 'Flag Anguilla', icon: flagAnguilla});
openFlagsTable.set('flagAnguillaColor', {name: 'Flag Anguilla Color', icon: flagAnguillaColor});
openFlagsTable.set('flagAntarctica', {name: 'Flag Antarctica', icon: flagAntarctica});
openFlagsTable.set('flagAntarcticaColor', {name: 'Flag Antarctica Color', icon: flagAntarcticaColor});
openFlagsTable.set('flagAntiguaAndBarbuda', {name: 'Flag Antigua And Barbuda', icon: flagAntiguaAndBarbuda});
openFlagsTable.set('flagAntiguaAndBarbudaColor', {
    name: 'Flag Antigua And Barbuda Color',
    icon: flagAntiguaAndBarbudaColor,
});
openFlagsTable.set('flagArgentina', {name: 'Flag Argentina', icon: flagArgentina});
openFlagsTable.set('flagArgentinaColor', {name: 'Flag Argentina Color', icon: flagArgentinaColor});
openFlagsTable.set('flagArmenia', {name: 'Flag Armenia', icon: flagArmenia});
openFlagsTable.set('flagArmeniaColor', {name: 'Flag Armenia Color', icon: flagArmeniaColor});
openFlagsTable.set('flagAruba', {name: 'Flag Aruba', icon: flagAruba});
openFlagsTable.set('flagArubaColor', {name: 'Flag Aruba Color', icon: flagArubaColor});
openFlagsTable.set('flagAscensionIsland', {name: 'Flag Ascension Island', icon: flagAscensionIsland});
openFlagsTable.set('flagAscensionIslandColor', {name: 'Flag Ascension Island Color', icon: flagAscensionIslandColor});
openFlagsTable.set('flagAustralia', {name: 'Flag AUstralia', icon: flagAustralia});
openFlagsTable.set('flagAustraliaColor', {name: 'Flag Australia Color', icon: flagAustraliaColor});
openFlagsTable.set('flagAustria', {name: 'Flag Austria', icon: flagAustria});
openFlagsTable.set('flagAustriaColor', {name: 'Flag Austria Color', icon: flagAustriaColor});
openFlagsTable.set('flagAzerbaijan', {name: 'Flag Azerbaijan', icon: flagAzerbaijan});
openFlagsTable.set('flagAzerbaijanColor', {name: 'Flag Azerbaijan Color', icon: flagAzerbaijanColor});
openFlagsTable.set('flagBahamas', {name: 'Flag Bahamas', icon: flagBahamas});
openFlagsTable.set('flagBahamasColor', {name: 'Flag Bahamas Color', icon: flagBahamasColor});
openFlagsTable.set('flagBahrain', {name: 'Flag Bahrain', icon: flagBahrain});
openFlagsTable.set('flagBahrainColor', {name: 'Flag Bahrain Color', icon: flagBahrainColor});
openFlagsTable.set('flagBangladesh', {name: 'Flag Bangladesh', icon: flagBangladesh});
openFlagsTable.set('flagBangladeshColor', {name: 'Flag Bangladesh Color', icon: flagBangladeshColor});
openFlagsTable.set('flagBarbados', {name: 'Flag Barbados', icon: flagBarbados});
openFlagsTable.set('flagBarbadosColor', {name: 'Flag Barbados Color', icon: flagBarbadosColor});
openFlagsTable.set('flagBelarus', {name: 'Flag Belarus', icon: flagBelarus});
openFlagsTable.set('flagBelarusColor', {name: 'Flag Belarus Color', icon: flagBelarusColor});
openFlagsTable.set('flagBelgium', {name: 'Flag Belgium', icon: flagBelgium});
openFlagsTable.set('flagBelgiumColor', {name: 'Flag Belgium Color', icon: flagBelgiumColor});
openFlagsTable.set('flagBelize', {name: 'Flag Belize', icon: flagBelize});
openFlagsTable.set('flagBelizeColor', {name: 'Flag Belize Color', icon: flagBelizeColor});
openFlagsTable.set('flagBenin', {name: 'Flag Benin', icon: flagBenin});
openFlagsTable.set('flagBeninColor', {name: 'Flag Benin Color', icon: flagBeninColor});
openFlagsTable.set('flagBermuda', {name: 'Flag Bermuda', icon: flagBermuda});
openFlagsTable.set('flagBermudaColor', {name: 'Flag Bermuda Color', icon: flagBermudaColor});
openFlagsTable.set('flagBhutan', {name: 'Flag Bhutan', icon: flagBhutan});
openFlagsTable.set('flagBhutanColor', {name: 'Flag Bhutan Color', icon: flagBhutanColor});
openFlagsTable.set('flagBolivia', {name: 'Flag Bolivia', icon: flagBolivia});
openFlagsTable.set('flagBoliviaColor', {name: 'Flag Bolivia Color', icon: flagBoliviaColor});
openFlagsTable.set('flagBosniaAndHerzegovina', {name: 'Flag Bosnia And Herzegovina', icon: flagBosniaAndHerzegovina});
openFlagsTable.set('flagBosniaAndHerzegovinaColor', {
    name: 'Flag Bosnia And Herzegovina Color',
    icon: flagBosniaAndHerzegovinaColor,
});
openFlagsTable.set('flagBotswana', {name: 'Flag Botswana', icon: flagBotswana});
openFlagsTable.set('flagBotswanaColor', {name: 'Flag Botswana Color', icon: flagBotswanaColor});
openFlagsTable.set('flagBouvetIsland', {name: 'Flag Bouvet Island', icon: flagBouvetIsland});
openFlagsTable.set('flagBouvetIslandColor', {name: 'Flag Bouvet Island Color', icon: flagBouvetIslandColor});
openFlagsTable.set('flagBrazil', {name: 'Flag Brazil', icon: flagBrazil});
openFlagsTable.set('flagBrazilColor', {name: 'Flag Brazil Color', icon: flagBrazilColor});
openFlagsTable.set('flagBritishIndianOceanTerritory', {
    name: 'Flag British Indian Ocean Territory',
    icon: flagBritishIndianOceanTerritory,
});
openFlagsTable.set('flagBritishIndianOceanTerritoryColor', {
    name: 'Flag British Indian Ocean Territory Color',
    icon: flagBritishIndianOceanTerritoryColor,
});
openFlagsTable.set('flagBritishVirginIslands', {name: 'Flag British Virgin Islands', icon: flagBritishVirginIslands});
openFlagsTable.set('flagBritishVirginIslandsColor', {
    name: 'Flag British Virgin Islands Color',
    icon: flagBritishVirginIslandsColor,
});
openFlagsTable.set('flagBrunei', {name: 'Flag Brunei', icon: flagBrunei});
openFlagsTable.set('flagBruneiColor', {name: 'Flag Brunei Color', icon: flagBruneiColor});
openFlagsTable.set('flagBulgaria', {name: 'Flag Bulgaria', icon: flagBulgaria});
openFlagsTable.set('flagBulgariaColor', {name: 'Flag Bulgaria Color', icon: flagBulgariaColor});
openFlagsTable.set('flagBurkinaFaso', {name: 'Flag Burkina Faso', icon: flagBurkinaFaso});
openFlagsTable.set('flagBurkinaFasoColor', {name: 'Flag Burkina Faso Color', icon: flagBurkinaFasoColor});
openFlagsTable.set('flagBurundi', {name: 'Flag Burundi', icon: flagBurundi});
openFlagsTable.set('flagBurundiColor', {name: 'Flag Burundi Color', icon: flagBurundiColor});
openFlagsTable.set('flagCambodia', {name: 'Flag Cambodia', icon: flagCambodia});
openFlagsTable.set('flagCambodiaColor', {name: 'Flag Cambodia Color', icon: flagCambodiaColor});
openFlagsTable.set('flagCameroon', {name: 'Flag Cameroon', icon: flagCameroon});
openFlagsTable.set('flagCameroonColor', {name: 'Flag Cameroon Color', icon: flagCameroonColor});
openFlagsTable.set('flagCanada', {name: 'Flag Canada', icon: flagCanada});
openFlagsTable.set('flagCanadaColor', {name: 'Flag Canada Color', icon: flagCanadaColor});
openFlagsTable.set('flagCanaryIslands', {name: 'Flag Canary Islands', icon: flagCanaryIslands});
openFlagsTable.set('flagCanaryIslandsColor', {name: 'Flag Canary Islands Color', icon: flagCanaryIslandsColor});
openFlagsTable.set('flagCapeVerde', {name: 'Flag Cape Verde', icon: flagCapeVerde});
openFlagsTable.set('flagCapeVerdeColor', {name: 'Flag Cape Verde', icon: flagCapeVerdeColor});
openFlagsTable.set('flagCaribbeanNetherlands', {name: 'Flag Caribbean Netherlands', icon: flagCaribbeanNetherlands});
openFlagsTable.set('flagCaribbeanNetherlandsColor', {
    name: 'Flag Caribbean Netherlands Color',
    icon: flagCaribbeanNetherlandsColor,
});
openFlagsTable.set('flagCaymanIslands', {name: 'Flag Cayman Islands', icon: flagCaymanIslands});
openFlagsTable.set('flagCaymanIslandsColor', {name: 'Flag Cayman Islands Color', icon: flagCaymanIslandsColor});
openFlagsTable.set('flagCentralAfricanRepublic', {
    name: 'Flag Central African Republic',
    icon: flagCentralAfricanRepublic,
});
openFlagsTable.set('flagCentralAfricanRepublicColor', {
    name: 'Flag Central African Republic Color',
    icon: flagCentralAfricanRepublicColor,
});
openFlagsTable.set('flagCeutaAndMelilla', {name: 'Flag Ceuta And Melilla', icon: flagCeutaAndMelilla});
openFlagsTable.set('flagCeutaAndMelillaColor', {name: 'Flag Ceuta And Melilla Color', icon: flagCeutaAndMelillaColor});
openFlagsTable.set('flagChad', {name: 'Flag Chad', icon: flagChad});
openFlagsTable.set('flagChadColor', {name: 'Flag Chad Color', icon: flagChadColor});
openFlagsTable.set('flagChile', {name: 'Flag Chile', icon: flagChile});
openFlagsTable.set('flagChileColor', {name: 'Flag Chile Color', icon: flagChileColor});
openFlagsTable.set('flagChina', {name: 'Flag China', icon: flagChina});
openFlagsTable.set('flagChinaColor', {name: 'Flag China Color', icon: flagChinaColor});
openFlagsTable.set('flagChristmasIsland', {name: 'Flag Christmas Island', icon: flagChristmasIsland});
openFlagsTable.set('flagChristmasIslandColor', {name: 'Flag Christmas Island Color', icon: flagChristmasIslandColor});
openFlagsTable.set('flagClippertonIsland', {name: 'Flag Clipperton Island', icon: flagClippertonIsland});
openFlagsTable.set('flagClippertonIslandColor', {name: 'Flag Clipperton Island', icon: flagClippertonIslandColor});
openFlagsTable.set('flagCocosKeelingIslands', {name: 'Flag Cocos Keeling Islands', icon: flagCocosKeelingIslands});
openFlagsTable.set('flagCocosKeelingIslandsColor', {
    name: 'Flag Cocos Keeling Islands Color',
    icon: flagCocosKeelingIslandsColor,
});
openFlagsTable.set('flagColombia', {name: 'Flag Colombia', icon: flagColombia});
openFlagsTable.set('flagColombiaColor', {name: 'Flag Colombia Color', icon: flagColombiaColor});
openFlagsTable.set('flagComoros', {name: 'Flag Comoros', icon: flagComoros});
openFlagsTable.set('flagComorosColor', {name: 'Flag Comoros Color', icon: flagComorosColor});
openFlagsTable.set('flagCongoBrazzaville', {name: 'Flag Congo Brazzaville', icon: flagCongoBrazzaville});
openFlagsTable.set('flagCongoBrazzavilleColor', {
    name: 'Flag Congo Brazzaville Color',
    icon: flagCongoBrazzavilleColor,
});
openFlagsTable.set('flagCongoKinshasa', {name: 'Flag Congo Kinshasa', icon: flagCongoKinshasa});
openFlagsTable.set('flagCongoKinshasaColor', {name: 'Flag Congo Kinhasa Color', icon: flagCongoKinshasaColor});
openFlagsTable.set('flagCookIslands', {name: 'Flag Cook Islands', icon: flagCookIslands});
openFlagsTable.set('flagCookIslandsColor', {name: 'Flag Cook Islands Color', icon: flagCookIslandsColor});
openFlagsTable.set('flagCostaRica', {name: 'Flag Costa Rica', icon: flagCostaRica});
openFlagsTable.set('flagCostaRicaColor', {name: 'Flag Costa Rica Color', icon: flagCostaRicaColor});
openFlagsTable.set('flagCroatia', {name: 'Flag Croatia', icon: flagCroatia});
openFlagsTable.set('flagCroatiaColor', {name: 'Flag Croatia Color', icon: flagCroatiaColor});
openFlagsTable.set('flagCuba', {name: 'Flag Cuba', icon: flagCuba});
openFlagsTable.set('flagCubaColor', {name: 'Flag Cuba Color', icon: flagCubaColor});
openFlagsTable.set('flagCyprus', {name: 'Flag Cyprus', icon: flagCyprus});
openFlagsTable.set('flagCyprusColor', {name: 'Flag Cyprus Color', icon: flagCyprusColor});
openFlagsTable.set('flagCzechia', {name: 'Flag Czechia', icon: flagCzechia});
openFlagsTable.set('flagCzechiaColor', {name: 'Flag Czechia Color', icon: flagCzechiaColor});
openFlagsTable.set('flagDenmark', {name: 'Flag Denmark', icon: flagDenmark});
openFlagsTable.set('flagDenmarkColor', {name: 'Flag Denmark Color', icon: flagDenmarkColor});
openFlagsTable.set('flagDiegoGarcia', {name: 'Flag Diego Garcia', icon: flagDiegoGarcia});
openFlagsTable.set('flagDiegoGarciaColor', {name: 'Flag Diego Garcia Color', icon: flagDiegoGarciaColor});
openFlagsTable.set('flagDjibouti', {name: 'Flag Djibouti', icon: flagDjibouti});
openFlagsTable.set('flagDjiboutiColor', {name: 'Flag Djibouti Color', icon: flagDjiboutiColor});
openFlagsTable.set('flagDominica', {name: 'Flag Dominica', icon: flagDominica});
openFlagsTable.set('flagDominicaColor', {name: 'Flag Dominica Color', icon: flagDominicaColor});
openFlagsTable.set('flagDominicanRepublic', {name: 'Flag Dominican Republic', icon: flagDominicanRepublic});
openFlagsTable.set('flagDominicanRepublicColor', {
    name: 'Flag Dominican Republic Color',
    icon: flagDominicanRepublicColor,
});
openFlagsTable.set('flagEcuador', {name: 'Flag Ecuador', icon: flagEcuador});
openFlagsTable.set('flagEcuadorColor', {name: 'Flag Ecuador Color', icon: flagEcuadorColor});
openFlagsTable.set('flagEgypt', {name: 'Flag Egypt', icon: flagEgypt});
openFlagsTable.set('flagEgyptColor', {name: 'Flag Egypt Color', icon: flagEgyptColor});
openFlagsTable.set('flagElSalvador', {name: 'Flag El Salvador', icon: flagElSalvador});
openFlagsTable.set('flagElSalvadorColor', {name: 'Flag El Salvador Color', icon: flagElSalvadorColor});
openFlagsTable.set('flagEquatorialGuinea', {name: 'Flag Equatorial Guinea', icon: flagEquatorialGuinea});
openFlagsTable.set('flagEquatorialGuineaColor', {
    name: 'Flag Equatorial Guinea Color',
    icon: flagEquatorialGuineaColor,
});
openFlagsTable.set('flagEritrea', {name: 'Flag Eritrea', icon: flagEritrea});
openFlagsTable.set('flagEritreaColor', {name: 'Flag Eritrea Color ', icon: flagEritreaColor});
openFlagsTable.set('flagEstonia', {name: 'Flag Estonia', icon: flagEstonia});
openFlagsTable.set('flagEstoniaColor', {name: 'Flag Estonia Color', icon: flagEstoniaColor});
openFlagsTable.set('flagEswatini', {name: 'Flag Eswatini', icon: flagEswatini});
openFlagsTable.set('flagEswatiniColor', {name: 'Flag Eswatini Color', icon: flagEswatiniColor});
openFlagsTable.set('flagEthiopia', {name: 'Flag Ethiopia', icon: flagEthiopia});
openFlagsTable.set('flagEthiopiaColor', {name: 'Flag Ethiopia Color', icon: flagEthiopiaColor});
openFlagsTable.set('flagEuropeanUnion', {name: 'Flag European Union', icon: flagEuropeanUnion});
openFlagsTable.set('flagEuropeanUnionColor', {name: 'Flag European Union Color', icon: flagEuropeanUnionColor});
openFlagsTable.set('flagFalklandIslands', {name: 'Flag Falkland Islands', icon: flagFalklandIslands});
openFlagsTable.set('flagFalklandIslandsColor', {name: 'Flag Falkland Islands Color', icon: flagFalklandIslandsColor});
openFlagsTable.set('flagFaroeIslands', {name: 'Flag Faroe Islands', icon: flagFaroeIslands});
openFlagsTable.set('flagFaroeIslandsColor', {name: 'Flag Faroe Islands Color', icon: flagFaroeIslandsColor});
openFlagsTable.set('flagFiji', {name: 'Flag Fiji', icon: flagFiji});
openFlagsTable.set('flagFijiColor', {name: 'Flag Fiji Color', icon: flagFijiColor});
openFlagsTable.set('flagFinland', {name: 'Flag Finland', icon: flagFinland});
openFlagsTable.set('flagFinlandColor', {name: 'Flag Finland Color', icon: flagFinlandColor});
openFlagsTable.set('flagFrance', {name: 'Flag France', icon: flagFrance});
openFlagsTable.set('flagFranceColor', {name: 'Flag France Color', icon: flagFranceColor});
openFlagsTable.set('flagFrenchGuiana', {name: 'Flag French Guiana', icon: flagFrenchGuiana});
openFlagsTable.set('flagFrenchGuianaColor', {name: 'Flag French Guiana Color', icon: flagFrenchGuianaColor});
openFlagsTable.set('flagFrenchPolynesia', {name: 'Flag French Polynesia', icon: flagFrenchPolynesia});
openFlagsTable.set('flagFrenchPolynesiaColor', {name: 'Flag French Polynesia Color', icon: flagFrenchPolynesiaColor});
openFlagsTable.set('flagFrenchSouthernTerritories', {
    name: 'Flag French Southern Territories',
    icon: flagFrenchSouthernTerritories,
});
openFlagsTable.set('flagFrenchSouthernTerritoriesColor', {
    name: 'Flag French Southern Territories Color',
    icon: flagFrenchSouthernTerritoriesColor,
});
openFlagsTable.set('flagGabon', {name: 'Flag Gabon', icon: flagGabon});
openFlagsTable.set('flagGabonColor', {name: 'Flag Gabon Color', icon: flagGabonColor});
openFlagsTable.set('flagGambia', {name: 'Flag Gambia', icon: flagGambia});
openFlagsTable.set('flagGambiaColor', {name: 'Flag Gambia Color', icon: flagGambiaColor});
openFlagsTable.set('flagGeorgia', {name: 'Flag Georgia', icon: flagGeorgia});
openFlagsTable.set('flagGeorgiaColor', {name: 'Flag Georgia Color', icon: flagGeorgiaColor});
openFlagsTable.set('flagGermany', {name: 'Flag Germany', icon: flagGermany});
openFlagsTable.set('flagGermanyColor', {name: 'Flag Germany Color', icon: flagGermanyColor});
openFlagsTable.set('flagGhana', {name: 'Flag Ghana', icon: flagGhana});
openFlagsTable.set('flagGhanaColor', {name: 'Flag Ghana Color', icon: flagGhanaColor});
openFlagsTable.set('flagGibraltar', {name: 'Flag Gibraltar', icon: flagGibraltar});
openFlagsTable.set('flagGibraltarColor', {name: 'Flag Gibraltar Color', icon: flagGibraltarColor});
openFlagsTable.set('flagGreece', {name: 'Flag Greece', icon: flagGreece});
openFlagsTable.set('flagGreeceColor', {name: 'Flag Greece Color', icon: flagGreeceColor});
openFlagsTable.set('flagGreenland', {name: 'Flag Greenland', icon: flagGreenland});
openFlagsTable.set('flagGreenlandColor', {name: 'Flag Greenland Color', icon: flagGreenlandColor});
openFlagsTable.set('flagGrenada', {name: 'Flag Grenada', icon: flagGrenada});
openFlagsTable.set('flagGrenadaColor', {name: 'Flag Grenada Color', icon: flagGrenadaColor});
openFlagsTable.set('flagGuadeloupe', {name: 'Flag Guadeloupe', icon: flagGuadeloupe});
openFlagsTable.set('flagGuadeloupeColor', {name: 'Flag Guadeloupe', icon: flagGuadeloupeColor});
openFlagsTable.set('flagGuam', {name: 'Flag Guam', icon: flagGuam});
openFlagsTable.set('flagGuamColor', {name: 'Flag Guam Color', icon: flagGuamColor});
openFlagsTable.set('flagGuatemala', {name: 'Flag Guatemala', icon: flagGuatemala});
openFlagsTable.set('flagGuatemalaColor', {name: 'Flag Guatemala Color', icon: flagGuatemalaColor});
openFlagsTable.set('flagGuernsey', {name: 'Flag Guernsey', icon: flagGuernsey});
openFlagsTable.set('flagGuernseyColor', {name: 'Flag Guernsey Color', icon: flagGuernseyColor});
openFlagsTable.set('flagGuinea', {name: 'Flag Guinea', icon: flagGuinea});
openFlagsTable.set('flagGuineaColor', {name: 'Flag Guinea Color', icon: flagGuineaColor});
openFlagsTable.set('flagGuineaBissau', {name: 'Flag Guinea Bissau', icon: flagGuineaBissau});
openFlagsTable.set('flagGuineaBissauColor', {name: 'Flag Guinea Bissau Color', icon: flagGuineaBissauColor});
openFlagsTable.set('flagGuyana', {name: 'Flag Guyana', icon: flagGuyana});
openFlagsTable.set('flagGuyanaColor', {name: 'Flag Guyana Color', icon: flagGuyanaColor});
openFlagsTable.set('flagHaiti', {name: 'Flag Haiti', icon: flagHaiti});
openFlagsTable.set('flagHaitiColor', {name: 'Flag Haiti Color', icon: flagHaitiColor});
openFlagsTable.set('flagHeardAndMcDonaldIslands', {
    name: 'Flag Heard And McDonald Islands',
    icon: flagHeardAndMcDonaldIslands,
});
openFlagsTable.set('flagHeardAndMcDonaldIslandsColor', {
    name: 'Flag Heard And McDonald Islands Color',
    icon: flagHeardAndMcDonaldIslandsColor,
});
openFlagsTable.set('flagHonduras', {name: 'Flag Honduras', icon: flagHonduras});
openFlagsTable.set('flagHondurasColor', {name: 'Flag Honduras Color', icon: flagHondurasColor});
openFlagsTable.set('flagHongkongSARChina', {name: 'Flag Hongkong SAR China', icon: flagHongKongSARChina});
openFlagsTable.set('flagHongkongSARChinaColor', {
    name: 'Flag Hongkong SAR China Color',
    icon: flagHongKongSARChinaColor,
});
openFlagsTable.set('flagHungary', {name: 'Flag Hungary', icon: flagHungary});
openFlagsTable.set('flagHungaryColor', {name: 'Flag Hungary Color', icon: flagHungaryColor});
openFlagsTable.set('flagIceland', {name: 'Flag Iceland', icon: flagIceland});
openFlagsTable.set('flagIcelandColor', {name: 'Flag Iceland Color', icon: flagIcelandColor});
openFlagsTable.set('flagIndia', {name: 'Flag India', icon: flagIndia});
openFlagsTable.set('flagIndiaColor', {name: 'Flag India Color', icon: flagIndiaColor});
openFlagsTable.set('flagIndonesia', {name: 'Flag Indonesia', icon: flagIndonesia});
openFlagsTable.set('flagIndonesiaColor', {name: 'Flag Indonesia Color', icon: flagIndonesiaColor});
openFlagsTable.set('flagIran', {name: 'Flag Iran', icon: flagIran});
openFlagsTable.set('flagIranColor', {name: 'Flag Iran Color', icon: flagIranColor});
openFlagsTable.set('flagIraq', {name: 'Flag Iraq', icon: flagIraq});
openFlagsTable.set('flagIraqColor', {name: 'Flag Iraq Color', icon: flagIraqColor});
openFlagsTable.set('flagIreland', {name: 'Flag Ireland', icon: flagIreland});
openFlagsTable.set('flagIrelandColor', {name: 'Flag Ireland Color', icon: flagIrelandColor});
openFlagsTable.set('flagIsleOfMan', {name: 'Flag Isle Of Man', icon: flagIsleOfMan});
openFlagsTable.set('flagIsleOfManColor', {name: 'Flag Isle Of Man Color', icon: flagIsleOfManColor});
openFlagsTable.set('flagIsrael', {name: 'Flag Israel', icon: flagIsrael});
openFlagsTable.set('flagIsraelColor', {name: 'Flag Israel Color', icon: flagIsraelColor});
openFlagsTable.set('flagItaly', {name: 'Flag Italy', icon: flagItaly});
openFlagsTable.set('flagItalyColor', {name: 'Flag Italy Color', icon: flagItalyColor});
openFlagsTable.set('flagJamaica', {name: 'Flag Jamaica', icon: flagJamaica});
openFlagsTable.set('flagJamaicaColor', {name: 'Flag Jamaica Color', icon: flagJamaicaColor});
openFlagsTable.set('flagJapan', {name: 'Flag Japan', icon: flagJapan});
openFlagsTable.set('flagJapanColor', {name: 'Flag Japan Color', icon: flagJapanColor});
openFlagsTable.set('flagJersey', {name: 'Flag Jersey', icon: flagJersey});
openFlagsTable.set('flagJerseyColor', {name: 'Flag Jersey Color', icon: flagJerseyColor});
openFlagsTable.set('flagJordan', {name: 'Flag Jordan', icon: flagJordan});
openFlagsTable.set('flagJordanColor', {name: 'Flag Jordan Color', icon: flagJordanColor});
openFlagsTable.set('flagKazakhstan', {name: 'Flag Kazakhstan', icon: flagKazakhstan});
openFlagsTable.set('flagKazakhstanColor', {name: 'Flag Kazakhstan Color', icon: flagKazakhstanColor});
openFlagsTable.set('flagKenya', {name: 'Flag Kenya', icon: flagKenya});
openFlagsTable.set('flagKenyaColor', {name: 'Flag Kenya Color', icon: flagKenyaColor});
openFlagsTable.set('flagKiribati', {name: 'Flag Kiribati', icon: flagKiribati});
openFlagsTable.set('flagKiribatiColor', {name: 'Flag Kiribati Color', icon: flagKiribatiColor});
openFlagsTable.set('flagKosovo', {name: 'Flag Kosovo', icon: flagKosovo});
openFlagsTable.set('flagKosovoColor', {name: 'Flag Kosovo Color', icon: flagKosovoColor});
openFlagsTable.set('flagKuwait', {name: 'Flag Kuwait', icon: flagKuwait});
openFlagsTable.set('flagKuwaitColor', {name: 'Flag Kuwait Color', icon: flagKuwaitColor});
openFlagsTable.set('flagKyrgyzstan', {name: 'Flag Kyrgyzstan', icon: flagKyrgyzstan});
openFlagsTable.set('flagKyrgyzstanColor', {name: 'Flag Kyrgyzstan Color', icon: flagKyrgyzstanColor});
openFlagsTable.set('flagLaos', {name: 'Flag Laos', icon: flagLaos});
openFlagsTable.set('flagLaosColor', {name: 'Flag Laos Color', icon: flagLaosColor});
openFlagsTable.set('flagLatvia', {name: 'Flag Latvia', icon: flagLatvia});
openFlagsTable.set('flagLatviaColor', {name: 'Flag Latvia Color', icon: flagLatviaColor});
openFlagsTable.set('flagLebanon', {name: 'Flag Lebanon', icon: flagLebanon});
openFlagsTable.set('flagLebanonColor', {name: 'Flag Lebanon Color', icon: flagLebanonColor});
openFlagsTable.set('flagLesotho', {name: 'Flag Lesotho', icon: flagLesotho});
openFlagsTable.set('flagLesothoColor', {name: 'Flag Lesotho Color', icon: flagLesothoColor});
openFlagsTable.set('flagLiberia', {name: 'Flag Liberia', icon: flagLiberia});
openFlagsTable.set('flagLiberiaColor', {name: 'Flag Libera Color', icon: flagLiberiaColor});
openFlagsTable.set('flagLibya', {name: 'Flag Libya', icon: flagLibya});
openFlagsTable.set('flagLibyaColor', {name: 'Flag Libya Color', icon: flagLibyaColor});
openFlagsTable.set('flagLiechtenstein', {name: 'Flag Liechtenstein', icon: flagLiechtenstein});
openFlagsTable.set('flagLiechtensteinColor', {name: 'Flag Liechtenstein Color', icon: flagLiechtensteinColor});
openFlagsTable.set('flagLithuania', {name: 'Flag Lithuania', icon: flagLithuania});
openFlagsTable.set('flagLithuaniaColor', {name: 'Flag Lithuania Color', icon: flagLithuaniaColor});
openFlagsTable.set('flagLuxembourg', {name: 'Flag Luxembourg', icon: flagLuxembourg});
openFlagsTable.set('flagLuxembourgColor', {name: 'Flag Luxembourg Color', icon: flagLuxembourgColor});
openFlagsTable.set('flagMacaoSARChina', {name: 'Flag Macao SAR China', icon: flagMacaoSARChina});
openFlagsTable.set('flagMacaoSARChinaColor', {name: 'Flag Macao SAR China Color', icon: flagMacaoSARChinaColor});
openFlagsTable.set('flagMadagascar', {name: 'Flag Madagascar', icon: flagMadagascar});
openFlagsTable.set('flagMadagascarColor', {name: 'Flag Madagascar Color', icon: flagMadagascarColor});
openFlagsTable.set('flagMalawi', {name: 'Flag Malawi', icon: flagMalawi});
openFlagsTable.set('flagMalawiColor', {name: 'Flag Malawi Color', icon: flagMalawiColor});
openFlagsTable.set('flagMalaysia', {name: 'Flag Malaysia', icon: flagMalaysia});
openFlagsTable.set('flagMalaysiaColor', {name: 'Flag Malaysia Color', icon: flagMalaysiaColor});
openFlagsTable.set('flagMaldives', {name: 'Flag Maldives', icon: flagMaldives});
openFlagsTable.set('flagMaldivesColor', {name: 'Flag Maldives Color', icon: flagMaldivesColor});
openFlagsTable.set('flagMali', {name: 'Flag Mali', icon: flagMali});
openFlagsTable.set('flagMaliColor', {name: 'Flag Mali Color', icon: flagMaliColor});
openFlagsTable.set('flagMalta', {name: 'Flag Malta', icon: flagMalta});
openFlagsTable.set('flagMaltaColor', {name: 'Flag Malta Color', icon: flagMaltaColor});
openFlagsTable.set('flagMarshallIslands', {name: 'Flag Marshall Islands', icon: flagMarshallIslands});
openFlagsTable.set('flagMarshallIslandsColor', {name: 'Flag Marshall Islands Color', icon: flagMarshallIslandsColor});
openFlagsTable.set('flagMartinique', {name: 'Flag Martinique', icon: flagMartinique});
openFlagsTable.set('flagMartiniqueColor', {name: 'Flag Martinique Color', icon: flagMartiniqueColor});
openFlagsTable.set('flagMauritania', {name: 'Flag Mauritania', icon: flagMauritania});
openFlagsTable.set('flagMauritaniaColor', {name: 'Flag Mauritania Color', icon: flagMauritaniaColor});
openFlagsTable.set('flagMauritius', {name: 'Flag Mauritius', icon: flagMauritius});
openFlagsTable.set('flagMauritiusColor', {name: 'Flag Mauritius Color', icon: flagMauritiusColor});
openFlagsTable.set('flagMayotte', {name: 'Flag Mayotte', icon: flagMayotte});
openFlagsTable.set('flagMayotteColor', {name: 'Flag Mayotte Color', icon: flagMayotteColor});
openFlagsTable.set('flagMexico', {name: 'Flag Mexico', icon: flagMexico});
openFlagsTable.set('flagMexicoColor', {name: 'Flag Mexico Color', icon: flagMexicoColor});
openFlagsTable.set('flagMicronesia', {name: 'Flag Micronesia', icon: flagMicronesia});
openFlagsTable.set('flagMicronesiaColor', {name: 'Flag Micronesia Color', icon: flagMicronesiaColor});
openFlagsTable.set('flagMoldova', {name: 'Flag Moldova', icon: flagMoldova});
openFlagsTable.set('flagMoldovaColor', {name: 'Flag Moldova Color', icon: flagMoldovaColor});
openFlagsTable.set('flagMonaco', {name: 'Flag Monaco', icon: flagMonaco});
openFlagsTable.set('flagMonacoColor', {name: 'Flag Monaco Color', icon: flagMonacoColor});
openFlagsTable.set('flagMongolia', {name: 'Flag Mongolia', icon: flagMongolia});
openFlagsTable.set('flagMongoliaColor', {name: 'Flag Mongolia Color', icon: flagMongoliaColor});
openFlagsTable.set('flagMontenegro', {name: 'Flag Montenegro', icon: flagMontenegro});
openFlagsTable.set('flagMontenegroColor', {name: 'Flag Montenegro Color', icon: flagMontenegroColor});
openFlagsTable.set('flagMontserrat', {name: 'Flag Montserrat', icon: flagMontserrat});
openFlagsTable.set('flagMontserratColor', {name: 'Flag Montserrat Color', icon: flagMontserratColor});
openFlagsTable.set('flagMorocco', {name: 'Flag Morocco', icon: flagMorocco});
openFlagsTable.set('flagMoroccoColor', {name: 'Flag Morocco Color', icon: flagMoroccoColor});
openFlagsTable.set('flagMozambique', {name: 'Flag Mozambique', icon: flagMozambique});
openFlagsTable.set('flagMozambiqueColor', {name: 'Flag Mozambique Color', icon: flagMozambiqueColor});
openFlagsTable.set('flagMyanmarBurma', {name: 'Flag Myanmar Burma', icon: flagMyanmarBurma});
openFlagsTable.set('flagMyanmarBurmaColor', {name: 'Flag Myanmar Burma Color', icon: flagMyanmarBurmaColor});
openFlagsTable.set('flagNamibia', {name: 'Flag Namibia', icon: flagNamibia});
openFlagsTable.set('flagNamibiaColor', {name: 'Flag Namibia Color', icon: flagNamibiaColor});
openFlagsTable.set('flagNauru', {name: 'Flag Nauru', icon: flagNauru});
openFlagsTable.set('flagNauruColor', {name: 'Flag Nauru Color', icon: flagNauruColor});
openFlagsTable.set('flagNepal', {name: 'Flag Nepal', icon: flagNepal});
openFlagsTable.set('flagNepalColor', {name: 'Flag Nepal Color', icon: flagNepalColor});
openFlagsTable.set('flagNetherlands', {name: 'Flag Netherlands', icon: flagNetherlands});
openFlagsTable.set('flagNetherlandsColor', {name: 'Flag Netherlands Color', icon: flagNetherlandsColor});
openFlagsTable.set('flagNewCaledonia', {name: 'Flag New Caledonia', icon: flagNewCaledonia});
openFlagsTable.set('flagNewCaledoniaColor', {name: 'Flag New Caledonia Color', icon: flagNewCaledoniaColor});
openFlagsTable.set('flagNewZealand', {name: 'Flag New Zealand', icon: flagNewZealand});
openFlagsTable.set('flagNewZealandColor', {name: 'Flag New Zealand Color', icon: flagNewZealandColor});
openFlagsTable.set('flagNicaragua', {name: 'Flag Nicaragua', icon: flagNicaragua});
openFlagsTable.set('flagNicaraguaColor', {name: 'Flag Nicaragua Color', icon: flagNicaraguaColor});
openFlagsTable.set('flagNiger', {name: 'Flag Niger', icon: flagNiger});
openFlagsTable.set('flagNigerColor', {name: 'Flag Niger Color', icon: flagNigerColor});
openFlagsTable.set('flagNigeria', {name: 'Flag Nigeria', icon: flagNigeria});
openFlagsTable.set('flagNigeriaColor', {name: 'Flag Nigeria Color', icon: flagNigeriaColor});
openFlagsTable.set('flagNiue', {name: 'Flag Niue', icon: flagNiue});
openFlagsTable.set('flagNiueColor', {name: 'Flag Niue Color', icon: flagNiueColor});
openFlagsTable.set('flagNorfolkIsland', {name: 'Flag Norfolk Island', icon: flagNorfolkIsland});
openFlagsTable.set('flagNorfolkIslandColor', {name: 'Flag Norfolk Island Color', icon: flagNorfolkIslandColor});
openFlagsTable.set('flagNorthernMarianaIslands', {
    name: 'Flag Northern Mariana Islands',
    icon: flagNorthernMarianaIslands,
});
openFlagsTable.set('flagNorthernMarianaIslandsColor', {
    name: 'Flag Northern Mariana Islands Color',
    icon: flagNorthernMarianaIslandsColor,
});
openFlagsTable.set('flagNorthKorea', {name: 'Flag North Korea', icon: flagNorthKorea});
openFlagsTable.set('flagNorthKoreaColor', {name: 'Flag North Korea Color', icon: flagNorthKoreaColor});
openFlagsTable.set('flagNorthMacedonia', {name: 'Flag North Macedonia', icon: flagNorthMacedonia});
openFlagsTable.set('flagNorthMacedoniaColor', {name: 'Flag North Macedonia', icon: flagNorthMacedoniaColor});
openFlagsTable.set('flagNorway', {name: 'Flag Norway', icon: flagNorway});
openFlagsTable.set('flagNorwayColor', {name: 'Flag Norway Color', icon: flagNorwayColor});
openFlagsTable.set('flagOman', {name: 'Flag Oman', icon: flagOman});
openFlagsTable.set('flagOmanColor', {name: 'Flag Oman Color', icon: flagOmanColor});
openFlagsTable.set('flagPakistan', {name: 'Flag Pakistan', icon: flagPakistan});
openFlagsTable.set('flagPakistanColor', {name: 'Flag Pakistan Color', icon: flagPakistanColor});
openFlagsTable.set('flagPalau', {name: 'Flag Palau', icon: flagPalau});
openFlagsTable.set('flagPalauColor', {name: 'Flag Palau Color', icon: flagPalauColor});
openFlagsTable.set('flagPalestinianTerritories', {
    name: 'Flag Palestinian Territories',
    icon: flagPalestinianTerritories,
});
openFlagsTable.set('flagPalestinianTerritoriesColor', {
    name: 'Flag Palestinian Territories Color',
    icon: flagPalestinianTerritoriesColor,
});
openFlagsTable.set('flagPanama', {name: 'Flag Panama', icon: flagPanama});
openFlagsTable.set('flagPanamaColor', {name: 'Flag Panama Color', icon: flagPanamaColor});
openFlagsTable.set('flagPapuaNewGuinea', {name: 'Flag Papua New Guinea', icon: flagPapuaNewGuinea});
openFlagsTable.set('flagPapuaNewGuineaColor', {name: 'Flag Papua New Guinea Color', icon: flagPapuaNewGuineaColor});
openFlagsTable.set('flagParaguay', {name: 'Flag Paraguay', icon: flagParaguay});
openFlagsTable.set('flagParaguayColor', {name: 'Flag Paraguay Color', icon: flagParaguayColor});
openFlagsTable.set('flagPeru', {name: 'Flag Peru', icon: flagPeru});
openFlagsTable.set('flagPeruColor', {name: 'Flag Peru Color', icon: flagPeruColor});
openFlagsTable.set('flagPhilippines', {name: 'Flag Philippines', icon: flagPhilippines});
openFlagsTable.set('flagPhilippinesColor', {name: 'Flag Philippines Color', icon: flagPhilippinesColor});
openFlagsTable.set('flagPitcairnIslands', {name: 'Flag Pitcairn Islands', icon: flagPitcairnIslands});
openFlagsTable.set('flagPitcairnIslandsColor', {name: 'Flag Pitcairn Islands Color', icon: flagPitcairnIslandsColor});
openFlagsTable.set('flagPoland', {name: 'Flag Poland', icon: flagPoland});
openFlagsTable.set('flagPolandColor', {name: 'Flag Poland Color', icon: flagPolandColor});
openFlagsTable.set('flagPortugal', {name: 'Flag Portugal', icon: flagPortugal});
openFlagsTable.set('flagPortugalColor', {name: 'Flag Portugal Color', icon: flagPortugalColor});
openFlagsTable.set('flagPuertoRico', {name: 'Flag Puerto Rico', icon: flagPuertoRico});
openFlagsTable.set('flagPuertoRicoColor', {name: 'Flag Puerto Rico Color', icon: flagPuertoRicoColor});
openFlagsTable.set('flagQatar', {name: 'Flag Qatar', icon: flagQatar});
openFlagsTable.set('flagQatarColor', {name: 'Flag Qatar Color', icon: flagQatarColor});
openFlagsTable.set('flagRomania', {name: 'Flag Romania', icon: flagRomania});
openFlagsTable.set('flagRomaniaColor', {name: 'Flag Romania Color', icon: flagRomaniaColor});
openFlagsTable.set('flagRussia', {name: 'Flag Russia', icon: flagRussia});
openFlagsTable.set('flagRussiaColor', {name: 'Flag Russia Color', icon: flagRussiaColor});
openFlagsTable.set('flagRwanda', {name: 'Flag Rwanda', icon: flagRwanda});
openFlagsTable.set('flagRwandaColor', {name: 'Flag Rwanda Color', icon: flagRwandaColor});
openFlagsTable.set('flagSamoa', {name: 'Flag Samoa', icon: flagSamoa});
openFlagsTable.set('flagSamoaColor', {name: 'Flag Samoa Color', icon: flagSamoaColor});
openFlagsTable.set('flagSanMarino', {name: 'Flag San Marino', icon: flagSanMarino});
openFlagsTable.set('flagSanMarinoColor', {name: 'Flag San Marino Color', icon: flagSanMarinoColor});
openFlagsTable.set('flagSaudiArabia', {name: 'Flag Saudi Arabia', icon: flagSaudiArabia});
openFlagsTable.set('flagSaudiArabiaColor', {name: 'Flag Saudi Arabia Color', icon: flagSaudiArabiaColor});
openFlagsTable.set('flagSenegal', {name: 'Flag Senegal', icon: flagSenegal});
openFlagsTable.set('flagSenegalColor', {name: 'Flag Senegal Color', icon: flagSenegalColor});
openFlagsTable.set('flagSerbia', {name: 'Flag Serbia', icon: flagSerbia});
openFlagsTable.set('flagSerbiaColor', {name: 'Flag Serbia Color', icon: flagSerbiaColor});
openFlagsTable.set('flagSeychelles', {name: 'Flag Seychelles', icon: flagSeychelles});
openFlagsTable.set('flagSeychellesColor', {name: 'Flag Seychelles Color', icon: flagSeychellesColor});
openFlagsTable.set('flagSierraLeone', {name: 'Flag Sierra Leone', icon: flagSierraLeone});
openFlagsTable.set('flagSierraLeoneColor', {name: 'Flage Sierra Leone Color', icon: flagSierraLeoneColor});
openFlagsTable.set('flagSingapore', {name: 'Flag Singapore', icon: flagSingapore});
openFlagsTable.set('flagSingaporeColor', {name: 'Flag Singapore Color', icon: flagSingaporeColor});
openFlagsTable.set('flagSintMaarten', {name: 'Flag Sint Maarten', icon: flagSintMaarten});
openFlagsTable.set('flagSintMaartenColor', {name: 'Flag Sint Maarten Color', icon: flagSintMaartenColor});
openFlagsTable.set('flagSlovakia', {name: 'Flag Slovakia', icon: flagSlovakia});
openFlagsTable.set('flagSlovakiaColor', {name: 'Flag Slovakia Color', icon: flagSlovakiaColor});
openFlagsTable.set('flagSlovenia', {name: 'Flag Slovenia', icon: flagSlovenia});
openFlagsTable.set('flagSloveniaColor', {name: 'Flage Slovenia Color', icon: flagSloveniaColor});
openFlagsTable.set('flagSolomonIslands', {name: 'Flag Solomon Islands', icon: flagSolomonIslands});
openFlagsTable.set('flagSolomonIslandsColor', {name: 'Flag Solomon Islands Color', icon: flagSolomonIslandsColor});
openFlagsTable.set('flagSomalia', {name: 'Flag Somalia', icon: flagSomalia});
openFlagsTable.set('flagSomaliaColor', {name: 'Flag Somalia Color', icon: flagSomaliaColor});
openFlagsTable.set('flagSouthAfrica', {name: 'Flag South Africa', icon: flagSouthAfrica});
openFlagsTable.set('flagSouthAfricaColor', {name: 'Flag South Africa Color', icon: flagSouthAfricaColor});
openFlagsTable.set('flagSouthGeorgiaAndSouthSandwichIslands', {
    name: 'Flag South Georgia And South Sandwich Islands',
    icon: flagSouthGeorgiaAndSouthSandwichIslands,
});
openFlagsTable.set('flagSouthGeorgiaAndSouthSandwichIslandsColor', {
    name: 'Flag South Georgia And South Sandwich Islands Color',
    icon: flagSouthGeorgiaAndSouthSandwichIslandsColor,
});
openFlagsTable.set('flagSouthKorea', {name: 'Flag South Korea', icon: flagSouthKorea});
openFlagsTable.set('flagSouthKoreaColor', {name: 'Flag South Korea Color', icon: flagSouthKoreaColor});
openFlagsTable.set('flagSouthSudan', {name: 'Flag South Sudan', icon: flagSouthSudan});
openFlagsTable.set('flagSouthSudanColor', {name: 'Flag South Sudan Color', icon: flagSouthSudanColor});
openFlagsTable.set('flagSpain', {name: 'Flag Spain', icon: flagSpain});
openFlagsTable.set('flagSpainColor', {name: 'Flag Spain Color', icon: flagSpainColor});
openFlagsTable.set('flagSriLanka', {name: 'Flag Sri Lanka', icon: flagSriLanka});
openFlagsTable.set('flagSriLankaColor', {name: 'Flag Sri Lanka', icon: flagSriLankaColor});
openFlagsTable.set('flagStHelena', {name: 'Flag St Helena', icon: flagStHelena});
openFlagsTable.set('flagStHelenaColor', {name: 'Flag St Helena Color', icon: flagStHelenaColor});
openFlagsTable.set('flagStKittsAndNevis', {name: 'Flag St Kitts And Nevis', icon: flagStKittsAndNevis});
openFlagsTable.set('flagStKittsAndNevisColor', {name: 'Flag St Kitts And Nevis Color', icon: flagStKittsAndNevisColor});
openFlagsTable.set('flagStLucia', {name: 'Flag St Lucia', icon: flagStLucia});
openFlagsTable.set('flagStLuciaColor', {name: 'Flag St Lucia Color', icon: flagStLuciaColor});
openFlagsTable.set('flagStMartin', {name: 'Flag St Martin', icon: flagStMartin});
openFlagsTable.set('flagStMartinColor', {name: 'Flag St Martin Color', icon: flagStMartinColor});
openFlagsTable.set('flagStPierreAndMiquelon', {name: 'Flag St Pierre And Miquelon', icon: flagStPierreAndMiquelon});
openFlagsTable.set('flagStPierreAndMiquelonColor', {
    name: 'Flag St Pierre And Miquelon Color',
    icon: flagStPierreAndMiquelonColor,
});
openFlagsTable.set('flagStVincentAndGrenadines', {
    name: 'Flag St Vincent And Grenadines',
    icon: flagStVincentAndGrenadines,
});
openFlagsTable.set('flagStVincentAndGrenadinesColor', {
    name: 'Flag St Vincent And Grenadines Color',
    icon: flagStVincentAndGrenadinesColor,
});
openFlagsTable.set('flagSudan', {name: 'Flag Sudan', icon: flagSudan});
openFlagsTable.set('flagSudanColor', {name: 'Flag Sudan Color', icon: flagSudanColor});
openFlagsTable.set('flagSuriname', {name: 'Flag Suriname', icon: flagSuriname});
openFlagsTable.set('flagSurinameColor', {name: 'Flag Suriname Color', icon: flagSurinameColor});
openFlagsTable.set('flagSvalbardAndJanMayen', {name: 'Flag Svalbard And Jan Mayen', icon: flagSvalbardAndJanMayen});
openFlagsTable.set('flagSvalbardAndJanMayenColor', {
    name: 'Flag Svalbard And Jan Mayen Color',
    icon: flagSvalbardAndJanMayenColor,
});
openFlagsTable.set('flagSweden', {name: 'Flag Sweden', icon: flagSweden});
openFlagsTable.set('flagSwedenColor', {name: 'Flag Sweden Color', icon: flagSwedenColor});
openFlagsTable.set('flagSwitzerland', {name: 'Flag Switzerland', icon: flagSwitzerland});
openFlagsTable.set('flagSwitzerlandColor', {name: 'Flag Switzerland Color', icon: flagSwitzerlandColor});
openFlagsTable.set('flagSyria', {name: 'Flag Syria', icon: flagSyria});
openFlagsTable.set('flagSyriaColor', {name: 'Flag Syria Color', icon: flagSyriaColor});
openFlagsTable.set('flagTaiwan', {name: 'Flag Taiwan', icon: flagTaiwan});
openFlagsTable.set('flagTaiwanColor', {name: 'Flag Taiwan Color', icon: flagTaiwanColor});
openFlagsTable.set('flagTajikistan', {name: 'Flag Tajikistan', icon: flagTajikistan});
openFlagsTable.set('flagTajikistanColor', {name: 'Flag Tajikistan Color', icon: flagTajikistanColor});
openFlagsTable.set('flagTanzania', {name: 'Flag Tanzania', icon: flagTanzania});
openFlagsTable.set('flagTanzaniaColor', {name: 'Flag Tanzania Colr', icon: flagTanzaniaColor});
openFlagsTable.set('flagThailand', {name: 'Flag Thailand', icon: flagThailand});
openFlagsTable.set('flagThailandColor', {name: 'Flag Thailand Color', icon: flagThailandColor});
openFlagsTable.set('flagTimorLeste', {name: 'Flag Timor Leste', icon: flagTimorLeste});
openFlagsTable.set('flagTimorLesteColor', {name: 'Flag Timor Leste Color', icon: flagTimorLesteColor});
openFlagsTable.set('flagTogo', {name: 'Flag Togo', icon: flagTogo});
openFlagsTable.set('flagTogoColor', {name: 'Flag Togo Color', icon: flagTogoColor});
openFlagsTable.set('flagTokelau', {name: 'Flag Tokelau', icon: flagTokelau});
openFlagsTable.set('flagTokelauColor', {name: 'Flag Tokelau Color', icon: flagTokelauColor});
openFlagsTable.set('flagTonga', {name: 'Flag Tonga', icon: flagTonga});
openFlagsTable.set('flagTongaColor', {name: 'Flag Tonga Color', icon: flagTongaColor});
openFlagsTable.set('flagTrinidadAndTobago', {name: 'Flag Trinidad And Tobago', icon: flagTrinidadAndTobago});
openFlagsTable.set('flagTrinidadAndTobagoColor', {
    name: 'Flag Trinidad And Tobago Color',
    icon: flagTrinidadAndTobagoColor,
});
openFlagsTable.set('flagTristanDaCunha', {name: 'Flag Tristan Da Cunha', icon: flagTristanDaCunha});
openFlagsTable.set('flagTristanDaCunhaColor', {name: 'Flag Tristan Da Cunha Color', icon: flagTristanDaCunhaColor});
openFlagsTable.set('flagTunisia', {name: 'Flag Tunisia', icon: flagTunisia});
openFlagsTable.set('flagTunisiaColor', {name: 'Flag Tunisia Color', icon: flagTunisiaColor});
openFlagsTable.set('flagTurkey', {name: 'Flag Turkey', icon: flagTurkey});
openFlagsTable.set('flagTurkeyColor', {name: 'Flag Turkey Color', icon: flagTurkeyColor});
openFlagsTable.set('flagTurkmenistan', {name: 'Flag Turkmenistan', icon: flagTurkmenistan});
openFlagsTable.set('flagTurkmenistanColor', {name: 'Flag Turkmenistan Color', icon: flagTurkmenistanColor});
openFlagsTable.set('flagTurksAndCaicosIslands', {
    name: 'Flag Turks And Caicos Islands',
    icon: flagTurksAndCaicosIslands,
});
openFlagsTable.set('flagTurksAndCaicosIslandsColor', {
    name: 'Flag Turks And Caicos Islands Color',
    icon: flagTurksAndCaicosIslandsColor,
});
openFlagsTable.set('flagTuvalu', {name: 'Flag Tuvalu', icon: flagTuvalu});
openFlagsTable.set('flagTuvaluColor', {name: 'Flag Tuvalu Color', icon: flagTuvaluColor});
openFlagsTable.set('flagUSOutlyingIslands', {name: 'Flag US Outlying Islands', icon: flagUSOutlyingIslands});
openFlagsTable.set('flagUSOutlyingIslandsColor', {
    name: 'Flag US Outlying Islands Color',
    icon: flagUSOutlyingIslandsColor,
});
openFlagsTable.set('flagUSVirginIslands', {name: 'Flag US Virgin Islands', icon: flagUSVirginIslands});
openFlagsTable.set('flagUSVirginIslandsColor', {name: 'Flag US Virgin Islands Color', icon: flagUSVirginIslandsColor});
openFlagsTable.set('flagUganda', {name: 'Flag Uganda', icon: flagUganda});
openFlagsTable.set('flagUgandaColor', {name: 'Flag Uganda Color', icon: flagUgandaColor});
openFlagsTable.set('flagUkraine', {name: 'Flag Ukraine', icon: flagUkraine});
openFlagsTable.set('flagUkraineColor', {name: 'Flag Ukraine Color', icon: flagUkraineColor});
openFlagsTable.set('flagUnitedArabEmirates', {name: 'Flag United Arab Emirates', icon: flagUnitedArabEmirates});
openFlagsTable.set('flagUnitedArabEmiratesColor', {
    name: 'Flag United Arab Emirates Color',
    icon: flagUnitedArabEmiratesColor,
});
openFlagsTable.set('flagUnitedKingdom', {name: 'Flag United Kingdom', icon: flagUnitedKingdom});
openFlagsTable.set('flagUnitedKingdomColor', {name: 'Flag United Kingdom Color', icon: flagUnitedKingdomColor});
openFlagsTable.set('flagUnitedNations', {name: 'Flag United Nations', icon: flagUnitedNations});
openFlagsTable.set('flagUnitedNationsColor', {name: 'Flag United Nations Color', icon: flagUnitedNationsColor});
openFlagsTable.set('flagUnitedStates', {name: 'Flag United States', icon: flagUnitedStates});
openFlagsTable.set('flagUnitedStatesColor', {name: 'Flag United States Color', icon: flagUnitedStatesColor});
openFlagsTable.set('flagUruguay', {name: 'Flag Uruguay', icon: flagUruguay});
openFlagsTable.set('flagUruguayColor', {name: 'Flag Uruguay Color', icon: flagUruguayColor});
openFlagsTable.set('flagUzbekistan', {name: 'Flag Uzbekistan', icon: flagUzbekistan});
openFlagsTable.set('flagUzbekistanColor', {name: 'Flag Uzbekistan Color', icon: flagUzbekistanColor});
openFlagsTable.set('flagVanuatu', {name: 'Flag Vanuatu', icon: flagVanuatu});
openFlagsTable.set('flagVanuatuColor', {name: 'Flag Vanuatu Color', icon: flagVanuatuColor});
openFlagsTable.set('flagVaticanCity', {name: 'Flag Vatican City', icon: flagVaticanCity});
openFlagsTable.set('flagVaticanCityColor', {name: 'Flag Vatican City Color', icon: flagVaticanCityColor});
openFlagsTable.set('flagVenezuela', {name: 'Flag Venezuela', icon: flagVenezuela});
openFlagsTable.set('flagVenezuelaColor', {name: 'Flag Venezuela Color', icon: flagVenezuelaColor});
openFlagsTable.set('flagVietnam', {name: 'Flag Vietnam', icon: flagVietnam});
openFlagsTable.set('flagVietnamColor', {name: 'Flag Vietnam Color', icon: flagVietnamColor});
openFlagsTable.set('flagWallisAndFutuna', {name: 'Flag Wallis And Futuna', icon: flagWallisAndFutuna});
openFlagsTable.set('flagWallisAndFutunaColor', {name: 'Flag Wallis And Futuna Color', icon: flagWallisAndFutunaColor});
openFlagsTable.set('flagWesternSahara', {name: 'Flag Western Sahara', icon: flagWesternSahara});
openFlagsTable.set('flagWesternSaharaColor', {name: 'Flag Western Sahara Color', icon: flagWesternSaharaColor});
openFlagsTable.set('flagYemen', {name: 'Flag Yemen', icon: flagYemen});
openFlagsTable.set('flagYemenColor', {name: 'Flag Yemen Color', icon: flagYemenColor});
openFlagsTable.set('flagZambia', {name: 'Flag Zambia', icon: flagZambia});
openFlagsTable.set('flagZambiaColor', {name: 'Flag Zambia Color', icon: flagZambiaColor});
openFlagsTable.set('flagZimbabwe', {name: 'Flag Zimbabwe', icon: flagZimbabwe});
openFlagsTable.set('flagZimbabweColor', {name: 'Flag Zimbabwe Color', icon: flagZimbabweColor});
openFlagsTable.set('blackFlag', {name: 'Black Flag', icon: blackFlag});
openFlagsTable.set('blackFlagColor', {name: 'Black Flag Color', icon: blackFlagColor});
openFlagsTable.set('chequeredFlag', {name: 'Chequered Flag', icon: chequeredFlag});
openFlagsTable.set('chequeredFlagColor', {name: 'Chequered Flag Color', icon: chequeredFlagColor});
openFlagsTable.set('crossedFlags', {name: 'Crossed Flags', icon: crossedFlags});
openFlagsTable.set('crossedFlagsColor', {name: 'Crossed Flags Color', icon: crossedFlagsColor});
openFlagsTable.set('pirateFlag', {name: 'Pirate Flag', icon: pirateFlag});
openFlagsTable.set('pirateFlagColor', {name: 'Pirate Flag Color', icon: pirateFlagColor});
openFlagsTable.set('rainbowFlag', {name: 'Rainbow Flag', icon: rainbowFlag});
openFlagsTable.set('rainbowFlagColor', {name: 'Rainbow Flag Color', icon: rainbowFlagColor});
openFlagsTable.set('transgenderFlag', {name: 'Transgender Flag', icon: transgenderFlag});
openFlagsTable.set('transgenderFlagColor', {name: 'Transgender Flag', icon: transgenderFlagColor});
openFlagsTable.set('triangularFlag', {name: 'Triagular Flag', icon: triangularFlag});
openFlagsTable.set('triangularFlagColor', {name: 'Triangular Flag', icon: triangularFlagColor});
openFlagsTable.set('whiteFlag', {name: 'White Flag', icon: whiteFlag});
openFlagsTable.set('whiteFlagColor', {name: 'White Flag Color', icon: whiteFlagColor});
openFlagsTable.set('flagEngland', {name: 'Flag England', icon: flagEngland});
openFlagsTable.set('flagEnglandColor', {name: 'Flag England Color', icon: flagEnglandColor});
openFlagsTable.set('flagScotland', {name: 'Flag Scotland', icon: flagScotland});
openFlagsTable.set('flagScotlandColor', {name: 'Flag Scotland Color', icon: flagScotlandColor});
openFlagsTable.set('flagWales', {name: 'Flag Wales', icon: flagWales});
openFlagsTable.set('flagWalesColor', {name: 'Flag Wales Color', icon: flagWalesColor});

export const OA_ICON_SIZE = openFlagsTable.size;
