import bellhopBell from './icons/travel-places/hotel/bellhop-bell.svg';
import bellhopBellColor from './icons/travel-places/hotel/bellhop-bell_color.svg';
import luggage from './icons/travel-places/hotel/luggage.svg';
import luggageColor from './icons/travel-places/hotel/luggage_color.svg';
import bank from './icons/travel-places/place-building/bank.svg';
import bankColor from './icons/travel-places/place-building/bank_color.svg';
import brick from './icons/travel-places/place-building/brick.svg';
import brickColor from './icons/travel-places/place-building/brick_color.svg';
import buildingConstruction from './icons/travel-places/place-building/building-construction.svg';
import buildingConstructionColor from './icons/travel-places/place-building/building-construction_color.svg';
import castle from './icons/travel-places/place-building/castle.svg';
import castleColor from './icons/travel-places/place-building/castle_color.svg';
import classicalBuilding from './icons/travel-places/place-building/classical-building.svg';
import classicalBuildingColor from './icons/travel-places/place-building/classical-building_color.svg';
import convenienceStore from './icons/travel-places/place-building/convenience-store.svg';
import convenienceStoreColor from './icons/travel-places/place-building/convenience-store_color.svg';
import departmentStore from './icons/travel-places/place-building/department-store.svg';
import departmentStoreColor from './icons/travel-places/place-building/department-store_color.svg';
import derelictHouse from './icons/travel-places/place-building/derelict-house.svg';
import derelictHouseColor from './icons/travel-places/place-building/derelict-house_color.svg';
import factory from './icons/travel-places/place-building/factory.svg';
import factoryColor from './icons/travel-places/place-building/factory_color.svg';
import hospital from './icons/travel-places/place-building/hospital.svg';
import hospitalColor from './icons/travel-places/place-building/hospital_color.svg';
import hotel from './icons/travel-places/place-building/hotel.svg';
import hotelColor from './icons/travel-places/place-building/hotel_color.svg';
import house from './icons/travel-places/place-building/house.svg';
import houseColor from './icons/travel-places/place-building/house_color.svg';
import houses from './icons/travel-places/place-building/houses.svg';
import housesColor from './icons/travel-places/place-building/houses_color.svg';
import houseWithGarden from './icons/travel-places/place-building/house-with-garden.svg';
import houseWithGardenColor from './icons/travel-places/place-building/house-with-garden_color.svg';
import hut from './icons/travel-places/place-building/hut.svg';
import hutColor from './icons/travel-places/place-building/hut_color.svg';
import japaneseCastle from './icons/travel-places/place-building/Japanese-castle.svg';
import japaneseCastleColor from './icons/travel-places/place-building/Japanese-castle_color.svg';
import japanesePostOffice from './icons/travel-places/place-building/Japanese-post-office.svg';
import japanesePostOfficeColor from './icons/travel-places/place-building/Japanese-post-office_color.svg';
import loveHotel from './icons/travel-places/place-building/love-hotel.svg';
import loveHotelColor from './icons/travel-places/place-building/love-hotel_color.svg';
import officeBuilding from './icons/travel-places/place-building/office-building.svg';
import officeBuildingColor from './icons/travel-places/place-building/office-building_color.svg';
import postOffice from './icons/travel-places/place-building/post-office.svg';
import postOfficeColor from './icons/travel-places/place-building/post-office_color.svg';
import rock from './icons/travel-places/place-building/rock.svg';
import rockColor from './icons/travel-places/place-building/rock_color.svg';
import school from './icons/travel-places/place-building/school.svg';
import schoolColor from './icons/travel-places/place-building/school_color.svg';
import stadium from './icons/travel-places/place-building/stadium.svg';
import stadiumColor from './icons/travel-places/place-building/stadium_color.svg';
import statueOfLiberty from './icons/travel-places/place-building/Statue-of-Liberty.svg';
import statueOfLibertyColor from './icons/travel-places/place-building/Statue-of-Liberty_color.svg';
import tokyoTower from './icons/travel-places/place-building/Tokyo-tower.svg';
import tokyoTowerColor from './icons/travel-places/place-building/Tokyo-tower_color.svg';
import wedding from './icons/travel-places/place-building/wedding.svg';
import weddingColor from './icons/travel-places/place-building/wedding_color.svg';
import wood from './icons/travel-places/place-building/wood.svg';
import woodColor from './icons/travel-places/place-building/wood_color.svg';
import beachWithUmbrella from './icons/travel-places/place-geographic/beach-with-umbrella.svg';
import beachWithUmbrellaColor from './icons/travel-places/place-geographic/beach-with-umbrella_color.svg';
import camping from './icons/travel-places/place-geographic/camping.svg';
import campingColor from './icons/travel-places/place-geographic/camping_color.svg';
import desert from './icons/travel-places/place-geographic/desert.svg';
import desertColor from './icons/travel-places/place-geographic/desert_color.svg';
import desertIsland from './icons/travel-places/place-geographic/desert-island.svg';
import desertIslandColor from './icons/travel-places/place-geographic/desert-island_color.svg';
import mountain from './icons/travel-places/place-geographic/mountain.svg';
import mountainColor from './icons/travel-places/place-geographic/mountain_color.svg';
import mountFuji from './icons/travel-places/place-geographic/mount-fuji.svg';
import mountFujiColor from './icons/travel-places/place-geographic/mount-fuji_color.svg';
import nationalPark from './icons/travel-places/place-geographic/national-park.svg';
import nationalParkColor from './icons/travel-places/place-geographic/national-park_color.svg';
import snowCappedMountain from './icons/travel-places/place-geographic/snow-capped-mountain.svg';
import snowCappedMountainColor from './icons/travel-places/place-geographic/snow-capped-mountain_color.svg';
import volcano from './icons/travel-places/place-geographic/volcano.svg';
import volcanoColor from './icons/travel-places/place-geographic/volcano_color.svg';
import compass from './icons/travel-places/place-map/compass.svg';
import compassColor from './icons/travel-places/place-map/compass_color.svg';
import globeShowingAmericas from './icons/travel-places/place-map/globe-showing-Americas.svg';
import globeShowingAmericasColor from './icons/travel-places/place-map/globe-showing-Americas_color.svg';
import globeShowingAsiaAustralia from './icons/travel-places/place-map/globe-showing-Asia-Australia.svg';
import globeShowingAsiaAustraliaColor from './icons/travel-places/place-map/globe-showing-Asia-Australia_color.svg';
import globeShowingEuropeAfrica from './icons/travel-places/place-map/globe-showing-Europe-Africa.svg';
import globeShowingEuropeAfricaColor from './icons/travel-places/place-map/globe-showing-Europe-Africa_color.svg';
import globeWithMeridians from './icons/travel-places/place-map/globe-with-meridians.svg';
import globeWithMeridiansColor from './icons/travel-places/place-map/globe-with-meridians_color.svg';
import mapOfJapan from './icons/travel-places/place-map/map-of-Japan.svg';
import mapOfJapanColor from './icons/travel-places/place-map/map-of-Japan_color.svg';
import worldMap from './icons/travel-places/place-map/world-map.svg';
import worldMapColor from './icons/travel-places/place-map/world-map_color.svg';
import barberPole from './icons/travel-places/place-other/barber-pole.svg';
import barberPoleColor from './icons/travel-places/place-other/barber-pole_color.svg';
import bridgeAtNight from './icons/travel-places/place-other/bridge-at-night.svg';
import bridgeAtNightColor from './icons/travel-places/place-other/bridge-at-night_color.svg';
import carouselHorse from './icons/travel-places/place-other/carousel-horse.svg';
import carouselHorseColor from './icons/travel-places/place-other/carousel-horse_color.svg';
import circusTent from './icons/travel-places/place-other/circus-tent.svg';
import circusTentColor from './icons/travel-places/place-other/circus-tent_color.svg';
import cityscape from './icons/travel-places/place-other/cityscape.svg';
import cityscapeColor from './icons/travel-places/place-other/cityscape_color.svg';
import cityscapeAtDusk from './icons/travel-places/place-other/cityscape-at-dusk.svg';
import cityscapeAtDuskColor from './icons/travel-places/place-other/cityscape-at-dusk_color.svg';
import ferrisWheel from './icons/travel-places/place-other/ferris-wheel.svg';
import ferrisWheelColor from './icons/travel-places/place-other/ferris-wheel_color.svg';
import foggy from './icons/travel-places/place-other/foggy.svg';
import foggyColor from './icons/travel-places/place-other/foggy_color.svg';
import fountain from './icons/travel-places/place-other/fountain.svg';
import fountainColor from './icons/travel-places/place-other/fountain_color.svg';
import hotSprings from './icons/travel-places/place-other/hot-springs.svg';
import hotSpringsColor from './icons/travel-places/place-other/hot-springs_color.svg';
import nightWithStars from './icons/travel-places/place-other/night-with-stars.svg';
import nightWithStarsColor from './icons/travel-places/place-other/night-with-stars_color.svg';
import playgroundSlide from './icons/travel-places/place-other/playground-slide.svg';
import playgroundSlideColor from './icons/travel-places/place-other/playground-slide_color.svg';
import rollerCoaster from './icons/travel-places/place-other/roller-coaster.svg';
import rollerCoasterColor from './icons/travel-places/place-other/roller-coaster_color.svg';
import sunrise from './icons/travel-places/place-other/sunrise.svg';
import sunriseColor from './icons/travel-places/place-other/sunrise_color.svg';
import sunriseOverMountains from './icons/travel-places/place-other/sunrise-over-mountains.svg';
import sunriseOverMountainsColor from './icons/travel-places/place-other/sunrise-over-mountains_color.svg';
import sunset from './icons/travel-places/place-other/sunset.svg';
import sunsetColor from './icons/travel-places/place-other/sunset_color.svg';
import tent from './icons/travel-places/place-other/tent.svg';
import tentColor from './icons/travel-places/place-other/tent_color.svg';
import church from './icons/travel-places/place-religious/church.svg';
import churchColor from './icons/travel-places/place-religious/church_color.svg';
import hinduTemple from './icons/travel-places/place-religious/hindu-temple.svg';
import hinduTempleColor from './icons/travel-places/place-religious/hindu-temple_color.svg';
import kaaba from './icons/travel-places/place-religious/kaaba.svg';
import kaabaColor from './icons/travel-places/place-religious/kaaba_color.svg';
import mosque from './icons/travel-places/place-religious/mosque.svg';
import mosqueColor from './icons/travel-places/place-religious/mosque_color.svg';
import shintoShrine from './icons/travel-places/place-religious/shinto-shrine.svg';
import shintoShrineColor from './icons/travel-places/place-religious/shinto-shrine_color.svg';
import synagogue from './icons/travel-places/place-religious/synagogue.svg';
import synagogueColor from './icons/travel-places/place-religious/synagogue_color.svg';
import closedUmbrella from './icons/travel-places/sky-weather/closed-umbrella.svg';
import closedUmbrellaColor from './icons/travel-places/sky-weather/closed-umbrella_color.svg';
import cloud from './icons/travel-places/sky-weather/cloud.svg';
import cloudColor from './icons/travel-places/sky-weather/cloud_color.svg';
import cloudWithLightning from './icons/travel-places/sky-weather/cloud-with-lightning.svg';
import cloudWithLightningColor from './icons/travel-places/sky-weather/cloud-with-lightning_color.svg';
import cloudWithLightningAndRain from './icons/travel-places/sky-weather/cloud-with-lightning-and-rain.svg';
import cloudWithLightningAndRainColor from './icons/travel-places/sky-weather/cloud-with-lightning-and-rain_color.svg';
import cloudWithRain from './icons/travel-places/sky-weather/cloud-with-rain.svg';
import cloudWithRainColor from './icons/travel-places/sky-weather/cloud-with-rain_color.svg';
import cloudWithSnow from './icons/travel-places/sky-weather/cloud-with-snow.svg';
import cloudWithSnowColor from './icons/travel-places/sky-weather/cloud-with-snow_color.svg';
import comet from './icons/travel-places/sky-weather/comet.svg';
import cometColor from './icons/travel-places/sky-weather/comet_color.svg';
import crescentMoon from './icons/travel-places/sky-weather/crescent-moon.svg';
import crescentMoonColor from './icons/travel-places/sky-weather/crescent-moon_color.svg';
import cyclone from './icons/travel-places/sky-weather/cyclone.svg';
import cycloneColor from './icons/travel-places/sky-weather/cyclone_color.svg';
import droplet from './icons/travel-places/sky-weather/droplet.svg';
import dropletColor from './icons/travel-places/sky-weather/droplet_color.svg';
import fire from './icons/travel-places/sky-weather/fire.svg';
import fireColor from './icons/travel-places/sky-weather/fire_color.svg';
import firstQuarterMoon from './icons/travel-places/sky-weather/first-quarter-moon.svg';
import firstQuarterMoonColor from './icons/travel-places/sky-weather/first-quarter-moon_color.svg';
import firstQuarterMoonFace from './icons/travel-places/sky-weather/first-quarter-moon-face.svg';
import firstQuarterMoonFaceColor from './icons/travel-places/sky-weather/first-quarter-moon-face_color.svg';
import fog from './icons/travel-places/sky-weather/fog.svg';
import fogColor from './icons/travel-places/sky-weather/fog_color.svg';
import fullMoon from './icons/travel-places/sky-weather/full-moon.svg';
import fullMoonColor from './icons/travel-places/sky-weather/full-moon_color.svg';
import fullMoonFace from './icons/travel-places/sky-weather/full-moon-face.svg';
import fullMoonFaceColor from './icons/travel-places/sky-weather/full-moon-face_color.svg';
import glowingStar from './icons/travel-places/sky-weather/glowing-star.svg';
import glowingStarColor from './icons/travel-places/sky-weather/glowing-star_color.svg';
import highVoltage from './icons/travel-places/sky-weather/high-voltage.svg';
import highVoltageColor from './icons/travel-places/sky-weather/high-voltage_color.svg';
import lastQuarterMoon from './icons/travel-places/sky-weather/last-quarter-moon.svg';
import lastQuarterMoonColor from './icons/travel-places/sky-weather/last-quarter-moon_color.svg';
import lastQuarterMoonFace from './icons/travel-places/sky-weather/last-quarter-moon-face.svg';
import lastQuarterMoonFaceColor from './icons/travel-places/sky-weather/last-quarter-moon-face_color.svg';
import milkyWay from './icons/travel-places/sky-weather/milky-way.svg';
import milkyWayColor from './icons/travel-places/sky-weather/milky-way_color.svg';
import newMoon from './icons/travel-places/sky-weather/new-moon.svg';
import newMoonColor from './icons/travel-places/sky-weather/new-moon_color.svg';
import newMoonFace from './icons/travel-places/sky-weather/new-moon-face.svg';
import newMoonFaceColor from './icons/travel-places/sky-weather/new-moon-face_color.svg';
import rainbow from './icons/travel-places/sky-weather/rainbow.svg';
import rainbowColor from './icons/travel-places/sky-weather/rainbow_color.svg';
import ringedPlanet from './icons/travel-places/sky-weather/ringed-planet.svg';
import ringedPlanetColor from './icons/travel-places/sky-weather/ringed-planet_color.svg';
import shootingStar from './icons/travel-places/sky-weather/shooting-star.svg';
import shootingStarColor from './icons/travel-places/sky-weather/shooting-star_color.svg';
import snowflake from './icons/travel-places/sky-weather/snowflake.svg';
import snowflakeColor from './icons/travel-places/sky-weather/snowflake_color.svg';
import snowman from './icons/travel-places/sky-weather/snowman.svg';
import snowmanColor from './icons/travel-places/sky-weather/snowman_color.svg';
import snowmanWithoutSnow from './icons/travel-places/sky-weather/snowman-without-snow.svg';
import snowmanWithoutSnowColor from './icons/travel-places/sky-weather/snowman-without-snow_color.svg';
import star from './icons/travel-places/sky-weather/star.svg';
import starColor from './icons/travel-places/sky-weather/star_color.svg';
import sun from './icons/travel-places/sky-weather/sun.svg';
import sunColor from './icons/travel-places/sky-weather/sun_color.svg';
import sunBehindCloud from './icons/travel-places/sky-weather/sun-behind-cloud.svg';
import sunBehindCloudColor from './icons/travel-places/sky-weather/sun-behind-cloud_color.svg';
import sunBehindLargeCloud from './icons/travel-places/sky-weather/sun-behind-large-cloud.svg';
import sunBehindLargeCloudColor from './icons/travel-places/sky-weather/sun-behind-large-cloud_color.svg';
import sunBehindRainCloud from './icons/travel-places/sky-weather/sun-behind-rain-cloud.svg';
import sunBehindRainCloudColor from './icons/travel-places/sky-weather/sun-behind-rain-cloud_color.svg';
import sunBehindSmallCloud from './icons/travel-places/sky-weather/sun-behind-small-cloud.svg';
import sunBehindSmallCloudColor from './icons/travel-places/sky-weather/sun-behind-small-cloud_color.svg';
import sunWithFace from './icons/travel-places/sky-weather/sun-with-face.svg';
import sunWithFaceColor from './icons/travel-places/sky-weather/sun-with-face_color.svg';
import thermometer from './icons/travel-places/sky-weather/thermometer.svg';
import thermometerColor from './icons/travel-places/sky-weather/thermometer_color.svg';
import tornado from './icons/travel-places/sky-weather/tornado.svg';
import tornadoColor from './icons/travel-places/sky-weather/tornado_color.svg';
import umbrella from './icons/travel-places/sky-weather/umbrella.svg';
import umbrellaColor from './icons/travel-places/sky-weather/umbrella_color.svg';
import umbrellaOnGround from './icons/travel-places/sky-weather/umbrella-on-ground.svg';
import umbrellaOnGroundColor from './icons/travel-places/sky-weather/umbrella-on-ground_color.svg';
import umbrellaWithRainDrops from './icons/travel-places/sky-weather/umbrella-with-rain-drops.svg';
import umbrellaWithRainDropsColor from './icons/travel-places/sky-weather/umbrella-with-rain-drops_color.svg';
import waningCrescentMoon from './icons/travel-places/sky-weather/waning-crescent-moon.svg';
import waningCrescentMoonColor from './icons/travel-places/sky-weather/waning-crescent-moon_color.svg';
import waningGibbousMoon from './icons/travel-places/sky-weather/waning-gibbous-moon.svg';
import waningGibbousMoonColor from './icons/travel-places/sky-weather/waning-gibbous-moon_color.svg';
import waterWave from './icons/travel-places/sky-weather/water-wave.svg';
import waterWaveColor from './icons/travel-places/sky-weather/water-wave_color.svg';
import waxingCrescentMoon from './icons/travel-places/sky-weather/waxing-crescent-moon.svg';
import waxingCrescentMoonColor from './icons/travel-places/sky-weather/waxing-crescent-moon_color.svg';
import waxingGibbousMoon from './icons/travel-places/sky-weather/waxing-gibbous-moon.svg';
import waxingGibbousMoonColor from './icons/travel-places/sky-weather/waxing-gibbous-moon_color.svg';
import windFace from './icons/travel-places/sky-weather/wind-face.svg';
import windFaceColor from './icons/travel-places/sky-weather/wind-face_color.svg';
import alarmClock from './icons/travel-places/time/alarm-clock.svg';
import alarmClockColor from './icons/travel-places/time/alarm-clock_color.svg';
import eightOClock from './icons/travel-places/time/eight-oâclock.svg';
import eightOClockColor from './icons/travel-places/time/eight-oâclock_color.svg';
import eightThirty from './icons/travel-places/time/eight-thirty.svg';
import eightThirtyColor from './icons/travel-places/time/eight-thirty_color.svg';
import elevenOClock from './icons/travel-places/time/eleven-oâclock.svg';
import elevenOClockColor from './icons/travel-places/time/eleven-oâclock_color.svg';
import elevenThirty from './icons/travel-places/time/eleven-thirty.svg';
import elevenThirtyColor from './icons/travel-places/time/eleven-thirty_color.svg';
import fiveOClock from './icons/travel-places/time/five-oâclock.svg';
import fiveOClockColor from './icons/travel-places/time/five-oâclock_color.svg';
import fiveThirty from './icons/travel-places/time/five-thirty.svg';
import fiveThirtyColor from './icons/travel-places/time/five-thirty_color.svg';
import fourOClock from './icons/travel-places/time/four-oâclock.svg';
import fourOClockColor from './icons/travel-places/time/four-oâclock_color.svg';
import fourThirty from './icons/travel-places/time/four-thirty.svg';
import fourThirtyColor from './icons/travel-places/time/four-thirty_color.svg';
import hourglassDone from './icons/travel-places/time/hourglass-done.svg';
import hourglassDoneColor from './icons/travel-places/time/hourglass-done_color.svg';
import hourglassNotDone from './icons/travel-places/time/hourglass-not-done.svg';
import hourglassNotDoneColor from './icons/travel-places/time/hourglass-not-done_color.svg';
import mantelpieceClock from './icons/travel-places/time/mantelpiece-clock.svg';
import mantelpieceClockColor from './icons/travel-places/time/mantelpiece-clock_color.svg';
import nineOClock from './icons/travel-places/time/nine-oâclock.svg';
import nineOClockColor from './icons/travel-places/time/nine-oâclock_color.svg';
import nineThirty from './icons/travel-places/time/nine-thirty.svg';
import nineThirtyColor from './icons/travel-places/time/nine-thirty_color.svg';
import oneOClock from './icons/travel-places/time/one-oâclock.svg';
import oneOClockColor from './icons/travel-places/time/one-oâclock_color.svg';
import oneThirty from './icons/travel-places/time/one-thirty.svg';
import oneThirtyColor from './icons/travel-places/time/one-thirty_color.svg';
import sevenOClock from './icons/travel-places/time/seven-oâclock.svg';
import sevenOClockColor from './icons/travel-places/time/seven-oâclock_color.svg';
import sevenThirty from './icons/travel-places/time/seven-thirty.svg';
import sevenThirtyColor from './icons/travel-places/time/seven-thirty_color.svg';
import sixOClock from './icons/travel-places/time/six-oâclock.svg';
import sixOClockColor from './icons/travel-places/time/six-oâclock_color.svg';
import sixThirty from './icons/travel-places/time/six-thirty.svg';
import sixThirtyColor from './icons/travel-places/time/six-thirty_color.svg';
import stopwatch from './icons/travel-places/time/stopwatch.svg';
import stopwatchColor from './icons/travel-places/time/stopwatch_color.svg';
import tenOClock from './icons/travel-places/time/ten-oâclock.svg';
import tenOClockColor from './icons/travel-places/time/ten-oâclock_color.svg';
import tenThirty from './icons/travel-places/time/ten-thirty.svg';
import tenThirtyColor from './icons/travel-places/time/ten-thirty_color.svg';
import threeOClock from './icons/travel-places/time/three-oâclock.svg';
import threeOClockColor from './icons/travel-places/time/three-oâclock_color.svg';
import threeThirty from './icons/travel-places/time/three-thirty.svg';
import threeThirtyColor from './icons/travel-places/time/three-thirty_color.svg';
import timerClock from './icons/travel-places/time/timer-clock.svg';
import timerClockColor from './icons/travel-places/time/timer-clock_color.svg';
import twelveOClock from './icons/travel-places/time/twelve-oâclock.svg';
import twelveOClockColor from './icons/travel-places/time/twelve-oâclock_color.svg';
import twelveThirty from './icons/travel-places/time/twelve-thirty.svg';
import twelveThirtyColor from './icons/travel-places/time/twelve-thirty_color.svg';
import watch from './icons/travel-places/time/watch.svg';
import watchColor from './icons/travel-places/time/watch_color.svg';
import aerialTramway from './icons/travel-places/transport-air/aerial-tramway.svg';
import aerialTramwayColor from './icons/travel-places/transport-air/aerial-tramway_color.svg';
import airplane from './icons/travel-places/transport-air/airplane.svg';
import airplaneColor from './icons/travel-places/transport-air/airplane_color.svg';
import airplaneArrival from './icons/travel-places/transport-air/airplane-arrival.svg';
import airplaneArrivalColor from './icons/travel-places/transport-air/airplane-arrival_color.svg';
import airplaneDeparture from './icons/travel-places/transport-air/airplane-departure.svg';
import airplaneDepartureColor from './icons/travel-places/transport-air/airplane-departure_color.svg';
import flyingSaucer from './icons/travel-places/transport-air/flying-saucer.svg';
import flyingSaucerColor from './icons/travel-places/transport-air/flying-saucer_color.svg';
import helicopter from './icons/travel-places/transport-air/helicopter.svg';
import helicopterColor from './icons/travel-places/transport-air/helicopter_color.svg';
import mountainCableway from './icons/travel-places/transport-air/mountain-cableway.svg';
import mountainCablewayColor from './icons/travel-places/transport-air/mountain-cableway_color.svg';
import parachute from './icons/travel-places/transport-air/parachute.svg';
import parachuteColor from './icons/travel-places/transport-air/parachute_color.svg';
import rocket from './icons/travel-places/transport-air/rocket.svg';
import rocketColor from './icons/travel-places/transport-air/rocket_color.svg';
import satellite from './icons/travel-places/transport-air/satellite.svg';
import satelliteColor from './icons/travel-places/transport-air/satellite_color.svg';
import seat from './icons/travel-places/transport-air/seat.svg';
import seatColor from './icons/travel-places/transport-air/seat_color.svg';
import smallAirplane from './icons/travel-places/transport-air/small-airplane.svg';
import smallAirplaneColor from './icons/travel-places/transport-air/small-airplane_color.svg';
import suspensionRailway from './icons/travel-places/transport-air/suspension-railway.svg';
import suspensionRailwayColor from './icons/travel-places/transport-air/suspension-railway_color.svg';
import ambulance from './icons/travel-places/transport-ground/ambulance.svg';
import ambulanceColor from './icons/travel-places/transport-ground/ambulance_color.svg';
import articulatedLorry from './icons/travel-places/transport-ground/articulated-lorry.svg';
import articulatedLorryColor from './icons/travel-places/transport-ground/articulated-lorry_color.svg';
import automobile from './icons/travel-places/transport-ground/automobile.svg';
import automobileColor from './icons/travel-places/transport-ground/automobile_color.svg';
import autoRickshaw from './icons/travel-places/transport-ground/auto-rickshaw.svg';
import autoRickshawColor from './icons/travel-places/transport-ground/auto-rickshaw_color.svg';
import bicycle from './icons/travel-places/transport-ground/bicycle.svg';
import bicycleColor from './icons/travel-places/transport-ground/bicycle_color.svg';
import bulletTrain from './icons/travel-places/transport-ground/bullet-train.svg';
import bulletTrainColor from './icons/travel-places/transport-ground/bullet-train_color.svg';
import bus from './icons/travel-places/transport-ground/bus.svg';
import busColor from './icons/travel-places/transport-ground/bus_color.svg';
import busStop from './icons/travel-places/transport-ground/bus-stop.svg';
import busStopColor from './icons/travel-places/transport-ground/bus-stop_color.svg';
import construction from './icons/travel-places/transport-ground/construction.svg';
import constructionColor from './icons/travel-places/transport-ground/construction_color.svg';
import deliveryTruck from './icons/travel-places/transport-ground/delivery-truck.svg';
import deliveryTruckColor from './icons/travel-places/transport-ground/delivery-truck_color.svg';
import fireEngine from './icons/travel-places/transport-ground/fire-engine.svg';
import fireEngineColor from './icons/travel-places/transport-ground/fire-engine_color.svg';
import fuelPump from './icons/travel-places/transport-ground/fuel-pump.svg';
import fuelPumpColor from './icons/travel-places/transport-ground/fuel-pump_color.svg';
import highSpeedTrain from './icons/travel-places/transport-ground/high-speed-train.svg';
import highSpeedTrainColor from './icons/travel-places/transport-ground/high-speed-train_color.svg';
import horizontalTrafficLight from './icons/travel-places/transport-ground/horizontal-traffic-light.svg';
import horizontalTrafficLightColor from './icons/travel-places/transport-ground/horizontal-traffic-light_color.svg';
import kickScooter from './icons/travel-places/transport-ground/kick-scooter.svg';
import kickScooterColor from './icons/travel-places/transport-ground/kick-scooter_color.svg';
import lightRail from './icons/travel-places/transport-ground/light-rail.svg';
import lightRailColor from './icons/travel-places/transport-ground/light-rail_color.svg';
import locomotive from './icons/travel-places/transport-ground/locomotive.svg';
import locomotiveColor from './icons/travel-places/transport-ground/locomotive_color.svg';
import manualWheelchair from './icons/travel-places/transport-ground/manual-wheelchair.svg';
import manualWheelchairColor from './icons/travel-places/transport-ground/manual-wheelchair_color.svg';
import metro from './icons/travel-places/transport-ground/metro.svg';
import metroColor from './icons/travel-places/transport-ground/metro_color.svg';
import minibus from './icons/travel-places/transport-ground/minibus.svg';
import minibusColor from './icons/travel-places/transport-ground/minibus_color.svg';
import monorail from './icons/travel-places/transport-ground/monorail.svg';
import monorailColor from './icons/travel-places/transport-ground/monorail_color.svg';
import motorcycle from './icons/travel-places/transport-ground/motorcycle.svg';
import motorcycleColor from './icons/travel-places/transport-ground/motorcycle_color.svg';
import motorizedWheelchair from './icons/travel-places/transport-ground/motorized-wheelchair.svg';
import motorizedWheelchairColor from './icons/travel-places/transport-ground/motorized-wheelchair_color.svg';
import motorScooter from './icons/travel-places/transport-ground/motor-scooter.svg';
import motorScooterColor from './icons/travel-places/transport-ground/motor-scooter_color.svg';
import motorway from './icons/travel-places/transport-ground/motorway.svg';
import motorwayColor from './icons/travel-places/transport-ground/motorway_color.svg';
import mountainRailway from './icons/travel-places/transport-ground/mountain-railway.svg';
import mountainRailwayColor from './icons/travel-places/transport-ground/mountain-railway_color.svg';
import oilDrum from './icons/travel-places/transport-ground/oil-drum.svg';
import oilDrumColor from './icons/travel-places/transport-ground/oil-drum_color.svg';
import oncomingAutomobile from './icons/travel-places/transport-ground/oncoming-automobile.svg';
import oncomingAutomobileColor from './icons/travel-places/transport-ground/oncoming-automobile_color.svg';
import oncomingBus from './icons/travel-places/transport-ground/oncoming-bus.svg';
import oncomingBusColor from './icons/travel-places/transport-ground/oncoming-bus_color.svg';
import oncomingPoliceCar from './icons/travel-places/transport-ground/oncoming-police-car.svg';
import oncomingPoliceCarColor from './icons/travel-places/transport-ground/oncoming-police-car_color.svg';
import oncomingTaxi from './icons/travel-places/transport-ground/oncoming-taxi.svg';
import oncomingTaxiColor from './icons/travel-places/transport-ground/oncoming-taxi_color.svg';
import pickupTruck from './icons/travel-places/transport-ground/pickup-truck.svg';
import pickupTruckColor from './icons/travel-places/transport-ground/pickup-truck_color.svg';
import policeCar from './icons/travel-places/transport-ground/police-car.svg';
import policeCarColor from './icons/travel-places/transport-ground/police-car_color.svg';
import policeCarLight from './icons/travel-places/transport-ground/police-car-light.svg';
import policeCarLightColor from './icons/travel-places/transport-ground/police-car-light_color.svg';
import racingCar from './icons/travel-places/transport-ground/racing-car.svg';
import racingCarColor from './icons/travel-places/transport-ground/racing-car_color.svg';
import railwayCar from './icons/travel-places/transport-ground/railway-car.svg';
import railwayCarColor from './icons/travel-places/transport-ground/railway-car_color.svg';
import railwayTrack from './icons/travel-places/transport-ground/railway-track.svg';
import railwayTrackColor from './icons/travel-places/transport-ground/railway-track_color.svg';
import rollerSkate from './icons/travel-places/transport-ground/roller-skate.svg';
import rollerSkateColor from './icons/travel-places/transport-ground/roller-skate_color.svg';
import skateboard from './icons/travel-places/transport-ground/skateboard.svg';
import skateboardColor from './icons/travel-places/transport-ground/skateboard_color.svg';
import sportUtilityVehicle from './icons/travel-places/transport-ground/sport-utility-vehicle.svg';
import sportUtilityVehicleColor from './icons/travel-places/transport-ground/sport-utility-vehicle_color.svg';
import station from './icons/travel-places/transport-ground/station.svg';
import stationColor from './icons/travel-places/transport-ground/station_color.svg';
import stopSign from './icons/travel-places/transport-ground/stop-sign.svg';
import stopSignColor from './icons/travel-places/transport-ground/stop-sign_color.svg';
import taxi from './icons/travel-places/transport-ground/taxi.svg';
import taxiColor from './icons/travel-places/transport-ground/taxi_color.svg';
import tractor from './icons/travel-places/transport-ground/tractor.svg';
import tractorColor from './icons/travel-places/transport-ground/tractor_color.svg';
import train from './icons/travel-places/transport-ground/train.svg';
import trainColor from './icons/travel-places/transport-ground/train_color.svg';
import tram from './icons/travel-places/transport-ground/tram.svg';
import tramColor from './icons/travel-places/transport-ground/tram_color.svg';
import trolleybus from './icons/travel-places/transport-ground/trolleybus.svg';
import trolleybusColor from './icons/travel-places/transport-ground/trolleybus_color.svg';
import verticalTrafficLight from './icons/travel-places/transport-ground/vertical-traffic-light.svg';
import verticalTrafficLightColor from './icons/travel-places/transport-ground/vertical-traffic-light_color.svg';
import wheel from './icons/travel-places/transport-ground/wheel.svg';
import wheelColor from './icons/travel-places/transport-ground/wheel_color.svg';
import anchor from './icons/travel-places/transport-water/anchor.svg';
import anchorColor from './icons/travel-places/transport-water/anchor_color.svg';
import canoe from './icons/travel-places/transport-water/canoe.svg';
import canoeColor from './icons/travel-places/transport-water/canoe_color.svg';
import ferry from './icons/travel-places/transport-water/ferry.svg';
import ferryColor from './icons/travel-places/transport-water/ferry_color.svg';
import motorBoat from './icons/travel-places/transport-water/motor-boat.svg';
import motorBoatColor from './icons/travel-places/transport-water/motor-boat_color.svg';
import passengerShip from './icons/travel-places/transport-water/passenger-ship.svg';
import passengerShipColor from './icons/travel-places/transport-water/passenger-ship_color.svg';
import ringBuoy from './icons/travel-places/transport-water/ring-buoy.svg';
import ringBuoyColor from './icons/travel-places/transport-water/ring-buoy_color.svg';
import sailboat from './icons/travel-places/transport-water/sailboat.svg';
import sailboatColor from './icons/travel-places/transport-water/sailboat_color.svg';
import ship from './icons/travel-places/transport-water/ship.svg';
import shipColor from './icons/travel-places/transport-water/ship_color.svg';
import speedboat from './icons/travel-places/transport-water/speedboat.svg';
import speedboatColor from './icons/travel-places/transport-water/speedboat_color.svg';

import {IconProps} from './use-search';

export const openTravelPlacesTable = new Map<string, Omit<IconProps, 'id'>>();

openTravelPlacesTable.set('bellhopBell', {name: 'Bellhop Bell', icon: bellhopBell});
openTravelPlacesTable.set('bellhopBellColor', {name: 'Bellhop Bell Color', icon: bellhopBellColor});
openTravelPlacesTable.set('luggage', {name: 'Luggage', icon: luggage});
openTravelPlacesTable.set('luggageColor', {name: 'Luggage Color', icon: luggageColor});
openTravelPlacesTable.set('bank', {name: 'Bank', icon: bank});
openTravelPlacesTable.set('bankColor', {name: 'Bank Color', icon: bankColor});
openTravelPlacesTable.set('brick', {name: 'Brick', icon: brick});
openTravelPlacesTable.set('brickColor', {name: 'Brick Color', icon: brickColor});
openTravelPlacesTable.set('buildingConstruction', {name: 'Building Construction', icon: buildingConstruction});
openTravelPlacesTable.set('buildingConstructionColor', {
    name: 'Building Construction Color',
    icon: buildingConstructionColor,
});
openTravelPlacesTable.set('castle', {name: 'Castle', icon: castle});
openTravelPlacesTable.set('castleColor', {name: 'Castle Color', icon: castleColor});
openTravelPlacesTable.set('classicalBuilding', {name: 'Classical Building', icon: classicalBuilding});
openTravelPlacesTable.set('classicalBuildingColor', {name: 'Classical Building Color', icon: classicalBuildingColor});
openTravelPlacesTable.set('convenienceStore', {name: 'Convenience Store', icon: convenienceStore});
openTravelPlacesTable.set('convenienceStoreColor', {name: 'Convenience Store Color', icon: convenienceStoreColor});
openTravelPlacesTable.set('departmentStore', {name: 'Department Store', icon: departmentStore});
openTravelPlacesTable.set('departmentStoreColor', {name: 'Department Store Color', icon: departmentStoreColor});
openTravelPlacesTable.set('derelictHouse', {name: 'Derelict House', icon: derelictHouse});
openTravelPlacesTable.set('derelictHouseColor', {name: 'Derelict House Color', icon: derelictHouseColor});
openTravelPlacesTable.set('factory', {name: 'Factory', icon: factory});
openTravelPlacesTable.set('factoryColor', {name: 'Factory Color', icon: factoryColor});
openTravelPlacesTable.set('hospital', {name: 'Hospital', icon: hospital});
openTravelPlacesTable.set('hospitalColor', {name: 'Hospital Color', icon: hospitalColor});
openTravelPlacesTable.set('hotel', {name: 'Hotel', icon: hotel});
openTravelPlacesTable.set('hotelColor', {name: 'Hotel Color', icon: hotelColor});
openTravelPlacesTable.set('house', {name: 'House', icon: house});
openTravelPlacesTable.set('houseColor', {name: 'House Color', icon: houseColor});
openTravelPlacesTable.set('houses', {name: 'Houses', icon: houses});
openTravelPlacesTable.set('housesColor', {name: 'Houses Color', icon: housesColor});
openTravelPlacesTable.set('houseWithGarden', {name: 'House With Garden', icon: houseWithGarden});
openTravelPlacesTable.set('houseWithGardenColor', {name: 'House With Garden Color', icon: houseWithGardenColor});
openTravelPlacesTable.set('hut', {name: 'Hut', icon: hut});
openTravelPlacesTable.set('hutColor', {name: 'Hut Color', icon: hutColor});
openTravelPlacesTable.set('japaneseCastle', {name: 'Japanese Castle', icon: japaneseCastle});
openTravelPlacesTable.set('japaneseCastleColor', {name: 'Japanese Castle Color', icon: japaneseCastleColor});
openTravelPlacesTable.set('japanesePostOffice', {name: 'Japanese Post Office', icon: japanesePostOffice});
openTravelPlacesTable.set('japanesePostOfficeColor', {
    name: 'Japanese Post Office Color',
    icon: japanesePostOfficeColor,
});
openTravelPlacesTable.set('loveHotel', {name: 'Love Hotel', icon: loveHotel});
openTravelPlacesTable.set('loveHotelColor', {name: 'Love Hotel Color', icon: loveHotelColor});
openTravelPlacesTable.set('officeBuilding', {name: 'Office Building', icon: officeBuilding});
openTravelPlacesTable.set('officeBuildingColor', {name: 'Office Building Color', icon: officeBuildingColor});
openTravelPlacesTable.set('postOffice', {name: 'Post Office', icon: postOffice});
openTravelPlacesTable.set('postOfficeColor', {name: 'Post Office Color', icon: postOfficeColor});
openTravelPlacesTable.set('rock', {name: 'Rock', icon: rock});
openTravelPlacesTable.set('rockColor', {name: 'Rock Color', icon: rockColor});
openTravelPlacesTable.set('school', {name: 'School', icon: school});
openTravelPlacesTable.set('schoolColor', {name: 'School Color', icon: schoolColor});
openTravelPlacesTable.set('stadium', {name: 'Stadium', icon: stadium});
openTravelPlacesTable.set('stadiumColor', {name: 'Stadium Color', icon: stadiumColor});
openTravelPlacesTable.set('statueOfLiberty', {name: 'Statue Of Liberty', icon: statueOfLiberty});
openTravelPlacesTable.set('statueOfLibertyColor', {name: 'Statue Of Liberty Color', icon: statueOfLibertyColor});
openTravelPlacesTable.set('tokyoTower', {name: 'Tokyo Tower', icon: tokyoTower});
openTravelPlacesTable.set('tokyoTowerColor', {name: 'Tokyo Tower Color', icon: tokyoTowerColor});
openTravelPlacesTable.set('wedding', {name: 'Wedding', icon: wedding});
openTravelPlacesTable.set('weddingColor', {name: 'Wedding Color', icon: weddingColor});
openTravelPlacesTable.set('wood', {name: 'Wood', icon: wood});
openTravelPlacesTable.set('woodColor', {name: 'Wood Color', icon: woodColor});
openTravelPlacesTable.set('beachWithUmbrella', {name: 'Beach With Umbrella', icon: beachWithUmbrella});
openTravelPlacesTable.set('beachWithUmbrellaColor', {name: 'Beach With Umbrella Color', icon: beachWithUmbrellaColor});
openTravelPlacesTable.set('camping', {name: 'Camping', icon: camping});
openTravelPlacesTable.set('campingColor', {name: 'Camping Color', icon: campingColor});
openTravelPlacesTable.set('desert', {name: 'Desert', icon: desert});
openTravelPlacesTable.set('desertColor', {name: 'Desert Color', icon: desertColor});
openTravelPlacesTable.set('desertIsland', {name: 'Desert Island', icon: desertIsland});
openTravelPlacesTable.set('desertIslandColor', {name: 'Desert Island Color', icon: desertIslandColor});
openTravelPlacesTable.set('mountain', {name: 'Mountain', icon: mountain});
openTravelPlacesTable.set('mountainColor', {name: 'Mountain Color', icon: mountainColor});
openTravelPlacesTable.set('mountFuji', {name: 'Mounty Fuji', icon: mountFuji});
openTravelPlacesTable.set('mountFujiColor', {name: 'Mount Fuji Color', icon: mountFujiColor});
openTravelPlacesTable.set('nationalPark', {name: 'National Park', icon: nationalPark});
openTravelPlacesTable.set('nationalParkColor', {name: 'National Park Color', icon: nationalParkColor});
openTravelPlacesTable.set('snowCappedMountain', {name: 'Snow Capped Mountain', icon: snowCappedMountain});
openTravelPlacesTable.set('snowCappedMountainColor', {
    name: 'Snow Capped Mountain Color',
    icon: snowCappedMountainColor,
});
openTravelPlacesTable.set('volcano', {name: 'Volcano', icon: volcano});
openTravelPlacesTable.set('volcanoColor', {name: 'Volcano Color', icon: volcanoColor});
openTravelPlacesTable.set('compass', {name: 'Compass', icon: compass});
openTravelPlacesTable.set('compassColor', {name: 'Compass Color', icon: compassColor});
openTravelPlacesTable.set('globeShowingAmericas', {name: 'Globe Showing Americas', icon: globeShowingAmericas});
openTravelPlacesTable.set('globeShowingAmericasColor', {
    name: 'Globe Showing Americas Color',
    icon: globeShowingAmericasColor,
});
openTravelPlacesTable.set('globeShowingAsiaAustralia', {name: 'Globe Showing Asia', icon: globeShowingAsiaAustralia});
openTravelPlacesTable.set('globeShowingAsiaAustraliaColor', {
    name: 'Globe Showing Asia Australia Color',
    icon: globeShowingAsiaAustraliaColor,
});
openTravelPlacesTable.set('globeShowingEuropeAfrica', {
    name: 'Globe Showing Europe Africa',
    icon: globeShowingEuropeAfrica,
});
openTravelPlacesTable.set('globeShowingEuropeAfricaColor', {
    name: 'Globe Showing Europe Africa Color',
    icon: globeShowingEuropeAfricaColor,
});
openTravelPlacesTable.set('globeWithMeridians', {name: 'Globe With Meridians', icon: globeWithMeridians});
openTravelPlacesTable.set('globeWithMeridiansColor', {
    name: 'Globe With Meridians Color',
    icon: globeWithMeridiansColor,
});
openTravelPlacesTable.set('mapOfJapan', {name: 'Map Of Japan', icon: mapOfJapan});
openTravelPlacesTable.set('mapOfJapanColor', {name: 'Map Of Japan Color', icon: mapOfJapanColor});
openTravelPlacesTable.set('worldMap', {name: 'World Map', icon: worldMap});
openTravelPlacesTable.set('worldMapColor', {name: 'World Map Color', icon: worldMapColor});
openTravelPlacesTable.set('barberPole', {name: 'Barber Pole', icon: barberPole});
openTravelPlacesTable.set('barberPoleColor', {name: 'Barber Pole Color', icon: barberPoleColor});
openTravelPlacesTable.set('bridgeAtNight', {name: 'Bridge At Night', icon: bridgeAtNight});
openTravelPlacesTable.set('bridgeAtNightColor', {name: 'Bridge At Night Color', icon: bridgeAtNightColor});
openTravelPlacesTable.set('carouselHorse', {name: 'Carousel Horse', icon: carouselHorse});
openTravelPlacesTable.set('carouselHorseColor', {name: 'Carousel Horse Color', icon: carouselHorseColor});
openTravelPlacesTable.set('circusTent', {name: 'Circus Tent', icon: circusTent});
openTravelPlacesTable.set('circusTentColor', {name: 'Circus Tent Color', icon: circusTentColor});
openTravelPlacesTable.set('cityscape', {name: 'Cityscape', icon: cityscape});
openTravelPlacesTable.set('cityscapeColor', {name: 'Cityscape Color', icon: cityscapeColor});
openTravelPlacesTable.set('cityscapeAtDusk', {name: 'Cityscape At Dusk', icon: cityscapeAtDusk});
openTravelPlacesTable.set('cityscapeAtDuskColor', {name: 'Cityscape At Dusk Color', icon: cityscapeAtDuskColor});
openTravelPlacesTable.set('ferrisWheel', {name: 'Ferris Wheel', icon: ferrisWheel});
openTravelPlacesTable.set('ferrisWheelColor', {name: 'Ferris Wheel Color', icon: ferrisWheelColor});
openTravelPlacesTable.set('foggy', {name: 'Foggy', icon: foggy});
openTravelPlacesTable.set('foggyColor', {name: 'Foggy Color', icon: foggyColor});
openTravelPlacesTable.set('fountain', {name: 'Fountain', icon: fountain});
openTravelPlacesTable.set('fountainColor', {name: 'Fountain Color', icon: fountainColor});
openTravelPlacesTable.set('hotSprings', {name: 'Hot Springs', icon: hotSprings});
openTravelPlacesTable.set('hotSpringsColor', {name: 'Hot Springs Color', icon: hotSpringsColor});
openTravelPlacesTable.set('nightWithStars', {name: 'Night With Stars', icon: nightWithStars});
openTravelPlacesTable.set('nightWithStarsColor', {name: 'Night With Stars Color', icon: nightWithStarsColor});
openTravelPlacesTable.set('playgroundSlide', {name: 'Playground Slide', icon: playgroundSlide});
openTravelPlacesTable.set('playgroundSlideColor', {name: 'Playground Slide Color', icon: playgroundSlideColor});
openTravelPlacesTable.set('rollerCoaster', {name: 'Roller Coaster', icon: rollerCoaster});
openTravelPlacesTable.set('rollerCoasterColor', {name: 'Roller Coaster Color', icon: rollerCoasterColor});
openTravelPlacesTable.set('sunrise', {name: 'Sunrise', icon: sunrise});
openTravelPlacesTable.set('sunriseColor', {name: 'Sunrise Color', icon: sunriseColor});
openTravelPlacesTable.set('sunriseOverMountains', {name: 'Sunrise Over Mountains', icon: sunriseOverMountains});
openTravelPlacesTable.set('sunriseOverMountainsColor', {
    name: 'Sunrise Over Mountains Color',
    icon: sunriseOverMountainsColor,
});
openTravelPlacesTable.set('sunset', {name: 'Sunset', icon: sunset});
openTravelPlacesTable.set('sunsetColor', {name: 'Sunset Color', icon: sunsetColor});
openTravelPlacesTable.set('tent', {name: 'Tent', icon: tent});
openTravelPlacesTable.set('tentColor', {name: 'Tent Color', icon: tentColor});
openTravelPlacesTable.set('church', {name: 'Church', icon: church});
openTravelPlacesTable.set('churchColor', {name: 'Church Color', icon: churchColor});
openTravelPlacesTable.set('hinduTemple', {name: 'Hindu Temple', icon: hinduTemple});
openTravelPlacesTable.set('hinduTempleColor', {name: 'Hindu Temple Color', icon: hinduTempleColor});
openTravelPlacesTable.set('kaaba', {name: 'Kaaba', icon: kaaba});
openTravelPlacesTable.set('kaabaColor', {name: 'Kaaba Color', icon: kaabaColor});
openTravelPlacesTable.set('mosque', {name: 'Mosque', icon: mosque});
openTravelPlacesTable.set('mosqueColor', {name: 'Mosque Color', icon: mosqueColor});
openTravelPlacesTable.set('shintoShrine', {name: 'Shinto Shrine', icon: shintoShrine});
openTravelPlacesTable.set('shintoShrineColor', {name: 'Shinto Shrine Color', icon: shintoShrineColor});
openTravelPlacesTable.set('synagogue', {name: 'Synagogue', icon: synagogue});
openTravelPlacesTable.set('synagogueColor', {name: 'Synagogue Color', icon: synagogueColor});
openTravelPlacesTable.set('closedUmbrella', {name: 'Closed Umbrella', icon: closedUmbrella});
openTravelPlacesTable.set('closedUmbrellaColor', {name: 'Closed Umbrella Color', icon: closedUmbrellaColor});
openTravelPlacesTable.set('cloud', {name: 'Cloud', icon: cloud});
openTravelPlacesTable.set('cloudColor', {name: 'Cloud Color', icon: cloudColor});
openTravelPlacesTable.set('cloudWithLightning', {name: 'Cloud With Lightning', icon: cloudWithLightning});
openTravelPlacesTable.set('cloudWithLightningColor', {
    name: 'Cloud With Lightning Color',
    icon: cloudWithLightningColor,
});
openTravelPlacesTable.set('cloudWithLightningAndRain', {
    name: 'Cloud With Lightning And Rain',
    icon: cloudWithLightningAndRain,
});
openTravelPlacesTable.set('cloudWithLightningAndRainColor', {
    name: 'Cloud With Lightning And Rain Color',
    icon: cloudWithLightningAndRainColor,
});
openTravelPlacesTable.set('cloudWithRain', {name: 'Cloud With Rain', icon: cloudWithRain});
openTravelPlacesTable.set('cloudWithRainColor', {name: 'Cloud With Rain Color', icon: cloudWithRainColor});
openTravelPlacesTable.set('cloudWithSnow', {name: 'Cloud With Snow', icon: cloudWithSnow});
openTravelPlacesTable.set('cloudWithSnowColor', {name: 'Cloud With Snow Color', icon: cloudWithSnowColor});
openTravelPlacesTable.set('comet', {name: 'Comet', icon: comet});
openTravelPlacesTable.set('cometColor', {name: 'Comet Color', icon: cometColor});
openTravelPlacesTable.set('crescentMoon', {name: 'Crescent Moon', icon: crescentMoon});
openTravelPlacesTable.set('crescentMoonColor', {name: 'Crescent Moon Color', icon: crescentMoonColor});
openTravelPlacesTable.set('cyclone', {name: 'Cyclone', icon: cyclone});
openTravelPlacesTable.set('cycloneColor', {name: 'Cyclone Color', icon: cycloneColor});
openTravelPlacesTable.set('droplet', {name: 'Droplet', icon: droplet});
openTravelPlacesTable.set('dropletColor', {name: 'Droplet Color', icon: dropletColor});
openTravelPlacesTable.set('fire', {name: 'Fire', icon: fire});
openTravelPlacesTable.set('fireColor', {name: 'Fire Color', icon: fireColor});
openTravelPlacesTable.set('firstQuarterMoon', {name: 'First Quarter Moon', icon: firstQuarterMoon});
openTravelPlacesTable.set('firstQuarterMoonColor', {name: 'First Quarter Moon Color', icon: firstQuarterMoonColor});
openTravelPlacesTable.set('firstQuarterMoonFace', {name: 'First Quarter Moon Face', icon: firstQuarterMoonFace});
openTravelPlacesTable.set('firstQuarterMoonFaceColor', {
    name: 'First Quarter Moon Face Color',
    icon: firstQuarterMoonFaceColor,
});
openTravelPlacesTable.set('fog', {name: 'fog', icon: fog});
openTravelPlacesTable.set('fogColor', {name: 'Fog Color', icon: fogColor});
openTravelPlacesTable.set('fullMoon', {name: 'Full Moon', icon: fullMoon});
openTravelPlacesTable.set('fullMoonColor', {name: 'Full Moon Color', icon: fullMoonColor});
openTravelPlacesTable.set('fullMoonFace', {name: 'Full Moon Face', icon: fullMoonFace});
openTravelPlacesTable.set('fullMoonFaceColor', {name: 'Full Moon Face Color', icon: fullMoonFaceColor});
openTravelPlacesTable.set('glowingStar', {name: 'Glowing Star', icon: glowingStar});
openTravelPlacesTable.set('glowingStarColor', {name: 'Glowing Star Color', icon: glowingStarColor});
openTravelPlacesTable.set('highVoltage', {name: 'High Voltage', icon: highVoltage});
openTravelPlacesTable.set('highVoltageColor', {name: 'High Voltage Color', icon: highVoltageColor});
openTravelPlacesTable.set('lastQuarterMoon', {name: 'Last Quarter Moon', icon: lastQuarterMoon});
openTravelPlacesTable.set('lastQuarterMoonColor', {name: 'Last Quarter Moon Color', icon: lastQuarterMoonColor});
openTravelPlacesTable.set('lastQuarterMoonFace', {name: 'Last Quarter Moon Face', icon: lastQuarterMoonFace});
openTravelPlacesTable.set('lastQuarterMoonFaceColor', {
    name: 'Last Quarter Moon Face Color',
    icon: lastQuarterMoonFaceColor,
});
openTravelPlacesTable.set('milkyWay', {name: 'Milky Way', icon: milkyWay});
openTravelPlacesTable.set('milkyWayColor', {name: 'Milky Way Color', icon: milkyWayColor});
openTravelPlacesTable.set('newMoon', {name: 'New Moon', icon: newMoon});
openTravelPlacesTable.set('newMoonColor', {name: 'New Moon Color', icon: newMoonColor});
openTravelPlacesTable.set('newMoonFace', {name: 'New Moon Face', icon: newMoonFace});
openTravelPlacesTable.set('newMoonFaceColor', {name: 'New Moon Face Color', icon: newMoonFaceColor});
openTravelPlacesTable.set('rainbow', {name: 'Rainbow', icon: rainbow});
openTravelPlacesTable.set('rainbowColor', {name: 'Rainbow Color', icon: rainbowColor});
openTravelPlacesTable.set('ringedPlanet', {name: 'Ringed Planet', icon: ringedPlanet});
openTravelPlacesTable.set('ringedPlanetColor', {name: 'Ringed Planet Color', icon: ringedPlanetColor});
openTravelPlacesTable.set('shootingStar', {name: 'Shooting Star', icon: shootingStar});
openTravelPlacesTable.set('shootingStarColor', {name: 'Shooting Star Color', icon: shootingStarColor});
openTravelPlacesTable.set('snowflake', {name: 'Snowflake', icon: snowflake});
openTravelPlacesTable.set('snowflakeColor', {name: 'Snowflake Color', icon: snowflakeColor});
openTravelPlacesTable.set('snowman', {name: 'Snowman', icon: snowman});
openTravelPlacesTable.set('snowmanColor', {name: 'Snowman Color', icon: snowmanColor});
openTravelPlacesTable.set('snowmanWithoutSnow', {name: 'Snowman Without Snow', icon: snowmanWithoutSnow});
openTravelPlacesTable.set('snowmanWithoutSnowColor', {
    name: 'Snowman Without Snow Color',
    icon: snowmanWithoutSnowColor,
});
openTravelPlacesTable.set('star', {name: 'Star', icon: star});
openTravelPlacesTable.set('starColor', {name: 'Star Color', icon: starColor});
openTravelPlacesTable.set('sun', {name: 'Sun', icon: sun});
openTravelPlacesTable.set('sunColor', {name: 'Sun Color', icon: sunColor});
openTravelPlacesTable.set('sunBehindCloud', {name: 'Sun Behind Cloud', icon: sunBehindCloud});
openTravelPlacesTable.set('sunBehindCloudColor', {name: 'Sun Behind Cloud Color', icon: sunBehindCloudColor});
openTravelPlacesTable.set('sunBehindLargeCloud', {name: 'Sun Behind Large Cloud', icon: sunBehindLargeCloud});
openTravelPlacesTable.set('sunBehindLargeCloudColor', {
    name: ' Sun Behind Large Cloud Color',
    icon: sunBehindLargeCloudColor,
});
openTravelPlacesTable.set('sunBehindRainCloud', {name: 'Sun Behind Rain Cloud', icon: sunBehindRainCloud});
openTravelPlacesTable.set('sunBehindRainCloudColor', {
    name: 'Sun Behind Rain Cloud Color',
    icon: sunBehindRainCloudColor,
});
openTravelPlacesTable.set('sunBehindSmallCloud', {name: 'Sun Behind Small Cloud', icon: sunBehindSmallCloud});
openTravelPlacesTable.set('sunBehindSmallCloudColor', {
    name: 'Sun Behind Small Cloud Color',
    icon: sunBehindSmallCloudColor,
});
openTravelPlacesTable.set('sunWithFace', {name: 'Sun With Face', icon: sunWithFace});
openTravelPlacesTable.set('sunWithFaceColor', {name: 'Sun With Face Color', icon: sunWithFaceColor});
openTravelPlacesTable.set('thermometer', {name: 'Thermometer', icon: thermometer});
openTravelPlacesTable.set('thermometerColor', {name: 'Thermometer Color', icon: thermometerColor});
openTravelPlacesTable.set('tornado', {name: 'Tornado', icon: tornado});
openTravelPlacesTable.set('tornadoCOlor', {name: 'Tornado Color', icon: tornadoColor});
openTravelPlacesTable.set('umbrella', {name: 'Umbrella', icon: umbrella});
openTravelPlacesTable.set('umbrellaColor', {name: 'Umbrella Color', icon: umbrellaColor});
openTravelPlacesTable.set('umbrellaOnGround', {name: 'Umbrella On Ground', icon: umbrellaOnGround});
openTravelPlacesTable.set('umbrellaOnGroundColor', {name: 'Umbrella On Ground Color', icon: umbrellaOnGroundColor});
openTravelPlacesTable.set('umbrellaWithRainDrops', {name: 'Umbrella With Rain Drops', icon: umbrellaWithRainDrops});
openTravelPlacesTable.set('umbrellaWithRainDropsColor', {
    name: 'Umbrella With Rain Drops Color',
    icon: umbrellaWithRainDropsColor,
});
openTravelPlacesTable.set('waningCrescentMoon', {name: 'Waning Crescent Moon', icon: waningCrescentMoon});
openTravelPlacesTable.set('waningCrescentMoonColor', {
    name: 'Waning Crescent Moon Color',
    icon: waningCrescentMoonColor,
});
openTravelPlacesTable.set('waningGibbousMoon', {name: 'Waning Gibbous Moon', icon: waningGibbousMoon});
openTravelPlacesTable.set('waningGibbousMoonColor', {name: 'Waning Gibbous Moon Color', icon: waningGibbousMoonColor});
openTravelPlacesTable.set('waterWave', {name: 'Water Wave', icon: waterWave});
openTravelPlacesTable.set('waterWaveColor', {name: 'Water Wave Color', icon: waterWaveColor});
openTravelPlacesTable.set('waxingCrescentMoon', {name: 'Waxing Crescent Moon', icon: waxingCrescentMoon});
openTravelPlacesTable.set('waxingCrescentMoonColor', {
    name: 'Waxing Crescent Moon Color',
    icon: waxingCrescentMoonColor,
});
openTravelPlacesTable.set('waxingGibbousMoon', {name: 'Waxing Gibbous Moon', icon: waxingGibbousMoon});
openTravelPlacesTable.set('waxingGibbousMoonColor', {name: 'Waxing Gibbous Moon Color', icon: waxingGibbousMoonColor});
openTravelPlacesTable.set('windFace', {name: 'Wind Face', icon: windFace});
openTravelPlacesTable.set('windFaceColor', {name: 'Wind Face Color', icon: windFaceColor});
openTravelPlacesTable.set('alarmClock', {name: 'Alarm Clock', icon: alarmClock});
openTravelPlacesTable.set('alarmClockColor', {name: 'Alarm Clock Color', icon: alarmClockColor});
openTravelPlacesTable.set('eightOClock', {name: 'Eight O Clock', icon: eightOClock});
openTravelPlacesTable.set('eightOClockColor', {name: 'Eight O Clock Color', icon: eightOClockColor});
openTravelPlacesTable.set('eightThirty', {name: 'Eight Thirty', icon: eightThirty});
openTravelPlacesTable.set('eightThirtyColor', {name: 'Eight Thirty Color', icon: eightThirtyColor});
openTravelPlacesTable.set('elevenOClock', {name: 'Eleven O Clock', icon: elevenOClock});
openTravelPlacesTable.set('elevenOClockColor', {name: 'Eleven O Clock Color', icon: elevenOClockColor});
openTravelPlacesTable.set('elevenThirty', {name: 'Eleven Thirty', icon: elevenThirty});
openTravelPlacesTable.set('elevenThirtyColor', {name: 'Eleven Thirty Color', icon: elevenThirtyColor});
openTravelPlacesTable.set('fiveOClock', {name: 'Five O Clock', icon: fiveOClock});
openTravelPlacesTable.set('fiveOClockColor', {name: 'Fire O Clock Color', icon: fiveOClockColor});
openTravelPlacesTable.set('fiveThirty', {name: 'Five Thirty', icon: fiveThirty});
openTravelPlacesTable.set('fiveThirtyColor', {name: 'Five Thirty Color', icon: fiveThirtyColor});
openTravelPlacesTable.set('fourOClock', {name: 'Four O Clock', icon: fourOClock});
openTravelPlacesTable.set('fourOClockColor', {name: 'Four O Clock Color', icon: fourOClockColor});
openTravelPlacesTable.set('fourThirty', {name: 'Four Thirty', icon: fourThirty});
openTravelPlacesTable.set('fourThirtyColor', {name: 'Four Thirty Color', icon: fourThirtyColor});
openTravelPlacesTable.set('hourglassDone', {name: 'Hourglass Done', icon: hourglassDone});
openTravelPlacesTable.set('hourglassDoneColor', {name: 'Hourglass Done Color', icon: hourglassDoneColor});
openTravelPlacesTable.set('hourglassNotDone', {name: 'Hourglass Not Done', icon: hourglassNotDone});
openTravelPlacesTable.set('hourglassNotDoneColor', {name: 'Hourglass Not Done Color', icon: hourglassNotDoneColor});
openTravelPlacesTable.set('mantelpieceClock', {name: 'Mantelpiece Clock', icon: mantelpieceClock});
openTravelPlacesTable.set('mantelpieceClockColor', {name: 'Mantelpiece Clock Color', icon: mantelpieceClockColor});
openTravelPlacesTable.set('nineOClock', {name: 'Nine O Clock', icon: nineOClock});
openTravelPlacesTable.set('nineOClockColor', {name: 'Nine O Clock Color', icon: nineOClockColor});
openTravelPlacesTable.set('nineThirty', {name: 'Nine Thirty', icon: nineThirty});
openTravelPlacesTable.set('nineThirtyColor', {name: 'Nine Thirty Color', icon: nineThirtyColor});
openTravelPlacesTable.set('oneOClock', {name: 'Nine O Clock', icon: oneOClock});
openTravelPlacesTable.set('oneOClockColor', {name: 'Nine O Clock Color', icon: oneOClockColor});
openTravelPlacesTable.set('oneThirty', {name: 'One Thirty', icon: oneThirty});
openTravelPlacesTable.set('oneThirtyColor', {name: 'One Thirty Color', icon: oneThirtyColor});
openTravelPlacesTable.set('sevenOClock', {name: 'Seven O Clock', icon: sevenOClock});
openTravelPlacesTable.set('sevenOClockColor', {name: 'Seven O Clock Color', icon: sevenOClockColor});
openTravelPlacesTable.set('sevenThirty', {name: 'Seven Thirty', icon: sevenThirty});
openTravelPlacesTable.set('sevenThirtyColor', {name: 'Seven Thirty Color', icon: sevenThirtyColor});
openTravelPlacesTable.set('sixOClock', {name: 'Six O Clock', icon: sixOClock});
openTravelPlacesTable.set('sixOClockColor', {name: 'Six O Clock Color', icon: sixOClockColor});
openTravelPlacesTable.set('sixThirty', {name: 'Six Thirty', icon: sixThirty});
openTravelPlacesTable.set('sixThirtyColor', {name: 'Six Thirty Color', icon: sixThirtyColor});
openTravelPlacesTable.set('stopwatch', {name: 'Stopwatch', icon: stopwatch});
openTravelPlacesTable.set('stopwatchColor', {name: 'Stopwatch Color', icon: stopwatchColor});
openTravelPlacesTable.set('tenOClock', {name: 'Ten O Clock', icon: tenOClock});
openTravelPlacesTable.set('tenOClockColor', {name: 'Ten O Clock Color', icon: tenOClockColor});
openTravelPlacesTable.set('tenThirty', {name: 'Ten Thirty', icon: tenThirty});
openTravelPlacesTable.set('tenThirtyColor', {name: 'Ten Thirty Color', icon: tenThirtyColor});
openTravelPlacesTable.set('threeOClock', {name: 'Three O Clock', icon: threeOClock});
openTravelPlacesTable.set('threeOClockColor', {name: 'Three O Clock Color', icon: threeOClockColor});
openTravelPlacesTable.set('threeThirty', {name: 'Three Thirty', icon: threeThirty});
openTravelPlacesTable.set('threeThirtyColor', {name: 'Three Thirty Color', icon: threeThirtyColor});
openTravelPlacesTable.set('timerClock', {name: 'Timer Clock', icon: timerClock});
openTravelPlacesTable.set('timerClockColor', {name: 'Timer Clock Color', icon: timerClockColor});
openTravelPlacesTable.set('twelveOClock', {name: 'Twelve O Clock', icon: twelveOClock});
openTravelPlacesTable.set('twelveOClockColor', {name: 'Twelve O Clock Color', icon: twelveOClockColor});
openTravelPlacesTable.set('twelveThirty', {name: 'Twelve Thirty', icon: twelveThirty});
openTravelPlacesTable.set('twelveThirtyColor', {name: 'Twelve Thirty Color', icon: twelveThirtyColor});
openTravelPlacesTable.set('watch', {name: 'Watch', icon: watch});
openTravelPlacesTable.set('watchColor', {name: 'Watch Color', icon: watchColor});
openTravelPlacesTable.set('aerialTramway', {name: 'Aerial Tramway', icon: aerialTramway});
openTravelPlacesTable.set('aerialTramwayColor', {name: 'Aerial Tramway Color', icon: aerialTramwayColor});
openTravelPlacesTable.set('airplane', {name: 'Airplane', icon: airplane});
openTravelPlacesTable.set('airplaneColor', {name: 'Airplane Color', icon: airplaneColor});
openTravelPlacesTable.set('airplaneArrival', {name: 'Airplane Arrival', icon: airplaneArrival});
openTravelPlacesTable.set('airplaneArrivalColor', {name: 'Airplane Arrival Color', icon: airplaneArrivalColor});
openTravelPlacesTable.set('airplaneDeparture', {name: 'Airplane Departure', icon: airplaneDeparture});
openTravelPlacesTable.set('airplaneDepartureColor', {name: 'Airplane Departure Color', icon: airplaneDepartureColor});
openTravelPlacesTable.set('flyingSaucer', {name: 'Flying Saucer', icon: flyingSaucer});
openTravelPlacesTable.set('flyingSaucerColor', {name: 'Flying Saucer Color', icon: flyingSaucerColor});
openTravelPlacesTable.set('helicopter', {name: 'Helicopter', icon: helicopter});
openTravelPlacesTable.set('helicopterColor', {name: 'Helicopter Color', icon: helicopterColor});
openTravelPlacesTable.set('mountainCableway', {name: 'Mountain Cableway', icon: mountainCableway});
openTravelPlacesTable.set('mountainCablewayColor', {name: 'Mountain Cableway Color', icon: mountainCablewayColor});
openTravelPlacesTable.set('parachute', {name: 'Parachute', icon: parachute});
openTravelPlacesTable.set('parachuteColor', {name: 'Parachute Color', icon: parachuteColor});
openTravelPlacesTable.set('rocket', {name: 'Rocket', icon: rocket});
openTravelPlacesTable.set('rocketColor', {name: 'Rocket Color', icon: rocketColor});
openTravelPlacesTable.set('satellite', {name: 'Satellite', icon: satellite});
openTravelPlacesTable.set('satelliteColor', {name: 'Satellite Color', icon: satelliteColor});
openTravelPlacesTable.set('seat', {name: 'Seat', icon: seat});
openTravelPlacesTable.set('seatColor', {name: 'Seat Color', icon: seatColor});
openTravelPlacesTable.set('smallAirplane', {name: 'Small Airplane', icon: smallAirplane});
openTravelPlacesTable.set('smallAirplaneColor', {name: 'Small Airplane Color', icon: smallAirplaneColor});
openTravelPlacesTable.set('suspensionRailway', {name: 'Suspension Railway', icon: suspensionRailway});
openTravelPlacesTable.set('suspensionRailwayColor', {name: 'Suspension Railway Color', icon: suspensionRailwayColor});
openTravelPlacesTable.set('ambulance', {name: 'Ambulance', icon: ambulance});
openTravelPlacesTable.set('ambulanceColor', {name: 'Ambulance Color', icon: ambulanceColor});
openTravelPlacesTable.set('articulatedLorry', {name: 'Articulated Lorry', icon: articulatedLorry});
openTravelPlacesTable.set('articulatedLorryColor', {name: 'Articulated Lorry', icon: articulatedLorryColor});
openTravelPlacesTable.set('automobile', {name: 'Automobile', icon: automobile});
openTravelPlacesTable.set('automobileColor', {name: 'Automobile Color', icon: automobileColor});
openTravelPlacesTable.set('autoRickshaw', {name: 'Auto Rickshaw', icon: autoRickshaw});
openTravelPlacesTable.set('autoRickshawColor', {name: 'Auto Rickshaw Color', icon: autoRickshawColor});
openTravelPlacesTable.set('bicycle', {name: 'Bicycle', icon: bicycle});
openTravelPlacesTable.set('bicycleColor', {name: 'Bicycle Color', icon: bicycleColor});
openTravelPlacesTable.set('bulletTrain', {name: 'Bullet Train', icon: bulletTrain});
openTravelPlacesTable.set('bulletTrainColor', {name: 'Bullet Train Color', icon: bulletTrainColor});
openTravelPlacesTable.set('bus', {name: 'Bus', icon: bus});
openTravelPlacesTable.set('busColor', {name: 'Bus Color', icon: busColor});
openTravelPlacesTable.set('busStop', {name: 'Bus Stop', icon: busStop});
openTravelPlacesTable.set('busStopColor', {name: 'Bus Stop Color', icon: busStopColor});
openTravelPlacesTable.set('construction', {name: 'Construction', icon: construction});
openTravelPlacesTable.set('constructionColor', {name: 'Construction Color', icon: constructionColor});
openTravelPlacesTable.set('deliveryTruck', {name: 'Delivery Truck', icon: deliveryTruck});
openTravelPlacesTable.set('deliveryTruckColor', {name: 'Delivery Truck Color', icon: deliveryTruckColor});
openTravelPlacesTable.set('fireEngine', {name: 'Fire Engine', icon: fireEngine});
openTravelPlacesTable.set('fireEngineColor', {name: 'Fire Engine Color', icon: fireEngineColor});
openTravelPlacesTable.set('fuelPump', {name: 'Fuel Pump', icon: fuelPump});
openTravelPlacesTable.set('fuelPumpColor', {name: 'Fuel Pump Color', icon: fuelPumpColor});
openTravelPlacesTable.set('highSpeedTrain', {name: 'High Speed Train', icon: highSpeedTrain});
openTravelPlacesTable.set('highSpeedTrainColor', {name: 'High Speed Train Color', icon: highSpeedTrainColor});
openTravelPlacesTable.set('horizontalTrafficLight', {name: 'Horizontal Traffic Light', icon: horizontalTrafficLight});
openTravelPlacesTable.set('horizontalTrafficLightColor', {
    name: 'Horizontal Traffic Light Color',
    icon: horizontalTrafficLightColor,
});
openTravelPlacesTable.set('kickScooter', {name: 'Kick Scooter', icon: kickScooter});
openTravelPlacesTable.set('kickScooterColor', {name: 'Kick Scooter Color', icon: kickScooterColor});
openTravelPlacesTable.set('lightRail', {name: 'Light Rail', icon: lightRail});
openTravelPlacesTable.set('lightRailColor', {name: 'Light Rail Color', icon: lightRailColor});
openTravelPlacesTable.set('locomotive', {name: 'Locomotive', icon: locomotive});
openTravelPlacesTable.set('locomotiveColor', {name: 'Locomotive Color', icon: locomotiveColor});
openTravelPlacesTable.set('manualWheelchair', {name: 'Manual Wheelchair', icon: manualWheelchair});
openTravelPlacesTable.set('manualWheelchairColor', {name: 'Manual Wheelchair Color', icon: manualWheelchairColor});
openTravelPlacesTable.set('metro', {name: 'Metro', icon: metro});
openTravelPlacesTable.set('metroColor', {name: 'Metro Color', icon: metroColor});
openTravelPlacesTable.set('minibus', {name: 'Minibus', icon: minibus});
openTravelPlacesTable.set('minibusColor', {name: 'Minibus Color', icon: minibusColor});
openTravelPlacesTable.set('monorail', {name: 'Monorail', icon: monorail});
openTravelPlacesTable.set('monorailColor', {name: 'Monorail Color', icon: monorailColor});
openTravelPlacesTable.set('motorcycle', {name: 'Motorcycle', icon: motorcycle});
openTravelPlacesTable.set('motorcycleColor', {name: 'Motorcycle Color', icon: motorcycleColor});
openTravelPlacesTable.set('motorizedWheelchair', {name: 'Motorized Wheelchair', icon: motorizedWheelchair});
openTravelPlacesTable.set('motorizedWheelchairColor', {
    name: 'Motorized Wheelchair Color',
    icon: motorizedWheelchairColor,
});
openTravelPlacesTable.set('motorScooter', {name: 'Motor Scooter', icon: motorScooter});
openTravelPlacesTable.set('motorScooterColor', {name: 'Motor Scooter Color', icon: motorScooterColor});
openTravelPlacesTable.set('motorway', {name: 'Motorway', icon: motorway});
openTravelPlacesTable.set('motorwayColor', {name: 'Motorway Color', icon: motorwayColor});
openTravelPlacesTable.set('mountainRailway', {name: 'Mountain Railway', icon: mountainRailway});
openTravelPlacesTable.set('mountainRailwayColor', {name: 'Mountain Railway Color', icon: mountainRailwayColor});
openTravelPlacesTable.set('oilDrum', {name: 'Oil Drum', icon: oilDrum});
openTravelPlacesTable.set('oilDrumColor', {name: 'Oil Drum Color', icon: oilDrumColor});
openTravelPlacesTable.set('oncomingAutomobile', {name: 'Oncoming Automobile', icon: oncomingAutomobile});
openTravelPlacesTable.set('oncomingAutomobileColor', {
    name: 'Oncoming Automobile Color',
    icon: oncomingAutomobileColor,
});
openTravelPlacesTable.set('oncomingBus', {name: 'Oncoming Bus', icon: oncomingBus});
openTravelPlacesTable.set('oncomingBusColor', {name: 'Oncoming Bus Color', icon: oncomingBusColor});
openTravelPlacesTable.set('oncomingPoliceCar', {name: 'Oncoming Police Car', icon: oncomingPoliceCar});
openTravelPlacesTable.set('oncomingPoliceCarColor', {name: 'Oncoming Police Car Color', icon: oncomingPoliceCarColor});
openTravelPlacesTable.set('oncomingTaxi', {name: 'Oncoming Taxi', icon: oncomingTaxi});
openTravelPlacesTable.set('oncomingTaxiColor', {name: 'Oncoming Taxi Color', icon: oncomingTaxiColor});
openTravelPlacesTable.set('pickupTruck', {name: 'Pickup Truck', icon: pickupTruck});
openTravelPlacesTable.set('pickupTruckColor', {name: 'Pickup Truck Color', icon: pickupTruckColor});
openTravelPlacesTable.set('policeCar', {name: 'Police Car', icon: policeCar});
openTravelPlacesTable.set('policeCarColor', {name: 'Police Car Color', icon: policeCarColor});
openTravelPlacesTable.set('policeCarLight', {name: 'Police Car Light', icon: policeCarLight});
openTravelPlacesTable.set('policeCarLightColor', {name: 'Police Car Light Color', icon: policeCarLightColor});
openTravelPlacesTable.set('racingCar', {name: 'Racing Car', icon: racingCar});
openTravelPlacesTable.set('racingCarColor', {name: 'Racing Car Color', icon: racingCarColor});
openTravelPlacesTable.set('railwayCar', {name: 'Railway Car', icon: railwayCar});
openTravelPlacesTable.set('railwayCarColor', {name: 'Railway Car Color', icon: railwayCarColor});
openTravelPlacesTable.set('railwayTrack', {name: 'Railway Track', icon: railwayTrack});
openTravelPlacesTable.set('railwayTrackColor', {name: 'Railway Track Color', icon: railwayTrackColor});
openTravelPlacesTable.set('rollerSkate', {name: 'Roller Skate', icon: rollerSkate});
openTravelPlacesTable.set('rollerSkateColor', {name: 'Roller Skate Color', icon: rollerSkateColor});
openTravelPlacesTable.set('skateboard', {name: 'Skateboard', icon: skateboard});
openTravelPlacesTable.set('skateboardColor', {name: 'Skateboard Color', icon: skateboardColor});
openTravelPlacesTable.set('sportUtilityVehicle', {name: 'Sport Utility Vehicle', icon: sportUtilityVehicle});
openTravelPlacesTable.set('sportUtilityVehicleColor', {
    name: 'Sport Utility Vehicle Color',
    icon: sportUtilityVehicleColor,
});
openTravelPlacesTable.set('station', {name: 'Station', icon: station});
openTravelPlacesTable.set('stationColor', {name: 'Station Color', icon: stationColor});
openTravelPlacesTable.set('stopSign', {name: 'Stop Sign', icon: stopSign});
openTravelPlacesTable.set('stopSignColor', {name: 'Stop Sign Color', icon: stopSignColor});
openTravelPlacesTable.set('taxi', {name: 'Taxi', icon: taxi});
openTravelPlacesTable.set('taxiColor', {name: 'Taxi Color', icon: taxiColor});
openTravelPlacesTable.set('tractor', {name: 'Tractor', icon: tractor});
openTravelPlacesTable.set('tractorColor', {name: 'Tractor Color', icon: tractorColor});
openTravelPlacesTable.set('train', {name: 'Train', icon: train});
openTravelPlacesTable.set('trainColor', {name: 'Train Color', icon: trainColor});
openTravelPlacesTable.set('tram', {name: 'Tram', icon: tram});
openTravelPlacesTable.set('tramColor', {name: 'Tram Color', icon: tramColor});
openTravelPlacesTable.set('trolleybus', {name: 'Trolleybus', icon: trolleybus});
openTravelPlacesTable.set('trolleybusColor', {name: 'Trolleybus Color', icon: trolleybusColor});
openTravelPlacesTable.set('verticalTrafficLight', {name: 'Vertical Traffic Light', icon: verticalTrafficLight});
openTravelPlacesTable.set('verticalTrafficLightColor', {
    name: 'Vertical Traffic Light Color',
    icon: verticalTrafficLightColor,
});
openTravelPlacesTable.set('wheel', {name: 'Wheel', icon: wheel});
openTravelPlacesTable.set('wheelColor', {name: 'Wheel Color', icon: wheelColor});
openTravelPlacesTable.set('anchor', {name: 'Anchor', icon: anchor});
openTravelPlacesTable.set('anchorColor', {name: 'Anchor Color', icon: anchorColor});
openTravelPlacesTable.set('canoe', {name: 'Canoe', icon: canoe});
openTravelPlacesTable.set('canoeColor', {name: 'Canoe Color', icon: canoeColor});
openTravelPlacesTable.set('ferry', {name: 'Ferry', icon: ferry});
openTravelPlacesTable.set('ferryColor', {name: 'Ferry Color', icon: ferryColor});
openTravelPlacesTable.set('motorBoat', {name: 'Motor Boat', icon: motorBoat});
openTravelPlacesTable.set('motorBoatColor', {name: 'Motor Boat Color', icon: motorBoatColor});
openTravelPlacesTable.set('passengerShip', {name: 'Passenger Ship', icon: passengerShip});
openTravelPlacesTable.set('passengerShipColor', {name: 'Passenger Ship Color', icon: passengerShipColor});
openTravelPlacesTable.set('ringBuoy', {name: 'Ring Buoy', icon: ringBuoy});
openTravelPlacesTable.set('ringBuoyColor', {name: 'Ring Buoy Color', icon: ringBuoyColor});
openTravelPlacesTable.set('sailboat', {name: 'Sailboat', icon: sailboat});
openTravelPlacesTable.set('sailboatColor', {name: 'Sailboat Color', icon: sailboatColor});
openTravelPlacesTable.set('ship', {name: 'Ship', icon: ship});
openTravelPlacesTable.set('shipColor', {name: 'Ship Color', icon: shipColor});
openTravelPlacesTable.set('speedboat', {name: 'Speedboat', icon: speedboat});
openTravelPlacesTable.set('speedboatColor', {name: 'Speedboat Color', icon: speedboatColor});

export const OPEN_TRAVEL_PLACES_ICON_SIZE = openTravelPlacesTable.size;
