import blueBook from './icons/objects/book-paper/blue-book.svg';
import blueBookColor from './icons/objects/book-paper/blue-book_color.svg';
import bookmark from './icons/objects/book-paper/bookmark.svg';
import bookmarkColor from './icons/objects/book-paper/bookmark_color.svg';
import bookmarkTabs from './icons/objects/book-paper/bookmark-tabs.svg';
import bookmarkTabsColor from './icons/objects/book-paper/bookmark-tabs_color.svg';
import books from './icons/objects/book-paper/books.svg';
import booksColor from './icons/objects/book-paper/books_color.svg';
import closedBook from './icons/objects/book-paper/closed-book.svg';
import closedBookColor from './icons/objects/book-paper/closed-book_color.svg';
import greenBook from './icons/objects/book-paper/green-book.svg';
import greenBookColor from './icons/objects/book-paper/green-book_color.svg';
import label from './icons/objects/book-paper/label.svg';
import labelColor from './icons/objects/book-paper/label_color.svg';
import ledger from './icons/objects/book-paper/ledger.svg';
import ledgerColor from './icons/objects/book-paper/ledger_color.svg';
import newspaper from './icons/objects/book-paper/newspaper.svg';
import newspaperColor from './icons/objects/book-paper/newspaper_color.svg';
import notebook from './icons/objects/book-paper/notebook.svg';
import notebookColor from './icons/objects/book-paper/notebook_color.svg';
import notebookWithDecorativeCover from './icons/objects/book-paper/notebook-with-decorative-cover.svg';
import notebookWithDecorativeCoverColor from './icons/objects/book-paper/notebook-with-decorative-cover_color.svg';
import openBook from './icons/objects/book-paper/open-book.svg';
import openBookColor from './icons/objects/book-paper/open-book_color.svg';
import orangeBook from './icons/objects/book-paper/orange-book.svg';
import orangeBookColor from './icons/objects/book-paper/orange-book_color.svg';
import pageFacingUp from './icons/objects/book-paper/page-facing-up.svg';
import pageFacingUpColor from './icons/objects/book-paper/page-facing-up_color.svg';
import pageWithCurl from './icons/objects/book-paper/page-with-curl.svg';
import pageWithCurlColor from './icons/objects/book-paper/page-with-curl_color.svg';
import rolledUpNewspaper from './icons/objects/book-paper/rolled-up-newspaper.svg';
import rolledUpNewspaperColor from './icons/objects/book-paper/rolled-up-newspaper_color.svg';
import scroll from './icons/objects/book-paper/scroll.svg';
import scrollColor from './icons/objects/book-paper/scroll_color.svg';
import backpack from './icons/objects/clothing/backpack.svg';
import backpackColor from './icons/objects/clothing/backpack_color.svg';
import balletShoes from './icons/objects/clothing/ballet-shoes.svg';
import balletShoesColor from './icons/objects/clothing/ballet-shoes_color.svg';
import bikini from './icons/objects/clothing/bikini.svg';
import bikiniColor from './icons/objects/clothing/bikini_color.svg';
import billedCap from './icons/objects/clothing/billed-cap.svg';
import billedCapColor from './icons/objects/clothing/billed-cap_color.svg';
import briefs from './icons/objects/clothing/briefs.svg';
import briefsColor from './icons/objects/clothing/briefs_color.svg';
import clutchBag from './icons/objects/clothing/clutch-bag.svg';
import clutchBagColor from './icons/objects/clothing/clutch-bag_color.svg';
import coat from './icons/objects/clothing/coat.svg';
import coatColor from './icons/objects/clothing/coat_color.svg';
import crown from './icons/objects/clothing/crown.svg';
import crownColor from './icons/objects/clothing/crown_color.svg';
import dress from './icons/objects/clothing/dress.svg';
import dressColor from './icons/objects/clothing/dress_color.svg';
import flatShoe from './icons/objects/clothing/flat-shoe.svg';
import flatShoeColor from './icons/objects/clothing/flat-shoe_color.svg';
import gemStone from './icons/objects/clothing/gem-stone.svg';
import gemStoneColor from './icons/objects/clothing/gem-stone_color.svg';
import glasses from './icons/objects/clothing/glasses.svg';
import glassesColor from './icons/objects/clothing/glasses_color.svg';
import gloves from './icons/objects/clothing/gloves.svg';
import glovesColor from './icons/objects/clothing/gloves_color.svg';
import goggles from './icons/objects/clothing/goggles.svg';
import gogglesColor from './icons/objects/clothing/goggles_color.svg';
import graduationCap from './icons/objects/clothing/graduation-cap.svg';
import graduationCapColor from './icons/objects/clothing/graduation-cap_color.svg';
import handbag from './icons/objects/clothing/handbag.svg';
import handbagColor from './icons/objects/clothing/handbag_color.svg';
import highHeeledShoe from './icons/objects/clothing/high-heeled-shoe.svg';
import highHeeledShoeColor from './icons/objects/clothing/high-heeled-shoe_color.svg';
import hikingBoot from './icons/objects/clothing/hiking-boot.svg';
import hikingBootColor from './icons/objects/clothing/hiking-boot_color.svg';
import jeans from './icons/objects/clothing/jeans.svg';
import jeansColor from './icons/objects/clothing/jeans_color.svg';
import kimono from './icons/objects/clothing/kimono.svg';
import kimonoColor from './icons/objects/clothing/kimono_color.svg';
import labCoat from './icons/objects/clothing/lab-coat.svg';
import labCoatColor from './icons/objects/clothing/lab-coat_color.svg';
import lipstick from './icons/objects/clothing/lipstick.svg';
import lipstickColor from './icons/objects/clothing/lipstick_color.svg';
import mansShoe from './icons/objects/clothing/manâs-shoe.svg';
import mansShoeColor from './icons/objects/clothing/manâs-shoe_color.svg';
import militaryHelmet from './icons/objects/clothing/military-helmet.svg';
import militaryHelmetColor from './icons/objects/clothing/military-helmet_color.svg';
import necktie from './icons/objects/clothing/necktie.svg';
import necktieColor from './icons/objects/clothing/necktie_color.svg';
import onePieceSwimsuit from './icons/objects/clothing/one-piece-swimsuit.svg';
import onePieceSwimsuitColor from './icons/objects/clothing/one-piece-swimsuit_color.svg';
import prayerBeads from './icons/objects/clothing/prayer-beads.svg';
import prayerBeadsColor from './icons/objects/clothing/prayer-beads_color.svg';
import purse from './icons/objects/clothing/purse.svg';
import purseColor from './icons/objects/clothing/purse_color.svg';
import rescueWorkersHelmet from './icons/objects/clothing/rescue-workerâs-helmet.svg';
import rescueWorkersHelmetColor from './icons/objects/clothing/rescue-workerâs-helmet_color.svg';
import ring from './icons/objects/clothing/ring.svg';
import ringColor from './icons/objects/clothing/ring_color.svg';
import runningShoe from './icons/objects/clothing/running-shoe.svg';
import runningShoeColor from './icons/objects/clothing/running-shoe_color.svg';
import safetyVest from './icons/objects/clothing/safety-vest.svg';
import safetyVestColor from './icons/objects/clothing/safety-vest_color.svg';
import sari from './icons/objects/clothing/sari.svg';
import sariColor from './icons/objects/clothing/sari_color.svg';
import scarf from './icons/objects/clothing/scarf.svg';
import scarfColor from './icons/objects/clothing/scarf_color.svg';
import shoppingBags from './icons/objects/clothing/shopping-bags.svg';
import shoppingBagsColor from './icons/objects/clothing/shopping-bags_color.svg';
import shorts from './icons/objects/clothing/shorts.svg';
import shortsColor from './icons/objects/clothing/shorts_color.svg';
import socks from './icons/objects/clothing/socks.svg';
import socksColor from './icons/objects/clothing/socks_color.svg';
import sunglasses from './icons/objects/clothing/sunglasses.svg';
import sunglassesColor from './icons/objects/clothing/sunglasses_color.svg';
import thongSandal from './icons/objects/clothing/thong-sandal.svg';
import thongSandalColor from './icons/objects/clothing/thong-sandal_color.svg';
import topHat from './icons/objects/clothing/top-hat.svg';
import topHatColor from './icons/objects/clothing/top-hat_color.svg';
import tShirt from './icons/objects/clothing/t-shirt.svg';
import tShirtColor from './icons/objects/clothing/t-shirt_color.svg';
import womansBoot from './icons/objects/clothing/womanâs-boot.svg';
import womansBootColor from './icons/objects/clothing/womanâs-boot_color.svg';
import womansClothes from './icons/objects/clothing/womanâs-clothes.svg';
import womansClothesColor from './icons/objects/clothing/womanâs-clothes_color.svg';
import womansHat from './icons/objects/clothing/womanâs-hat.svg';
import womansHatColor from './icons/objects/clothing/womanâs-hat_color.svg';
import womansSandal from './icons/objects/clothing/womanâs-sandal.svg';
import womansSandalColor from './icons/objects/clothing/womanâs-sandal_color.svg';
import abacus from './icons/objects/computer/abacus.svg';
import abacusColor from './icons/objects/computer/abacus_color.svg';
import battery from './icons/objects/computer/battery.svg';
import batteryColor from './icons/objects/computer/battery_color.svg';
import computerDisk from './icons/objects/computer/computer-disk.svg';
import computerDiskColor from './icons/objects/computer/computer-disk_color.svg';
import computerMouse from './icons/objects/computer/computer-mouse.svg';
import computerMouseColor from './icons/objects/computer/computer-mouse_color.svg';
import desktopComputer from './icons/objects/computer/desktop-computer.svg';
import desktopComputerColor from './icons/objects/computer/desktop-computer_color.svg';
import dvd from './icons/objects/computer/dvd.svg';
import dvdColor from './icons/objects/computer/dvd_color.svg';
import electricPlug from './icons/objects/computer/electric-plug.svg';
import electricPlugColor from './icons/objects/computer/electric-plug_color.svg';
import floppyDisk from './icons/objects/computer/floppy-disk.svg';
import floppyDiskColor from './icons/objects/computer/floppy-disk_color.svg';
import keyboard from './icons/objects/computer/keyboard.svg';
import keyboardColor from './icons/objects/computer/keyboard_color.svg';
import laptop from './icons/objects/computer/laptop.svg';
import laptopColor from './icons/objects/computer/laptop_color.svg';
import lowBattery from './icons/objects/computer/low-battery.svg';
import lowBatteryColor from './icons/objects/computer/low-battery_color.svg';
import opticalDisk from './icons/objects/computer/optical-disk.svg';
import opticalDiskColor from './icons/objects/computer/optical-disk_color.svg';
import printer from './icons/objects/computer/printer.svg';
import printerColor from './icons/objects/computer/printer_color.svg';
import trackball from './icons/objects/computer/trackball.svg';
import trackballColor from './icons/objects/computer/trackball_color.svg';
import basket from './icons/objects/household/basket.svg';
import basketColor from './icons/objects/household/basket_color.svg';
import bathtub from './icons/objects/household/bathtub.svg';
import bathtubColor from './icons/objects/household/bathtub_color.svg';
import bed from './icons/objects/household/bed.svg';
import bedColor from './icons/objects/household/bed_color.svg';
import broom from './icons/objects/household/broom.svg';
import broomColor from './icons/objects/household/broom_color.svg';
import bubbles from './icons/objects/household/bubbles.svg';
import bubblesColor from './icons/objects/household/bubbles_color.svg';
import bucket from './icons/objects/household/bucket.svg';
import bucketColor from './icons/objects/household/bucket_color.svg';
import chair from './icons/objects/household/chair.svg';
import chairColor from './icons/objects/household/chair_color.svg';
import couchAndLamp from './icons/objects/household/couch-and-lamp.svg';
import couchAndLampColor from './icons/objects/household/couch-and-lamp_color.svg';
import door from './icons/objects/household/door.svg';
import doorColor from './icons/objects/household/door_color.svg';
import elevator from './icons/objects/household/elevator.svg';
import elevatorColor from './icons/objects/household/elevator_color.svg';
import fireExtinguisher from './icons/objects/household/fire-extinguisher.svg';
import fireExtinguisherColor from './icons/objects/household/fire-extinguisher_color.svg';
import lotionBottle from './icons/objects/household/lotion-bottle.svg';
import lotionBottleColor from './icons/objects/household/lotion-bottle_color.svg';
import mirror from './icons/objects/household/mirror.svg';
import mirrorColor from './icons/objects/household/mirror_color.svg';
import mouseTrap from './icons/objects/household/mouse-trap.svg';
import mouseTrapColor from './icons/objects/household/mouse-trap_color.svg';
import plunger from './icons/objects/household/plunger.svg';
import plungerColor from './icons/objects/household/plunger_color.svg';
import razor from './icons/objects/household/razor.svg';
import razorColor from './icons/objects/household/razor_color.svg';
import rollOfPaper from './icons/objects/household/roll-of-paper.svg';
import rollOfPaperColor from './icons/objects/household/roll-of-paper_color.svg';
import safetyPin from './icons/objects/household/safety-pin.svg';
import safetyPinColor from './icons/objects/household/safety-pin_color.svg';
import shoppingCart from './icons/objects/household/shopping-cart.svg';
import shoppingCartColor from './icons/objects/household/shopping-cart_color.svg';
import shower from './icons/objects/household/shower.svg';
import showerColor from './icons/objects/household/shower_color.svg';
import soap from './icons/objects/household/soap.svg';
import soapColor from './icons/objects/household/soap_color.svg';
import sponge from './icons/objects/household/sponge.svg';
import spongeColor from './icons/objects/household/sponge_color.svg';
import toilet from './icons/objects/household/toilet.svg';
import toiletColor from './icons/objects/household/toilet_color.svg';
import toothbrush from './icons/objects/household/toothbrush.svg';
import toothbrushColor from './icons/objects/household/toothbrush_color.svg';
import window from './icons/objects/household/window.svg';
import windowColor from './icons/objects/household/window_color.svg';
import camera from './icons/objects/light-video/camera.svg';
import cameraColor from './icons/objects/light-video/camera_color.svg';
import cameraWithFlash from './icons/objects/light-video/camera-with-flash.svg';
import cameraWithFlashColor from './icons/objects/light-video/camera-with-flash_color.svg';
import candle from './icons/objects/light-video/candle.svg';
import candleColor from './icons/objects/light-video/candle_color.svg';
import clapperBoard from './icons/objects/light-video/clapper-board.svg';
import clapperBoardColor from './icons/objects/light-video/clapper-board_color.svg';
import diyaLamp from './icons/objects/light-video/diya-lamp.svg';
import diyaLampColor from './icons/objects/light-video/diya-lamp_color.svg';
import filmFrames from './icons/objects/light-video/film-frames.svg';
import filmFramesColor from './icons/objects/light-video/film-frames_color.svg';
import filmProjector from './icons/objects/light-video/film-projector.svg';
import filmProjectorColor from './icons/objects/light-video/film-projector_color.svg';
import flashlight from './icons/objects/light-video/flashlight.svg';
import flashlightColor from './icons/objects/light-video/flashlight_color.svg';
import lightBulb from './icons/objects/light-video/light-bulb.svg';
import lightBulbColor from './icons/objects/light-video/light-bulb_color.svg';
import magnifyingGlassTiltedLeft from './icons/objects/light-video/magnifying-glass-tilted-left.svg';
import magnifyingGlassTiltedLeftColor from './icons/objects/light-video/magnifying-glass-tilted-left_color.svg';
import magnifyingGlassTiltedRight from './icons/objects/light-video/magnifying-glass-tilted-right.svg';
import magnifyingGlassTiltedRightColor from './icons/objects/light-video/magnifying-glass-tilted-right_color.svg';
import movieCamera from './icons/objects/light-video/movie-camera.svg';
import movieCameraColor from './icons/objects/light-video/movie-camera_color.svg';
import redPaperLantern from './icons/objects/light-video/red-paper-lantern.svg';
import redPaperLanternColor from './icons/objects/light-video/red-paper-lantern_color.svg';
import television from './icons/objects/light-video/television.svg';
import televisionColor from './icons/objects/light-video/television_color.svg';
import videoCamera from './icons/objects/light-video/video-camera.svg';
import videoCameraColor from './icons/objects/light-video/video-camera_color.svg';
import videocassette from './icons/objects/light-video/videocassette.svg';
import videocassetteColor from './icons/objects/light-video/videocassette_color.svg';
import key from './icons/objects/lock/key.svg';
import keyColor from './icons/objects/lock/key_color.svg';
import locked from './icons/objects/lock/locked.svg';
import lockedColor from './icons/objects/lock/locked_color.svg';
import lockedWithKey from './icons/objects/lock/locked-with-key.svg';
import lockedWithKeyColor from './icons/objects/lock/locked-with-key_color.svg';
import lockedWithPen from './icons/objects/lock/locked-with-pen.svg';
import lockedWithPenColor from './icons/objects/lock/locked-with-pen_color.svg';
import oldKey from './icons/objects/lock/old-key.svg';
import oldKeyColor from './icons/objects/lock/old-key_color.svg';
import unlocked from './icons/objects/lock/unlocked.svg';
import unlockedColor from './icons/objects/lock/unlocked_color.svg';
import ballotBoxWithBallot from './icons/objects/mail/ballot-box-with-ballot.svg';
import ballotBoxWithBallotColor from './icons/objects/mail/ballot-box-with-ballot_color.svg';
import closedMailboxWithLoweredFlag from './icons/objects/mail/closed-mailbox-with-lowered-flag.svg';
import closedMailboxWithLoweredFlagColor from './icons/objects/mail/closed-mailbox-with-lowered-flag_color.svg';
import closedMailboxWithRaisedFlag from './icons/objects/mail/closed-mailbox-with-raised-flag.svg';
import closedMailboxWithRaisedFlagColor from './icons/objects/mail/closed-mailbox-with-raised-flag_color.svg';
import eMail from './icons/objects/mail/e-mail.svg';
import eMailColor from './icons/objects/mail/e-mail_color.svg';
import envelope from './icons/objects/mail/envelope.svg';
import envelopeColor from './icons/objects/mail/envelope_color.svg';
import envelopeWithArrow from './icons/objects/mail/envelope-with-arrow.svg';
import envelopeWithArrowColor from './icons/objects/mail/envelope-with-arrow_color.svg';
import inboxTray from './icons/objects/mail/inbox-tray.svg';
import inboxTrayColor from './icons/objects/mail/inbox-tray_color.svg';
import incomingEnvelope from './icons/objects/mail/incoming-envelope.svg';
import incomingEnvelopeColor from './icons/objects/mail/incoming-envelope_color.svg';
import openMailboxWithLoweredFlag from './icons/objects/mail/open-mailbox-with-lowered-flag.svg';
import openMailboxWithLoweredFlagColor from './icons/objects/mail/open-mailbox-with-lowered-flag_color.svg';
import openMailboxWithRaisedFlag from './icons/objects/mail/open-mailbox-with-raised-flag.svg';
import openMailboxWithRaisedFlagColor from './icons/objects/mail/open-mailbox-with-raised-flag_color.svg';
import outboxTray from './icons/objects/mail/outbox-tray.svg';
import outboxTrayColor from './icons/objects/mail/outbox-tray_color.svg';
import openPackage from './icons/objects/mail/package.svg';
import openPackageColor from './icons/objects/mail/package_color.svg';
import postbox from './icons/objects/mail/postbox.svg';
import postboxColor from './icons/objects/mail/postbox_color.svg';
import adhesiveBandage from './icons/objects/medical/adhesive-bandage.svg';
import adhesiveBandageColor from './icons/objects/medical/adhesive-bandage_color.svg';
import crutch from './icons/objects/medical/crutch.svg';
import crutchColor from './icons/objects/medical/crutch_color.svg';
import dropOfBlood from './icons/objects/medical/drop-of-blood.svg';
import dropOfBloodColor from './icons/objects/medical/drop-of-blood_color.svg';
import pill from './icons/objects/medical/pill.svg';
import pillColor from './icons/objects/medical/pill_color.svg';
import stethoscope from './icons/objects/medical/stethoscope.svg';
import stethoscopeColor from './icons/objects/medical/stethoscope_color.svg';
import syringe from './icons/objects/medical/syringe.svg';
import syringeColor from './icons/objects/medical/syringe_color.svg';
import xRay from './icons/objects/medical/x-ray.svg';
import xRayColor from './icons/objects/medical/x-ray_color.svg';
import chartIncreasingWithYen from './icons/objects/money/chart-increasing-with-yen.svg';
import chartIncreasingWithYenColor from './icons/objects/money/chart-increasing-with-yen_color.svg';
import coin from './icons/objects/money/coin.svg';
import coinColor from './icons/objects/money/coin_color.svg';
import creditCard from './icons/objects/money/credit-card.svg';
import creditCardColor from './icons/objects/money/credit-card_color.svg';
import dollarBanknote from './icons/objects/money/dollar-banknote.svg';
import dollarBanknoteColor from './icons/objects/money/dollar-banknote_color.svg';
import euroBanknote from './icons/objects/money/euro-banknote.svg';
import euroBanknoteColor from './icons/objects/money/euro-banknote_color.svg';
import moneyBag from './icons/objects/money/money-bag.svg';
import moneyBagColor from './icons/objects/money/money-bag_color.svg';
import moneyWithWings from './icons/objects/money/money-with-wings.svg';
import moneyWithWingsColor from './icons/objects/money/money-with-wings_color.svg';
import poundBanknote from './icons/objects/money/pound-banknote.svg';
import poundBanknoteColor from './icons/objects/money/pound-banknote_color.svg';
import receipt from './icons/objects/money/receipt.svg';
import receiptColor from './icons/objects/money/receipt_color.svg';
import yenBanknote from './icons/objects/money/yen-banknote.svg';
import yenBanknoteColor from './icons/objects/money/yen-banknote_color.svg';
import controlKnobs from './icons/objects/music/control-knobs.svg';
import controlKnobsColor from './icons/objects/music/control-knobs_color.svg';
import headphone from './icons/objects/music/headphone.svg';
import headphoneColor from './icons/objects/music/headphone_color.svg';
import levelSlider from './icons/objects/music/level-slider.svg';
import levelSliderColor from './icons/objects/music/level-slider_color.svg';
import microphone from './icons/objects/music/microphone.svg';
import microphoneColor from './icons/objects/music/microphone_color.svg';
import musicalNote from './icons/objects/music/musical-note.svg';
import musicalNoteColor from './icons/objects/music/musical-note_color.svg';
import musicalNotes from './icons/objects/music/musical-notes.svg';
import musicalNotesColor from './icons/objects/music/musical-notes_color.svg';
import musicalScore from './icons/objects/music/musical-score.svg';
import musicalScoreColor from './icons/objects/music/musical-score_color.svg';
import radio from './icons/objects/music/radio.svg';
import radioColor from './icons/objects/music/radio_color.svg';
import studioMicrophone from './icons/objects/music/studio-microphone.svg';
import studioMicrophoneColor from './icons/objects/music/studio-microphone_color.svg';
import accordion from './icons/objects/musical-instrument/accordion.svg';
import accordionColor from './icons/objects/musical-instrument/accordion_color.svg';
import banjo from './icons/objects/musical-instrument/banjo.svg';
import banjoColor from './icons/objects/musical-instrument/banjo_color.svg';
import drum from './icons/objects/musical-instrument/drum.svg';
import drumColor from './icons/objects/musical-instrument/drum_color.svg';
import guitar from './icons/objects/musical-instrument/guitar.svg';
import guitarColor from './icons/objects/musical-instrument/guitar_color.svg';
import longDrum from './icons/objects/musical-instrument/long-drum.svg';
import longDrumColor from './icons/objects/musical-instrument/long-drum_color.svg';
import musicalKeyboard from './icons/objects/musical-instrument/musical-keyboard.svg';
import musicalKeyboardColor from './icons/objects/musical-instrument/musical-keyboard_color.svg';
import saxophone from './icons/objects/musical-instrument/saxophone.svg';
import saxophoneColor from './icons/objects/musical-instrument/saxophone_color.svg';
import trumpet from './icons/objects/musical-instrument/trumpet.svg';
import trumpetColor from './icons/objects/musical-instrument/trumpet_color.svg';
import violin from './icons/objects/musical-instrument/violin.svg';
import violinColor from './icons/objects/musical-instrument/violin_color.svg';
import barChart from './icons/objects/office/bar-chart.svg';
import barChartColor from './icons/objects/office/bar-chart_color.svg';
import briefcase from './icons/objects/office/briefcase.svg';
import briefcaseColor from './icons/objects/office/briefcase_color.svg';
import calendar from './icons/objects/office/calendar.svg';
import calendarColor from './icons/objects/office/calendar_color.svg';
import cardFileBox from './icons/objects/office/card-file-box.svg';
import cardFileBoxColor from './icons/objects/office/card-file-box_color.svg';
import cardIndex from './icons/objects/office/card-index.svg';
import cardIndexColor from './icons/objects/office/card-index_color.svg';
import cardIndexDividers from './icons/objects/office/card-index-dividers.svg';
import cardIndexDividersColor from './icons/objects/office/card-index-dividers_color.svg';
import chartDecreasing from './icons/objects/office/chart-decreasing.svg';
import chartDecreasingColor from './icons/objects/office/chart-decreasing_color.svg';
import chartIncreasing from './icons/objects/office/chart-increasing.svg';
import chartIncreasingColor from './icons/objects/office/chart-increasing_color.svg';
import clipboard from './icons/objects/office/clipboard.svg';
import clipboardColor from './icons/objects/office/clipboard_color.svg';
import fileCabinet from './icons/objects/office/file-cabinet.svg';
import fileCabinetColor from './icons/objects/office/file-cabinet_color.svg';
import fileFolder from './icons/objects/office/file-folder.svg';
import fileFolderColor from './icons/objects/office/file-folder_color.svg';
import linkedPaperclips from './icons/objects/office/linked-paperclips.svg';
import linkedPaperclipsColor from './icons/objects/office/linked-paperclips_color.svg';
import openFileFolder from './icons/objects/office/open-file-folder.svg';
import openFileFolderColor from './icons/objects/office/open-file-folder.svg';
import paperclip from './icons/objects/office/paperclip.svg';
import paperclipColor from './icons/objects/office/paperclip_color.svg';
import pushpin from './icons/objects/office/pushpin.svg';
import pushpinColor from './icons/objects/office/pushpin_color.svg';
import roundPushpin from './icons/objects/office/round-pushpin.svg';
import roundPushpinColor from './icons/objects/office/round-pushpin_color.svg';
import scissors from './icons/objects/office/scissors.svg';
import scissorsColor from './icons/objects/office/scissors_color.svg';
import spiralCalendar from './icons/objects/office/spiral-calendar.svg';
import spiralCalendarColor from './icons/objects/office/spiral-calendar_color.svg';
import spiralNotepad from './icons/objects/office/spiral-notepad.svg';
import spiralNotepadColor from './icons/objects/office/spiral-notepad_color.svg';
import straightRuler from './icons/objects/office/straight-ruler.svg';
import straightRulerColor from './icons/objects/office/straight-ruler_color.svg';
import tearOffCalendar from './icons/objects/office/tear-off-calendar.svg';
import tearOffCalendarColor from './icons/objects/office/tear-off-calendar_color.svg';
import triangularRuler from './icons/objects/office/triangular-ruler.svg';
import triangularRulerColor from './icons/objects/office/triangular-ruler_color.svg';
import wastebasket from './icons/objects/office/wastebasket.svg';
import wastebasketColor from './icons/objects/office/wastebasket_color.svg';
import cigarette from './icons/objects/other-object/cigarette.svg';
import cigaretteColor from './icons/objects/other-object/cigarette_color.svg';
import coffin from './icons/objects/other-object/coffin.svg';
import coffinColor from './icons/objects/other-object/coffin_color.svg';
import funeralUrn from './icons/objects/other-object/funeral-urn.svg';
import funeralUrnColor from './icons/objects/other-object/funeral-urn_color.svg';
import headstone from './icons/objects/other-object/headstone.svg';
import headstoneColor from './icons/objects/other-object/headstone_color.svg';
import identificationCard from './icons/objects/other-object/identification-card.svg';
import identificationCardColor from './icons/objects/other-object/identification-card_color.svg';
import moai from './icons/objects/other-object/moai.svg';
import moaiColor from './icons/objects/other-object/moai_color.svg';
import placard from './icons/objects/other-object/placard.svg';
import placardColor from './icons/objects/other-object/placard_color.svg';
import faxMachine from './icons/objects/phone/fax-machine.svg';
import faxMachineColor from './icons/objects/phone/fax-machine_color.svg';
import mobilePhone from './icons/objects/phone/mobile-phone.svg';
import mobilePhoneColor from './icons/objects/phone/mobile-phone_color.svg';
import mobilePhoneWithArrow from './icons/objects/phone/mobile-phone-with-arrow.svg';
import mobilePhoneWithArrowColor from './icons/objects/phone/mobile-phone-with-arrow_color.svg';
import pager from './icons/objects/phone/pager.svg';
import pagerColor from './icons/objects/phone/pager_color.svg';
import telephone from './icons/objects/phone/telephone.svg';
import telephoneColor from './icons/objects/phone/telephone_color.svg';
import telephoneReceiver from './icons/objects/phone/telephone-receiver.svg';
import telephoneReceiverColor from './icons/objects/phone/telephone-receiver_color.svg';
import alembic from './icons/objects/science/alembic.svg';
import alembicColor from './icons/objects/science/alembic_color.svg';
import dna from './icons/objects/science/dna.svg';
import dnaColor from './icons/objects/science/dna_color.svg';
import microscope from './icons/objects/science/microscope.svg';
import microscopeColor from './icons/objects/science/microscope_color.svg';
import petriDish from './icons/objects/science/petri-dish.svg';
import petriDishColor from './icons/objects/science/petri-dish_color.svg';
import satelliteAntenna from './icons/objects/science/satellite-antenna.svg';
import satelliteAntennaColor from './icons/objects/science/satellite-antenna_color.svg';
import telescope from './icons/objects/science/telescope.svg';
import telescopeColor from './icons/objects/science/telescope_color.svg';
import testTube from './icons/objects/science/test-tube.svg';
import testTubeColor from './icons/objects/science/test-tube_color.svg';
import bell from './icons/objects/sound/bell.svg';
import bellColor from './icons/objects/sound/bell_color.svg';
import bellWithSlash from './icons/objects/sound/bell-with-slash.svg';
import bellWithSlashColor from './icons/objects/sound/bell-with-slash_color.svg';
import loudspeaker from './icons/objects/sound/loudspeaker.svg';
import loudspeakerColor from './icons/objects/sound/loudspeaker_color.svg';
import megaphone from './icons/objects/sound/megaphone.svg';
import megaphoneColor from './icons/objects/sound/megaphone_color.svg';
import mutedSpeaker from './icons/objects/sound/muted-speaker.svg';
import mutedSpeakerColor from './icons/objects/sound/muted-speaker_color.svg';
import postalHorn from './icons/objects/sound/postal-horn.svg';
import postalHornColor from './icons/objects/sound/postal-horn_color.svg';
import speakerHighVolume from './icons/objects/sound/speaker-high-volume.svg';
import speakerHighVolumeColor from './icons/objects/sound/speaker-high-volume_color.svg';
import speakerLowVolume from './icons/objects/sound/speaker-low-volume.svg';
import speakerLowVolumeColor from './icons/objects/sound/speaker-low-volume_color.svg';
import speakerMediumVolume from './icons/objects/sound/speaker-medium-volume.svg';
import speakerMediumVolumeColor from './icons/objects/sound/speaker-medium-volume_color.svg';
import axe from './icons/objects/tool/axe.svg';
import axeColor from './icons/objects/tool/axe_color.svg';
import balanceScale from './icons/objects/tool/balance-scale.svg';
import balanceScaleColor from './icons/objects/tool/balance-scale_color.svg';
import boomerang from './icons/objects/tool/boomerang.svg';
import boomerangColor from './icons/objects/tool/boomerang_color.svg';
import bowAndArrow from './icons/objects/tool/bow-and-arrow.svg';
import bowAndArrowColor from './icons/objects/tool/bow-and-arrow_color.svg';
import carpentrySaw from './icons/objects/tool/carpentry-saw.svg';
import carpentrySawColor from './icons/objects/tool/carpentry-saw_color.svg';
import chains from './icons/objects/tool/chains.svg';
import chainsColor from './icons/objects/tool/chains_color.svg';
import clamp from './icons/objects/tool/clamp.svg';
import clampColor from './icons/objects/tool/clamp_color.svg';
import crossedSwords from './icons/objects/tool/crossed-swords.svg';
import crossedSwordsColor from './icons/objects/tool/crossed-swords_color.svg';
import dagger from './icons/objects/tool/dagger.svg';
import daggerColor from './icons/objects/tool/dagger_color.svg';
import gear from './icons/objects/tool/gear.svg';
import gearColor from './icons/objects/tool/gear_color.svg';
import hammer from './icons/objects/tool/hammer.svg';
import hammerColor from './icons/objects/tool/hammer_color.svg';
import hammerAndPick from './icons/objects/tool/hammer-and-pick.svg';
import hammerAndPickColor from './icons/objects/tool/hammer-and-pick_color.svg';
import hammerAndWrench from './icons/objects/tool/hammer-and-wrench.svg';
import hammerAndWrenchColor from './icons/objects/tool/hammer-and-wrench_color.svg';
import hook from './icons/objects/tool/hook.svg';
import hookColor from './icons/objects/tool/hook_color.svg';
import ladder from './icons/objects/tool/ladder.svg';
import ladderColor from './icons/objects/tool/ladder_color.svg';
import link from './icons/objects/tool/link.svg';
import linkColor from './icons/objects/tool/link_color.svg';
import magnet from './icons/objects/tool/magnet.svg';
import magnetColor from './icons/objects/tool/magnet_color.svg';
import nutAndBolt from './icons/objects/tool/nut-and-bolt.svg';
import nutAndBoltColor from './icons/objects/tool/nut-and-bolt_color.svg';
import pick from './icons/objects/tool/pick.svg';
import pickColor from './icons/objects/tool/pick_color.svg';
import screwdriver from './icons/objects/tool/screwdriver.svg';
import screwdriverColor from './icons/objects/tool/screwdriver_color.svg';
import shield from './icons/objects/tool/shield.svg';
import shieldColor from './icons/objects/tool/shield_color.svg';
import toolbox from './icons/objects/tool/toolbox.svg';
import toolboxColor from './icons/objects/tool/toolbox_color.svg';
import waterPistol from './icons/objects/tool/water-pistol.svg';
import waterPistolColor from './icons/objects/tool/water-pistol_color.svg';
import whiteCane from './icons/objects/tool/white-cane.svg';
import whiteCaneColor from './icons/objects/tool/white-cane_color.svg';
import wrench from './icons/objects/tool/wrench.svg';
import wrenchColor from './icons/objects/tool/wrench_color.svg';
import blackNib from './icons/objects/writing/black-nib.svg';
import blackNibColor from './icons/objects/writing/black-nib_color.svg';
import crayon from './icons/objects/writing/crayon.svg';
import crayonColor from './icons/objects/writing/crayon_color.svg';
import fountainPen from './icons/objects/writing/fountain-pen.svg';
import fountainPenColor from './icons/objects/writing/fountain-pen_color.svg';
import memo from './icons/objects/writing/memo.svg';
import memoColor from './icons/objects/writing/memo_color.svg';
import paintbrush from './icons/objects/writing/paintbrush.svg';
import paintbrushColor from './icons/objects/writing/paintbrush_color.svg';
import pen from './icons/objects/writing/pen.svg';
import penColor from './icons/objects/writing/pen_color.svg';
import pencil from './icons/objects/writing/pencil.svg';
import pencilColor from './icons/objects/writing/pencil_color.svg';

import {IconProps} from './use-search';

export const openObjectsTable = new Map<string, Omit<IconProps, 'id'>>();

openObjectsTable.set('blueBook', {name: 'Blue Book', icon: blueBook});
openObjectsTable.set('blueBookColor', {name: 'Blue Book Color', icon: blueBookColor});
openObjectsTable.set('bookmark', {name: 'Bookmark', icon: bookmark});
openObjectsTable.set('bookmarkColor', {name: 'Bookmark Color', icon: bookmarkColor});
openObjectsTable.set('bookmarkTabs', {name: 'Bookmark Tabs', icon: bookmarkTabs});
openObjectsTable.set('bookmarkTabsColor', {name: 'Bookmark Tabs Color', icon: bookmarkTabsColor});
openObjectsTable.set('books', {name: 'Books', icon: books});
openObjectsTable.set('booksColor', {name: 'Books Color', icon: booksColor});
openObjectsTable.set('closedBook', {name: 'Closed Book', icon: closedBook});
openObjectsTable.set('closedBookColor', {name: 'Closed Book Color', icon: closedBookColor});
openObjectsTable.set('greenBook', {name: 'Green Book', icon: greenBook});
openObjectsTable.set('greenBookColor', {name: 'Green Book Color', icon: greenBookColor});
openObjectsTable.set('label', {name: 'Label', icon: label});
openObjectsTable.set('labelColor', {name: 'Label Color', icon: labelColor});
openObjectsTable.set('ledger', {name: 'Ledger', icon: ledger});
openObjectsTable.set('ledgerColor', {name: 'Ledger Color', icon: ledgerColor});
openObjectsTable.set('newspaper', {name: 'Newspaper', icon: newspaper});
openObjectsTable.set('newspaperColor', {name: 'Newspaper Color', icon: newspaperColor});
openObjectsTable.set('notebook', {name: 'Notebook', icon: notebook});
openObjectsTable.set('notebookColor', {name: 'Notebook Color', icon: notebookColor});
openObjectsTable.set('notebookWithDecorativeCover', {
    name: 'Notebook With Decorative Cover',
    icon: notebookWithDecorativeCover,
});
openObjectsTable.set('notebookWithDecorativeCoverColor', {
    name: 'Notebook With Decorative Cover Color',
    icon: notebookWithDecorativeCoverColor,
});
openObjectsTable.set('openBook', {name: 'Open Book', icon: openBook});
openObjectsTable.set('openBookColor', {name: 'Open Book Color', icon: openBookColor});
openObjectsTable.set('orangeBook', {name: 'Orange Book', icon: orangeBook});
openObjectsTable.set('orangeBookColor', {name: 'Orange Book Color', icon: orangeBookColor});
openObjectsTable.set('pageFacingUp', {name: 'Page Facing Up', icon: pageFacingUp});
openObjectsTable.set('pageFacingUpColor', {name: 'Page Facing Up Color', icon: pageFacingUpColor});
openObjectsTable.set('pageWithCurl', {name: 'Page With Curl', icon: pageWithCurl});
openObjectsTable.set('pageWithCurlColor', {name: 'Page With Curl Color', icon: pageWithCurlColor});
openObjectsTable.set('rolledUpNewspaper', {name: 'Rolled Up Newspaper', icon: rolledUpNewspaper});
openObjectsTable.set('rolledUpNewspaperColor', {name: 'Rolled Up Newspaper Color', icon: rolledUpNewspaperColor});
openObjectsTable.set('scroll', {name: 'Scroll', icon: scroll});
openObjectsTable.set('scrollColor', {name: 'Scroll Color', icon: scrollColor});
openObjectsTable.set('backpack', {name: 'Backpack', icon: backpack});
openObjectsTable.set('backpackColor', {name: 'Backpack Color', icon: backpackColor});
openObjectsTable.set('balletShoes', {name: 'Ballet Shoes', icon: balletShoes});
openObjectsTable.set('balletShoesColor', {name: 'Ballet Shoes Color', icon: balletShoesColor});
openObjectsTable.set('bikini', {name: 'Bikini', icon: bikini});
openObjectsTable.set('bikiniColor', {name: 'Bikini Color', icon: bikiniColor});
openObjectsTable.set('billedCap', {name: 'Billed Cap', icon: billedCap});
openObjectsTable.set('billedCapColor', {name: 'Billed Cap Color', icon: billedCapColor});
openObjectsTable.set('briefs', {name: 'Briefs', icon: briefs});
openObjectsTable.set('briefsColor', {name: 'Briefs Color', icon: briefsColor});
openObjectsTable.set('clutchBag', {name: 'Clutch Bag', icon: clutchBag});
openObjectsTable.set('clutchBagColor', {name: 'Clutch Bag Color', icon: clutchBagColor});
openObjectsTable.set('coat', {name: 'Coat', icon: coat});
openObjectsTable.set('coatColor', {name: 'Coat Color', icon: coatColor});
openObjectsTable.set('crown', {name: 'Crown', icon: crown});
openObjectsTable.set('crownColor', {name: 'Crown Color', icon: crownColor});
openObjectsTable.set('dress', {name: 'Dress', icon: dress});
openObjectsTable.set('dressColor', {name: 'Dress Color', icon: dressColor});
openObjectsTable.set('flatShoe', {name: 'Flat Shoe', icon: flatShoe});
openObjectsTable.set('flatShoeColor', {name: 'Flat Shoe Color', icon: flatShoeColor});
openObjectsTable.set('gemStone', {name: 'Gem Stone', icon: gemStone});
openObjectsTable.set('gemStoneColor', {name: 'Gem Stone Color', icon: gemStoneColor});
openObjectsTable.set('glasses', {name: 'Glasses', icon: glasses});
openObjectsTable.set('glassesColor', {name: 'Glasses Color', icon: glassesColor});
openObjectsTable.set('gloves', {name: 'Gloves', icon: gloves});
openObjectsTable.set('glovesColor', {name: 'Gloves Color', icon: glovesColor});
openObjectsTable.set('goggles', {name: 'Goggles', icon: goggles});
openObjectsTable.set('gogglesColor', {name: 'Goggles Color', icon: gogglesColor});
openObjectsTable.set('graduationCap', {name: 'Graduation Cap', icon: graduationCap});
openObjectsTable.set('graduationCapColor', {name: 'Graduation Cap Color', icon: graduationCapColor});
openObjectsTable.set('handbag', {name: 'Handbag', icon: handbag});
openObjectsTable.set('handbagColor', {name: 'Handbag Color', icon: handbagColor});
openObjectsTable.set('highHeeledShoe', {name: 'High Heeled Shoe', icon: highHeeledShoe});
openObjectsTable.set('highHeeledShoeColor', {name: 'High Heeled Shoe Color', icon: highHeeledShoeColor});
openObjectsTable.set('hikingBoot', {name: 'Hiking Boot', icon: hikingBoot});
openObjectsTable.set('hikingBootColor', {name: 'Hiking Boot Color', icon: hikingBootColor});
openObjectsTable.set('jeans', {name: 'Jeans', icon: jeans});
openObjectsTable.set('jeansColor', {name: 'Jeans Color', icon: jeansColor});
openObjectsTable.set('kimono', {name: 'Kimono', icon: kimono});
openObjectsTable.set('kimonoColor', {name: 'Kimono Color', icon: kimonoColor});
openObjectsTable.set('labCoat', {name: 'Lab Coat', icon: labCoat});
openObjectsTable.set('labCoatColor', {name: 'Lab Coat Color', icon: labCoatColor});
openObjectsTable.set('lipstick', {name: 'Lipstick', icon: lipstick});
openObjectsTable.set('lipstickColor', {name: 'Lipstick Color', icon: lipstickColor});
openObjectsTable.set('mansShoe', {name: 'Mans Shoe', icon: mansShoe});
openObjectsTable.set('mansShoeColor', {name: 'Mans Shoe Color', icon: mansShoeColor});
openObjectsTable.set('militaryHelmet', {name: 'Military Helmet', icon: militaryHelmet});
openObjectsTable.set('militaryHelmetColor', {name: 'Military Helmet Color', icon: militaryHelmetColor});
openObjectsTable.set('necktie', {name: 'Necktie', icon: necktie});
openObjectsTable.set('necktieColor', {name: 'Necktie Color', icon: necktieColor});
openObjectsTable.set('onePieceSwimsuit', {name: 'One Piece Swimsuit', icon: onePieceSwimsuit});
openObjectsTable.set('onePieceSwimsuitColor', {name: 'One Piece Swimsuit Color', icon: onePieceSwimsuitColor});
openObjectsTable.set('prayerBeads', {name: 'Prayer Beads', icon: prayerBeads});
openObjectsTable.set('prayerBeadsColor', {name: 'Prayer Beads Color', icon: prayerBeadsColor});
openObjectsTable.set('purse', {name: 'Purse', icon: purse});
openObjectsTable.set('purseColor', {name: 'Purse Color', icon: purseColor});
openObjectsTable.set('rescueWorkersHelmet', {name: 'Rescue Workers Helmet', icon: rescueWorkersHelmet});
openObjectsTable.set('rescueWorkersHelmetColor', {name: 'Rescue Workers Helmet Color', icon: rescueWorkersHelmetColor});
openObjectsTable.set('ring', {name: 'Ring', icon: ring});
openObjectsTable.set('ringColor', {name: 'Ring Color', icon: ringColor});
openObjectsTable.set('runningShoe', {name: 'Running Shoe', icon: runningShoe});
openObjectsTable.set('runningShoeColor', {name: 'Running Shoe Color', icon: runningShoeColor});
openObjectsTable.set('safetyVest', {name: 'Safety Vest', icon: safetyVest});
openObjectsTable.set('safetyVestColor', {name: 'Safety Vest Color', icon: safetyVestColor});
openObjectsTable.set('sari', {name: 'Sari', icon: sari});
openObjectsTable.set('sariColor', {name: 'Sari Color', icon: sariColor});
openObjectsTable.set('scarf', {name: 'Scarf', icon: scarf});
openObjectsTable.set('scarfColor', {name: 'Scarf Color', icon: scarfColor});
openObjectsTable.set('shoppingBags', {name: 'Shopping Bags', icon: shoppingBags});
openObjectsTable.set('shoppingBagsColor', {name: 'Shopping Bags Color', icon: shoppingBagsColor});
openObjectsTable.set('shorts', {name: 'Shorts', icon: shorts});
openObjectsTable.set('shortsColor', {name: 'Shorts Color', icon: shortsColor});
openObjectsTable.set('socks', {name: 'Socks', icon: socks});
openObjectsTable.set('socksColor', {name: 'SocksColor', icon: socksColor});
openObjectsTable.set('sunglasses', {name: 'Sunglasses', icon: sunglasses});
openObjectsTable.set('sunglassesColor', {name: 'Sunglasses Color', icon: sunglassesColor});
openObjectsTable.set('thongSandal', {name: 'Thong Sandal', icon: thongSandal});
openObjectsTable.set('thongSandalColor', {name: 'Thong Sandal Color', icon: thongSandalColor});
openObjectsTable.set('topHat', {name: 'Top Hat', icon: topHat});
openObjectsTable.set('topHatColor', {name: 'Top Hat Color', icon: topHatColor});
openObjectsTable.set('tShirt', {name: 'T Shirt', icon: tShirt});
openObjectsTable.set('tShirtColor', {name: 'T Shirt Color', icon: tShirtColor});
openObjectsTable.set('womansBoot', {name: 'Womans Boot', icon: womansBoot});
openObjectsTable.set('womansBootColor', {name: 'Womans Boot Color', icon: womansBootColor});
openObjectsTable.set('womansClothes', {name: 'Womans Clothes', icon: womansClothes});
openObjectsTable.set('womansClothesColor', {name: 'Womans Clotes Color', icon: womansClothesColor});
openObjectsTable.set('womansHat', {name: 'Womans Hat', icon: womansHat});
openObjectsTable.set('womansHatColor', {name: 'Womans Hat Color', icon: womansHatColor});
openObjectsTable.set('womansSandal', {name: 'Womans Sandal', icon: womansSandal});
openObjectsTable.set('womansSandalColor', {name: 'Womans Sandal Color', icon: womansSandalColor});
openObjectsTable.set('abacus', {name: 'Abacus', icon: abacus});
openObjectsTable.set('abacusColor', {name: 'Abacus Color', icon: abacusColor});
openObjectsTable.set('battery', {name: 'Battery', icon: battery});
openObjectsTable.set('batteryColor', {name: 'Battery Color', icon: batteryColor});
openObjectsTable.set('computerDisk', {name: 'Computer Disk', icon: computerDisk});
openObjectsTable.set('computerDiskColor', {name: 'Computer Disk Color', icon: computerDiskColor});
openObjectsTable.set('computerMouse', {name: 'Computer Mouse', icon: computerMouse});
openObjectsTable.set('computerMouseColor', {name: 'Computer Mouse Color', icon: computerMouseColor});
openObjectsTable.set('desktopComputer', {name: 'Desktop Computer', icon: desktopComputer});
openObjectsTable.set('desktopComputerColor', {name: 'Desktop Computer Color', icon: desktopComputerColor});
openObjectsTable.set('dvd', {name: 'DVD', icon: dvd});
openObjectsTable.set('dvdColor', {name: 'DVD Color', icon: dvdColor});
openObjectsTable.set('electricPlug', {name: 'Electric Plug', icon: electricPlug});
openObjectsTable.set('electricPlugColor', {name: 'Electric Plug Color', icon: electricPlugColor});
openObjectsTable.set('floppyDisk', {name: 'Floppy Disk', icon: floppyDisk});
openObjectsTable.set('floppyDiskColor', {name: 'Floppy Disk Color', icon: floppyDiskColor});
openObjectsTable.set('keyboard', {name: 'Keyboard', icon: keyboard});
openObjectsTable.set('keyboardColor', {name: 'Keyboard Color', icon: keyboardColor});
openObjectsTable.set('laptop', {name: 'Laptop', icon: laptop});
openObjectsTable.set('laptopColor', {name: 'Laptop Color', icon: laptopColor});
openObjectsTable.set('lowBattery', {name: 'Low Battery', icon: lowBattery});
openObjectsTable.set('lowBatteryColor', {name: 'Low Battery Color', icon: lowBatteryColor});
openObjectsTable.set('opticalDisk', {name: 'Optical Disk', icon: opticalDisk});
openObjectsTable.set('opticalDiskColor', {name: 'Optical Disk Color', icon: opticalDiskColor});
openObjectsTable.set('printer', {name: 'Printer', icon: printer});
openObjectsTable.set('printerColor', {name: 'Printer Color', icon: printerColor});
openObjectsTable.set('trackball', {name: 'Trackball', icon: trackball});
openObjectsTable.set('trackballColor', {name: 'Trackball Color', icon: trackballColor});
openObjectsTable.set('basket', {name: 'Basket', icon: basket});
openObjectsTable.set('basketColor', {name: 'Basket Color', icon: basketColor});
openObjectsTable.set('bathtub', {name: 'Bathtub', icon: bathtub});
openObjectsTable.set('bathtubColor', {name: 'Bathtub Color', icon: bathtubColor});
openObjectsTable.set('bed', {name: 'Bed', icon: bed});
openObjectsTable.set('bedColor', {name: 'Bed Color', icon: bedColor});
openObjectsTable.set('broom', {name: 'Broom', icon: broom});
openObjectsTable.set('broomColor', {name: 'Broom Color', icon: broomColor});
openObjectsTable.set('bubbles', {name: 'Bubbles', icon: bubbles});
openObjectsTable.set('bubblesColor', {name: 'Bubbles Color', icon: bubblesColor});
openObjectsTable.set('bucket', {name: 'Bucket', icon: bucket});
openObjectsTable.set('bucketColor', {name: 'Bucket Color', icon: bucketColor});
openObjectsTable.set('chair', {name: 'Chair', icon: chair});
openObjectsTable.set('chairColor', {name: 'Chair Color', icon: chairColor});
openObjectsTable.set('couchAndLamp', {name: 'Couch And Lamp', icon: couchAndLamp});
openObjectsTable.set('couchAndLampColor', {name: 'Couch And Lamp Color', icon: couchAndLampColor});
openObjectsTable.set('door', {name: 'Door', icon: door});
openObjectsTable.set('doorColor', {name: 'Door', icon: doorColor});
openObjectsTable.set('elevator', {name: 'Elevator', icon: elevator});
openObjectsTable.set('elevatorColor', {name: 'Elevator Color', icon: elevatorColor});
openObjectsTable.set('fireExtinguisher', {name: 'Fire Extinguisher', icon: fireExtinguisher});
openObjectsTable.set('fireExtinguisherColor', {name: 'Fire Extinguisher', icon: fireExtinguisherColor});
openObjectsTable.set('lotionBottle', {name: 'Lotion Bottle', icon: lotionBottle});
openObjectsTable.set('lotionBottleColor', {name: 'Lotion Bottle Color', icon: lotionBottleColor});
openObjectsTable.set('mirror', {name: 'Mirror', icon: mirror});
openObjectsTable.set('mirrorColor', {name: 'Mirror Color', icon: mirrorColor});
openObjectsTable.set('mouseTrap', {name: 'Mouse Trap', icon: mouseTrap});
openObjectsTable.set('mouseTrapColor', {name: 'Mouse Trap Color', icon: mouseTrapColor});
openObjectsTable.set('plunger', {name: 'Plunger', icon: plunger});
openObjectsTable.set('plungerColor', {name: 'Plunger Color', icon: plungerColor});
openObjectsTable.set('razor', {name: 'Razor', icon: razor});
openObjectsTable.set('razorColor', {name: 'Razor Color', icon: razorColor});
openObjectsTable.set('rollOfPaper', {name: 'Roll Of Paper', icon: rollOfPaper});
openObjectsTable.set('rollOfPaperColor', {name: 'Roll Of Paper Color', icon: rollOfPaperColor});
openObjectsTable.set('safetyPin', {name: 'Safety Pin', icon: safetyPin});
openObjectsTable.set('safetyPinColor', {name: 'Safety Pin Color', icon: safetyPinColor});
openObjectsTable.set('shoppingCart', {name: 'Shopping Cart', icon: shoppingCart});
openObjectsTable.set('shoppingCartColor', {name: 'Shopping Cart Color', icon: shoppingCartColor});
openObjectsTable.set('shower', {name: 'Shower', icon: shower});
openObjectsTable.set('showerColor', {name: 'Shower Color', icon: showerColor});
openObjectsTable.set('soap', {name: 'Soap', icon: soap});
openObjectsTable.set('soapColor', {name: 'Soap Color', icon: soapColor});
openObjectsTable.set('sponge', {name: 'Sponge', icon: sponge});
openObjectsTable.set('spongeColor', {name: 'Sponge Color', icon: spongeColor});
openObjectsTable.set('toilet', {name: 'Toilet', icon: toilet});
openObjectsTable.set('toiletColor', {name: 'Toilet Color', icon: toiletColor});
openObjectsTable.set('toothbrush', {name: 'Toothbrush', icon: toothbrush});
openObjectsTable.set('toothbrushColor', {name: 'Toothbrush Color', icon: toothbrushColor});
openObjectsTable.set('window', {name: 'Window', icon: window});
openObjectsTable.set('windowColor', {name: 'Windown Color', icon: windowColor});
openObjectsTable.set('camera', {name: 'Camera', icon: camera});
openObjectsTable.set('cameraColor', {name: 'Camera Color', icon: cameraColor});
openObjectsTable.set('cameraWithFlash', {name: 'Camera With Flash', icon: cameraWithFlash});
openObjectsTable.set('cameraWithFlashColor', {name: 'Camera With Flash Color', icon: cameraWithFlashColor});
openObjectsTable.set('candle', {name: 'Candle', icon: candle});
openObjectsTable.set('candleColor', {name: 'Candle Color', icon: candleColor});
openObjectsTable.set('clapperBoard', {name: 'Clapper Board', icon: clapperBoard});
openObjectsTable.set('clapperBoardColor', {name: 'Clapper Board Color', icon: clapperBoardColor});
openObjectsTable.set('diyaLamp', {name: 'Diya Lamp', icon: diyaLamp});
openObjectsTable.set('diyaLampColor', {name: 'Diya Lamp Color', icon: diyaLampColor});
openObjectsTable.set('filmFrames', {name: 'Film Frames', icon: filmFrames});
openObjectsTable.set('filmFramesColor', {name: 'Film Frames Color', icon: filmFramesColor});
openObjectsTable.set('filmProjector', {name: 'Film Projector', icon: filmProjector});
openObjectsTable.set('filmProjectorColor', {name: 'Film Projector Color', icon: filmProjectorColor});
openObjectsTable.set('flashlight', {name: 'Flashlight', icon: flashlight});
openObjectsTable.set('flashlightColor', {name: 'Flashlight Color', icon: flashlightColor});
openObjectsTable.set('lightBulb', {name: 'Light Bulb', icon: lightBulb});
openObjectsTable.set('lightBulbColor', {name: 'Light Bulb Color', icon: lightBulbColor});
openObjectsTable.set('magnifyingGlassTiltedLeft', {
    name: 'Magnifying Glass Tilted Left',
    icon: magnifyingGlassTiltedLeft,
});
openObjectsTable.set('magnifyingGlassTiltedLeftColor', {
    name: 'Magnifying Glass Tilted Left Color',
    icon: magnifyingGlassTiltedLeftColor,
});
openObjectsTable.set('magnifyingGlassTiltedRight', {
    name: 'Magnifying Glass Titled Right',
    icon: magnifyingGlassTiltedRight,
});
openObjectsTable.set('magnifyingGlassTiltedRightColor', {
    name: 'Magnifying Glass Tilted Right Color',
    icon: magnifyingGlassTiltedRightColor,
});
openObjectsTable.set('movieCamera', {name: 'Movie Camera', icon: movieCamera});
openObjectsTable.set('movieCameraColor', {name: 'Movie Camera Color', icon: movieCameraColor});
openObjectsTable.set('redPaperLantern', {name: 'Red Paper Lantern', icon: redPaperLantern});
openObjectsTable.set('redPaperLanternColor', {name: 'Red Paper Lantern Color', icon: redPaperLanternColor});
openObjectsTable.set('television', {name: 'Television', icon: television});
openObjectsTable.set('televisionColor', {name: 'Television Color', icon: televisionColor});
openObjectsTable.set('videoCamera', {name: 'Video Camera', icon: videoCamera});
openObjectsTable.set('videoCameraColor', {name: 'Video Camera Color', icon: videoCameraColor});
openObjectsTable.set('videocassette', {name: 'Videocassette', icon: videocassette});
openObjectsTable.set('videocassetteColor', {name: 'Videocassette Color', icon: videocassetteColor});
openObjectsTable.set('key', {name: 'Key', icon: key});
openObjectsTable.set('keyColor', {name: 'Key Color', icon: keyColor});
openObjectsTable.set('locked', {name: 'Locked', icon: locked});
openObjectsTable.set('lockedColor', {name: 'Locked Color', icon: lockedColor});
openObjectsTable.set('lockedWithKey', {name: 'Locked With Key', icon: lockedWithKey});
openObjectsTable.set('lockedWithKeyColor', {name: 'Locked With Key Color', icon: lockedWithKeyColor});
openObjectsTable.set('lockedWithPen', {name: 'Locked With Pen', icon: lockedWithPen});
openObjectsTable.set('lockedWithPenColor', {name: 'Locked With Pen Color', icon: lockedWithPenColor});
openObjectsTable.set('oldKey', {name: 'Old Key', icon: oldKey});
openObjectsTable.set('oldKeyColor', {name: 'Old Key Color', icon: oldKeyColor});
openObjectsTable.set('unlocked', {name: 'Unlocked', icon: unlocked});
openObjectsTable.set('unlockedColor', {name: 'Unlocked Color', icon: unlockedColor});
openObjectsTable.set('ballotBoxWithBallot', {name: 'Ballot Box With Ballot', icon: ballotBoxWithBallot});
openObjectsTable.set('ballotBoxWithBallotColor', {
    name: 'Ballot Box With Ballot Color',
    icon: ballotBoxWithBallotColor,
});
openObjectsTable.set('closedMailboxWithLoweredFlag', {
    name: 'Closed Mailbox With Lowered Flag',
    icon: closedMailboxWithLoweredFlag,
});
openObjectsTable.set('closedMailboxWithLoweredFlagColor', {
    name: 'Closed Mailbox With Lowered Flag Color',
    icon: closedMailboxWithLoweredFlagColor,
});
openObjectsTable.set('closedMailboxWithRaisedFlag', {
    name: 'Closed Mailbox With Raised Flag',
    icon: closedMailboxWithRaisedFlag,
});
openObjectsTable.set('closedMailboxWithRaisedFlagColor', {
    name: 'Closed Mailbox With Raised Flag Color',
    icon: closedMailboxWithRaisedFlagColor,
});
openObjectsTable.set('eMail', {name: 'E Mail', icon: eMail});
openObjectsTable.set('eMailColor', {name: 'E Mail Color', icon: eMailColor});
openObjectsTable.set('envelope', {name: 'Envelope', icon: envelope});
openObjectsTable.set('envelopeColor', {name: 'Envelope Color', icon: envelopeColor});
openObjectsTable.set('envelopeWithArrow', {name: 'Envelope With Arrow', icon: envelopeWithArrow});
openObjectsTable.set('envelopeWithArrowColor', {name: 'Envelope With Arrow Color', icon: envelopeWithArrowColor});
openObjectsTable.set('inboxTray', {name: 'Inbox Tray', icon: inboxTray});
openObjectsTable.set('inboxTrayColor', {name: 'Inbox Tray Color', icon: inboxTrayColor});
openObjectsTable.set('incomingEnvelope', {name: 'Incoming Envelope', icon: incomingEnvelope});
openObjectsTable.set('incomingEnvelopeColor', {name: 'Incoming Envelope Color', icon: incomingEnvelopeColor});
openObjectsTable.set('openMailboxWithLoweredFlag', {
    name: 'Open Mailbox With Lowered Flag',
    icon: openMailboxWithLoweredFlag,
});
openObjectsTable.set('openMailboxWithLoweredFlagColor', {
    name: 'Open Mailbox With Lowered Flag Color',
    icon: openMailboxWithLoweredFlagColor,
});
openObjectsTable.set('openMailboxWithRaisedFlag', {
    name: 'Open Mailbox With Raised Flag',
    icon: openMailboxWithRaisedFlag,
});
openObjectsTable.set('openMailboxWithRaisedFlagColor', {
    name: 'Open Mailbox With Raised Flag Color',
    icon: openMailboxWithRaisedFlagColor,
});
openObjectsTable.set('outboxTray', {name: 'Outbox Tray', icon: outboxTray});
openObjectsTable.set('outboxTrayColor', {name: 'Outbox Tray Color', icon: outboxTrayColor});
openObjectsTable.set('openPackage', {name: 'Package', icon: openPackage});
openObjectsTable.set('openPackageColor', {name: 'Package Color', icon: openPackageColor});
openObjectsTable.set('postbox', {name: 'Postbox', icon: postbox});
openObjectsTable.set('postboxColor', {name: 'Postbox Color', icon: postboxColor});
openObjectsTable.set('adhesiveBandage', {name: 'Adhesive Bandage', icon: adhesiveBandage});
openObjectsTable.set('adhesiveBandageColor', {name: 'Adhesive Bandage Color', icon: adhesiveBandageColor});
openObjectsTable.set('crutch', {name: 'Crutch', icon: crutch});
openObjectsTable.set('crutchColor', {name: 'Crutch Color', icon: crutchColor});
openObjectsTable.set('dropOfBlood', {name: 'Drop Of Blood', icon: dropOfBlood});
openObjectsTable.set('dropOfBloodColor', {name: 'Drop Of Blood Color', icon: dropOfBloodColor});
openObjectsTable.set('pill', {name: 'Pill', icon: pill});
openObjectsTable.set('pillColor', {name: 'Pill Color', icon: pillColor});
openObjectsTable.set('stethoscope', {name: 'Stethoscope', icon: stethoscope});
openObjectsTable.set('stethoscopeColor', {name: 'Stethoscope Color', icon: stethoscopeColor});
openObjectsTable.set('syringe', {name: 'Syringe', icon: syringe});
openObjectsTable.set('syringeColor', {name: 'Syringe Color', icon: syringeColor});
openObjectsTable.set('xRay', {name: 'X Ray', icon: xRay});
openObjectsTable.set('xRayColor', {name: 'X Ray Color', icon: xRayColor});
openObjectsTable.set('chartIncreasingWithYen', {name: 'Chart Increasing With Yen', icon: chartIncreasingWithYen});
openObjectsTable.set('chartIncreasingWithYenColor', {
    name: 'Chart Increasing With Yen Color',
    icon: chartIncreasingWithYenColor,
});
openObjectsTable.set('coin', {name: 'Coin', icon: coin});
openObjectsTable.set('coinColor', {name: 'Coin Color', icon: coinColor});
openObjectsTable.set('creditCard', {name: 'Credit Card', icon: creditCard});
openObjectsTable.set('creditCardColor', {name: 'Credit Card Color', icon: creditCardColor});
openObjectsTable.set('dollarBanknote', {name: 'Dollar Banknote', icon: dollarBanknote});
openObjectsTable.set('dollarBanknoteColor', {name: 'Dollar Banknote Color', icon: dollarBanknoteColor});
openObjectsTable.set('euroBanknote', {name: 'Euro Banknote', icon: euroBanknote});
openObjectsTable.set('euroBanknoteColor', {name: 'Euro Banknote Color', icon: euroBanknoteColor});
openObjectsTable.set('moneyBag', {name: 'Money Bag', icon: moneyBag});
openObjectsTable.set('moneyBagColor', {name: 'Money Bag Color', icon: moneyBagColor});
openObjectsTable.set('moneyWithWings', {name: 'Money With Wings', icon: moneyWithWings});
openObjectsTable.set('moneyWithWingsColor', {name: 'Money With Wings Color', icon: moneyWithWingsColor});
openObjectsTable.set('poundBanknote', {name: 'Pound Banknote', icon: poundBanknote});
openObjectsTable.set('poundBanknoteColor', {name: 'Pound Banknote Color', icon: poundBanknoteColor});
openObjectsTable.set('receipt', {name: 'Receipt', icon: receipt});
openObjectsTable.set('receiptColor', {name: 'Receipt Color', icon: receiptColor});
openObjectsTable.set('yenBanknote', {name: 'Yen Banknote', icon: yenBanknote});
openObjectsTable.set('yenBanknoteColor', {name: 'Yen Banknote Color', icon: yenBanknoteColor});
openObjectsTable.set('controlKnobs', {name: 'Control Knobs', icon: controlKnobs});
openObjectsTable.set('controlKnobsColor', {name: 'Control Knobs Color', icon: controlKnobsColor});
openObjectsTable.set('headphone', {name: 'Headphone', icon: headphone});
openObjectsTable.set('headphoneColor', {name: 'Headphone Color', icon: headphoneColor});
openObjectsTable.set('levelSlider', {name: 'Level Slider', icon: levelSlider});
openObjectsTable.set('levelSliderColor', {name: 'Level Slider Color', icon: levelSliderColor});
openObjectsTable.set('microphone', {name: 'Microphone', icon: microphone});
openObjectsTable.set('microphoneColor', {name: 'Microphone Color', icon: microphoneColor});
openObjectsTable.set('musicalNote', {name: 'Musical Note', icon: musicalNote});
openObjectsTable.set('musicalNoteColor', {name: 'Musical Note Color', icon: musicalNoteColor});
openObjectsTable.set('musicalNotes', {name: 'Musical Notes', icon: musicalNotes});
openObjectsTable.set('musicalNotesColor', {name: 'Musical Notes Color', icon: musicalNotesColor});
openObjectsTable.set('musicalScore', {name: 'Musical Score', icon: musicalScore});
openObjectsTable.set('musicalScoreColor', {name: 'Musical Score Color', icon: musicalScoreColor});
openObjectsTable.set('radio', {name: 'Radio', icon: radio});
openObjectsTable.set('radioColor', {name: 'Radio Color', icon: radioColor});
openObjectsTable.set('studioMicrophone', {name: 'Studio Microphone', icon: studioMicrophone});
openObjectsTable.set('studioMicrophoneColor', {name: 'Studio Microphone Color', icon: studioMicrophoneColor});
openObjectsTable.set('accordion', {name: 'Accordion', icon: accordion});
openObjectsTable.set('accordionColor', {name: 'Accordion Color', icon: accordionColor});
openObjectsTable.set('banjo', {name: 'Banjo', icon: banjo});
openObjectsTable.set('banjoColor', {name: 'Banjo Color', icon: banjoColor});
openObjectsTable.set('drum', {name: 'Drum', icon: drum});
openObjectsTable.set('drumColor', {name: 'Drum Color', icon: drumColor});
openObjectsTable.set('guitar', {name: 'Guitar', icon: guitar});
openObjectsTable.set('guitarColor', {name: 'Guitar Color', icon: guitarColor});
openObjectsTable.set('longDrum', {name: 'Long Drum', icon: longDrum});
openObjectsTable.set('longDrumColor', {name: 'Long Drum Color', icon: longDrumColor});
openObjectsTable.set('musicalKeyboard', {name: 'Musical Keyboard', icon: musicalKeyboard});
openObjectsTable.set('musicalKeyboardColor', {name: 'Musical Keyboard Color', icon: musicalKeyboardColor});
openObjectsTable.set('saxophone', {name: 'Saxophone', icon: saxophone});
openObjectsTable.set('saxophoneColor', {name: 'Saxophone Color', icon: saxophoneColor});
openObjectsTable.set('trumpet', {name: 'Trumpet', icon: trumpet});
openObjectsTable.set('trumpetColor', {name: 'Trumpet Color', icon: trumpetColor});
openObjectsTable.set('violin', {name: 'Violin', icon: violin});
openObjectsTable.set('violinColor', {name: 'Violin Color', icon: violinColor});
openObjectsTable.set('barChart', {name: 'Bar Chart', icon: barChart});
openObjectsTable.set('barChartColor', {name: 'Bar Chart Color', icon: barChartColor});
openObjectsTable.set('briefcase', {name: 'Briefcase', icon: briefcase});
openObjectsTable.set('briefcaseColor', {name: 'Briefcase Color', icon: briefcaseColor});
openObjectsTable.set('calendar', {name: 'Calendar', icon: calendar});
openObjectsTable.set('calendarColor', {name: 'Calendar Color', icon: calendarColor});
openObjectsTable.set('cardFileBox', {name: 'Card File Box', icon: cardFileBox});
openObjectsTable.set('cardFileBoxColor', {name: 'Card File Box Color', icon: cardFileBoxColor});
openObjectsTable.set('cardIndex', {name: 'Card Index', icon: cardIndex});
openObjectsTable.set('cardIndexColor', {name: 'Card Index Color', icon: cardIndexColor});
openObjectsTable.set('cardIndexDividers', {name: 'Card Index Dividers', icon: cardIndexDividers});
openObjectsTable.set('cardIndexDividersColor', {name: 'Card Index Dividers Color', icon: cardIndexDividersColor});
openObjectsTable.set('chartDecreasing', {name: 'Chart Decreasing', icon: chartDecreasing});
openObjectsTable.set('chartDecreasingColor', {name: 'Chart Decreasing Color', icon: chartDecreasingColor});
openObjectsTable.set('chartIncreasing', {name: 'Chart Increasing', icon: chartIncreasing});
openObjectsTable.set('chartIncreasingColor', {name: 'Chart Increasing Color', icon: chartIncreasingColor});
openObjectsTable.set('clipboard', {name: 'Clipboard', icon: clipboard});
openObjectsTable.set('clipboardColor', {name: 'Clipboard Color', icon: clipboardColor});
openObjectsTable.set('fileCabinet', {name: 'File Cabinet', icon: fileCabinet});
openObjectsTable.set('fileCabinetColor', {name: 'File Cabinet Color', icon: fileCabinetColor});
openObjectsTable.set('fileFolder', {name: 'File Folder', icon: fileFolder});
openObjectsTable.set('fileFolderColor', {name: 'File Folder Color', icon: fileFolderColor});
openObjectsTable.set('linkedPaperclips', {name: 'Linked Paperclips', icon: linkedPaperclips});
openObjectsTable.set('linkedPaperclipsColor', {name: 'Linked Paperclips Color', icon: linkedPaperclipsColor});
openObjectsTable.set('openFileFolder', {name: 'Open File Folder', icon: openFileFolder});
openObjectsTable.set('openFileFolderColor', {name: 'Open File Folder Color', icon: openFileFolderColor});
openObjectsTable.set('paperclip', {name: 'Paperclip', icon: paperclip});
openObjectsTable.set('paperclipColor', {name: 'Paperclip Color', icon: paperclipColor});
openObjectsTable.set('pushpin', {name: 'Pushpin', icon: pushpin});
openObjectsTable.set('pushpinColor', {name: 'Pushpin', icon: pushpinColor});
openObjectsTable.set('roundPushpin', {name: 'Round Pushpin', icon: roundPushpin});
openObjectsTable.set('roundPushpinColor', {name: 'Round Pushpin Color', icon: roundPushpinColor});
openObjectsTable.set('scissors', {name: 'Scissors', icon: scissors});
openObjectsTable.set('scissorsColor', {name: 'Scissors Color', icon: scissorsColor});
openObjectsTable.set('spiralCalendar', {name: 'Spiral Calendar', icon: spiralCalendar});
openObjectsTable.set('spiralCalendarColor', {name: 'Spiral Calendar Color', icon: spiralCalendarColor});
openObjectsTable.set('spiralNotepad', {name: 'Spiral Notepad', icon: spiralNotepad});
openObjectsTable.set('spiralNotepadColor', {name: 'Spiral Notepad Color', icon: spiralNotepadColor});
openObjectsTable.set('straightRuler', {name: 'Straight Ruler', icon: straightRuler});
openObjectsTable.set('straightRulerColor', {name: 'Straight Ruler Color', icon: straightRulerColor});
openObjectsTable.set('tearOffCalendar', {name: 'Tear Off Calendar', icon: tearOffCalendar});
openObjectsTable.set('tearOffCalendarColor', {name: 'Tear Off Calendar Color', icon: tearOffCalendarColor});
openObjectsTable.set('triangularRuler', {name: 'Triangular Ruler', icon: triangularRuler});
openObjectsTable.set('triangularRulerColor', {name: 'Triangular Ruler Color', icon: triangularRulerColor});
openObjectsTable.set('wastebasket', {name: 'Wastebasket', icon: wastebasket});
openObjectsTable.set('wastebasketColor', {name: 'Wastebasket Color', icon: wastebasketColor});
openObjectsTable.set('cigarette', {name: 'Cigarette', icon: cigarette});
openObjectsTable.set('cigaretteColor', {name: 'Cigarette Color', icon: cigaretteColor});
openObjectsTable.set('coffin', {name: 'Coffin', icon: coffin});
openObjectsTable.set('coffinColor', {name: 'Coffin Color', icon: coffinColor});
openObjectsTable.set('funeralUrn', {name: 'Funeral Urn', icon: funeralUrn});
openObjectsTable.set('funeralUrnColor', {name: 'Funeral Urn Color', icon: funeralUrnColor});
openObjectsTable.set('headstone', {name: 'Headstone', icon: headstone});
openObjectsTable.set('headstoneColor', {name: 'Headstone Color', icon: headstoneColor});
openObjectsTable.set('identificationCard', {name: 'Identification Card', icon: identificationCard});
openObjectsTable.set('identificationCardColor', {name: 'Identification Card Color', icon: identificationCardColor});
openObjectsTable.set('moai', {name: 'Moai', icon: moai});
openObjectsTable.set('moaiColor', {name: 'Moai Color', icon: moaiColor});
openObjectsTable.set('placard', {name: 'Placard', icon: placard});
openObjectsTable.set('placardColor', {name: 'Placard Color', icon: placardColor});
openObjectsTable.set('faxMachine', {name: 'Fax Machine', icon: faxMachine});
openObjectsTable.set('faxMachineColor', {name: 'Fax Machine Color', icon: faxMachineColor});
openObjectsTable.set('mobilePhone', {name: 'Mobile Phone', icon: mobilePhone});
openObjectsTable.set('mobilePhoneColor', {name: 'Mobile Phone Color', icon: mobilePhoneColor});
openObjectsTable.set('mobilePhoneWithArrow', {name: 'Mobile Phone With Arrow', icon: mobilePhoneWithArrow});
openObjectsTable.set('mobilePhoneWithArrowColor', {
    name: 'Mobile Phone With Arrow Color',
    icon: mobilePhoneWithArrowColor,
});
openObjectsTable.set('pager', {name: 'Pager', icon: pager});
openObjectsTable.set('pagerColor', {name: 'Pager Color', icon: pagerColor});
openObjectsTable.set('telephone', {name: 'Telephone', icon: telephone});
openObjectsTable.set('telephoneColor', {name: 'Telephone Color', icon: telephoneColor});
openObjectsTable.set('telephoneReceiver', {name: 'Telephone Receiver', icon: telephoneReceiver});
openObjectsTable.set('telephoneReceiverColor', {name: 'Telephone Receiver Color', icon: telephoneReceiverColor});
openObjectsTable.set('alembic', {name: 'Alembic', icon: alembic});
openObjectsTable.set('alembicColor', {name: 'Alembic Color', icon: alembicColor});
openObjectsTable.set('dna', {name: 'DNA', icon: dna});
openObjectsTable.set('dnaColor', {name: 'DNA Color', icon: dnaColor});
openObjectsTable.set('microscope', {name: 'Microscope', icon: microscope});
openObjectsTable.set('microscopeColor', {name: 'Microscope Color', icon: microscopeColor});
openObjectsTable.set('petriDish', {name: 'Petri Dish', icon: petriDish});
openObjectsTable.set('petriDishColor', {name: 'Petri Dish Color', icon: petriDishColor});
openObjectsTable.set('satelliteAntenna', {name: 'Satellite Antenna', icon: satelliteAntenna});
openObjectsTable.set('satelliteAntennaColor', {name: 'Satellite Antenna Color', icon: satelliteAntennaColor});
openObjectsTable.set('telescope', {name: 'Telescope', icon: telescope});
openObjectsTable.set('telescopeColor', {name: 'Telescope Color', icon: telescopeColor});
openObjectsTable.set('testTube', {name: 'Test Tube', icon: testTube});
openObjectsTable.set('testTubeColor', {name: 'Test Tube Color', icon: testTubeColor});
openObjectsTable.set('bell', {name: 'Bell', icon: bell});
openObjectsTable.set('bellColor', {name: 'Bell Color', icon: bellColor});
openObjectsTable.set('bellWithSlash', {name: 'Bell With Slash', icon: bellWithSlash});
openObjectsTable.set('bellWithSlashColor', {name: 'Bell With Slash Color', icon: bellWithSlashColor});
openObjectsTable.set('loudspeaker', {name: 'Loudspeaker', icon: loudspeaker});
openObjectsTable.set('loudspeakerColor', {name: 'Loudspeaker Color', icon: loudspeakerColor});
openObjectsTable.set('megaphone', {name: 'Megaphone', icon: megaphone});
openObjectsTable.set('megaphoneColor', {name: 'Megaphone Color', icon: megaphoneColor});
openObjectsTable.set('mutedSpeaker', {name: 'Muted Speaker', icon: mutedSpeaker});
openObjectsTable.set('mutedSpeakerColor', {name: 'Muted Speaker Color', icon: mutedSpeakerColor});
openObjectsTable.set('postalHorn', {name: 'Postal Horn', icon: postalHorn});
openObjectsTable.set('postalHornColor', {name: 'Postal Horn Color', icon: postalHornColor});
openObjectsTable.set('speakerHighVolume', {name: 'Speaker High Volume', icon: speakerHighVolume});
openObjectsTable.set('speakerHighVolumeColor', {name: 'Speaker High Volume Color', icon: speakerHighVolumeColor});
openObjectsTable.set('speakerLowVolume', {name: 'Speaker Low Volume', icon: speakerLowVolume});
openObjectsTable.set('speakerLowVolumeColor', {name: 'Speaker Low Volume Color', icon: speakerLowVolumeColor});
openObjectsTable.set('speakerMediumVolume', {name: 'Speaker Medium Volume', icon: speakerMediumVolume});
openObjectsTable.set('speakerMediumVolumeColor', {name: 'Speaker Medium Volume Color', icon: speakerMediumVolumeColor});
openObjectsTable.set('axe', {name: 'Axe', icon: axe});
openObjectsTable.set('axeColor', {name: 'Axe Color', icon: axeColor});
openObjectsTable.set('balanceScale', {name: 'Balance Scale', icon: balanceScale});
openObjectsTable.set('balanceScaleColor', {name: 'Balance Scale Color', icon: balanceScaleColor});
openObjectsTable.set('boomerang', {name: 'Boomerang', icon: boomerang});
openObjectsTable.set('boomerangColor', {name: 'Boomerang Color', icon: boomerangColor});
openObjectsTable.set('bowAndArrow', {name: 'Bow And Arrow', icon: bowAndArrow});
openObjectsTable.set('bowAndArrowColor', {name: 'Bow And Arrow Color', icon: bowAndArrowColor});
openObjectsTable.set('carpentrySaw', {name: 'Carpentry Saw', icon: carpentrySaw});
openObjectsTable.set('carpentrySawColor', {name: 'Carpentry Saw Color', icon: carpentrySawColor});
openObjectsTable.set('chains', {name: 'Chains', icon: chains});
openObjectsTable.set('chainsColor', {name: 'Chains Color', icon: chainsColor});
openObjectsTable.set('clamp', {name: 'Clamp', icon: clamp});
openObjectsTable.set('clampColor', {name: 'Clamp Color', icon: clampColor});
openObjectsTable.set('crossedSwords', {name: 'Crossed Swords', icon: crossedSwords});
openObjectsTable.set('crossedSwordsColor', {name: 'Crossed Swords Color', icon: crossedSwordsColor});
openObjectsTable.set('dagger', {name: 'Dagger', icon: dagger});
openObjectsTable.set('daggerColor', {name: 'Dagger Color', icon: daggerColor});
openObjectsTable.set('gear', {name: 'Gear', icon: gear});
openObjectsTable.set('gearColor', {name: 'Gear Color', icon: gearColor});
openObjectsTable.set('hammer', {name: 'Hammer', icon: hammer});
openObjectsTable.set('hammerColor', {name: 'Hammer Color', icon: hammerColor});
openObjectsTable.set('hammerAndPick', {name: 'Hammer And Pick', icon: hammerAndPick});
openObjectsTable.set('hammerAndPickColor', {name: 'Hammer And Pick Color', icon: hammerAndPickColor});
openObjectsTable.set('hammerAndWrench', {name: 'Hammer And Wrench', icon: hammerAndWrench});
openObjectsTable.set('hammerAndWrenchColor', {name: 'Hammer And Wrench Color', icon: hammerAndWrenchColor});
openObjectsTable.set('hook', {name: 'Hook', icon: hook});
openObjectsTable.set('hookColor', {name: 'Hook Color', icon: hookColor});
openObjectsTable.set('ladder', {name: 'Ladder', icon: ladder});
openObjectsTable.set('ladderColor', {name: 'Ladder Color', icon: ladderColor});
openObjectsTable.set('link', {name: 'Link', icon: link});
openObjectsTable.set('linkColor', {name: 'Link Color', icon: linkColor});
openObjectsTable.set('magnet', {name: 'Magnet', icon: magnet});
openObjectsTable.set('magnetColor', {name: 'Magnet Color', icon: magnetColor});
openObjectsTable.set('nutAndBolt', {name: 'Nut And Bolt', icon: nutAndBolt});
openObjectsTable.set('nutAndBoltColor', {name: 'Nut And Bolt Color', icon: nutAndBoltColor});
openObjectsTable.set('pick', {name: 'Pick', icon: pick});
openObjectsTable.set('pickColor', {name: 'Pick Color', icon: pickColor});
openObjectsTable.set('screwdriver', {name: 'Screwdriver', icon: screwdriver});
openObjectsTable.set('screwdriverColor', {name: 'Screwdriver Color', icon: screwdriverColor});
openObjectsTable.set('shield', {name: 'Shield', icon: shield});
openObjectsTable.set('shieldColor', {name: 'Shield Color', icon: shieldColor});
openObjectsTable.set('toolbox', {name: 'Toolbox', icon: toolbox});
openObjectsTable.set('toolboxColor', {name: 'Toolbox Color', icon: toolboxColor});
openObjectsTable.set('waterPistol', {name: 'Water Pistol', icon: waterPistol});
openObjectsTable.set('waterPistolColor', {name: 'Water Pistol Color', icon: waterPistolColor});
openObjectsTable.set('whiteCane', {name: 'White Cane', icon: whiteCane});
openObjectsTable.set('whiteCaneColor', {name: 'White Cane Color', icon: whiteCaneColor});
openObjectsTable.set('wrench', {name: 'Wrench', icon: wrench});
openObjectsTable.set('wrenchColor', {name: 'Wrench Color', icon: wrenchColor});
openObjectsTable.set('blackNib', {name: 'Black Nib', icon: blackNib});
openObjectsTable.set('blackNibColor', {name: 'Black Nib Color', icon: blackNibColor});
openObjectsTable.set('crayon', {name: 'Crayon', icon: crayon});
openObjectsTable.set('crayonColor', {name: 'Crayon Color', icon: crayonColor});
openObjectsTable.set('fountainPen', {name: 'Fountain Pen', icon: fountainPen});
openObjectsTable.set('fountainPenColor', {name: 'Fountain Pen Color', icon: fountainPenColor});
openObjectsTable.set('memo', {name: 'Memo', icon: memo});
openObjectsTable.set('memoColor', {name: 'Memo Color', icon: memoColor});
openObjectsTable.set('paintbrush', {name: 'Paintbrush', icon: paintbrush});
openObjectsTable.set('paintbrushColor', {name: 'PaintBrushColor', icon: paintbrushColor});
openObjectsTable.set('pen', {name: 'pen', icon: pen});
openObjectsTable.set('penColor', {name: 'Pen Color', icon: penColor});
openObjectsTable.set('pencil', {name: 'Pencil', icon: pencil});
openObjectsTable.set('pencilColor', {name: 'Pencil Color', icon: pencilColor});

export const OA_ICON_SIZE = openObjectsTable.size;
