import amphora from './icons/food-drink/dishware/amphora.svg';
import amphoraColor from './icons/food-drink/dishware/amphora_color.svg';
import chopsticks from './icons/food-drink/dishware/chopsticks.svg';
import chopsticksColor from './icons/food-drink/dishware/chopsticks_color.svg';
import forkAndKnife from './icons/food-drink/dishware/fork-and-knife.svg';
import forkAndKnifeColor from './icons/food-drink/dishware/fork-and-knife_color.svg';
import forkAndKnifeWithPlate from './icons/food-drink/dishware/fork-and-knife-with-plate.svg';
import forkAndKnifeWithPlateColor from './icons/food-drink/dishware/fork-and-knife-with-plate_color.svg';
import jar from './icons/food-drink/dishware/jar.svg';
import jarColor from './icons/food-drink/dishware/jar_color.svg';
import kitchenKnife from './icons/food-drink/dishware/kitchen-knife.svg';
import kitchenKnifeColor from './icons/food-drink/dishware/kitchen-knife_color.svg';
import spoon from './icons/food-drink/dishware/spoon.svg';
import spoonColor from './icons/food-drink/dishware/spoon_color.svg';
import babyBottle from './icons/food-drink/drink/baby-bottle.svg';
import babyBottleColor from './icons/food-drink/drink/baby-bottle_color.svg';
import beerMug from './icons/food-drink/drink/beer-mug.svg';
import beerMugColor from './icons/food-drink/drink/beer-mug_color.svg';
import beverageBox from './icons/food-drink/drink/beverage-box.svg';
import beverageBoxColor from './icons/food-drink/drink/beverage-box_color.svg';
import bottleWithPoppingCork from './icons/food-drink/drink/bottle-with-popping-cork.svg';
import bottleWithPoppingCorkColor from './icons/food-drink/drink/bottle-with-popping-cork_color.svg';
import bubbleTea from './icons/food-drink/drink/bubble-tea.svg';
import bubbleTeaColor from './icons/food-drink/drink/bubble-tea_color.svg';
import clinkingBeerMugs from './icons/food-drink/drink/clinking-beer-mugs.svg';
import clinkingBeerMugsColor from './icons/food-drink/drink/clinking-beer-mugs_color.svg';
import clinkingGlasses from './icons/food-drink/drink/clinking-glasses.svg';
import clinkingGlassesColor from './icons/food-drink/drink/clinking-glasses_color.svg';
import cocktailGlass from './icons/food-drink/drink/cocktail-glass.svg';
import cocktailGlassColor from './icons/food-drink/drink/cocktail-glass_color.svg';
import cupWithStraw from './icons/food-drink/drink/cup-with-straw.svg';
import cupWithStrawColor from './icons/food-drink/drink/cup-with-straw_color.svg';
import glassOfMilk from './icons/food-drink/drink/glass-of-milk.svg';
import glassOfMilkColor from './icons/food-drink/drink/glass-of-milk_color.svg';
import hotBeverage from './icons/food-drink/drink/hot-beverage.svg';
import hotBeverageColor from './icons/food-drink/drink/hot-beverage_color.svg';
import ice from './icons/food-drink/drink/ice.svg';
import iceColor from './icons/food-drink/drink/ice_color.svg';
import mate from './icons/food-drink/drink/mate.svg';
import mateColor from './icons/food-drink/drink/mate_color.svg';
import pouringLiquid from './icons/food-drink/drink/pouring-liquid.svg';
import pouringLiquidColor from './icons/food-drink/drink/pouring-liquid_color.svg';
import sake from './icons/food-drink/drink/sake.svg';
import sakeColor from './icons/food-drink/drink/sake_color.svg';
import teacupWithoutHandle from './icons/food-drink/drink/teacup-without-handle.svg';
import teacupWithoutHandleColor from './icons/food-drink/drink/teacup-without-handle_color.svg';
import teapot from './icons/food-drink/drink/teapot.svg';
import teapotColor from './icons/food-drink/drink/teapot_color.svg';
import tropicalDrink from './icons/food-drink/drink/tropical-drink.svg';
import tropicalDrinkColor from './icons/food-drink/drink/tropical-drink_color.svg';
import tumblerGlass from './icons/food-drink/drink/tumbler-glass.svg';
import tumblerGlassColor from './icons/food-drink/drink/tumbler-glass_color.svg';
import wineGlass from './icons/food-drink/drink/wine-glass.svg';
import wineGlassColor from './icons/food-drink/drink/wine-glass_color.svg';
import bentoBox from './icons/food-drink/food-asian/bento-box.svg';
import bentoBoxColor from './icons/food-drink/food-asian/bento-box_color.svg';
import cookedRice from './icons/food-drink/food-asian/cooked-rice.svg';
import cookedRiceColor from './icons/food-drink/food-asian/cooked-rice_color.svg';
import curryRice from './icons/food-drink/food-asian/curry-rice.svg';
import curryRiceColor from './icons/food-drink/food-asian/curry-rice_color.svg';
import dango from './icons/food-drink/food-asian/dango.svg';
import dangoColor from './icons/food-drink/food-asian/dango_color.svg';
import dumpling from './icons/food-drink/food-asian/dumpling.svg';
import dumplingColor from './icons/food-drink/food-asian/dumpling_color.svg';
import fishCakeWithSwirl from './icons/food-drink/food-asian/fish-cake-with-swirl.svg';
import fishCakeWithSwirlColor from './icons/food-drink/food-asian/fish-cake-with-swirl_color.svg';
import fortuneCookie from './icons/food-drink/food-asian/fortune-cookie.svg';
import fortuneCookieColor from './icons/food-drink/food-asian/fortune-cookie_color.svg';
import friedShrimp from './icons/food-drink/food-asian/fried-shrimp.svg';
import friedShrimpColor from './icons/food-drink/food-asian/fried-shrimp_color.svg';
import moonCake from './icons/food-drink/food-asian/moon-cake.svg';
import moonCakeColor from './icons/food-drink/food-asian/moon-cake_color.svg';
import oden from './icons/food-drink/food-asian/oden.svg';
import odenColor from './icons/food-drink/food-asian/oden_color.svg';
import riceBall from './icons/food-drink/food-asian/rice-ball.svg';
import riceBallColor from './icons/food-drink/food-asian/rice-ball_color.svg';
import riceCracker from './icons/food-drink/food-asian/rice-cracker.svg';
import riceCrackerColor from './icons/food-drink/food-asian/rice-cracker_color.svg';
import roastedSweetPotato from './icons/food-drink/food-asian/roasted-sweet-potato.svg';
import roastedSweetPotatoColor from './icons/food-drink/food-asian/roasted-sweet-potato_color.svg';
import spaghetti from './icons/food-drink/food-asian/spaghetti.svg';
import spaghettiColor from './icons/food-drink/food-asian/spaghetti_color.svg';
import steamingBowl from './icons/food-drink/food-asian/steaming-bowl.svg';
import steamingBowlColor from './icons/food-drink/food-asian/steaming-bowl_color.svg';
import sushi from './icons/food-drink/food-asian/sushi.svg';
import sushiColor from './icons/food-drink/food-asian/sushi_color.svg';
import takeoutBox from './icons/food-drink/food-asian/takeout-box.svg';
import takeoutBoxColor from './icons/food-drink/food-asian/takeout-box_color.svg';
import banana from './icons/food-drink/food-fruit/banana.svg';
import bananaColor from './icons/food-drink/food-fruit/banana_color.svg';
import blueberries from './icons/food-drink/food-fruit/blueberries.svg';
import blueberriesColor from './icons/food-drink/food-fruit/blueberries_color.svg';
import cherries from './icons/food-drink/food-fruit/cherries.svg';
import cherriesColor from './icons/food-drink/food-fruit/cherries_color.svg';
import coconut from './icons/food-drink/food-fruit/coconut.svg';
import coconutColor from './icons/food-drink/food-fruit/coconut_color.svg';
import grapes from './icons/food-drink/food-fruit/grapes.svg';
import grapesColor from './icons/food-drink/food-fruit/grapes_color.svg';
import greenApple from './icons/food-drink/food-fruit/green-apple.svg';
import greenAppleColor from './icons/food-drink/food-fruit/green-apple_color.svg';
import kiwiFruit from './icons/food-drink/food-fruit/kiwi-fruit.svg';
import kiwiFruitColor from './icons/food-drink/food-fruit/kiwi-fruit_color.svg';
import lemon from './icons/food-drink/food-fruit/lemon.svg';
import lemonColor from './icons/food-drink/food-fruit/lemon_color.svg';
import mango from './icons/food-drink/food-fruit/mango.svg';
import mangoColor from './icons/food-drink/food-fruit/mango_color.svg';
import melon from './icons/food-drink/food-fruit/melon.svg';
import melonColor from './icons/food-drink/food-fruit/melon_color.svg';
import olive from './icons/food-drink/food-fruit/olive.svg';
import oliveColor from './icons/food-drink/food-fruit/olive_color.svg';
import peach from './icons/food-drink/food-fruit/peach.svg';
import peachColor from './icons/food-drink/food-fruit/peach_color.svg';
import pear from './icons/food-drink/food-fruit/pear.svg';
import pearColor from './icons/food-drink/food-fruit/pear_color.svg';
import pineapple from './icons/food-drink/food-fruit/pineapple.svg';
import pineappleColor from './icons/food-drink/food-fruit/pineapple_color.svg';
import redApple from './icons/food-drink/food-fruit/red-apple.svg';
import redAppleColor from './icons/food-drink/food-fruit/red-apple_color.svg';
import strawberry from './icons/food-drink/food-fruit/strawberry.svg';
import strawberryColor from './icons/food-drink/food-fruit/strawberry_color.svg';
import tangerine from './icons/food-drink/food-fruit/tangerine.svg';
import tangerineColor from './icons/food-drink/food-fruit/tangerine_color.svg';
import tomato from './icons/food-drink/food-fruit/tomato.svg';
import tomatoColor from './icons/food-drink/food-fruit/tomato_color.svg';
import watermelon from './icons/food-drink/food-fruit/watermelon.svg';
import watermelonColor from './icons/food-drink/food-fruit/watermelon_color.svg';
import crab from './icons/food-drink/food-marine/crab.svg';
import crabColor from './icons/food-drink/food-marine/crab_color.svg';
import lobster from './icons/food-drink/food-marine/lobster.svg';
import lobsterColor from './icons/food-drink/food-marine/lobster_color.svg';
import oyster from './icons/food-drink/food-marine/oyster.svg';
import oysterColor from './icons/food-drink/food-marine/oyster_color.svg';
import shrimp from './icons/food-drink/food-marine/shrimp.svg';
import shrimpColor from './icons/food-drink/food-marine/shrimp_color.svg';
import squid from './icons/food-drink/food-marine/squid.svg';
import squidColor from './icons/food-drink/food-marine/squid_color.svg';
import bacon from './icons/food-drink/food-prepared/bacon.svg';
import baconColor from './icons/food-drink/food-prepared/bacon_color.svg';
import bagel from './icons/food-drink/food-prepared/bagel.svg';
import bagelColor from './icons/food-drink/food-prepared/bagel_color.svg';
import baguetteBread from './icons/food-drink/food-prepared/baguette-bread.svg';
import baguetteBreadColor from './icons/food-drink/food-prepared/baguette-bread_color.svg';
import bowlWithSpoon from './icons/food-drink/food-prepared/bowl-with-spoon.svg';
import bowlWithSpoonColor from './icons/food-drink/food-prepared/bowl-with-spoon_color.svg';
import bread from './icons/food-drink/food-prepared/bread.svg';
import breadColor from './icons/food-drink/food-prepared/bread_color.svg';
import burrito from './icons/food-drink/food-prepared/burrito.svg';
import burritoColor from './icons/food-drink/food-prepared/burrito_color.svg';
import butter from './icons/food-drink/food-prepared/butter.svg';
import butterColor from './icons/food-drink/food-prepared/butter_color.svg';
import cannedFood from './icons/food-drink/food-prepared/canned-food.svg';
import cannedFoodColor from './icons/food-drink/food-prepared/canned-food_color.svg';
import cheeseWedge from './icons/food-drink/food-prepared/cheese-wedge.svg';
import cheeseWedgeColor from './icons/food-drink/food-prepared/cheese-wedge_color.svg';
import cooking from './icons/food-drink/food-prepared/cooking.svg';
import cookingColor from './icons/food-drink/food-prepared/cooking_color.svg';
import croissant from './icons/food-drink/food-prepared/croissant.svg';
import croissantColor from './icons/food-drink/food-prepared/croissant_color.svg';
import cutOfMeat from './icons/food-drink/food-prepared/cut-of-meat.svg';
import cutOfMeatColor from './icons/food-drink/food-prepared/cut-of-meat_color.svg';
import egg from './icons/food-drink/food-prepared/egg.svg';
import eggColor from './icons/food-drink/food-prepared/egg_color.svg';
import falafel from './icons/food-drink/food-prepared/falafel.svg';
import falafelColor from './icons/food-drink/food-prepared/falafel_color.svg';
import flatbread from './icons/food-drink/food-prepared/flatbread.svg';
import flatbreadColor from './icons/food-drink/food-prepared/flatbread_color.svg';
import fondue from './icons/food-drink/food-prepared/fondue.svg';
import fondueColor from './icons/food-drink/food-prepared/fondue_color.svg';
import frenchFries from './icons/food-drink/food-prepared/french-fries.svg';
import frenchFriesColor from './icons/food-drink/food-prepared/french-fries_color.svg';
import greenSalad from './icons/food-drink/food-prepared/green-salad.svg';
import greenSaladColor from './icons/food-drink/food-prepared/green-salad_color.svg';
import hamburger from './icons/food-drink/food-prepared/hamburger.svg';
import hamburgerColor from './icons/food-drink/food-prepared/hamburger_color.svg';
import hotDog from './icons/food-drink/food-prepared/hot-dog.svg';
import hotDogColor from './icons/food-drink/food-prepared/hot-dog_color.svg';
import meatOnBone from './icons/food-drink/food-prepared/meat-on-bone.svg';
import meatOnBoneColor from './icons/food-drink/food-prepared/meat-on-bone_color.svg';
import pancakes from './icons/food-drink/food-prepared/pancakes.svg';
import pancakesColor from './icons/food-drink/food-prepared/pancakes_color.svg';
import pizza from './icons/food-drink/food-prepared/pizza.svg';
import pizzaColor from './icons/food-drink/food-prepared/pizza_color.svg';
import popcorn from './icons/food-drink/food-prepared/popcorn.svg';
import popcornColor from './icons/food-drink/food-prepared/popcorn_color.svg';
import potOfFood from './icons/food-drink/food-prepared/pot-of-food.svg';
import potOfFoodColor from './icons/food-drink/food-prepared/pot-of-food_color.svg';
import poultryLeg from './icons/food-drink/food-prepared/poultry-leg.svg';
import poultryLegColor from './icons/food-drink/food-prepared/poultry-leg_color.svg';
import pretzel from './icons/food-drink/food-prepared/pretzel.svg';
import pretzelColor from './icons/food-drink/food-prepared/pretzel_color.svg';
import salt from './icons/food-drink/food-prepared/salt.svg';
import saltColor from './icons/food-drink/food-prepared/salt_color.svg';
import sandwich from './icons/food-drink/food-prepared/sandwich.svg';
import sandwichColor from './icons/food-drink/food-prepared/sandwich_color.svg';
import shallowPanOfFood from './icons/food-drink/food-prepared/shallow-pan-of-food.svg';
import shallowPanOfFoodColor from './icons/food-drink/food-prepared/shallow-pan-of-food_color.svg';
import stuffedFlatbread from './icons/food-drink/food-prepared/stuffed-flatbread.svg';
import stuffedFlatbreadColor from './icons/food-drink/food-prepared/stuffed-flatbread_color.svg';
import taco from './icons/food-drink/food-prepared/taco.svg';
import tacoColor from './icons/food-drink/food-prepared/taco_color.svg';
import tamale from './icons/food-drink/food-prepared/tamale.svg';
import tamaleColor from './icons/food-drink/food-prepared/tamale_color.svg';
import waffle from './icons/food-drink/food-prepared/waffle.svg';
import waffleColor from './icons/food-drink/food-prepared/waffle_color.svg';
import birthdayCake from './icons/food-drink/food-sweet/birthday-cake.svg';
import birthdayCakeColor from './icons/food-drink/food-sweet/birthday-cake_color.svg';
import candy from './icons/food-drink/food-sweet/candy.svg';
import candyColor from './icons/food-drink/food-sweet/candy_color.svg';
import chocolateBar from './icons/food-drink/food-sweet/chocolate-bar.svg';
import chocolateBarColor from './icons/food-drink/food-sweet/chocolate-bar_color.svg';
import cookie from './icons/food-drink/food-sweet/cookie.svg';
import cookieColor from './icons/food-drink/food-sweet/cookie_color.svg';
import cupcake from './icons/food-drink/food-sweet/cupcake.svg';
import cupcakeColor from './icons/food-drink/food-sweet/cupcake_color.svg';
import custard from './icons/food-drink/food-sweet/custard.svg';
import custardColor from './icons/food-drink/food-sweet/custard_color.svg';
import doughnut from './icons/food-drink/food-sweet/doughnut.svg';
import doughnutColor from './icons/food-drink/food-sweet/doughnut_color.svg';
import honeyPot from './icons/food-drink/food-sweet/honey-pot.svg';
import honeyPotColor from './icons/food-drink/food-sweet/honey-pot_color.svg';
import iceCream from './icons/food-drink/food-sweet/ice-cream.svg';
import iceCreamColor from './icons/food-drink/food-sweet/ice-cream_color.svg';
import lollipop from './icons/food-drink/food-sweet/lollipop.svg';
import lollipopColor from './icons/food-drink/food-sweet/lollipop_color.svg';
import pie from './icons/food-drink/food-sweet/pie.svg';
import pieColor from './icons/food-drink/food-sweet/pie_color.svg';
import shavedIce from './icons/food-drink/food-sweet/shaved-ice.svg';
import shavedIceColor from './icons/food-drink/food-sweet/shaved-ice_color.svg';
import shortcake from './icons/food-drink/food-sweet/shortcake.svg';
import shortcakeColor from './icons/food-drink/food-sweet/shaved-ice_color.svg';
import softIceCream from './icons/food-drink/food-sweet/soft-ice-cream.svg';
import softIceCreamColor from './icons/food-drink/food-sweet/soft-ice-cream_color.svg';
import avocado from './icons/food-drink/food-vegetable/avocado.svg';
import avocadoColor from './icons/food-drink/food-vegetable/avocado_color.svg';
import beans from './icons/food-drink/food-vegetable/beans.svg';
import beansColor from './icons/food-drink/food-vegetable/beans_color.svg';
import bellPepper from './icons/food-drink/food-vegetable/bell-pepper.svg';
import bellPepperColor from './icons/food-drink/food-vegetable/bell-pepper_color.svg';
import broccoli from './icons/food-drink/food-vegetable/broccoli.svg';
import broccoliColor from './icons/food-drink/food-vegetable/broccoli_color.svg';
import carrot from './icons/food-drink/food-vegetable/carrot.svg';
import carrotColor from './icons/food-drink/food-vegetable/carrot_color.svg';
import chestnut from './icons/food-drink/food-vegetable/chestnut.svg';
import chestnutColor from './icons/food-drink/food-vegetable/chestnut_color.svg';
import cucumber from './icons/food-drink/food-vegetable/cucumber.svg';
import cucumberColor from './icons/food-drink/food-vegetable/cucumber_color.svg';
import earOfCorn from './icons/food-drink/food-vegetable/ear-of-corn.svg';
import earOfCornColor from './icons/food-drink/food-vegetable/ear-of-corn_color.svg';
import eggplant from './icons/food-drink/food-vegetable/eggplant.svg';
import eggplantColor from './icons/food-drink/food-vegetable/eggplant_color.svg';
import garlic from './icons/food-drink/food-vegetable/garlic.svg';
import garlicColor from './icons/food-drink/food-vegetable/garlic_color.svg';
import hotPepper from './icons/food-drink/food-vegetable/hot-pepper.svg';
import hotPepperColor from './icons/food-drink/food-vegetable/hot-pepper_color.svg';
import leafyGreen from './icons/food-drink/food-vegetable/leafy-green.svg';
import leafyGreenColor from './icons/food-drink/food-vegetable/leafy-green_color.svg';
import mushroom from './icons/food-drink/food-vegetable/mushroom.svg';
import mushroomColor from './icons/food-drink/food-vegetable/mushroom_color.svg';
import onion from './icons/food-drink/food-vegetable/onion.svg';
import onionColor from './icons/food-drink/food-vegetable/onion_color.svg';
import peanuts from './icons/food-drink/food-vegetable/peanuts.svg';
import peanutsColor from './icons/food-drink/food-vegetable/peanuts_color.svg';
import potato from './icons/food-drink/food-vegetable/potato.svg';
import potatoColor from './icons/food-drink/food-vegetable/potato_color.svg';

import {IconProps} from './use-search';

export const openFoodDrinkTable = new Map<string, Omit<IconProps, 'id'>>();

openFoodDrinkTable.set('amphora', {name: 'Amphora', icon: amphora});
openFoodDrinkTable.set('amphoraColor', {name: 'Amphora Color', icon: amphoraColor});
openFoodDrinkTable.set('chopsticks', {name: 'Chopsticks', icon: chopsticks});
openFoodDrinkTable.set('chopsticksColor', {name: 'Chopsticks Color', icon: chopsticksColor});
openFoodDrinkTable.set('forkAndKnife', {name: 'Fork And Knife', icon: forkAndKnife});
openFoodDrinkTable.set('forkAndKnifeColor', {name: 'Fork And Knife Color', icon: forkAndKnifeColor});
openFoodDrinkTable.set('forkAndKnifeWithPlate', {name: 'Fork And Knife With Plate', icon: forkAndKnifeWithPlate});
openFoodDrinkTable.set('forkAndKnifeWithPlateColor', {
    name: 'Fork And Knife With Plate Color',
    icon: forkAndKnifeWithPlateColor,
});
openFoodDrinkTable.set('jar', {name: 'Jar', icon: jar});
openFoodDrinkTable.set('jarColor', {name: 'Jar Color', icon: jarColor});
openFoodDrinkTable.set('kitchenKnife', {name: 'Kitchen Knife', icon: kitchenKnife});
openFoodDrinkTable.set('kitchenKnifeColor', {name: 'Kitchen Knife Color', icon: kitchenKnifeColor});
openFoodDrinkTable.set('spoon', {name: 'Spoon', icon: spoon});
openFoodDrinkTable.set('spoonColor', {name: 'Spoon Color', icon: spoonColor});
openFoodDrinkTable.set('babyBottle', {name: 'Baby Bottle', icon: babyBottle});
openFoodDrinkTable.set('babyBottleColor', {name: 'Baby Bottle Color', icon: babyBottleColor});
openFoodDrinkTable.set('beerMug', {name: 'Beer Mug', icon: beerMug});
openFoodDrinkTable.set('beerMugColor', {name: 'Beer Mug Color', icon: beerMugColor});
openFoodDrinkTable.set('beverageBox', {name: 'Beverage Box', icon: beverageBox});
openFoodDrinkTable.set('beverageBoxColor', {name: 'Beverage Box Color', icon: beverageBoxColor});
openFoodDrinkTable.set('bottleWithPoppingCork', {name: 'Bottle With Popping Cork', icon: bottleWithPoppingCork});
openFoodDrinkTable.set('bottleWithPoppingCorkColor', {
    name: 'Bottle With Popping Cork Color',
    icon: bottleWithPoppingCorkColor,
});
openFoodDrinkTable.set('bubbleTea', {name: 'Bubble Tea', icon: bubbleTea});
openFoodDrinkTable.set('bubbleTeaColor', {name: 'Bubble Tea Color', icon: bubbleTeaColor});
openFoodDrinkTable.set('clinkingBeerMugs', {name: 'Clinking Beer Mugs', icon: clinkingBeerMugs});
openFoodDrinkTable.set('clinkingBeerMugsColor', {name: 'Clinking Beer Mugs Color', icon: clinkingBeerMugsColor});
openFoodDrinkTable.set('clinkingGlasses', {name: 'Clinking Glasses', icon: clinkingGlasses});
openFoodDrinkTable.set('clinkingGlassesColor', {name: 'Clinking Glasses Color', icon: clinkingGlassesColor});
openFoodDrinkTable.set('cocktailGlass', {name: 'Cocktail Glass', icon: cocktailGlass});
openFoodDrinkTable.set('cocktailGlassColor', {name: 'Cocktail Glass Color', icon: cocktailGlassColor});
openFoodDrinkTable.set('cupWithStraw', {name: 'Cup With Straw', icon: cupWithStraw});
openFoodDrinkTable.set('cupWithStrawColor', {name: 'Cup With Straw Color', icon: cupWithStrawColor});
openFoodDrinkTable.set('glassOfMilk', {name: 'Glass Of Milk', icon: glassOfMilk});
openFoodDrinkTable.set('glassOfMilkColor', {name: 'Glass Of Milk Color', icon: glassOfMilkColor});
openFoodDrinkTable.set('hotBeverage', {name: 'Hot Beverage', icon: hotBeverage});
openFoodDrinkTable.set('hotBeverageColor', {name: 'Hot Beverage Color', icon: hotBeverageColor});
openFoodDrinkTable.set('ice', {name: 'Ice', icon: ice});
openFoodDrinkTable.set('iceColor', {name: 'Ice Color', icon: iceColor});
openFoodDrinkTable.set('mate', {name: 'Mate', icon: mate});
openFoodDrinkTable.set('mateColor', {name: 'Mate Color', icon: mateColor});
openFoodDrinkTable.set('pouringLiquid', {name: 'Pouring Liquid', icon: pouringLiquid});
openFoodDrinkTable.set('pouringLiquidColor', {name: 'Pouring Liquid Color', icon: pouringLiquidColor});
openFoodDrinkTable.set('sake', {name: 'Sake', icon: sake});
openFoodDrinkTable.set('sakeColor', {name: 'Sake Color', icon: sakeColor});
openFoodDrinkTable.set('teacupWithoutHandle', {name: 'Teacup Without Handle', icon: teacupWithoutHandle});
openFoodDrinkTable.set('teacupWithoutHandleColor', {
    name: 'Teacup Without Handle Color',
    icon: teacupWithoutHandleColor,
});
openFoodDrinkTable.set('teapot', {name: 'Teapot', icon: teapot});
openFoodDrinkTable.set('teapotColor', {name: 'Teapot Color', icon: teapotColor});
openFoodDrinkTable.set('tropicalDrink', {name: 'Tropical Drink', icon: tropicalDrink});
openFoodDrinkTable.set('tropicalDrinkColor', {name: 'Tropical Drink Color', icon: tropicalDrinkColor});
openFoodDrinkTable.set('tumblerGlass', {name: 'Tumbler Glass', icon: tumblerGlass});
openFoodDrinkTable.set('tumblerGlassColor', {name: 'Tumbler Glass Color', icon: tumblerGlassColor});
openFoodDrinkTable.set('wineGlass', {name: 'Wine Glass', icon: wineGlass});
openFoodDrinkTable.set('wineGlassColor', {name: 'Wine Glass Color', icon: wineGlassColor});
openFoodDrinkTable.set('bentoBox', {name: 'Bento Box', icon: bentoBox});
openFoodDrinkTable.set('bentoBoxColor', {name: 'Bento Box Color', icon: bentoBoxColor});
openFoodDrinkTable.set('cookedRice', {name: 'Cooked Rice', icon: cookedRice});
openFoodDrinkTable.set('cookedRiceColor', {name: 'Cooked Rice Color', icon: cookedRiceColor});
openFoodDrinkTable.set('curryRice', {name: 'Curry Rice', icon: curryRice});
openFoodDrinkTable.set('curryRiceColor', {name: 'Curry Rice Color', icon: curryRiceColor});
openFoodDrinkTable.set('dango', {name: 'Dango', icon: dango});
openFoodDrinkTable.set('dangoColor', {name: 'Dango Color', icon: dangoColor});
openFoodDrinkTable.set('dumpling', {name: 'Dumpling', icon: dumpling});
openFoodDrinkTable.set('dumplingColor', {name: 'Dumpling Color', icon: dumplingColor});
openFoodDrinkTable.set('fishCakeWithSwirl', {name: 'Fish Caked With Swirl', icon: fishCakeWithSwirl});
openFoodDrinkTable.set('fishCakeWithSwirlColor', {name: 'Fish Cake With Swirl Color', icon: fishCakeWithSwirlColor});
openFoodDrinkTable.set('fortuneCookie', {name: 'Fortune Cookie', icon: fortuneCookie});
openFoodDrinkTable.set('fortuneCookieColor', {name: 'Fortune Cookie Color', icon: fortuneCookieColor});
openFoodDrinkTable.set('friedShrimp', {name: 'Fried Shrimp', icon: friedShrimp});
openFoodDrinkTable.set('friedShrimpColor', {name: 'Fried Shrimp Color', icon: friedShrimpColor});
openFoodDrinkTable.set('moonCake', {name: 'Moon Cake', icon: moonCake});
openFoodDrinkTable.set('moonCakeColor', {name: 'Moon Cake Color', icon: moonCakeColor});
openFoodDrinkTable.set('oden', {name: 'Oden', icon: oden});
openFoodDrinkTable.set('odenColor', {name: 'Oden Color', icon: odenColor});
openFoodDrinkTable.set('riceBall', {name: 'Rice Ball', icon: riceBall});
openFoodDrinkTable.set('riceBallColor', {name: 'Rice Ball Color', icon: riceBallColor});
openFoodDrinkTable.set('riceCracker', {name: 'Rice Cracker', icon: riceCracker});
openFoodDrinkTable.set('riceCrackerColor', {name: 'Rice Cracker Color', icon: riceCrackerColor});
openFoodDrinkTable.set('roastedSweetPotato', {name: 'Roasted Sweet Potato', icon: roastedSweetPotato});
openFoodDrinkTable.set('roastedSweetPotatoColor', {name: 'Roasted Sweet Potato Color', icon: roastedSweetPotatoColor});
openFoodDrinkTable.set('spaghetti', {name: 'Spaghetti', icon: spaghetti});
openFoodDrinkTable.set('spaghettiColor', {name: 'Spaghetti Color', icon: spaghettiColor});
openFoodDrinkTable.set('steamingBowl', {name: 'Steaming Bowl', icon: steamingBowl});
openFoodDrinkTable.set('steamingBowlColor', {name: 'Steaming Bowl Color', icon: steamingBowlColor});
openFoodDrinkTable.set('sushi', {name: 'Sushi', icon: sushi});
openFoodDrinkTable.set('sushiColor', {name: 'Sushi Color', icon: sushiColor});
openFoodDrinkTable.set('takeoutBox', {name: 'Takeout Box Color', icon: takeoutBox});
openFoodDrinkTable.set('takeoutBoxColor', {name: 'Takeout Box Color', icon: takeoutBoxColor});
openFoodDrinkTable.set('banana', {name: 'Banana', icon: banana});
openFoodDrinkTable.set('bananaColor', {name: 'Banana Color', icon: bananaColor});
openFoodDrinkTable.set('blueberries', {name: 'Blueberries', icon: blueberries});
openFoodDrinkTable.set('blueberriesColor', {name: 'Blueberries Color', icon: blueberriesColor});
openFoodDrinkTable.set('cherries', {name: 'Cherries', icon: cherries});
openFoodDrinkTable.set('cherriesColor', {name: 'Cherries Color', icon: cherriesColor});
openFoodDrinkTable.set('coconut', {name: 'Coconut', icon: coconut});
openFoodDrinkTable.set('coconutColor', {name: 'Coconut Color', icon: coconutColor});
openFoodDrinkTable.set('grapes', {name: 'Grapes', icon: grapes});
openFoodDrinkTable.set('grapesColor', {name: 'Grapes Color', icon: grapesColor});
openFoodDrinkTable.set('greenApple', {name: 'Green Apple', icon: greenApple});
openFoodDrinkTable.set('greenAppleColor', {name: 'Green Apple Color', icon: greenAppleColor});
openFoodDrinkTable.set('kiwiFruit', {name: 'Kiwi Fruit', icon: kiwiFruit});
openFoodDrinkTable.set('kiwiFruitColor', {name: 'Kiwi Fruit Color', icon: kiwiFruitColor});
openFoodDrinkTable.set('lemon', {name: 'Lemon', icon: lemon});
openFoodDrinkTable.set('lemonColor', {name: 'Lemon Color', icon: lemonColor});
openFoodDrinkTable.set('mango', {name: 'Mango', icon: mango});
openFoodDrinkTable.set('mangoColor', {name: 'Mango Color', icon: mangoColor});
openFoodDrinkTable.set('melon', {name: 'Melon', icon: melon});
openFoodDrinkTable.set('melonColor', {name: 'Melon Color', icon: melonColor});
openFoodDrinkTable.set('olive', {name: 'Olive', icon: olive});
openFoodDrinkTable.set('oliveColor', {name: 'Olive Color', icon: oliveColor});
openFoodDrinkTable.set('peach', {name: 'Peach', icon: peach});
openFoodDrinkTable.set('peachColor', {name: 'Peach Color', icon: peachColor});
openFoodDrinkTable.set('pear', {name: 'Pear', icon: pear});
openFoodDrinkTable.set('pearColor', {name: 'Pear Color', icon: pearColor});
openFoodDrinkTable.set('pineapple', {name: 'Pineapple', icon: pineapple});
openFoodDrinkTable.set('pineappleColor', {name: 'Pineapple Color', icon: pineappleColor});
openFoodDrinkTable.set('redApple', {name: 'Red Apple', icon: redApple});
openFoodDrinkTable.set('redAppleColor', {name: 'Red Apple Color', icon: redAppleColor});
openFoodDrinkTable.set('strawberry', {name: 'Strawberry', icon: strawberry});
openFoodDrinkTable.set('strawberryColor', {name: 'Strawberry Color', icon: strawberryColor});
openFoodDrinkTable.set('tangerine', {name: 'Tangerine', icon: tangerine});
openFoodDrinkTable.set('tangerineColor', {name: 'Tangerine Color', icon: tangerineColor});
openFoodDrinkTable.set('tomato', {name: 'Tomato', icon: tomato});
openFoodDrinkTable.set('tomatoColor', {name: 'Tomato Color', icon: tomatoColor});
openFoodDrinkTable.set('watermelon', {name: 'Watermelon', icon: watermelon});
openFoodDrinkTable.set('watermelonColor', {name: 'Watermelon Color', icon: watermelonColor});
openFoodDrinkTable.set('crab', {name: 'Crab', icon: crab});
openFoodDrinkTable.set('crabColor', {name: 'Crab Color', icon: crabColor});
openFoodDrinkTable.set('lobster', {name: 'Lobster', icon: lobster});
openFoodDrinkTable.set('lobsterColor', {name: 'Lobster Color', icon: lobsterColor});
openFoodDrinkTable.set('oyster', {name: 'Oyster', icon: oyster});
openFoodDrinkTable.set('oysterColor', {name: 'Oyster Color', icon: oysterColor});
openFoodDrinkTable.set('shrimp', {name: 'Shrimp', icon: shrimp});
openFoodDrinkTable.set('shrimpColor', {name: 'Shrimp Color', icon: shrimpColor});
openFoodDrinkTable.set('squid', {name: 'Squid', icon: squid});
openFoodDrinkTable.set('squidColor', {name: 'Squid Color', icon: squidColor});
openFoodDrinkTable.set('bacon', {name: 'Bacon', icon: bacon});
openFoodDrinkTable.set('baconColor', {name: 'Bacon Color', icon: baconColor});
openFoodDrinkTable.set('bagel', {name: 'Bagel', icon: bagel});
openFoodDrinkTable.set('bagelColor', {name: 'Bagel Color', icon: bagelColor});
openFoodDrinkTable.set('baguetteBread', {name: 'Baguette Bread', icon: baguetteBread});
openFoodDrinkTable.set('baguetteBreadColor', {name: 'Baguette Bread Color', icon: baguetteBreadColor});
openFoodDrinkTable.set('bowlWithSpoon', {name: 'Bowl With Spoon', icon: bowlWithSpoon});
openFoodDrinkTable.set('bowlWithSpoonColor', {name: 'Bowl With Spoon Color', icon: bowlWithSpoonColor});
openFoodDrinkTable.set('bread', {name: 'Bread', icon: bread});
openFoodDrinkTable.set('breadColor', {name: 'Bread Color', icon: breadColor});
openFoodDrinkTable.set('burrito', {name: 'Burrito', icon: burrito});
openFoodDrinkTable.set('burritoColor', {name: 'Burrito Color', icon: burritoColor});
openFoodDrinkTable.set('butter', {name: 'Butter', icon: butter});
openFoodDrinkTable.set('butterColor', {name: 'Butter Color', icon: butterColor});
openFoodDrinkTable.set('cannedFood', {name: 'Canned Food', icon: cannedFood});
openFoodDrinkTable.set('cannedFoodColor', {name: 'Canned Food Color', icon: cannedFoodColor});
openFoodDrinkTable.set('cheeseWedge', {name: 'Cheese Wedge', icon: cheeseWedge});
openFoodDrinkTable.set('cheeseWedgeColor', {name: 'Cheese Wedge Color', icon: cheeseWedgeColor});
openFoodDrinkTable.set('cooking', {name: 'Cooking', icon: cooking});
openFoodDrinkTable.set('cookingColor', {name: 'Cooking Color', icon: cookingColor});
openFoodDrinkTable.set('croissant', {name: 'Croissant', icon: croissant});
openFoodDrinkTable.set('croissantColor', {name: 'Croissant Color', icon: croissantColor});
openFoodDrinkTable.set('cutOfMeat', {name: 'Cut Of Meat', icon: cutOfMeat});
openFoodDrinkTable.set('cutOfMeatColor', {name: 'Cut Of Meat Color', icon: cutOfMeatColor});
openFoodDrinkTable.set('egg', {name: 'Egg', icon: egg});
openFoodDrinkTable.set('eggColor', {name: 'Egg Color', icon: eggColor});
openFoodDrinkTable.set('falafel', {name: 'Falafel', icon: falafel});
openFoodDrinkTable.set('falafelColor', {name: 'Falafel Color', icon: falafelColor});
openFoodDrinkTable.set('flatbread', {name: 'Flatbread', icon: flatbread});
openFoodDrinkTable.set('flatbreadColor', {name: 'Flatbread Color', icon: flatbreadColor});
openFoodDrinkTable.set('fondue', {name: 'Fondue', icon: fondue});
openFoodDrinkTable.set('fondueColor', {name: 'Fondue Color', icon: fondueColor});
openFoodDrinkTable.set('frenchFries', {name: 'French Fries', icon: frenchFries});
openFoodDrinkTable.set('frenchFriesColor', {name: 'French Fries Color', icon: frenchFriesColor});
openFoodDrinkTable.set('greenSalad', {name: 'Green Salad', icon: greenSalad});
openFoodDrinkTable.set('greenSaladColor', {name: 'Green Salad Color', icon: greenSaladColor});
openFoodDrinkTable.set('hamburger', {name: 'Hamburger', icon: hamburger});
openFoodDrinkTable.set('hamburgerColor', {name: 'Hamburger Color', icon: hamburgerColor});
openFoodDrinkTable.set('hotDog', {name: 'Hot Dog', icon: hotDog});
openFoodDrinkTable.set('hotDogColor', {name: 'Hot Dog Color', icon: hotDogColor});
openFoodDrinkTable.set('meatOnBone', {name: 'Meat On Bone', icon: meatOnBone});
openFoodDrinkTable.set('meatOnBoneColor', {name: 'Meat On Bone Color', icon: meatOnBoneColor});
openFoodDrinkTable.set('pancakes', {name: 'Pancakes', icon: pancakes});
openFoodDrinkTable.set('pancakesColor', {name: 'Pancakes Color', icon: pancakesColor});
openFoodDrinkTable.set('pizza', {name: 'Pizza', icon: pizza});
openFoodDrinkTable.set('pizzaColor', {name: 'Pizza Color', icon: pizzaColor});
openFoodDrinkTable.set('popcorn', {name: 'Popcorn', icon: popcorn});
openFoodDrinkTable.set('popcornColor', {name: 'Popcorn Color', icon: popcornColor});
openFoodDrinkTable.set('potOfFood', {name: 'Pot Of Food', icon: potOfFood});
openFoodDrinkTable.set('potOfFoodColor', {name: 'Pot Of Food Color', icon: potOfFoodColor});
openFoodDrinkTable.set('poultryLeg', {name: 'Poultry Leg', icon: poultryLeg});
openFoodDrinkTable.set('poultryLegColor', {name: 'Poultry Leg Color', icon: poultryLegColor});
openFoodDrinkTable.set('pretzel', {name: 'Pretzel', icon: pretzel});
openFoodDrinkTable.set('pretzelColor', {name: 'Pretzel Color', icon: pretzelColor});
openFoodDrinkTable.set('salt', {name: 'Salt', icon: salt});
openFoodDrinkTable.set('saltColor', {name: 'Salt Color', icon: saltColor});
openFoodDrinkTable.set('sandwich', {name: 'Sandwich', icon: sandwich});
openFoodDrinkTable.set('sandwichColor', {name: 'Sandwich Color', icon: sandwichColor});
openFoodDrinkTable.set('shallowPanOfFood', {name: 'Shallow Pan Of Food', icon: shallowPanOfFood});
openFoodDrinkTable.set('shallowPanOfFoodColor', {name: 'Shallow Pan Of Food Color', icon: shallowPanOfFoodColor});
openFoodDrinkTable.set('stuffedFlatbread', {name: 'Stuffed Flatbread', icon: stuffedFlatbread});
openFoodDrinkTable.set('stuffedFlatbreadColor', {name: 'Stuffed Flat Bread Color', icon: stuffedFlatbreadColor});
openFoodDrinkTable.set('taco', {name: 'Taco', icon: taco});
openFoodDrinkTable.set('tacoColor', {name: 'Taco Color', icon: tacoColor});
openFoodDrinkTable.set('tamale', {name: 'Tamale', icon: tamale});
openFoodDrinkTable.set('tamaleColor', {name: 'Tamale Color', icon: tamaleColor});
openFoodDrinkTable.set('waffle', {name: 'Waffle', icon: waffle});
openFoodDrinkTable.set('waffleColor', {name: 'Waffle Color', icon: waffleColor});
openFoodDrinkTable.set('birthdayCake', {name: 'Birthday Cake', icon: birthdayCake});
openFoodDrinkTable.set('birthdayCakeColor', {name: 'Birthday Cake Color', icon: birthdayCakeColor});
openFoodDrinkTable.set('candy', {name: 'Candy', icon: candy});
openFoodDrinkTable.set('candyColor', {name: 'Candy Color', icon: candyColor});
openFoodDrinkTable.set('chocolateBar', {name: 'Chocolate Bar', icon: chocolateBar});
openFoodDrinkTable.set('chocolateBarColor', {name: 'Chocolate Bar Color', icon: chocolateBarColor});
openFoodDrinkTable.set('cookie', {name: 'Cookie', icon: cookie});
openFoodDrinkTable.set('cookieColor', {name: 'Cookie Color', icon: cookieColor});
openFoodDrinkTable.set('cupcake', {name: 'Cupcake', icon: cupcake});
openFoodDrinkTable.set('cupcakeColor', {name: 'Cupcake Color', icon: cupcakeColor});
openFoodDrinkTable.set('custard', {name: 'Custard', icon: custard});
openFoodDrinkTable.set('custardColor', {name: 'Custard Color', icon: custardColor});
openFoodDrinkTable.set('doughnut', {name: 'Doughnut', icon: doughnut});
openFoodDrinkTable.set('doughnutColor', {name: 'Doughnut Color', icon: doughnutColor});
openFoodDrinkTable.set('honeyPot', {name: 'Honey Pot', icon: honeyPot});
openFoodDrinkTable.set('honeyPotColor', {name: 'Honey Pot Color', icon: honeyPotColor});
openFoodDrinkTable.set('iceCream', {name: 'Ice Cream', icon: iceCream});
openFoodDrinkTable.set('iceCreamColor', {name: 'Ice Cream Color', icon: iceCreamColor});
openFoodDrinkTable.set('lollipop', {name: 'Lollipop', icon: lollipop});
openFoodDrinkTable.set('lollipopColor', {name: 'Lollipop Color', icon: lollipopColor});
openFoodDrinkTable.set('pie', {name: 'Pie', icon: pie});
openFoodDrinkTable.set('pieColor', {name: 'Pie Color', icon: pieColor});
openFoodDrinkTable.set('shavedIce', {name: 'Shaved Ice', icon: shavedIce});
openFoodDrinkTable.set('shavedIceColor', {name: 'Shaved Ice Color', icon: shavedIceColor});
openFoodDrinkTable.set('shortcake', {name: 'Shortcake', icon: shortcake});
openFoodDrinkTable.set('shortcakeColor', {name: 'Shortcake Color', icon: shortcakeColor});
openFoodDrinkTable.set('softIceCream', {name: 'Soft Ice Cream', icon: softIceCream});
openFoodDrinkTable.set('softIceCreamColor', {name: 'Soft Ice Cream Color', icon: softIceCreamColor});
openFoodDrinkTable.set('avocado', {name: 'Avocado', icon: avocado});
openFoodDrinkTable.set('avocadoColor', {name: 'Avocado Color', icon: avocadoColor});
openFoodDrinkTable.set('beans', {name: 'Beans', icon: beans});
openFoodDrinkTable.set('beansColor', {name: 'Beans Color', icon: beansColor});
openFoodDrinkTable.set('bellPepper', {name: 'Bell Pepper', icon: bellPepper});
openFoodDrinkTable.set('bellPepperColor', {name: 'Bell Pepper Color', icon: bellPepperColor});
openFoodDrinkTable.set('broccoli', {name: 'Broccoli', icon: broccoli});
openFoodDrinkTable.set('broccoliColor', {name: 'Broccoli Color', icon: broccoliColor});
openFoodDrinkTable.set('carrot', {name: 'Carrot', icon: carrot});
openFoodDrinkTable.set('carrotColor', {name: 'Carrot Color', icon: carrotColor});
openFoodDrinkTable.set('chestnut', {name: 'Chestnut', icon: chestnut});
openFoodDrinkTable.set('chestnutColor', {name: 'Chestnut Color', icon: chestnutColor});
openFoodDrinkTable.set('cucumber', {name: 'Cucumber', icon: cucumber});
openFoodDrinkTable.set('cucumberColor', {name: 'Cucumber Color', icon: cucumberColor});
openFoodDrinkTable.set('earOfCorn', {name: 'Ear Of Corn', icon: earOfCorn});
openFoodDrinkTable.set('earOfCornColor', {name: 'Ear Of Corn Color', icon: earOfCornColor});
openFoodDrinkTable.set('eggplant', {name: 'Eggplant', icon: eggplant});
openFoodDrinkTable.set('eggplantColor', {name: 'Eggplant Color', icon: eggplantColor});
openFoodDrinkTable.set('garlic', {name: 'Garlic', icon: garlic});
openFoodDrinkTable.set('garlicColor', {name: 'Garlic Color', icon: garlicColor});
openFoodDrinkTable.set('hotPepper', {name: 'Hot Pepper', icon: hotPepper});
openFoodDrinkTable.set('hotPepperColor', {name: 'Hot Pepper Color', icon: hotPepperColor});
openFoodDrinkTable.set('leafyGreen', {name: 'Leafy Green', icon: leafyGreen});
openFoodDrinkTable.set('leafyGreenColor', {name: 'Leafy Green Color', icon: leafyGreenColor});
openFoodDrinkTable.set('mushroom', {name: 'Mushroom', icon: mushroom});
openFoodDrinkTable.set('mushroomColor', {name: 'Mushroom Color', icon: mushroomColor});
openFoodDrinkTable.set('onion', {name: 'Onion', icon: onion});
openFoodDrinkTable.set('onionColor', {name: 'Onion Color', icon: onionColor});
openFoodDrinkTable.set('peanuts', {name: 'Peanuts', icon: peanuts});
openFoodDrinkTable.set('peanutsColor', {name: 'Peanuts Color', icon: peanutsColor});
openFoodDrinkTable.set('potato', {name: 'Potato', icon: potato});
openFoodDrinkTable.set('potatoColor', {name: 'Potato Color', icon: potatoColor});

export const OA_ICON_SIZE = openFoodDrinkTable.size;
